### ISSUE TITLE
napi_throw_type_error  arguments is different with Node 8 N-API

### ISSUE THREAD

**Issue by demohi** [nodejs/node-addon-api#100]
![image](https://user-images.githubusercontent.com/1209159/28953753-d8f6a954-790c-11e7-842f-81466e9216bb.png)

#### node 8 api doc
```
napi_throw_type_error
Added in: v8.0.0
NODE_EXTERN napi_status napi_throw_type_error(napi_env env, const char* msg);
[in] env: The environment that the API is invoked under.
[in] msg: C string representing the text to be associated with the error.
Returns napi_ok if the API succeeded.

This API throws a JavaScript TypeError with the text provided.

```

**Comment by jasongin** [comment]
Duplicate of https://github.com/nodejs/node-addon-api/issues/99

Currently this package works against the latest node nightly builds, and will work with the node 8.3.0 release that is expected soon.

N-API is still experimental, so there are occasional breaking changes. It should stabilize very soon though.

**Comment by demohi** [comment]
@jasongin  Thanks

**Comment by mhdawson** [comment]
@demohi , just to check that its now ok for you using 8.3.0 ?

**Comment by demohi** [comment]
@mhdawson  yes, it's ok now
