### ISSUE TITLE
addon built using N-API using Node v14 fails to load in Node v16

### ISSUE THREAD

**Issue by ThePrez** [nodejs/node-addon-api#1002]
Issue is being tracked in the addon issue tracker here: https://github.com/IBM/nodejs-idb-connector/issues/141

In a nutshell, the `idb-connector` addon, built against earlier versions of Node.js, is unable to load in Node v16 due to missing symbols. Of note, Node v16 is built using a newer version of GCC, which is likely to be a factor.

 I'm not sure whether this is an N-API defect, a compiler defect, a combination, or something else. Any insight is appreciated. Thanks!

**Comment by mhdawson** [comment]
We discussed in the Node-api team meeting today. From the quick search it looks like the node-addon-api does not use emplace-back so we believe it would be specific to the addon versus something introduced by node-addon-api itself.

There seems to be some confusion
* https://github.com/IBM/nodejs-idb-connector/issues/141#issuecomment-828097520 says that emplace back existing in gcc 6 but not in 10,
* https://github.com/IBM/nodejs-idb-connector/issues/141#issuecomment-836257605 seems to say that emplace back symbols exist in gcc 10 but not 6

Is it that they export different symbols ? 

It also sounds like it is symbols from Node.js which are outside of the node-api which are being used by the addon that are the issue.  Is that right ? 

One way to validate may be to create a simple addon that uses std::vector::emplace_back. Building it with gcc 6 and then running with gcc 10 in the path, it should fail with the same error, if we remove the use in the native addon it should then pass.  

We looked at linux and on Node 10.x and Node 12.x those symbols are not exported so this may be an IBM i specific issue.
