### ISSUE TITLE
How to create null or undefined Napi::Value?

### ISSUE THREAD

**Issue by SukantPal** [nodejs/node-addon-api#1006]
The documentation mentions:

> An empty Napi::Value is invalid, and most attempts to perform an operation on an empty Napi::Value will result in an exception. An empty Napi::Value is distinct from JavaScript null or undefined, which are valid values.

However, it does not state so I ask - how to construct valid `null` or `undefined` values?

**Comment by NickNaso** [comment]
Hi @SukantPal,
to create `null` or `undefined` value you should use the Followinf two methods of `Napi::Env` class:
- `Napi::Env::Undefined` see: https://github.com/nodejs/node-addon-api/blob/main/doc/env.md#undefined
- `Napi::Env::Null` see: https://github.com/nodejs/node-addon-api/blob/main/doc/env.md#null

Es.
```cpp
#include <napi.h>

Napi::Value Method(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  Napi::Value v = env.Undefinded();
  // ...
  return v;
}
```
I hope that this help you.
