### ISSUE TITLE
What's the best way to add native code to an existing project?

### ISSUE THREAD

**Issue by cesarvarela** [nodejs/node-addon-api#1010]
Hi, I'm working on an Electron app and need to add some native code.

Do I have to create another package and link it to the package of my Electron app? Or is there a better way? 

Thanks.

**Comment by mhdawson** [comment]
I don't have deep enough understanding of Electron to give a good answer so might we worth asking in the Electron if there are any alternatives.  In terms of adding native code, creating a native addon is the way to be able to call that native code from JavaScript running in Node.js

**Comment by mhdawson** [comment]
I think this has been answered to the ability of our team.  Going to close please let us know if you think that was not the right thing to do.
