### ISSUE TITLE
When developing, it is difficult to run a single test spec

### ISSUE THREAD

**Issue by KevinEady** [nodejs/node-addon-api#1016]
Running `npm test` will re-compile all files as it uses `node-gyp rebuild`. We can simplify this to compile only modified files by using `node-gyp build` -- however, modifying the `napi[-inl].h` file will consider _all_ test specs as modified. 

It would be helpful if we could have some way to compile + run only one test spec, such that only the relevant `.cc` file for that spec (as well as the overall binding) are compiled.

**Comment by deepakrkris** [comment]
I am working on this story

**Comment by deepakrkris** [comment]
@KevinEady @mhdawson I believe this can be closed for now, since we had some work on this and merged a PR

**Comment by mhdawson** [comment]
@deepakrkris the only question I have is if how to run a single test is documented somewhere? If so could you add the link here and then I think we can close.

**Comment by deepakrkris** [comment]
@mhdawson I think that is not documented. let me bring this up in our weekly meeting today. I can add in a readme or in a wiki

**Comment by mhdawson** [comment]
@deepakrkris thanks, I think adding to the Readme would be a good way to go.  I was out last week but will be there this week.

**Comment by deepakrkris** [comment]
@mhdawson doc PR  : https://github.com/nodejs/node-addon-api/pull/1199

**Comment by mhdawson** [comment]
@deepakrkris thanks landed that PR closing this. Many thanks for your work on making testing easier.
