### ISSUE TITLE
Why is it needed to call AdjustAmountOfExternalAllocatedMemory while v8 seem to already have that info?

### ISSUE THREAD

**Issue by rmdm** [nodejs/node-addon-api#1017]
We've discovered that our C++ addon is missing calls to `AdjustAmountOfExternalAllocatedMemory`. Without it our `process.memoryUsage().external` grows higher becasue of lower frequency of major gc. But could someone please explain why is it needed to call `AdjustAmountOfExternalAllocatedMemory` in the first place? Because it seems like v8 already got that information, as `process.memoryUsage().external` shows current external usage. It is probably not a node.js or node-addon-api issue, but I hope it is sufficiently relevant place to ask from the node.js addons perspective.

**Comment by mhdawson** [comment]
@rmdm, I believe that process.memoryUsage().external will only know about things which are allocated by Node.js itself (ie when Node.js knows it is allocating things that will result in external memory). 

If you are allocating memory for buffers etc. in your addon Node.js will not know about that and it will not be part of process.memoryUsags().external. My guess is that you are doing allocations and that is why you need Adjust AmountofExternalAllocatMemory.

**Comment by rmdm** [comment]
@mhdawson thank you for the response!

It is probably worth to provide some example with the observed behavior.

### binding.cc

```c++
#include <napi.h>
#include <v8.h> 
// yes, we are using some non-abi stable api, 
// but this fact by itselfs probably does not alter v8/node behavior much

using namespace Napi;

struct TUtf16StringExternalResource : public v8::String::ExternalStringResource {
    // the content is not important
    const uint16_t s[10000] = {0x6e, 0x61, 0x70, 0x69}; // a string starting with "napi" followed by null chars

    TUtf16StringExternalResource() {}

    const uint16_t* data() const {
        return s;
    }

    size_t length() const {
        return (sizeof s) / 2;
    }

    void Dispose() {
        // uncomment to trigger major gcs
        // v8::Isolate::GetCurrent()->AdjustAmountOfExternalAllocatedMemory(-length() * 2);
        delete this;
    }
};

Value GetStr(const CallbackInfo& info) {
    Env env = info.Env();

    auto isolate = v8::Isolate::GetCurrent();

    auto externalString = v8::String::NewExternalTwoByte(
        isolate,
        new TUtf16StringExternalResource()
    ).ToLocalChecked();

    // uncomment to trigger major gcs
    // isolate->AdjustAmountOfExternalAllocatedMemory(externalString->Length() * 2);

    auto result = Napi::String(env, reinterpret_cast<napi_value>(*externalString));

    return result;
}

Object Init(Env env, Object exports) {
  exports.Set(String::New(env, "getStr"), Function::New<GetStr>(env));
  return exports;
}

NODE_API_MODULE(NODE_GYP_MODULE_NAME, Init)
```

then the module is used like this in js:

### binding.js

```javascript
const binding = require('./build/Release/binding');

for (let i = 0; i < 10000; i++) {
    binding.getStr();

    if (i%1000 === 0) {
        const { rss, heapUsed, external } = process.memoryUsage();
        console.log(`rss: ${rss}\theapUsed: ${heapUsed}\texternal: ${external}`);
    }
}
console.log(binding.getStr());
```

### binding.gyp

```
{
  "targets": [
    {
      "target_name": "binding",
      "sources": [ "binding.cc" ],
      "include_dirs": ["<!(node -p \"require('node-addon-api').include_dir\")"],
      "defines": [ 'NAPI_DISABLE_CPP_EXCEPTIONS' ],
    }
  ]
}
```

### Results

The node.js version used in the next output examples is **14.17.3**, but **12.18.3** gives similar results.

So the output is the following for the case when calls to `AdjustAmountOfExternalAllocatedMemory` are commented out:

```
$ node --trace-gc binding.js 
[207772:0x5b6fb50]       44 ms: Scavenge 2.5 (3.0) -> 2.1 (4.0) MB, 1.0 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure 
rss: 31653888   heapUsed: 2646656       external: 881292
rss: 52948992   heapUsed: 3285088       external: 21053078
rss: 72937472   heapUsed: 3322720       external: 41053078
rss: 92942336   heapUsed: 3356280       external: 61053078
rss: 112947200  heapUsed: 3390400       external: 81053078
rss: 133222400  heapUsed: 3424064       external: 101053078
rss: 153288704  heapUsed: 3457960       external: 121053078
rss: 173293568  heapUsed: 3491696       external: 141053078
rss: 193298432  heapUsed: 3526272       external: 161053078
rss: 213303296  heapUsed: 3559944       external: 181053078
napi
[207772:0x5b6fb50]      213 ms: Scavenge 3.3 (5.3) -> 3.1 (6.0) MB, 1.4 / 0.0 ms  (average mu = 1.000, current mu = 1.000) task
```

and when `AdjustAmountOfExternalAllocatedMemory` calls are enabled:

```
$ node --trace-gc binding.js 
[207893:0x4c21b50]       44 ms: Scavenge 2.5 (3.0) -> 2.1 (4.0) MB, 1.0 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure 
rss: 31240192   heapUsed: 2668000       external: 881292
rss: 52535296   heapUsed: 3306336       external: 21053078
rss: 72523776   heapUsed: 3343968       external: 41053078
rss: 92798976   heapUsed: 3377528       external: 61053078
[207893:0x4c21b50]      118 ms: Mark-sweep 3.1 (5.0) -> 2.1 (5.3) MB, 2.6 / 0.0 ms  (+ 1.4 ms in 9 steps since start of marking, biggest step 0.3 ms, walltime since start of marking 4 ms) (average mu = 1.000, current mu = 1.000) finalize incremental marking via stack guard GC in old space requested
rss: 100282368  heapUsed: 2420104       external: 13966024
rss: 100282368  heapUsed: 2463864       external: 33966024
rss: 100282368  heapUsed: 2498768       external: 53966024
[207893:0x4c21b50]      135 ms: Mark-sweep 2.3 (7.3) -> 2.1 (7.5) MB, 1.7 / 0.0 ms  (+ 1.1 ms in 7 steps since start of marking, biggest step 0.2 ms, walltime since start of marking 3 ms) (average mu = 0.837, current mu = 0.837) finalize incremental marking via stack guard GC in old space requested
rss: 100659200  heapUsed: 2406032       external: 6666024
rss: 100659200  heapUsed: 2445528       external: 26666024
rss: 100659200  heapUsed: 2479160       external: 46666024
napi
```

So it looks like v8 does know about the external memory consumption by the external strings, and it gets included into `process.memoryUsage().external`, but for some reason v8 doesn't take the info into account for gc without additional `AdjustAmountOfExternalAllocatedMemory` calls.

**Comment by rmdm** [comment]
More than this, it looks like up to node.js v11 `AdjustAmountOfExternalAllocatedMemory(0)` even had been used directly as the source of the `external` metric - https://github.com/nodejs/node/commit/a5604a73d8d52219bcb97ff2934f81b67edc11af.

**Comment by mhdawson** [comment]
Seeing that you are using specific v8 calls that from the name sound like they would let V8 know about the external memory, then having that reported through the v8 data makes sense.

I wonder if calling AdjustAmountOfExternalAllocatedMemory acts as a trigger for the gc to check if it might run a gc based on change in external usage.  

It seems like this is all v8 related behaviour and you could likely create a v8 only test case and then report as a V8 issue?

**Comment by mhdawson** [comment]
@rmdm thanks, will be interesting to see what the V8 team says.

**Comment by rmdm** [comment]
Ok, it looks like v8 recognize this as an [API/GC low-priority issue](https://bugs.chromium.org/p/v8/issues/detail?id=11978#c4). Thank you for your help with pushing the issue in the proper direction!
