### ISSUE TITLE
3x overhead on Node 6

### ISSUE THREAD

**Issue by mcollina** [nodejs/node-addon-api#102]
I've benchmarked https://github.com/mcollina/native-hdr-histogram/tree/napi on Node 6.11 against the NAN implementation with https://github.com/mcollina/native-hdr-histogram/blob/napi/bench.js.

The result is that the NAPI version takes 167ms to complete, vs 67ms to the NAN version.
This might be related to _this_ specific implementation, as I have not tested it yet on Node 8.3.0 (I'm blocked on #101).

[flamegraph.html.zip](https://github.com/nodejs/node-addon-api/files/1200214/flamegraph.html.zip) <-- if a flamegraph might be of help.

**Comment by mcollina** [comment]
This is the flamegraph with NAN. There are some notable differences, so check them out.

[flamegraph.html.zip](https://github.com/nodejs/node-addon-api/files/1200224/flamegraph.html.zip)

**Comment by jasongin** [comment]
That's surprising, as I have not seen more than about 20% overhead even in the most extreme cases.

I'd like to look into it, but it might be a few days before I have time.

**Comment by mhdawson** [comment]
@jasongin have you had a chance to take a look yet ?

**Comment by jasongin** [comment]
Sorry I have not had time to look at this, and will not anytime soon. I will be on vacation 8/17 - 9/4.

**Comment by mhdawson** [comment]
@digitalinfinity volunteered to look at this as a priority in the N-API weekly meetin glast week.

**Comment by mhdawson** [comment]
@digitalinfinity can you add the info you reported in a meeting a while back so that we can close this issue.

**Comment by mhdawson** [comment]
Going to close out as Node.js 6.x is long out of LTS. Please let us know if this is not the right thing to do.
