### ISSUE TITLE
Napi::New string length checking 

### ISSUE THREAD

**Issue by JckXia** [nodejs/node-addon-api#1023]
One of the String class method `String::New(napi_env env, const char* val, size_t length) ` doesn't seem to have any checks in place to make sure that the string is shorter/equal to the length param.  In a case where the string is shorter than the length parameter passed in, for example: 
![Capture](https://user-images.githubusercontent.com/32422811/125982236-f3175271-68db-4ac7-81fb-b06112442d44.PNG)
a long string is returned which seemingly contains some random data in memory.
![sc](https://user-images.githubusercontent.com/32422811/125982786-bf12c3d6-0b18-4173-b2cb-dbbbf9e64c99.PNG)

 Should we add a check to make sure that `strlen(val) <= length`? 

The example above is produced using node version v14.17.0

**Comment by mhdawson** [comment]
Looking at the different signatures:
```C++
Napi::String::New(napi_env env, const std::string& value);
Napi::String::New(napi_env env, const std::u16::string& value);
Napi::String::New(napi_env env, const char* value);
Napi::String::New(napi_env env, const char16_t* value);
Napi::String::New(napi_env env, const char* value, size_t length);
Napi::String::New(napi_env env, const char16_t* value, size_t length);
```

There is a different version that you use with null terminated strings.  IN the case were the length is specified we don't know if the string is null terminated or not and so there is no way to check the length.

Therefore, I think it's ok as is.

**Comment by JckXia** [comment]
Thanks that makes sense!
