### ISSUE TITLE
NODE_API_SWALLOW_UNTHROWABLE_EXCEPTIONS  only catch one throw 

### ISSUE THREAD

**Issue by JsBlueCat** [nodejs/node-addon-api#1027]
use ```NODE_API_SWALLOW_UNTHROWABLE_EXCEPTIONS``` in defines will solve one throw problem.

but  if do another throw, the node-addon-api will be crashed

**Comment by KevinEady** [comment]
Hello,

We took a look at this in today's Node.js API meeting, and just and FYI this change was introduced via https://github.com/nodejs/node-addon-api/pull/975

**Comment by gabrielschulhof** [comment]
@JsBlueCat can you please try release 4.0.0 or later of node-addon-api and tell us whether you still see this issue and re-open it if you do?
