### ISSUE TITLE
How to manually construct Napi::CallbakInfo by c++? 

### ISSUE THREAD

**Issue by robertLiuLinFeng** [nodejs/node-addon-api#1029]
Hello, I used the node-addon-api in my project. Now I want to write some unit tests for project. 
It ask me to pass Napi::CallbackInfo object when invoking my addon functions. So can you tell me how to construct Napi::CallbackInfo object by c++ manually instead of automatically constructing them by js calls?
Thanks very much.

**Comment by mhdawson** [comment]
There has been no response from the OP in a month since the last question we agreed to close in the last Node-API team meeting. Please let us know if you think that was not the right thing to do.
