### ISSUE TITLE
Clarify compatibility with unsupported Node.js versions 

### ISSUE THREAD

**Issue by lpinca** [nodejs/node-addon-api#1031]
The documentation states that "the oldest Node.js version supported by the current version of `node-addon-api` (4.0.0) is Node.js 12.x".

Specifically, what makes `node-addon-api@4.0.0` incompatible with Node.js < 12?

I've compiled an addon that requires only `NAPI_VERSION` 1 using `node-addon-api@4.0.0` and Node.js 6.14.2 and it seems to work fine in all versions of Node.js >= 6.14.2. The same addon compiled with `node-addond-api@4.0.0` and Node.js 16.6.1 also works in Node.js >= 6.14.2 <= 16.6.1.

**Comment by KevinEady** [comment]
Hi @lpinca ,

We do not test anything lower than Node.js 12 in our CI, so we do not guarantee support for it. Futhermore, Node.js has its own build requirements which we try to match (eg. compiler versions). Removing support for older Node.js versions allows us to use newer compilers and standards.

The various Node.js version compatibilities are guarded under feature flags like you mentioned, the `NAPI_VERSION` macro.

Hope this helps.

**Comment by lpinca** [comment]
> Futhermore, Node.js has its own build requirements which we try to match (eg. compiler versions). Removing support for older Node.js versions allows us to use newer compilers and standards.

I thought about that and Node.js 12 uses `-std=gnu++1y`. If I want to keep compatibility with `-std=gnu++11` should I go back to `node-addon-api@3` or `node-addon-api@2`? It is not clear.

**Comment by lpinca** [comment]
I think I should use `node-addon-api@2` to be sure because the oldest Node.js version supported by `node-addon-api@3` is 10.x and Node.js 10 also uses `-std=gnu++1y`.

That said, `node-addon-api@3` works with `-std=gnu++11`. Is it safe to assume that the the 3.x release line will receive no compiler breaking changes now that `node-addon-api@4` has been released?

**Comment by KevinEady** [comment]
Hi again,

We don't anticipate any changes in the 3.x line, so there wouldn't be any compiler breaking changes.

**Comment by lpinca** [comment]
Ok, thank you.
