### ISSUE TITLE
Time for next release 4.1.0

### ISSUE THREAD

**Issue by NickNaso** [nodejs/node-addon-api#1032]
It's almost two months since the last 4.0.0 release. Now we added some new things and we should probably start thinking about doing a release.

**Comment by mhdawson** [comment]
+1

**Comment by NickNaso** [comment]
I'm starting to work on making the new release.

**Comment by NickNaso** [comment]
CI:
| Version | Job | Status |
|---:|---|:---:|
| v16.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/4561/ | ✓ |
| v14.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/4560/ | ✓ |
| v12.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/4559/ | ✓ |

CI:
| Version | Job | Status |
|---:|---|:---:|
| v16.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/4564/ | ✓ |
| v14.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/4563/ | ✓ |
| v12.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/4562/ | ✓ |

**Comment by NickNaso** [comment]
I'm closing the issue because the release has been published.
