### ISSUE TITLE
Correct method or example for consuming an async JS function in an addon?

### ISSUE THREAD

**Issue by alexciarlillo** [nodejs/node-addon-api#1033]
I am attempting to call an `async` JS function in my addon and trying to find any examples or pointers for doing so. Most of the documentation I am finding is the inverse: doing async work in C++. The goal here is that I am integrating a library which needs to make HTTP requests. I already have the functions to make these requests in JS and I don't want to maintain C++ versions of these same requests (and pull in additional HTTP request libraries to support it). Additionally, this code will run from a desktop app and the browser, so I want to maintain a single set of HTTP request functions in JS. The example is roughly:

```JavaScript
_onProduce = async ({requestParams} = {}) => {
    const {id} = await this.myService.CreateProducer({
      requestParams
    });

    return {id};
};
```

```cpp
Napi::Value Transport::SetProduceListener(const Napi::CallbackInfo& info) {
   this->listener_->onProduceRef_ = Napi::Persistent(info[1].As<Napi::Function>());
  return Napi::Boolean::New(info.Env(), true);
}
```

Some code will eventually trigger `Listener::OnProduce`

```cpp
std::future<std::string> Listener::OnProduce(
  const std::string& kind,
  const std::string& sourceId)
{
  std::promise<std::string> promise;

  promise.set_value("whatever");

  if (!this->onProduceRef_.IsEmpty()) {
    Napi::Env env = this->onProduceRef_.Env();

    auto requestData = Napi::Object::New(env);
    requestData.Set("kind", Napi::String::New(env, kind));
    requestData.Set("sourceId", Napi::String::New(env, sourceId));

    auto response = this->onProduceRef_.Call({requestData});
    auto responseObject = response.As<Napi::Object>();
    
    // I now have an object which is a promise. I want to wait until it resolves and retrieve the `id` value like so:

   std::string id = responseObject.Get("id").As<Napi::String>().Utf8Value();
   promise.set_value(id);
  } else {
    // no handler set - error
  }

  return promise.get_future();
}
```

So any tips on the correct method for handling this would be appreciated.

**Comment by AnkhHeart** [comment]
I am also running in to the same situation.
Is there any way to await the resolution of the promise in C++ and retrieve the return value using node-addon-api?

**Comment by KevinEady** [comment]
Hi @alexciarlillo , @AnkhHeart ,

I have created this example and waiting approval, hopefully this helps with your use-case: 
https://github.com/nodejs/node-addon-examples/pull/189

I create a thread-safe function (TSFN) in order to call into Node.js at any time. The TSFN calls the JavaScript function that returns a Promise. In C++, we attach a handler that `set_value`s the `std::promise` on the JavaScript promise via `.then`.

**Comment by mhdawson** [comment]
@alexciarlillo , @AnkhHeart the example @KevinEady has landed. Please let us know if you think that covers your question and this issue can be closed.

**Comment by alexciarlillo** [comment]
This is great! Thanks.
