### ISSUE TITLE
How to solve mingw-w64 does not support parameter: -undefined dynamic_lookup

### ISSUE THREAD

**Issue by wuliang142857** [nodejs/node-addon-api#1042]
Now I want to cross-compile a Node module for Windows platform using C++ on MacOS, and the cross-compilation tool used is `mingw-w64`. The compilation process is smooth, but the problem is the link that is the link that includes a set of parameters that are `-undefined dynamic_lookup`. But `mingw-w64` does not support `-undefined dynamic_lookup`.

> `-undefined dynamic_lookup` means: will mark all undefined symbols as having to be looked up at runtime.

I tried some other possible parameters, such as: `-Wl, --allow-shlib-undefined` or `-Wl, --unresolved-symbols=ignore-all`. Who knows how to solve this?

**Comment by NickNaso** [comment]
Hi @wuliang142857,
could take a look at this discussion https://github.com/nodejs/node/issues/38782#issuecomment-884458958 and see if it belo to solve your problem?

**Comment by gabrielschulhof** [comment]
@wuliang142857 @NickNaso provided a way in https://github.com/nodejs/node/issues/38782#issuecomment-884458958 that should help you structure your compilation to obtain the behaviour you need. If you still encounter problems in this regard, please re-open this issue!
