### ISSUE TITLE
Shared resources for concurrent access through worker treads

### ISSUE THREAD

**Issue by Patick-Bateman** [nodejs/node-addon-api#1057]
Is it possible to create a shared resource, for example a cache, which each of the worker threads will have access to (be able to read from it - most of the time, but sometimes partially invalidate/update it) therefore concurrent access?

**Comment by mhdawson** [comment]
If you mean a cache of C structures then you should be able to do that, you would need to use looking constructs to ensure safe access while also ensuring you don't block the event loops of the workers. The tricky part might be getting the pointer to the shared cache to each of the threads. A static might work but I know we discourage that. @gabrielschulhof throughts?

**Comment by mhdawson** [comment]
From a quick look through that seems reasonable to me.

**Comment by Patick-Bateman** [comment]
@mhdawson Thank you!
