### ISSUE TITLE
Can Napi::Env be used in a sub-thread?

### ISSUE THREAD

**Issue by robertLiuLinFeng** [nodejs/node-addon-api#1058]
I wrote a sample program to pass the Napi::Env object to the child thread for use, but an error occurred during runtime. 
the sample code is as follows:
```cpp
#include <napi.h>
#include <iostream>
#include <thread>
#include <chrono>

Napi::String Method(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();

  // ok
  // Napi::Object obj = Napi::Object::New(env);
  // obj.Set(Napi::String::New(env, "msg"), "hello world");

  // std::string str = obj.Get("msg").As<Napi::String>();
  // std::cout << "str : " << str << std::endl;

  std::thread t([](Napi::Env env) {
    std::cout << "run here 1" << std::endl;
    Napi::Object obj = Napi::Object::New(env);

    std::cout << "run here 2" << std::endl;
    obj.Set(Napi::String::New(env, "msg"), "hello world");

    std::cout << "run here 3" << std::endl;
    std::string str = obj.Get("msg").As<Napi::String>();
    std::cout << "str : " << str << std::endl;
  }, info.Env());
  t.join();

  return Napi::String::New(env, "world");
}

Napi::Object Init(Napi::Env env, Napi::Object exports) {
  exports.Set(Napi::String::New(env, "hello"),
              Napi::Function::New(env, Method));
  return exports;
}

NODE_API_MODULE(hello, Init)
```
the error is as follows:
![image](https://user-images.githubusercontent.com/38060518/131533292-24d877b3-c807-4280-aee8-06b1c18a4edf.png)

thanks for your help!

**Comment by JckXia** [comment]
Hey there! I believe in order to use ```Napi::Env``` the way you are intended to, you would have to do something like https://github.com/nodejs/node-addon-api/blob/main/doc/threadsafe.md using the ```Napi::ThreadSafeFunction```.

**Comment by mhdawson** [comment]
@JckXia is correct you can't use Napi:Env on another thread.  Napi:ThreadSafeFuntion provides a way to call back to the main thread to run any code that may run JavaScript (which includes using node-api).

**Comment by mhdawson** [comment]
I'm going to close this as I think it is answered. Please let us know if that was not the right thing to do.
