### ISSUE TITLE
Add linting for JavaScript code

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#1063]
- Suggestion is eslint with semistandard
- Only apply to files that are changed
- run apply as part of adding, list steps to generate lint changes
- have second person do run to make sure we don't have unintended changes

**Comment by rubiagatra** [comment]
Wanna help because this is good first issue, https://www.npmjs.com/package/eslint-config-semistandard using this semistandard?

**Comment by mhdawson** [comment]
@rubiagatra using eslint with https://www.npmjs.com/package/eslint-config-semistandard  is what I had in mind.

**Comment by mhdawson** [comment]
Thanks for working on this.

**Comment by rubiagatra** [comment]
Thank you for @mhdawson for your guidance!

For the next step of linting/tooling, should I create the issue?

**Comment by mhdawson** [comment]
@rubiagatra creating an issue that lists the files (maybe with checkboxes that can be checked when file is completed) which report errors along with the steps/approach for submitting a PR to run the lint fix/submit PR would be useful.  Some of things that come to mind for the process would be:

1) Make small modification to file, run link fix to get updated version 
2) If all required changes are fixed by linter, then open PR state that all changes were generated by --fix
3) If not all required changes were fixed by linter, then commit those from --fix in first commit. Manually fix the rest and add a second commit with those changes. Open PR with 2 commits, indicating the changes in the first commit were all generated with --fix
