### ISSUE TITLE
AsyncWorker OnOk / OnError never called for subclasses

### ISSUE THREAD

**Issue by koenkivits** [nodejs/node-addon-api#107]
Hi! 👋  First off, I wanted to say thanks for this module. I started developing my first native module a small time ago and just ported it to use this instead of Nan, and while the transition took me some work, the resulting code is much cleaner (to me, at least). :)

Here's an issue I ran in though:
The `AsyncWorker` class has the methods `OnOk` and `OnError`. Both these methods are virtual, seemingly implying you can override them to have custom success/error behavior (like with Nan's `HandleOKCallback` and `HandleErrorCallback`). However, overriding them has no effect.
My C++ knowledge is pretty basic, but I think this is because `AsyncWorker::OnWorkComplete` [statically casts the instance to the base class](https://github.com/nodejs/node-addon-api/blob/dfb59ac421d63b860f3ad2ffe08ea9e9ed3a1dcd/napi-inl.h#L2771), causing only the base class methods to ever be called.

Am I right? And is this considered a bug?

**Comment by jasongin** [comment]
Yes, that appears to be a bug. Thanks for reporting it!

We should add some test cases for subclassing `AsyncWorker`.

**Comment by koenkivits** [comment]
I'm actually kind of ashamed to be admitting this, and I'm facepalming pretty hard right now, but I made a mistake:
It's `OnOK`, not `OnOk`. It works fine. 🤦‍♂️
(`OnError` not working was an assumption based on the fact that `OnOk` wasn't being called)

Sorry for any time wasted
