### ISSUE TITLE
[Tests] TypedThreadSafeFunctions unit test coverage

### ISSUE THREAD

**Issue by JckXia** [nodejs/node-addon-api#1073]
| class                   | methods                                                                                                                          |
|-------------------------|----------------------------------------------------------------------------------------------------------------------------------|                           
 |TypedThreadSafeFunction |     |
 |Covered|TypedThreadSafeFunction New(napi_env env, ResourceString res, size_t maxQueueSize, size_t initThreadCnt, ContextType* ctx = nullptr) |
 |Covered | TypedThreadSafeFunction New(napi_env env, const Object& res, ResourceString resName, size_t maxQueueSize, size_t initThread, ContextType * ctx = nullptr) |
|covered(typed_threadsafe_function_ctx.cc) |TypedThreadSafeFunction New(napi_env env, ResourceString resName, size_t maxQSize, size_t initThreadCnt, ContextType * context, Finalizer finalizeCb, FinalizerDataType * data = nullptr) |
|Covered(see typed_threadsafe_function_sum.cc) |TypedThreadSafeFunction New(napi_env env, const Object& res, ResourceString resName, size_t maxQSize, size_t initThreadCnt, ContextType * context, Finalizer finalizeCb, FinalizerDataType * data = nullptr) |
|Covered|TypedThreadSafeFunction New(napi_env env, const Function& cb, ResourceString resName, size_t maxQSize, size_t initThreadCnt, ContextType * ctx= nullptr) |
|Covered(typed_threadsafe_function_ptr.cc)  |TypedThreadSafeFunction New(napi_env env, const Function& cb,  const Object& res, ResourceString resName, size_t maxQSize, size_t initThreadCnt, ContextType * ctx= nullptr) |
|Covered(typed_threadsafe_function.cc)  |TypedThreadSafeFunction New(napi_env, const Function& cb, ResourceString resName, size_t maxQSize, size_t initalThreadCnt, ContextType* ctx, Finalizer finalizeCb, FinalizerDataType* data = nullptr) |
|Covered|TypedThreadSafeFunction New (napi_env, CallbackType cb, const Object& res, ResourceString resName, size_t maxQSize, size_t initThreadCnt, ContextType* ctx, Finalizer finalizeCB, FinalizerDatType* data = nullptr) |
|Covered(see typed_threadsafe_function.cc)|napi_status BlockingCall(DataType* data =nullptr) const |
|Covered(See typed_threadsafe_function.cc)|napi_status NonBlockingCall(DataType* data =nullptr) const |
|Covered |void Ref(napi_env env) const |
|Covered(see typed_threadsafe_function.cc)|void Unref(napi_env env) const|
|Covered(See typed_threadsafe_function.cc)|napi_status Acquire() const |
|Covered ( see typed_threadsafe_function.cc) |napi_status Release() |
|Covered(see typed_threadsafe_function.cc)|napi_status Abort()|
|Covered( see typed_threadsafe_function.cc)|ContextType* GetContext() const|

**Comment by hionnode** [comment]
Hi, can I take this up ?

**Comment by NickNaso** [comment]
> Hi, can I take this up ?

Yes, you can.

**Comment by JckXia** [comment]
Coverage complete following https://github.com/nodejs/node-addon-api/pull/1201
