### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/node-addon-api#108]
@nodejs/n-api we should release, because 8.3.0 is out with `napi_create_number()` gone, and I can't reliably continue porting iotivity-node when node-addon-api has `napi_create_number()` and none of the other number-creating functions, and 8.3.x has all the others but not `napi_create_number()`.

**Comment by mhdawson** [comment]
I can look at doing that tomorrow (Friday)

I assume the wrapper has been updated ? 

 @nodejs/n-api @nodejs/addon-api any reason we'd not want to do a release now ?

**Comment by mhdawson** [comment]
I'd like some feedback from the rest of the team and I'm done for today so I'll look at this on Monday.

**Comment by mhdawson** [comment]
This release went out last week.
