### ISSUE TITLE
node native addon and signals

### ISSUE THREAD

**Issue by rubu** [nodejs/node-addon-api#1085]
I am making a native addon that installs signal handlers, and it seems that this somehow interacts with node and only under debuggger in vscode (so maybe this even isn't the appropriate place to ask this question). In short it seems that as soon as I install my handlers, calling sync stuff like `spawnSync` from `child_process` blocks the debugger.

But as a general question - if I install signal handlers in my native addon, what should I be doing to pass the signals to node - just call `raise` with the same signal I received, or is there api in napi that I should use to receive signals instead of installing handlers directly?

**Comment by rubu** [comment]
A workaround that I thought of was to install signal handlers in node via `process.on` and then pass them to my module via a callback, but as far as I understand `SIGCHILD` is not exposed and will not be sent via `process.on`.

**Comment by mhdawson** [comment]
We don't have any signal related APIs in node-api: https://nodejs.org/dist/latest-v16.x/docs/api/n-api.html.  

I don't think that `raise` will do what you want, I think your signal handler might just end up getting the signal again.

You would need to look at `chaining`, for example as described in https://stackoverflow.com/questions/10701713/signal-overwriting-other-signal-handlers and https://cboard.cprogramming.com/linux-programming/117417-sigaction-how-find-invoke-previous-signal-handler-sa_handler.html

**Comment by rubu** [comment]
@mhdawson thanks for the answer, yeah I realized a bit later than `raise` is not the way to go since I would get into my own handler. So either saving the old callbacks from `sigaction` (which does have the culprit that if there is another module that does this, I'll get those callbacks, but that module may not be chained further up) or actualyl have node expose them in js via`'process.on` and then I could deliver them to my module via n-api functions. The issue that I see is that https://nodejs.org/api/process.html#process_signal_events does not mention `SIGCHLD` so I guess it is swallowed internally. I will try to find the appropriate place in node and link it here so that others which run into this can understand.

**Comment by mhdawson** [comment]
@rubu thanks, will be good to have it documented here once you have some useful links.

**Comment by mhdawson** [comment]
I'm going to close this since the question has been answered. Please let us know if you think that was not the right thing to do.
