### ISSUE TITLE
Question about how Error::New() handles last error and exceptions

### ISSUE THREAD

**Issue by JckXia** [nodejs/node-addon-api#1089]
I was writing a small Cpp addon trying to see if there exists a scenario where the `_ref` class variable of `Error` class might be a nullptr. 
![TestAddon](https://user-images.githubusercontent.com/32422811/136665147-1e682dd3-c248-4ef8-8718-f52fb926e5bd.PNG)
Since it looks like the error_code `napi_boolean_expected` isn't handled by the switch statement inside `Error::New()`.

Though it looks like even though we are able to retrieve the error info using `napi_get_last_error_info` , once we call `napi_is_exception_pending` we will clear the last error and thus lose the error info from the previous invocation.
![newErrorCode](https://user-images.githubusercontent.com/32422811/136665423-438c8619-5492-4bfa-bee0-29a81de8dc55.PNG)

I am just wondering if this is the expected behaviour? Since it looks like the original error info( a const) is intended to be used elsewhere in the function body. Thanks!

**Comment by JckXia** [comment]
Hey @mhdawson , yeah I think adding that to the doc could help.  Though the issue with the `Error::New(env)` implementation could that the `napi_is_exception_pending` call mutates the `napi_extended_error_info` struct, while the switch statement in later parts of the code seems to work with the assumption that `info->error_code` has not been changed .  In this case, should we create a copy of the `info` struct?  

![ErrImpl](https://user-images.githubusercontent.com/32422811/137223753-91239860-1f1a-444a-806c-c0a0c98fa666.PNG)

**Comment by RaisinTen** [comment]
PR: https://github.com/nodejs/node-addon-api/pull/1092
