### ISSUE TITLE
AsyncProgressQueueWorker::Signal() does not trigger the TSFN

### ISSUE THREAD

**Issue by KevinEady** [nodejs/node-addon-api#1095]
As reported in https://github.com/nodejs/node-addon-api/pull/1086#issue-1017797535

**Comment by KevinEady** [comment]
Hi @legendecas , can you elaborate some more on the problem? Maybe we can discuss in today's call.

**Comment by KevinEady** [comment]
😅  The above fix might be a bit premature. Let's discuss in the call.

**Comment by legendecas** [comment]
@KevinEady the problem introduced in #853 is that it unconditionally suppressed the calls when the data is nullptr, for timing details you can checkout the graph here https://github.com/nodejs/node-addon-api/issues/821#issuecomment-723626374. So I believe we should try to find a way to distinguish `Signal`s (a user-initiated action) from duplicated activation from second uv idle callback (not a user-initiated action).

**Comment by KevinEady** [comment]
Current state: I have an implementation that solves this issue, but it suffers from the "not all of the async `Signal()` calls (which calls the TSFN `NonBlockingCall()`) get executed. We discussed in 28 Jan meeting to port the implementation over to Node-API directly (without using the node-addon-api wrapper) to see if it's an issue with the underlying thread-safe functions APIs or with the wrapper. This is currently ongoing.

**Comment by KevinEady** [comment]
Fixed by #1216
