### ISSUE TITLE
Windows build mystery (Release build vs. Debug build)

### ISSUE THREAD

**Issue by lukas2** [nodejs/node-addon-api#1098]
Hi, I am writing a module for an electron app and I am compiling it with `cmake-js` and it runs well on Linux and Mac. However, on Windows, the electron app will crash immediately IF it's a Release build. (Debug Builds work fine.)

After lots of trial and error I have identified, that the solution is to [tell the linker to add debug information](https://docs.microsoft.com/en-us/cpp/build/reference/debug-generate-debug-info?view=msvc-160).

So in my `CMakeLists` I write

```
target_link_options(node-api INTERFACE /DEBUG)
```

and it works! Even if the binary is a regular Release binary will all optimisations set to maximum.

I am a complete Windows noob, but I am hoping someone can explain to me what is going on and why this link setting seems to be required.

**Comment by NickNaso** [comment]
Hi @lukas2,
I tried to compile a simple [hello world](https://github.com/nodejs/node-addon-examples/tree/main/build_with_cmake/node-addon-api) example using cmake-js and both builds type (Release and Debug) worked fine.  
Is the repository of your project public? Could you post your `CMakeLists.txt` file? 
Which version of electron are you using?

**Comment by mhdawson** [comment]
I'm going to close this since there has not been a response from the Op after @NickNaso response/questions. Please let us know if that was not the right thing to do.
