### ISSUE TITLE
Adding napi_create_syntax_error

### ISSUE THREAD

**Issue by idan-at** [nodejs/node-addon-api#1099]
Hi,

Some of the known js tooling (webpack and babel for example) are re-written in other languages (esbuild in go, swc and parcel in rust)

Because of that, throwing a syntax error from napi makes sense. 
unfortunately, the API does not exist at this moment (although other native errors can be thrown, like type error and range error) 

what do you think about adding it? 

If it’s accepted, I’d be happy to contribute (if you can point me)

Thanks!

**Comment by NickNaso** [comment]
Hi @idan-at,
Syntax erros while detecting or parsing source code. See: [MDN Syntax Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError) and [ECMAScript](https://tc39.es/ecma262/#sec-native-error-types-used-in-this-standard-syntaxerror).
What I unsterstood is that adding this type of error could be helpful to build tools like esbuild, babel or swc using implemented like a native addon and return a more exaustive error in case of incorrect syntax.
This is a changes that need to be made on the Node.js core. In the specific we need to add two new functions:
```cpp
napi_status napi_throw_syntax_error(napi_env env, const char* code, const char* msg);
napi_status napi_create_syntax_error(napi_env env, napi_value code, napi_value msg, napi_value* result);
```
We can disccus this proposal in Node-API Team tomorrow. If you want to partecipate you can find all the info here: https://github.com/nodejs/abi-stable-node#meeting

**Comment by idan-at** [comment]
@NickNaso thank you for the quick reply.
Unfortunately I won't be able to attend today. I'd appreciate if you can bring it up and share your decision here.

If you find the API useful I will be happy to contribute.

Thanks

**Comment by mhdawson** [comment]
We discussed in the Node-API team meeting today, and agreed it would make sense to add methods to throw/create the errors listed in the spec including syntax_error.

If you'd like to submit a PR to core to add these and add equivalents to node-addon-api once the core PR lands that would be great.
