### ISSUE TITLE
Correct way to use EventEmitter and emit events from addon

### ISSUE THREAD

**Issue by bennycooly** [nodejs/node-addon-api#110]
So I've been looking around and see many different ways people have tried to use EventEmitter with C++ addons. I first tried to pass the `EventEmitter.emit` method directly to a C++ ObjectWrap constructor and invoke that method using `Napi::Function::Call({args})` but the C++ code cannot see the actual EventEmitter object and thus fails since `emit()` accesses the EventEmitter class variables. This can be trivially solved by just wrapping the `emit()` call using a JS callback:
```
emitter.on("event", (...args) => {
    console.log("event occurred!");
    for (let [index, arg] of args.entries()) {
        console.log(`arg${index}: ${arg}`);
    }
});

function emit(event, ...args) {
    emitter.emit(event, args);
}

Foo = new Foo(emit);
```

And in C++:
```
Foo::Foo(Napi::CallbackInfo const & info) {
    this->emit = info[0].As<Napi::Function>();
    emit.Call({Napi::String::New(info.Env(), "event"), Napi::String::New(info.Env(), "arg"});
}
```

However, I am just wondering if this is the correct way to actually emit events or not.

**Comment by jasongin** [comment]
>  but the C++ code cannot see the actual EventEmitter object and thus fails since emit() accesses the EventEmitter class variables

Sounds like you just need to [bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) the `emit` function to the emitter instance:

```
new Foo(emitter.emit.bind(emitter));
```

(And that is essentially what your adapter function does. But `Function.bind()` already exists for that purpose.)

**Comment by mhdawson** [comment]
#bennycooly did  Jason's suggestion resolve your issue ?  Just wondering if we can close this issue ?

**Comment by NickNaso** [comment]
Hi everyone,
today I worked at event emitter's usage with **N-API**.  The approach proposed by @jasongin work. I created some simple examples here:
**[Use emitter from a function](https://github.com/NickNaso/addon-event-emitter/tree/master/00])**
**[Extend event emitter using object wrap](https://github.com/NickNaso/addon-event-emitter/tree/master/01)**
If anyone has time and want take a look and maybe can send me a feedback could be fantastic.

**Comment by NickNaso** [comment]
Ok in this week I will work to complete another two examples about the event emitter usage after that I can add them to the repo.

**Comment by NickNaso** [comment]
Hi @bennycooly did you solved the problem? May we close this issue?

**Comment by bennycooly** [comment]
Yes, we can close this. I got mine to work using the object wrap!

**Comment by Globik** [comment]
@NickNaso  emit event from cpp is good but  what about from c?

**Comment by marcelman** [comment]
Hi @NickNaso,

I saw your example in https://github.com/NickNaso/addon-event-emitter/blob/master/00/src/emit-from-cpp.cc and it was very useful to understand how to use event emitter (I'm pretty new to NodeJS and NAPI). However, as you mention in your comment:

// All work but it's not a good practice bacause all long running task should be
// executed out of the event loop

Assuming that my worker thread is another C++ thread, how could I send the callback from that thread? for example:
 emit.Call({Napi::String::New(env, "data"), Napi::String::New(env, "data ...")});

As I understand this is not supported by design in NodeJS, and I saw that the NAPI implementantion of (Napi::AsyncWorker) does not support a progress callback.

**Comment by NickNaso** [comment]
Hi @marcelman ,
you're right you cannot call JavaScript from the `Napi::AsyncWorker` in the specific you cannot call JavaScript from the `Execute` method. 
For now this what you want to do is not directly supported by `Napi::AsyncWorker`, but you can take a  look here: [Asynchronous Thread-safe Function Calls](https://nodejs.org/dist/latest-v10.x/docs/api/n-api.html#n_api_asynchronous_thread_safe_function_calls) that allow you to call JavaScript function from the additional thread created by the add-on when you use `Napi::AsyncWorker`.
Hope to be helpful and in the next days I try to create a new example that cover your needs.

**Comment by zombiecong** [comment]
Hi @NickNaso ,
I also have same problem as @marcelman. Do you finish the new example?Is it possible to share it with me?

**Comment by markpiffer** [comment]
I was trying this with Napi::ThreadSafeFunction but it keeps crashing when Node encounters the function call in its event loop supposedly. The C++ itself runs through without problems.

```
Napi::ThreadSafeFunction emitFuncThreadSafe;

void configIAmEvent(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();

    Napi::Object eventEmitter = info[0].As<Napi::Object>();
    Napi::Value emitFuncValue = eventEmitter.Get("emit");
    if (emitFuncValue.IsFunction()) {
        Napi::Function emitFunction = emitFuncValue.As<Napi::Function>();
        emitFuncThreadSafe = Napi::ThreadSafeFunction::New(env, emitFunction, "IAmEventEmitter", 0, 5);
    }
}

void emit_iam(const char* ip) {
//    emitFunctionRef.BlockingCall(ip, [](Napi::Env env, Napi::Function f, const char* ip) { f.Call({Napi::String::New(env,"IAm"), Napi::String::New(env,ip)}); });
      emitFuncThreadSafe.NonBlockingCall(ip, [](Napi::Env env, Napi::Function f, const char* ip) {
          f.Call({Napi::String::New(env, "IAm"), Napi::String::New(env, ip)}); });
}
```

The result is a:

```
#
# Fatal error in HandleScope::HandleScope
# Entering the V8 API without proper locking in place
#

Exception: Exception 0x80000003 encountered at address 0x7ff6138bc532
Exception: Exception 0x80000003 encountered at address 0x7ff6138bbde0

Process finished with exit code 3
```

What am I doing wrong?
