### ISSUE TITLE
Constructor Overload [SO 200 bounty]

### ISSUE THREAD

**Issue by developer239** [nodejs/node-addon-api#1107]
[You can find SO question here.](https://stackoverflow.com/questions/70130805/c-n-api-multiple-type-signatures)

I would like to create my own wrapper for `cv::Vec`.

```cpp
#include <napi.h>
#include <opencv2/core/matx.hpp>

class Vec : public Napi::ObjectWrap<Vec> {
public:
  static Napi::Object Init(Napi::Env env, Napi::Object exports);

  explicit Vec(const Napi::CallbackInfo &info);

private:
  static Napi::FunctionReference constructor;

  //
  // no type named 'Vec' in namespace 'cv';
  // I would like this to be cv::Vec2 or cv::Vec3 ... of any type
  cv::Vec *_wrappedClass_;

  // duplicate member '_wrappedClass_'
  // cv::Vec2 *_wrappedClass_;
  // cv::Vec3 *_wrappedClass_;
};
```

Of course, the example above will not work because `cv::Vec` expects me to tell `type` and `size`. So something like this: `cv::Vec<int, 3>` would work and create a 3-dimensional vector.

My question is how do I properly overload the constructor and define the `_wrappedClass_` type?

Should I create classes `Vec2`, `Vec3`, and so on that would extend the current `Vec` class?

When I looked at how `justdudewhohacks` did it - you can find his codebase here: [opencv4nodejs](https://github.com/justadudewhohacks/opencv4nodejs/blob/master/cc/core/Vec.h). It seems more reasonable:

 - 1 cpp file
 - base header file
 - additional header files for class variants

Could you please point me in the right direction?

**Comment by developer239** [comment]
I asked a question with a bounty of 200 points. Happy hunting.

https://stackoverflow.com/questions/70130805/c-n-api-multiple-type-signatures

**Comment by gabrielschulhof** [comment]
One way would be to template the ObjectWrap class itself. Then you'd have one JS class for each cv::Vec class you end up using.

```cpp
#include <napi.h>
#include <opencv2/core/matx.hpp>

template <typename VecType>
class Vec : public Napi::ObjectWrap<Vec> {
public:
  static Napi::Object Init(Napi::Env env, Napi::Object exports);

  explicit Vec(const Napi::CallbackInfo &info);

private:
  static Napi::FunctionReference constructor;

  //
  // no type named 'Vec' in namespace 'cv';
  // I would like this to be cv::Vec2 or cv::Vec3 ... of any type
  VecType *_wrappedClass_;

  // duplicate member '_wrappedClass_'
  // cv::Vec2 *_wrappedClass_;
  // cv::Vec3 *_wrappedClass_;
};
```
Hopefully this will help you. If you find any issues with this approach, please feel free to re-open this issue.
