### ISSUE TITLE
[Bug] Some files don't exist in npm package?

### ISSUE THREAD

**Issue by southorange1228** [nodejs/node-addon-api#1108]
node-addon-api Verions: 4.2.0

i can't find any file called node_api.h in folder.

![image](https://user-images.githubusercontent.com/32590310/145365281-32624174-512c-4138-a0cb-f46dcc1aca9e.png)

![image](https://user-images.githubusercontent.com/32590310/145365115-2d73670c-9827-4c85-8442-60f2cd3e71c0.png)

But if version is 1.7.2, i can find it. How to solve this problem?
![image](https://user-images.githubusercontent.com/32590310/145365666-e7c22ce0-66f6-4e12-a4c6-8f1dc2c1ffff.png)

**Comment by NickNaso** [comment]
Hi @southorange1228,
the header file for Node-API is in the core of Node.js see: https://github.com/nodejs/node/blob/master/src/node_api.h
IN hte previous version of node-addon-api we need to support some version of Node.js that don't have the Node-API in the core and in that case we provided one through `node-addon-api` Now all the LTS release line have Node-API and we dropped it from `node-aadon-api`. If yu need header files for Node-API you can fine them here: https://github.com/nodejs/node-api-headers
Let me know if this help you.

**Comment by southorange1228** [comment]
Get it! Thanks~
