### ISSUE TITLE
CI and release process for this module

### ISSUE THREAD

**Issue by mcollina** [nodejs/node-addon-api#111]
As this module will get more popular, a more formal release process is needed, and we need to catch bugs before release.

Plus, we need to take #106 into account.

**Comment by gabrielschulhof** [comment]
To cover Linux and OSX we might use Travis' secure environment variable mechanism to create prebuilds - meaning we use Travis infrastructure.

OTOH, if we want to cover and test more platforms than that, we need to use Node's infrastructure, however, that means we need a secure mechanism for storing GH credentials.

@mhdawson is it possible to create a sort of clean-slate-job on ci.nodejs.org that has all the platforms for which we wish to produce prebuilds, but which doesn't actually download and build the Node.js source code? If so, I'd love to dive in flesh out the build process that produces the prebuilds. Of course, I still don't know about uploading to GH but, perhaps we can create an account with minimal privileges to upload the binaries to a location that will be trusted by the community.

**Comment by mcollina** [comment]
Travis cannot be used on the nodejs github organization for security reasons. It's very complicated.

**Comment by mhdawson** [comment]
@gabrielschulhof we can setup whatever Jobs that we need.  It sounds like we are actually discussing 2 things here.

1) Testing/releasing the npm module itself which I agree it would be good to have a Node.js CI job that can help on that from. 
2) Distributing pre-builds to help support earlier versions of Node.js.  The option of bundling it with the earlier versions that we ship sounds interesting as it would simplify the distribution process. 

I'd suggest we should discuss these 2 separately to avoid delaying one for the other.

**Comment by mcollina** [comment]
We need to build them as part of CI of this repo, as it's tied to the code in here, not on the one on Node.js. Or we might want to split the two things, and have a N-API layer for old node.js with a prebuilt, and have the C++ part of this not be prebuilt.

**Comment by mhdawson** [comment]
Work to setup initial CI job under: https://github.com/nodejs/build/issues/844

**Comment by mhdawson** [comment]
Job is now running and greed so I think we can close this.

https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api/ runs on master nightly, and as part of our release process, we run against LTS lines and current master - https://github.com/nodejs/node-addon-api/blob/master/doc/creating_a_release.md
