### ISSUE TITLE
Time for next release 4.3.0.

### ISSUE THREAD

**Issue by NickNaso** [nodejs/node-addon-api#1110]
It's almost 3 months since the last 4.2.0 release. Now we added some new things and we should probably start thinking about doing a release.

**Comment by mhdawson** [comment]
+1

**Comment by mhdawson** [comment]
We talked briefly in the Node-API team meeting today and @NickNaso will kickoff working on the release.

**Comment by NickNaso** [comment]
I'm starting to work on the release.

**Comment by NickNaso** [comment]
CI:
| Version | Job | Status |
|---:|---|:---:|
| main | https://ci.nodejs.org/job/node-test-node-addon-api-new/5198/ |  |
| v17.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/5200/ |  |
| v16.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/5202/ |  |
| v14.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/5204/ |  |
| v12.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/5206/ |  |

CI:
| Version | Job | Status |
|---:|---|:---:|
| main | https://ci.nodejs.org/job/node-test-node-addon-api-new/5199/ |  |
| v17.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/5201/ |  |
| v16.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/5203/ |  |
| v14.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/5205/ |  |
| v12.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/5207/ |  |

**Comment by NickNaso** [comment]
I'm closing the issue because the new release has been published on npm.
