### ISSUE TITLE
How do I call to the main thread and get data back?

### ISSUE THREAD

**Issue by kelvinhammond** [nodejs/node-addon-api#1113]
Hello,

I have a class which contains an array of objects which contain an `ObjectReference`. These objects are passed to an library which uses multi-threading, I then call a function on the `Object` held by the `ObjectReference` which throws:

```
#
# Fatal error in HandleScope::HandleScope
# Entering the V8 API without proper locking in place
#
```

I looked into `TypedThreadSafeFunction` but this doesn't fit my use case because it calls to the main thread and just continues leaving me unable to get the value from the js context. What is the proper way to call the js context and get or create values from a thread for use in that thread?

**Comment by KevinEady** [comment]
hi @kelvinhammond ,

I'm not exactly sure why you _can't_ use thread-safe functions...?

> because it calls to the main thread and just continues leaving me unable to get the value from the js context

Thread-safe functions have their own `Context`, which you can put this "array of objects which contain an `ObjectReference`", and access _and use_ their values within the `CallJs` function (which generally transforms the native data into JS data).

Can you provide some sort of code with what's failing for you?

Thanks, Kevin

**Comment by kelvinhammond** [comment]
Hello, thank you for the response.

The issue I was having is that the main thread (event loop) would:
1. create multiple thread safe function (TSF)
2. pass the TSFs to a library
3. The library would block the main thread, call the TSFs, and wait for them to join before returning.

The issue was that the TSF could not queue on the main event loop thread because it was blocked.

I have so far managed to work around this by creating an AsyncWorker and executing the library call on that worker thread as to not block the main thread. This allows the TSFs to queue on the main thread without problem and be joined. Once the result is return the async worker resolves a Promise to say its done, the promise is returned before it resolves as a result of the bound function.
