### ISSUE TITLE
Question about EscapableHandleScope

### ISSUE THREAD

**Issue by ClementDreptin** [nodejs/node-addon-api#1115]
Hi,

I'm trying to use an object coming from a `CallbackInfo` into an `AsyncWorker` but I can't get it to work. After some reading, it seems like I'm supposed to escape the object to the outer scope to be able to use it in my `AsyncWorker`. I made a simple example that takes an object and coverts it to a csv string, the string is then passed as the second argument of the callback:

main.cpp:
```C++
#include "MyClass.h"

Napi::Object Init(Napi::Env env, Napi::Object exports)
{
    Napi::Function func = MyClass::GetClass(env);

    Napi::FunctionReference *constructor = new Napi::FunctionReference();
    *constructor = Napi::Persistent(func);
    exports.Set("MyClass", func);

    env.SetInstanceData<Napi::FunctionReference>(constructor);

    return exports;
}

NODE_API_MODULE(addon, Init)
```

MyClass.h
```C++
#pragma once

#include <napi.h>
#include "PrintWorker.h"

class MyClass : public Napi::ObjectWrap<MyClass>
{
public:
    MyClass(const Napi::CallbackInfo &info)
        : ObjectWrap(info) {}

    static Napi::Function GetClass(Napi::Env env)
    {
        return DefineClass(env, "MyClass", { InstanceMethod("format", &MyClass::FormatAsync) });
    }
private:
    Napi::Value FormatAsync(const Napi::CallbackInfo &info)
    {
        Napi::Env env = info.Env();

        if (info.Length() < 2)
            Napi::Error::New(env, "You need to pass 2 arguments").ThrowAsJavaScriptException();

        if (!info[0].IsObject())
            Napi::TypeError::New(env, "Object expected as first argument").ThrowAsJavaScriptException();

        if (!info[1].IsFunction())
            Napi::TypeError::New(env, "Callback expected as second argument").ThrowAsJavaScriptException();

        Napi::EscapableHandleScope scope(env);
        Napi::Value obj = info[0];
        Napi::Function callback = info[1].As<Napi::Function>();

        PrintWorker *applyWorker = new PrintWorker(callback, scope.Escape(obj));
        applyWorker->Queue();

        return env.Undefined();
    }
};
```

PrintWorker.h:
```C++
#pragma once

#include <napi.h>
#include <string>

class PrintWorker : public Napi::AsyncWorker
{
public:
    PrintWorker(const Napi::Function &callback, const Napi::Value &obj)
        : Napi::AsyncWorker(callback), m_Obj(obj) {}

    void Execute() override
    {
        Napi::Object obj = m_Obj.As<Napi::Object>();
        Napi::Array keys = obj.GetPropertyNames();

        for (uint32_t i = 0; i < keys.Length(); i++)
        {
            std::string key = keys.Get(i).As<Napi::String>().Utf8Value();
            m_Result += key;

            std::string value = "," + obj.Get(key).As<Napi::String>().Utf8Value() + "\n";
            m_Result += value;
        }
    }

    void OnOK() override
    {
        Callback().Call({ Env().Undefined(), Napi::String::New(Env(), m_Result) });
    }
private:
    Napi::Value m_Obj;
    std::string m_Result;
};
```

test.js:
```JS
const { MyClass } = require('../build/Release/MyClass');
const instance = new MyClass();

instance.format({ foo: 'bar' }, (err, result) => {
  if (err) console.error(err);

  console.log(result);
});
```

When running the code in a debugger I get this error:
```
#
# Fatal error in HandleScope::HandleScope
# Entering the V8 API without proper locking in place
#
```
triggered at line 15 in PrintWorker.h:
```C++
Napi::Array keys = obj.GetPropertyNames();
```

When running the code in release mode the error changes, sometimes I get the same error I get when running the debugger and sometimes I get this one:
```
#
# Fatal error in v8::HandleScope::CreateHandle()
# Cannot create a handle without a HandleScope
#
```

Am I not using the `EscapableHandleScope` correctly? Am I not supposed to use an `EscapableHandleScope` for this case? If not, what I'm I supposed to use?

Thanks

**Comment by NickNaso** [comment]
Hi @ClementDreptin,
in the `Napi::AsyncWorker::Execute` method you cannot call JavaScript code because the code inside this method is executed in a separate thread. You can / call use any JavaScript code in `Napi::AsyncWorker::OnOK` or `Napi::AsyncWorker::OnError` .
This behavior is docuemtned here https://github.com/nodejs/node-addon-api/blob/main/doc/async_worker.md#execute
Maybe you could transform the object you want to use and tranform in a  C++ `std::map`  that you can use inside the `Napi::AsyncWorker::Execute` method or you could consider the usage of `Napi::ThreadSafeFunction` and `Napi::TypedThreadSafeFunction`.

**Comment by ClementDreptin** [comment]
Thanks for your repply @NickNaso,
I ended up transforming the JavaScript object into a `std::vector<std::string>` in the constructor and I manipulate this vector in `Execute`. Thanks for clearing things up, I'm closing the issue.
