### ISSUE TITLE
How to create Float32Array from vector<float> ?

### ISSUE THREAD

**Issue by alalialisiong** [nodejs/node-addon-api#1117]
Hi

I tried the code below but the data I checked in js was uint8array.

Napi::Buffer<float_t>::Copy(env, vec.data(), vec.size());

How to convert to Float32Array from vector<float>??

I hope you can give me an answer.

**Comment by NickNaso** [comment]
Hi @alalialisiong,
could you post your JavaScript and C++ code?

**Comment by mmomtchev** [comment]
```cpp
Napi::TypedArray array = Napi::Float32Array::New(env, vec.size());
memcpy(array.ArrayBuffer().Data(), vec.data(), vec.size() * sizeof(float));
```
`Buffer` will create a `Buffer` not a `TypedArray` - which is why it appears to be a `Uint8Array`

**Comment by alalialisiong** [comment]
> ```c++
> Napi::TypedArray array = Napi::Float32Array::New(env, vec.size());
> memcpy(array.ArrayBuffer().Data(), vec.data(), vec.size() * sizeof(float));
> ```
> 
> `Buffer` will create a `Buffer` not a `TypedArray` - which is why it appears to be a `Uint8Array`

Thank you for the reply. I'll try.

**Comment by mhdawson** [comment]
I'm going to close this issue as the question was answered and there has been no follow up since the last comment by the originator. Please let us know if that was not the right thing to do.
