### ISSUE TITLE
Fail to free memory in Finalizer of ArrayBuffer in WIndows

### ISSUE THREAD

**Issue by Leaking** [nodejs/node-addon-api#1121]
I create a vector<unsigned char> pointer in node c++ addon，and then pass the vector data to js by ArrayBuffer

```
// baton->rowsBuffer is a std::vector<unsigned char> pointer

Napi::ArrayBuffer arrayBuf = Napi::ArrayBuffer::New(env, baton->rowsBuffer->data(), baton->rowsBuffer->size(), [](void *hint, void* data){
       // here is Finalizer
       free(data);
    });
```
when i try to free memory in Finalizer, it crashs in windows, and it works in my MacOS

**Comment by mhdawson** [comment]
I think we'll need a more complete recreate to be able to help.

**Comment by mhdawson** [comment]
I'm going to close this since there has not been a response since the request for more info. Please let us know if you feel that was not the right thing to do.
