### ISSUE TITLE
Class constructors cannot be invoked without 'new'

### ISSUE THREAD

**Issue by p120ph37** [nodejs/node-addon-api#1123]
Currently, `ObjectWrap<T>::ConstructorCallbackWrapper` has a guard against calling the constructor as a javascript function without the "new" keyword (`TypeError: Class constructors cannot be invoked without 'new'`).  In a pure Javascript project, or in a non `node-addon-api` native project, it is possible to trap this sort of scenario and do something special other than abort -- often simply re-call the function as a constructor and return the new object, but potentially other clever things too.

If we could change the `ObjectWrap<T>::ConstructorCallbackWrapper` implementation to delegate to an overridable public static method when `!isConstructCall` rather than always aborting (e.g. `Value T::NonConstructFunction(const Napi::CallbackInfo& info)` with a default implementation that throws the usual `TypeError`), that would allow for more flexibility in porting older modules to use `node-addon-api` without changing their existing semantics.

**Comment by legendecas** [comment]
Calling a constructor created from `class {}` is throwing:

```js
(class {})(); // TypeError: Class constructors cannot be invoked without 'new'
```
I think this is expected behavior. As you can still create normal functions with `Napi::Function::New`.

**Comment by p120ph37** [comment]
Sure you can create normal functions with `Napi::Function::New`, but I don’t see a way in which you can create a dual-purpose function which can, depending on invocation context, act either as a normal function, or as an `ObjectWrap` constructor and `instanceof`-testable prototype.  This sort of thing is possible and even common in classic (pre-ES2015) js, and it is possible with `napi_wrap` directly, just not with the current `ObjectWrap` abstraction. For new development it is probably not a great idiom, but I have an older Node module I’m trying to port, and without this functionality, I can’t maintain backward compatibility with existing code.

It should be possible to support this feature with a fairly trivial hook.  I’ll see if I can whip up a PR in the morning…

**Comment by p120ph37** [comment]
I've opened PR #1125 to add this functionality, and tests which illustrate the use-case.

**Comment by KevinEady** [comment]
PR #1125 has landed in https://github.com/nodejs/node-addon-api/commit/cee899ade542d8d19429d2c32ac41f0cc5328d3a , closing issue.
