### ISSUE TITLE
Use void * or HANDLE with Napi::External

### ISSUE THREAD

**Issue by FLevent29** [nodejs/node-addon-api#1124]
Hi!

Is it possible for a JS variable to hold a c++ `void *`? Either no, or I am making a silly mistake somewhere:

```c++
Napi::External<HANDLE> MakeHandleNAPI(const Napi::CallbackInfo &info) {
    auto env = info.Env();
    if (info.Length() != 0) throw Napi::TypeError::New(env, noArgsErrMsg);
    // HANDLE to API object or NULL
    auto myNurHandle = CreateNurHandle();
    if (myNurHandle == NULL) throw Napi::Error::New(env, "Error on NUR handle creation");
    return Napi::External<HANDLE>::New(env, &myNurHandle, [](Napi::Env, HANDLE* handle) {
        FreeHandle(*handle);
    });
}
```

As soon as I run this from JS it crashes without any error messages.

Or maybe there's a better way, with Napi::ObjectWrap or something else?

**Comment by FLevent29** [comment]
Never mind, looks like it was something else that caused the issue. But there still remains a problem, when I get the `HANDLE` back from JS code and pass it to one of the API functions, it always spits back an `Invalid handle passed to function`, which means this is not going to work. I am not sure why that would happen, if I pass it around in c++ it has no problem whatsoever, even if I wrap it in `Napi::External` and then unwrap it. When I pass it to JS it goes out of scope and gets freed or something similar must be happening.

I really don't want to keep a global value for this `HANDLE`, so what other things could I try?

**Comment by KevinEady** [comment]
Hi @FLevent29 ,

We discussed in the 11 Feb Node API meeting your issue, and came up with some theories:

1. Does the method `CreateNurHandle` return some sort of smart pointer, such that the contents held get freed when the `MakeHandleNAPI` function finishes? 
2. If you return the `External` to JavaScript to store in some local variable (eg. you have some JavaScript method that calls this `MakeHandleNAPI`) and then the JavaScript method completes, the object can be marked as available for garbage collection and when it gets GC'd the finalizer will run and call your `FreeHandle()`. If you need the `External` to persist longer than your JavaScript function call, you may need to wrap it inside of a `Reference` so the GC won't clear it up.

**Comment by FLevent29** [comment]
I ended up using `Napi::ObjectWrap` and the whole class approach, and simply creating the handle at the creation of the object. Seems like a better way to go about it, and so far it seems to work alright.

Now that I've taken a second look at this it appears I inserted the wrong type, and so I passed the wrong value. It should be
```c++
Napi::External<void> MakeHandleNAPI(const Napi::CallbackInfo &info) {
    auto env = info.Env();
    if (info.Length() != 0) throw Napi::TypeError::New(env, noArgsErrMsg);
    // HANDLE to API object or NULL
    auto myNurHandle = CreateNurHandle();
    if (myNurHandle == NULL) throw Napi::Error::New(env, "Error on NUR handle creation");
    return Napi::External<void>::New(env, myNurHandle, [](Napi::Env, void *handle) {
        FreeHandle(handle);
    });
}
```

It is not a smart pointer, but I probably would've needed a `Reference` for it if I went this way.

Sorry I took up precious time with such an issue in your meeting, I was just confused by the `HANDLE` part, still pretty new to "somewhat advanced" c++.
