### ISSUE TITLE
How to free the data passed to a Property Descriptor?

### ISSUE THREAD

**Issue by somanuell** [nodejs/node-addon-api#1126]
I'm so sorry, I'm pretty sure I knew how to do this, but I forgot!

I use `Napi::Object::New(env);` to create a new JS object and then `Napi::PropertyDescriptor::Accessor` to add a "Getter" for a property.

My problem is that I pass some data (as void*) to the Accessor and that the data is obtained from `new`...

How do I ensure that that "data" is "deleted" when the JS Object is Garbage Collected?

**Comment by p120ph37** [comment]
Use `AddFinalizer` to bind a GC callback to the object: https://github.com/nodejs/node-addon-api/blob/main/doc/object.md#addfinalizer

**Comment by somanuell** [comment]
Thank you!

So if I build a JS object with 42 custom properties, each requiring its own malloced pointer, I have to store those 42 pointers in a std::vector and release them all in the "finalizer"?

**Comment by somanuell** [comment]
Again, thanks.
I can't use `ObjectWrap` because my C++ objects are based on some arbitraty instance of the COM Interface IDispatch, so methods and properties are unknwon at compile time. But they know have a std::vector member!

**Comment by somanuell** [comment]
(I forgot to say the obvious: I use the `napi_wrap` API in place of `ObjectWrap`...)
