### ISSUE TITLE
Some Napi::PropertyDescriptor::Accessor methods  trigger UB: Document string life cycle and add overrides that accept Napi::Env

### ISSUE THREAD

**Issue by somanuell** [nodejs/node-addon-api#1127]
In `<napi.h>` there are various declaration of overloads for `Napi::PropertyDescriptor::Accessor` wich accept a `const std::string& utf8name` parameter.
These declarations have implementation definitions in `"napi-inl.h"`

Here, these definitions rely on overloads which accept a `const char* utf8name` parameter, and use `.c_str()` to get the pointer...

Hence, with the code:

```
Napi::Object TheNewObject = Napi::Object::New(env);
std::vector<Napi::PropertyDescriptor> vProps;
for (size_t index = 0; index < 2; ++index ) {
	std::string strName("MyName_");
	strName += std::to_string(index);
	auto PD = Napi::PropertyDescriptor::Accessor(env,TheNewObject, strName, Caller );
	vProps.push_back(PD);
} 
```

The 2 PDs in the vector contains dangling pointers to strings out of scope.
What is that I don't understand correctly?

**Comment by somanuell** [comment]
Asked SO if it's real.
https://stackoverflow.com/questions/70942530/is-there-an-undefined-behavior-problem-with-some-apis-in-node-addon-api

**Comment by somanuell** [comment]
I just ended a quick test session under a debugger: I confirm that as soon as the for loop is exited, the vector contains PropertyDescriptors with dangling pointers in `_desc.utf8name`...

why is there no comment on my issue? What am I missing?

**Comment by KevinEady** [comment]
Hi @somanuell ,

The `napi_property_descriptor` expects one of either `napi_value name` or `const char* utf8name` to be null. Passing a pointer for `utf8name` constructs a new `napi_value` from the pointer, but this only occurs when the class is actually defined via `napi_define_class`.

We can discuss this in the next Node API meeting.

Thanks, Kevin

**Comment by somanuell** [comment]
Hi @KevinEady,
thanks for commenting, that's much appreciated.
Did you read my code, or the SO linked question?

`Conclusion: each time you use Napi::PropertyDescriptor::Accessor passing a std::string and then storing the PD in a vector, or just making the string goes out of scope with the PD still here, you trigger an undefined behavior!`

**Comment by KevinEady** [comment]
We discussed in the 11 Feb Node API meeting two approaches to solve this issue:
1. Have `PropertyDescriptor` have a copy of the `std::string` to take ownership of the data
2. Add a new overload to create a `PropertyDescriptor` with an `Napi::Env` in order to create a new `Napi::Value` based off of the string's contents.
3. Introduce a new class eg. `OwnedPropertyDescriptor` where this object would own the copy (sort of an extension of idea 1, but does not require changing existing logic)

We will table this discussion for next week when we have more members to discuss and can reach an agreement on the approach to use.

**Comment by mhdawson** [comment]
In this week's meeting we had a lighter attendance so will discuss next week.

**Comment by somanuell** [comment]
I'm in no way in position to say whatever, but I'll give my opinion anyway, as a C++ and `node-addon-api` happy user: deprecate the whole `Accessor` functions taking a `std::string` as argument, and introduce new functions, with another name.

**Comment by somanuell** [comment]
Anyway, don't forget that `napi_define_properties` can consume a `std::vector` of `napi_property_descriptor`, and that is very cool!

**Comment by gabrielschulhof** [comment]
At the February 25th, 2022 meeting of the Node-API Team we discussed this issue.

Our conclusion was that we need to document that the PropertyDescriptor factory methods that receive a `const std::string &` and those that receive a `const char *` require that the caller maintain the pointer until the resulting `PropertyDescriptor` objects are no longer used. Additionally we can create new overrides that accept a `Napi::Env` in addition to the existing parameters. Internally, these overrides will convert the `const char *` that needs maintenance to a `napi_value`. These new methods could then be used in loops such as described by the OP.

In your immediate case, @somanuell, you can modify the code to create a `std::vector<std::string>` to store the property names, then create a `std::vector<Napi::PropertyDescriptor>` to store the `PropertyDescriptor` objects, and then use the vector to define properties.

**Comment by mhdawson** [comment]
Good places to add in doc - 
https://github.com/nodejs/node-addon-api/blob/main/doc/property_descriptor.md#example

State that copies are not made, and what is passed in must remain valid until the descriptor will no longer be used, explain in context of example at the top.

**Comment by mhdawson** [comment]
Also needs to be added to https://github.com/nodejs/node-addon-api/blob/main/doc/class_property_descriptor.md

**Comment by somanuell** [comment]
Thanks all,

For now, I'm using a `std::vector<napi_property_descriptor>` paired with a `std::vector` of dynamically allocated `char*`. I can then use a single call to `napi_define_properties` (and then free what needs to be). I will revisit my code to go full `Napi::` with the same `std::vector<char*>` but with `std::vector<Napi::PropertyDescriptor>` and `Napi::DefineProperties`

**Comment by mhdawson** [comment]
@NickNaso will add to the documentation.
