### ISSUE TITLE
i don't get it  the  array can't be  property ?   or  i   make some  mistake?

### ISSUE THREAD

**Issue by yanwuguangjun** [nodejs/node-addon-api#1129]
#### my code  like this  

demo.h
`
class DLT_PROTO:public Napi::ObjectWrap<DLT_PROTO>{
public:
    static Napi::Object Init(Napi::Env env, Napi::Object exports);
    DLT_PROTO(const Napi::CallbackInfo &info);

    int read_index = 0;

    //Napi::Value toData();

    Napi::Value GetValue(const Napi::CallbackInfo &info);
    void SetValue(const Napi::CallbackInfo &info, const Napi::Value &value);

    Napi::Value GetKeys(const Napi::CallbackInfo &info);
    void SetKeys(const Napi::CallbackInfo &info, const Napi::Value &value);

    Napi::Array   _keys;
    Napi::Array   _values;

//    void next();
};

`

#### demo.cc
`

void DLT_PROTO::SetValue(const Napi::CallbackInfo &info, const Napi::Value &value) {
    this->_values = value.As<Napi::Array>();
}

Napi::Value DLT_PROTO::GetValue(const Napi::CallbackInfo &info) {
    printf("getvalue\n");
    return this->_values;
}

Napi::Value DLT_PROTO::GetKeys(const Napi::CallbackInfo &info) {
    printf("getkeys\n");
    return this->_keys;
}

void DLT_PROTO::SetKeys(const Napi::CallbackInfo &info, const Napi::Value &value ){
    this->_keys  = value.As<Napi::Array>();
}

DLT_PROTO::DLT_PROTO(const Napi::CallbackInfo &info) : Napi::ObjectWrap<DLT_PROTO>(info)
{

    printf("init \n");
    auto env = info.Env();
    this->_values = Napi::Array::New(env,5);
    this->_keys = Napi::Array::New(env,5);
}

Napi::Object DLT_PROTO::Init(Napi::Env env, Napi::Object exports){
    Napi::Function func = DefineClass(env, "DLT_PROTO", {
            InstanceAccessor<&DLT_PROTO::GetKeys,&DLT_PROTO::SetKeys>("keys"),
            InstanceAccessor<&DLT_PROTO::GetValue, &DLT_PROTO::SetValue>("values"),
    });

    Napi::FunctionReference *constructor = new Napi::FunctionReference();
    *constructor = Napi::Persistent(func);
    env.SetInstanceData(constructor);
    exports.Set("DLT_PROTO", func);
    return exports;
}
`

javascript code 

`
const proto = new addon.DLT_PROTO()
// proto.values.push("1234")
proto.keys.push("1234")
// proto.keys.push("1234")
// console.log(proto)
console.log(proto.values)
console.log(proto.keys)
`

compile  is  fine  
  but  when i  run zhe javascript 
the error code is 

`
getvalue
[ <5 empty items> ]
getkeys

 Fatal error in , line 0
 Check failed: (location_) != nullptr.

FailureMessage Object: 000000FCEEFAD320
 1: 00007FF71FCE401F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112511
 2: 00007FF71FC0116F v8::CFunctionInfo::HasOptions+7055
 3: 00007FF7208D7302 V8_Fatal+162
 4: 00007FF72024CF35 v8::internal::StringTable::TryStringToIndexOrLookupExisting+12197
 5: 00007FF72024AAB7 v8::internal::StringTable::TryStringToIndexOrLookupExisting+2855
 6: 00007FF72024DC58 v8::internal::StringTable::TryStringToIndexOrLookupExisting+15560
 7: 00007FF72024DF7E v8::internal::SerializeStackFrameInfo+94
 8: 00007FF720557E66 v8::internal::Builtins::code_handle+138166
 9: 00007FF7205553D0 v8::internal::Builtins::code_handle+127264
10: 00007FF7206335B1 v8::internal::SetupIsolateDelegate::SetupHeap+494673
11: 00007FF7206651D1 v8::internal::SetupIsolateDelegate::SetupHeap+698481
12: 00007FF720664F41 v8::internal::SetupIsolateDelegate::SetupHeap+697825
13: 00007FF720661DA9 v8::internal::SetupIsolateDelegate::SetupHeap+685129
14: 00007FF7206BA2B0 v8::internal::SetupIsolateDelegate::SetupHeap+1046864
15: 00007FF7205C5A5E v8::internal::SetupIsolateDelegate::SetupHeap+45310
16: 00007FF7205C5A5E v8::internal::SetupIsolateDelegate::SetupHeap+45310
17: 00007FF7205C5A5E v8::internal::SetupIsolateDelegate::SetupHeap+45310
18: 00007FF7205C3C6C v8::internal::SetupIsolateDelegate::SetupHeap+37644
19: 00007FF7205C386B v8::internal::SetupIsolateDelegate::SetupHeap+36619
20: 00007FF7204A45B1 v8::internal::Execution::CallWasm+1521
21: 00007FF7204A3E9F v8::internal::Execution::Call+191
`

**Comment by KevinEady** [comment]
Hi @yanwuguangjun ,

Is it possible for you to provide a repository that reproduces this crash?

**Comment by KevinEady** [comment]
Hi @rafael-conrado ,

Can you provide your code in a repo for us to run and look at?

**Comment by mhdawson** [comment]
I'm going to close this as there has not been a response to @KevinEady's requests for over a month. @yanwuguangjun please re-open if you still want help investigating.  @rafael-conrado please open a new issue if you have an issue you want help with.
