### ISSUE TITLE
Jenkins CI is broken after latest PRs being landed.

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#1137]
https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-new/nodes=debian8-64/5352/

**Comment by NickNaso** [comment]
@mhdawson I tried to fix in this PR https://github.com/nodejs/node-addon-api/pull/1138

**Comment by mhdawson** [comment]
I believe this is resolved. All tests had passed in the last CI I started - https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-LTS%20versions/1419/
