### ISSUE TITLE
Duplicate sections in "Object Wrap" documents

### ISSUE THREAD

**Issue by haoxi911** [nodejs/node-addon-api#1144]
For some reason, the following sections have multiple copies in [this](https://github.com/nodejs/node-addon-api/blob/main/doc/object_wrap.md) document.

1. DefineClass
2. StaticMethod
3. StaticAccessor
4. StaticValue

**Comment by mhdawson** [comment]
We discussed in the Node-API team meeting today and we think that they are not duplicates, just different function overloads for the same method. 

Can you clarify further?

**Comment by haoxi911** [comment]
You're right, I didn't look into the details of each function parameter while reporting the bug, it looks like duplicates because they have the same title and description, maybe you guys are using some tools to create the documents from code?

Anyway, thanks for the clarification!
