### ISSUE TITLE
Regular hang in thread safe function in CI testing

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#1150]
Seems consistent on Debian 8 and Node.js 12 but I've seen it intermittently on other platforms as well

https://ci.nodejs.org/job/node-test-node-addon-api-new/nodes=debian8-64/5608

**Comment by mhdawson** [comment]
```
Running test 'threadsafe_function/threadsafe_function_unref'
Running test 'typed_threadsafe_function/typed_threadsafe_function'
Running test 'typed_threadsafe_function/typed_threadsafe_function_ctx'
Running test 'typed_threadsafe_function/typed_threadsafe_function_existing_tsfn'
Running test 'typed_threadsafe_function/typed_threadsafe_function_ptr'
Running test 'typed_threadsafe_function/typed_threadsafe_function_sum'
Build timed out (after 60 minutes). Marking the build as failed.
Tests aborted with SIGTERM
npm ERR! Test failed.  See above for more details.
```

**Comment by mhdawson** [comment]
This time in s390 - https://ci.nodejs.org/job/node-test-node-addon-api-new/nodes=rhel8-s390x/5615/console

In past runs it seemed to fail every time on debian but not last night :).

There is also an issue on the core side which is likely related - https://github.com/nodejs/reliability/issues/224 (4 failures shown in that reliabiliity report)

**Comment by KevinEady** [comment]
Hi @mhdawson ,

I installed a debian 8 VM and again I am unable to reproduce any failures locally after 100 full test runs (not just threadsafe tests). I think we need to go with the next approach, getting access to the build server?

Thanks, Kevin

**Comment by mhdawson** [comment]
Created https://github.com/nodejs/build/issues/2919 to request access. Hopefully early next week we can get you access to the machine.
