### ISSUE TITLE
Listing ClassPropertyDescriptor

### ISSUE THREAD

**Issue by wass** [nodejs/node-addon-api#1157]
How do I make a wrapped object's `ClassPropertyDescriptor`'s show in a console.log output? I.e. if I have the following initialization

```
Napi::Object MyObject::Init(Napi::Env _Env, Napi::Object _Exports)
{
	Napi::Function Func =
		DefineClass
			(
				_Env,
				"MyObject",
				{
					, InstanceAccessor<&MyObject::f_GetID, &MyObject::f_SetID>("ID", static_cast<napi_property_attributes>(napi_writable | napi_enumerable))
				}
			)
		;

	_Exports.Set("MyObject", Func);

	return _Exports;
}
```

and call 

```
const myobject = new mynamespace.MyObject();
console.log(myobject);
```

from JavaScript, I get a 

```
MyObject {}
```

printout, so ID is not listed.

**Comment by wass** [comment]
Doing the following
```
console.log(util.inspect(myobject, { showHidden: true, depth: null }));
```
prints
```
MyObject { ID: [Getter/Setter] }
```
but it should work with `showHidden: false`? Adding my own custom toString does not help either, i.e. if I add 
```
, InstanceMethod<&MyObject::f_ToString>("toString", static_cast<napi_property_attributes>(napi_enumerable))
```
and
```
Napi::Value MyObject::f_ToString(Napi::CallbackInfo const &_Info)
{
	return Napi::String::New(_Info.Env(), "MyObject{ ID: '" + std::to_string(ID) + "' }");
}
```
does not give a default printout from 
```
util.format("%s", myobject);
```
instead you have to call
```
util.format("%s", myObject.toString());
```
explicitely. Note that I'm a C++ programmer so I probably miss something obvious.

**Comment by mhdawson** [comment]
@KevinEady did a quick check with:

```JavaScript
const object1 = {};

Object.defineProperty(object1, 'property1', {
  get: () => 42,
  enumerable: true, configurable: true
});

17:25:24.068 {}
17:25:26.218 object1
17:25:26.220 {}
17:25:34.629 Object.getOwnPropertyNames(object1)
17:25:34.631 ['property
```

So the behavior seems to be consistent across JavaScript/addons with node-addon-api.

**Comment by wass** [comment]
Ok, thank you! It would be nice if there was an easy way to list the contents of a node-addon-api lib. I've just wrapped a massive C++ library and it is challenging for the user to figure out what is included without constantly reading the old C++ documentation.
