### ISSUE TITLE
Boilerplate-less way to write node-addon-api code

### ISSUE THREAD

**Issue by ajihyf** [nodejs/node-addon-api#1163]
I've implemented https://github.com/ajihyf/node-addon-api-helper which may help to write boilerplate-less node-addon-api code.
There is another issue https://github.com/nodejs/node-addon-api/issues/294 but not active for a while. Though WebIDL isn't supported currently, the approach is more straightforward in a pure header way.
Feedback is welcome. :)

**Comment by mhdawson** [comment]
It's great to see higher layers build on node-addon-api. I won't have time to review in detail but just wanted to say that further layers on top were one of the things we were hoping for and there are many things we won't add to node-addon-api itself but which make sense in higher layer wrappers.
