### ISSUE TITLE
Help! I want to use our api like this. How should I do?

### ISSUE THREAD

**Issue by ToTheEnd7788** [nodejs/node-addon-api#1166]
<font color="orange">**As you guys see the below logics process**</font>
I just want to use emitter in callback which called by third part function, I am a fresh_user of node-addon-api and  cpp. Maybe the way of my using is not correct. Could you guys help me to resolve this need. 

### x.js
```.js
const addon = require("bindings")("x");
const { EventEmitter } = require("events");

const emitter = new EventEmitter();
// listeners
emitter.on('connected', () => console.log("Connected..."));
emitter.on(“data”, data => console.log("Data: ", data));

addon.init(emitter.emit.bind(emitter));
```
### x.cc
```.cc
#include <napi.h>
#include "third_part.h" // Has function named "ThirdPartyFunction"

// Define a global EventEmitter
Napi::FunctionReference EventEmitter;

// third_part function need to call below:
void callback(int id)
{
   // ... Sql data from db, and then call 'EventEmitter' function
   EventEmitter.Call({
       Napi::String::New(EventEmitter.Env(), "data"),
       Napi::String::New("Data From db which based on param id")
   });
   // When run x.js, and it's  called by third_part function, I get error:  
   //    #  Entering the v8 API without proper locking in place
}

Napi:: Initializer(const Napi::CallBackInfo& info)
{
    Napi::Env env = info.Env();
    EventEmitter = Napi::Persistent(info[0].As<Napi::Function>());
    EventEmitter.Call({ Napi::String::New(EventEmitter.Env(), "connected") });
    
     // !!!!!!! It's a third part function, and I can't change it!!
     ThirdPartyFunction(callback);
}

Napi::Object Init(Napi::Env env, Napi::Object exports)
{
    exports.Set(
       Napi::String::New(env, "init"),
       Napi::Function::New(env, Initializer)
    );

   return exports;
}

NODE_API_MODULE(test, Init);
```
'connected' event can work, but when third part function called **callback**,  get Error:
```
#
# Fatal error in HandleScope::HandleScope
# Entering the v8 API without proper locking in place
#
```

**Comment by ToTheEnd7788** [comment]
Why nobody can help me!!!

**Comment by KevinEady** [comment]
Hi @ToTheEnd7788 ,

You cannot call Node APIs outside of the Node thread. You will need to use any one of the Node multi-threading APIs. See [Async Operations](https://github.com/nodejs/node-addon-api/blob/main/doc/async_operations.md) and [Thread-safe Functions](https://github.com/nodejs/node-addon-api/blob/main/doc/threadsafe.md). From your use-case, the thread-safe function may be your best bet.

Let us know if this helps.

Thanks, Kevin

**Comment by ToTheEnd7788** [comment]
Hi @KevinEady 
I check the relative documents about Thread-safe Function, I think I had understood the usage way about my case, Thank You!
I'll close this after this reply
