### ISSUE TITLE
Next release - Drop support for 12.x

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#1169]
We should plan for a release soon after the end of April.

@NickNaso do you want to do the release?

**Comment by NickNaso** [comment]
Yes I can work at the next release v4.4.0. 
Please @nodejs/node-api take a look at PRs and see if we need something to be approved before to move on with the next release.

**Comment by mhdawson** [comment]
@NickNaso thanks. I don't see any PRs that I think we should wait for.

**Comment by NickNaso** [comment]
I'm starting to work on release.

**Comment by NickNaso** [comment]
CI:
| Version | Job | Status |
|---:|---|:---:|
| main | https://ci.nodejs.org/job/node-test-node-addon-api-new/5847/ | ✓ |
| v18.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/5848/ | ✓ |
| v16.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/5849/ | ✓ |
| v14.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/5850/ | ✓ |

**Comment by NickNaso** [comment]
The release v5.0.0 has been published.
