### ISSUE TITLE
Could you please make async itreator on plain C source example

### ISSUE THREAD

**Issue by vit1251** [nodejs/node-addon-api#1171]
Coudl you please provide async iterator implementation on pure C source code example?

**Comment by NickNaso** [comment]
What do you mean for async iterator could you explain better your need? Could you post an example?

**Comment by vit1251** [comment]
Example use C impoementation Node source code for:
```
for await (const item of napi.invoke()) {
  // processing item here...
}
```
It should stop iteration until iteration protocol is provide next promise item and resolve it.
This may using in process BigData array storage on Node side.

**Comment by KevinEady** [comment]
Hi @vit1251 ,

We discussed this in the 13 May Node API meeting. 

A JavaScript iterator is just an object that provides a standard structure. I will try to create an example for you and publish it in the examples for node-addon-api.

Thanks, Kevin

**Comment by KevinEady** [comment]
Hi @vit1251 ,

We added an async iterator example backed by threadsafe functions in our node-addon-examples repo: https://github.com/nodejs/node-addon-examples/tree/main/threadsafe-async-iterator/node-addon-api

Does this help in your use-case?

Thanks, Kevin

**Comment by KevinEady** [comment]
I'm not sure what you mean by "deprecated C++ API": node-addon-api is not deprecated at all. There is basically a 1:1 mapping of node-addon-api with the underlying Node-API calls, so it should be fairly straightforward to port. Let me know if you have any questions.

**Comment by vit1251** [comment]
@KevinEady so I got the wrong impression, as I meet with bugs in outdated native C++ modules (Node version mismatch) and assumed that the C variant with the portable ABI is more modern. Thanks.
