### ISSUE TITLE
eslint issue on Windows

### ISSUE THREAD

**Issue by egg-bread** [nodejs/node-addon-api#1175]
When running `npm run lint:fix` on Windows bash, lint doesn't actually work:
![image](https://user-images.githubusercontent.com/38633553/167314968-147d74c6-d8e7-42eb-9c3a-662038dcc3c9.png)

But when the eslint path is changed to `node_modules\\.bin\\eslint.cmd` in tools/eslint-format.js, lint works.

**Comment by JckXia** [comment]
Fixed with https://github.com/nodejs/node-addon-api/pull/1176
