### ISSUE TITLE
Converting UInt8Array from nodejs to c++ vector or array

### ISSUE THREAD

**Issue by Victor-99** [nodejs/node-addon-api#1178]
I have been trying to use node-addon-api to generate a module from c++. I have an UInt8Array as an input from the nodejs function. After days of attempts, I am able to grasp that UInt8Array in the index.cpp file, but not able to convert it to c++ datatypes such as `std::array` or `std::vector`. For Integer type or String type, I can cast it to using `ToNumber()` or `ToString()`. But for direct conversion of buffer, I am not able to figure out any approach. I do not have in depth knowledge on this concept. Please highlight ways to proceed with the conversion.

### Node side example call: 
`someModuleName(UIntArray.from([10,20,30,40]));`

### Index.cpp side call: 
Header used: `#include <napi.h>`
Data fetching: `Napi:: Buffer<uint8_t> bufferName = info[0].As<Buffer<uint8_t>>();`

**Comment by KevinEady** [comment]
Hi @Victor-99 , 

We discussed this in the 13 May Node API Meeting. We thought of two different approaches:
1. You may be able to use the Buffer's `Data()` and `Length()` in the `std::vector` constructor. Note that this will perform a copy of the data into the vector.
2. If you are using C++20 you can also use `std::span` which does not perform a copy like `std::vector`.
3. The [`ArrayBuffer::New`](https://github.com/nodejs/node-addon-api/blob/main/doc/array_buffer.md#new-1) method allows passing a pointer to data and the length. You will be able to modify the data of the `ArrayBuffer` on the JavaScript side (but not the size) and these changes should be propagated to the underlying data stored in the vector.

Let us know if you have any additional questions or concerns.

Thanks, Kevin

**Comment by Victor-99** [comment]
Hi @KevinEady 

Thank you for the response. I was able to fetch the data using `Data()`. However, while converting the fetched data back using `New()` I am getting an unusual error in the node function call. The c++ code compiles fine. But when calling the function on nodeJS side, it throws the following. It could be a newbie mistake I am making. Pardon me for that.

Index.cpp function:
```
Napi::Buffer<uint8_t> someFunction(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();
    Napi::Buffer<uint8_t> buffer = info[0].As<Napi::Buffer<uint8_t>>();
    uint8_t* res = buffer.Data();
    size_t length = buffer.ElementLength();
    return Napi::Buffer<uint8_t>::New(env,res,length);
}
```

Nodejs function call:
```
someData = hello.PrintHello(
    Uint8Array.from(
        [10,20,30]
        )
    )
console.log(someData);
```

Response I am getting:
```

#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 0x7ffc549cb160
 1: 0xb76401  [node]
 2: 0x1c09824 V8_Fatal(char const*, ...) [node]
 3: 0xfcecb1 v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) [node]
 4: 0xd204f8 v8::ArrayBuffer::GetBackingStore() [node]
 5: 0xabdc90 napi_get_typedarray_info [node]
 6: 0x7f3dac9f7ee5 someFunction(Napi::CallbackInfo const&) [/home/somePath/build/Release/sayHello.node]
 7: 0x7f3dac9f8b3e Napi::details::CallbackData<Napi::Buffer<unsigned char> (*)(Napi::CallbackInfo const&), Napi::Buffer<unsigned char> >::Wrapper(napi_env__*, napi_callback_info__*) [/home/somePath/build/Release/sayHello.node]
 8: 0xab45dd  [node]
 9: 0xd552fe  [node]
10: 0xd5671f v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x15f2179  [node]
Trace/breakpoint trap (core dumped)
```

If I replace return type in index.cpp from `return Napi::Buffer<uint8_t>::New(env,res,length);` to `return buffer`. It works fine. 


Also, I am curious about how the memory usage using `New()` will be. Will it create a new Buffer. Also, If it will automatically free the occupied space once the function call is complete.

**Comment by vmoroz** [comment]
@Victor-99, I had created a PR for the example that shows how to read and create `Uint8Array` in native code:
https://github.com/nodejs/node-addon-examples/pull/197
Please let me know if you want to see some other scenarios there.

**Comment by Victor-99** [comment]
Hi @KevinEady apologies for the confusion. I was trying to explore ways to fit in the data sent to c++ module. I was able to fetch the data using `Data()`. Only struggle I was facing was with the `New()`. Following the documents, I was trying to replicate `New(napi_env env, T* data, size_t length);` function call. When adding the pointer fetched using `Data()`, it throws error while running on node side, though the program compiles fine. For newly created pointers to some array, `New()` works fine. I was curious why that case fails and how the `New()` works in underlying architecture.

@vmoroz Thank you for the examples. I feel you have covered the basic scenario, and will be of much help in conversions required. We can close the thread as main objective is clarified and achieved.

**Comment by KevinEady** [comment]
Closing as per last comment from OP.
