### ISSUE TITLE
Freeing memory of AsyncWorker

### ISSUE THREAD

**Issue by hovnatan** [nodejs/node-addon-api#1181]
In https://github.com/nodejs/node-addon-api/blob/dc4f2bbe4a274184783d6ed9c2cc6de35627f8df/test/async_worker.cc#L13 the memory is allocated but never freed (with `delete` probably). Isn't this a memory leak? Thanks!

**Comment by mhdawson** [comment]
I'd have to spend more time to be 100% sure but I believe it likely cleans itself up because of this in the class it extends:

https://github.com/nodejs/node-addon-api/blob/dc4f2bbe4a274184783d6ed9c2cc6de35627f8df/napi-inl.h#L4910

When OnWorkComplete runs it calls Destroy to clean itself up.

**Comment by hovnatan** [comment]
Thanks! That explains it.
