### ISSUE TITLE
How to return multiple variables from a function

### ISSUE THREAD

**Issue by Jupiter1973** [nodejs/node-addon-api#1182]
I am a beginner in NAPI. My function returns something like this: Isn't there a more concise way?
The following data may be further added.
The return value is passed to the web as json from index.js.

As you can see, the cost problem that occurs for each function is a bigger drawback than the length problem. Is there a way in C++ to put those values ​​in an array and pass it to ret as an array?
ret.Set('result', Napi::Array::New(env, this->getData()->getResult());
As you know this isn't working.

```
Napi::value module_addon::SetData(const Napi::Env env){
  Napi::Object ret = Napi::Object::New(env);

  /* Is there any way to make this shorter? */
  ret.Set("Count", Napi::Number::New(env, this->wxr->getCount()));
  ret.Set("page", Napi::Number::New(env, this->getData()->getBkgnd()->num));
  ret.Set("width", Napi::Number::New(env, this->getData()->getBkgnd()->width));
  ret.Set("height", Napi::Number::New(env, this->getData()->getBkgnd()->heigt));
  ret.Set("size", Napi::Number::New(env, this->getData()->getBkgnd()->size));
  ret.Set("adr", Napi::Number::New(env, this->getData()->getBkgnd()->adr));
  ret.Set("txt", Napi::Number::New(env, this->getData()->char));

 return ret;
}

/* index.js */
  ......
  prev = new testAddon.Example();
  resData = prev.setData(num);

  res.json(resData);
```
Thanks for reading

**Comment by NickNaso** [comment]
Hi @Jupiter1973,
maybe you could use this way to create the object:
```cpp
Napi::value module_addon::SetData(const Napi::Env env){
  Napi::Object ret = Napi::Object::New(env);
  ret["Count"] = this->wxr->getCount();
  ret["Count"]= this->getData()->getBkgnd()->num;
  ret[Count""] = this->getData()->getBkgnd()->width;
  ret["Count"]= this->getData()->getBkgnd()->heigt;
  ret["Count"] = this->getData()->getBkgnd()->size;
  ret["Count"] =  this->getData()->getBkgnd()->adr;
  ret["Count"] =  this->getData()->char;

 return ret;
}
```

**Comment by Jupiter1973** [comment]
> Hi @Jupiter1973, maybe you could use this way to create the object:
> 
> ```c++
> Napi::value module_addon::SetData(const Napi::Env env){
>   Napi::Object ret = Napi::Object::New(env);
>   ret["Count"] = this->wxr->getCount();
>   ret["Count"]= this->getData()->getBkgnd()->num;
>   ret[Count""] = this->getData()->getBkgnd()->width;
>   ret["Count"]= this->getData()->getBkgnd()->heigt;
>   ret["Count"] = this->getData()->getBkgnd()->size;
>   ret["Count"] =  this->getData()->getBkgnd()->adr;
>   ret["Count"] =  this->getData()->char;
> 
>  return ret;
> }
> ```
There was a mistake in my code count. But your answer gave me a hint. In C++, putting values ​​in an array and passing the array to ret.
Is there a way to pass an array to ret?

**Comment by Jupiter1973** [comment]
> Hi @Jupiter1973, maybe you could use this way to create the object:
> 
> ```c++
> Napi::value module_addon::SetData(const Napi::Env env){
>   Napi::Object ret = Napi::Object::New(env);
>   ret["Count"] = this->wxr->getCount();
>   ret["Count"]= this->getData()->getBkgnd()->num;
>   ret[Count""] = this->getData()->getBkgnd()->width;
>   ret["Count"]= this->getData()->getBkgnd()->heigt;
>   ret["Count"] = this->getData()->getBkgnd()->size;
>   ret["Count"] =  this->getData()->getBkgnd()->adr;
>   ret["Count"] =  this->getData()->char;
> 
>  return ret;
> }
> ```
