### ISSUE TITLE
how to manage object lifecpan like FunctionReference ?

### ISSUE THREAD

**Issue by codenot** [nodejs/node-addon-api#1188]
i look the example。 when addon return object， we need write 
```  
Napi::Object Init(Napi::Env env, Napi::Object exports) {
  Napi::Function func = MyObject::GetClass(env);

  Napi::FunctionReference* constructor = new Napi::FunctionReference();
  *constructor = Napi::Persistent(func);
  env.SetInstanceData(constructor);

  exports.Set("MyObject", func);
  return exports;
}  
```

but if we return multi object, how to write  FunctionReference ?

``` 
Napi::Object Init(Napi::Env env, Napi::Object exports) {
    exports.Set(Napi::String::New(env, "In"), InternalInWrap::GetClass(env));
    exports.Set(Napi::String::New(env, "Out"), InternalOutWrap::GetClass(env));
    exports.Set(Napi::String::New(env, "SctpIn"), SctpInWrap::GetClass(env));
    exports.Set(Napi::String::New(env, "SctpOut"), SctpOutWrap::GetClass(env));
    
    return exports;
}
```

and i tried, use FunctionReference or not ,  Does not affect the program to run.

**Comment by KevinEady** [comment]
Hi @codenot ,

`SetInstanceData` only allows one value to be persisted -- any additional calls to this function will overwrite the previous instance data. 

It looks like you are using `ObjectWrap`, so what you can do is create an `Object` with the properties of this object being the constructors returned by your `InternalInWrap::GetClass(env)`, then use an `ObjectReference` to persist this inside the `SetInstanceData`.

Then you can construct your objects on the native side by getting the instance data as an `ObjectReference` and accessing the specific properties for whichever class you want to construct.

Does this help?

**Comment by codenot** [comment]
@KevinEady ，

yes, i use ObjectWrap to return object to js。
 
```
Napi::Object Init(Napi::Env env, Napi::Object exports)
{
    exports.Set(Napi::String::New(env, "In"), InternalInWrap::GetClass(env));
    exports.Set(Napi::String::New(env, "Out"), InternalOutWrap::GetClass(env));
    exports.Set(Napi::String::New(env, "SctpIn"), SctpInWrap::GetClass(env));
    exports.Set(Napi::String::New(env, "SctpOut"), SctpOutWrap::GetClass(env));

    Napi::ObjectReference* constructor = new Napi::ObjectReference();
    *constructor = Napi::Persistent(exports);
    env.SetInstanceData(constructor);

    return exports;
}
```
now i know to use ObjectReference.


---

I still have a question, why is it necessary to use it

```
var addon = require('addon');
var object = new addon.In();
...
console.log(object.xxx)
```

the above codes works without Reference.

**Comment by codenot** [comment]
@NickNaso @KevinEady  thx。 i got it.
