### ISSUE TITLE
tests failing after landing PRs for next release

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#119]
Just landed 117, 115, 114, 112 after talking with @gabrielschulhof about putting out a new release.

Unfortunately when I went to run the tests as a check before doing the release I'm getting:

```
> node-addon-api@0.6.3 test /home/mhdawson/newpull/land/node-addon-api
> node test

Starting test suite

Running test 'arraybuffer'
module.js:602
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/home/mhdawson/newpull/land/node-addon-api/test/build/Release/binding.node'
was compiled against the ABI-stable Node.js API (N-API).
This feature is experimental and must be enabled on the
command-line by adding --napi-modules.
    at Object.Module._extensions..node (module.js:602:18)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mhdawson/newpull/land/node-addon-api/test/arraybuffer.js:6:6)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
npm ERR! Test failed.  See above for more details.
-sh-4.2$ echo $NODE_PTIONS
```

I manged to get the tests to compile by make sure that `--napi-modules` was not set when the module was built, and then set when it is built,  but it looks like this commit is causing problems if you try to test with master:

```
commit 2b4e2d9a4b6436aa2bb92fa1477944d865f59e27
Author: Gabriel Schulhof <gabriel.schulhof@intel.com>
Date:   Mon Aug 21 22:50:22 2017 +0300

    Use a version check to determine if N-API is internal

    PR-URL: https://github.com/nodejs/node-addon-api/pull/114
    Reviewed-By: Michael Dawson <michael_dawson@ca.ibm.com>

```

**Comment by mhdawson** [comment]
@gabrielschulhof

**Comment by mhdawson** [comment]
It used to run when using

```
NODE_BUILD=/home/mhdawson/newpull/io.js
export PATH=$NODE_BUILD:$NODE_BUILD/../abi-stable-node-addon-examples/node_modules/node-gyp/bin/:$PATH
export NPM=$NODE_BUILD/deps/npm/bin/npm-cli.js
alias npm=$NPM
alias node-gyp=node-gyp.js
export npm_config_nodedir=$NODE_BUILD
```

and making sure `NODE_OPTIONS` was NOT set.

**Comment by mhdawson** [comment]
Just updating to latest version of master to make sure I see the same behavior there.

**Comment by mhdawson** [comment]
Recreates with latest master.

My guess is problem is related to updates in getNodeApiBuiltin that were part of 114.

@gabrielschulhof can you take a look its pretty much of the end of my day.

**Comment by gabrielschulhof** [comment]
@mhdawson I can't reproduce this. I made sure that all paths point to my node repo in `/home/nix/node/node`. In a fresh terminal, I can paste
```
export NODE_BUILD=/home/nix/node/node
export PATH="${NODE_BUILD}:${NODE_BUILD}/deps/npm/bin/node-gyp-bin:${NODE_BUILD}/deps/npm/bin:${PATH}"
export npm_config_nodedir=${NODE_BUILD}
alias npm=${NODE_BUILD}/deps/npm/bin/npm-cli.js
npm test
```
and it will run successfully. NODE_OPTIONS is not present in the environment.

**Comment by gabrielschulhof** [comment]
`npm test` works on released versions 6 and 8, but on 4 and 5.5.0 it attempt to use `Buffer.alloc()` which is not present (#120).

**Comment by gabrielschulhof** [comment]
@mhdawson the tests should pass on all versions of node including master after you add #121 and #122.

**Comment by mhdawson** [comment]
Landed 121 and 122, tests now pass will create release later this afternoon

**Comment by mhdawson** [comment]
Ok new release published.
