### ISSUE TITLE
Add node-gyp to package.json

### ISSUE THREAD

**Issue by grosch** [nodejs/node-addon-api#1192]
Would you please add an explicit node-gyp dependency to the package.json so that yarn stops complaining about it?  Thanks.

**Comment by grosch** [comment]
If using yarn 2/3 then yes, it will complain about that missing dependency.  However, yarn 2/3 has too many issues with things like 'ng add' so I went back to yarn 1.

**Comment by mhdawson** [comment]
@grosch I'm going to close this. Please let us know if you think that was not the right thing to do.
