### ISSUE TITLE
Is it possible to combine JS and C++ code on the same addon?

### ISSUE THREAD

**Issue by almosnow** [nodejs/node-addon-api#1194]
Hello all,

I'm building an addon that is pretty much an interface to a C++ library, it works well,

Thing is, I would like to provide regular JS functions alongside the ones exposed by the addon, like,

```
    addon
      |-- method_a(arguments): function that runs on the C++ object program
      |    ...
      |-- method_b: regular JS functions written in JS, as if it was Node (<-- this I don't know if it possible)

```

The reason for this is that there's plenty of utility functions (to cleanup arguments, set default parameters, perform variable checks, etc...) that I would like to ship alongside my node addon (i.e. part of the same package) but it would be much easier to program them in JS than on C++.

Is this possible?

Thanks.

**Comment by mhdawson** [comment]
I don't think we've thought specifically about that use case. Some ptions that come to mind that I think would work include:

1) You can wrap the addon in another JavaScript file and that export methods from both the addon and the JavaScript file on the export.
2) You can add methods to an addon after requiring it just like any other JavaScript Object.
3) In your Init method for the addon could could somehow lookup and add methods to the object being returned.

However I don't think any those except possibly the first help with packing regular methods along with the ones from the addon.

**Comment by almosnow** [comment]
Thanks for the info, @mhdawson!
