### ISSUE TITLE
Napi::HandleScope::HandleScope(const Napi::HandleScope &)cannot be referenced -- it is a deleted function

### ISSUE THREAD

**Issue by westlakem** [nodejs/node-addon-api#1197]
Disclamer: I know very little about C++.

When trying to convert an open source project from NAN to napi, I'm getting the following error when trying to ref a HandleScope object.

function "Napi::HandleScope::HandleScope(const Napi::HandleScope &)" (declared at line 2269 of "D:\devl\js\fsuipc-node\node_modules\node-addon-api\napi.h") cannot be referenced -- it is a deleted function

converting 
``` Nan::HandleScope scope;```
to
``` Napi::HandleScope::HandleScope(Napi::Env env);```
as referenced https://github.com/nodejs/node-addon-api/blob/main/doc/handle_scope.md

**Comment by legendecas** [comment]
You should be able to create a handle scope with a similar pattern in NAN:

```
// 'env' is a 'Napi::Env';
Napi::HandleScope scope(env);
```

The pattern in the document shows the declaration of the `Napi::HandleScope` constructor. It is not meant to be constructed in that way.

I believe we need an example in the HandleScope documentation.

**Comment by mhdawson** [comment]
@KevinEady will take a look at updating the documentation.
