### ISSUE TITLE
Building with clang-16 error `-Wenum-constexpr-conversion`

### ISSUE THREAD

**Issue by ammarfaizi2** [nodejs/node-addon-api#1198]
Hi,

Building with clang-16 error `-Wenum-constexpr-conversion`:

```
napi.h:1173:7: error: integer value -1 is outside the valid range of values [0, 15] for this enumeration type [-Wenum-constexpr-conversion]
      static_cast<napi_typedarray_type>(-1);
      ^
1 error generated.
```

**Comment by NickNaso** [comment]
Hi @ammarfaizi2,
I think that this issue is correlate with PR https://github.com/nodejs/node-addon-api/issues/1066 and issue https://github.com/nodejs/node-addon-api/issues/1066 wea re working on solve it. Thanks for reporting.

**Comment by NickNaso** [comment]
I'm closing the issue because it has been solved with PR https://github.com/nodejs/node-addon-api/pull/1209
