### ISSUE TITLE
No return value

### ISSUE THREAD

**Issue by donovanhiland** [nodejs/node-addon-api#1205]
Hello there.

I'm running in to the exact same issue as described by #425 . I figured I'd open up a new issue rather than continue in that one since it's been closed for a while.

I've run through all the suggestions including getting hooked up to lldb with the pause on exceptions option checked as @legraphista suggested in #425. 

The code works fine up until the point where I return a value from my Napi function. No exceptions are thrown, nothing. What I did notice is that the program no longer executes past that point. I set up a polling test to continually call the function on an interval and after the point where I don't receive a value the program hangs. No more function calls come through.

Any ideas there? Not sure how much I can post which I know is a real buzz kill but happy to share/try whatever I can.

**Comment by mhdawson** [comment]
@donovanhiland without seeing the code for the method trying to return the value it's going to be very hard to help.

This example includes a return value - https://github.com/nodejs/node-addon-examples/blob/main/2_function_arguments/node-addon-api/addon.cc so you could try working from a simple implementation like that towards what you have and see where it breaks as you add/introduce changes.

**Comment by donovanhiland** [comment]
@mhdawson Thanks for your response. After hacking on this for a few days I'm fairly confident the issue lives in a third party library we are using. I'm not sure why the debugger leads me through a successful function call and return value only to fail after the return but it must have just been a weird timing issue.
