### ISSUE TITLE
[QUESTION] callback function from JS to be passed in C++ utility functions.

### ISSUE THREAD

**Issue by rahul7822** [nodejs/node-addon-api#1215]
Hi,
I am new to *node-addon-api*, I can get a callback function from JS into C++ and the JS callback function can be executed correctly in C++. I am stuck at the following situation. 

I would be grateful if anybody can help. I went through many documentation and examples etc. but I couldn't find anything related to this.

I want the callback function to be passed in a utility function from the function where it has been received in the C++ side, (to be precise, I want to use it in a std::thread, so that if a condition is met, the callback function should be called and I will use the values in JS for further processing.)

My sample code is as below

### app.js
```
const { receiveCB } = require("./lib/binding.js");

let cbFun = function (msg) {
  console.log("callback Fun is called :", msg);
};

receiveCB(cbFun);
```
### binding.js
```
const addon = require("../build/Release/cbtest-native");
module.exports = { receiveCB: addon.receiveCB };
```
### cbtest.cc
```
#include <napi.h>
#include <iostream>

using namespace std;
using namespace Napi;

void utilityFun(Napi::Function cb) {
  //here I want to execute the callback received from JS
  //cb.Call(Env::Global, Napi::String::New(NULL, "Hello from utilityFun"));
}

void receiveCB(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  Napi::Function cb = info[0].As<Napi::Function>();

  //this works
  cb.Call(env.Global(), { Napi::String::New(env, "Hello from C++") });

  //need help in this call, how to achieve this ?
  utilityFun(cb);
}

Napi::Object Init(Napi::Env env, Napi::Object exports) {
  exports.Set(Napi::String::New(env, "receiveCB"), Napi::Function::New(env, receiveCB));
  return exports;
}

NODE_API_MODULE(addon, Init)
```

**Comment by JckXia** [comment]
Hey there! I believe if you want to invoke the callback from a util function, you'd have to pass the corresponding `env` variable as an argument parameter to `utilityFun`.  Also your string instantiation should also take this env as a parameter `String::New(env, "Hello from utilFun")` .

Regarding using `std::thread` with this setup, I'd recommend taking a look at `ThreadSafeFunctions` https://github.com/nodejs/node-addon-api/blob/main/doc/typed_threadsafe_function.md.

**Comment by rahul7822** [comment]
Hi @JckXia, Thanks for you quick response.
I tried you suggestion as below, but it doesn't work, I get the following error. The code doesn't even compile.

![image](https://user-images.githubusercontent.com/13984990/194455916-55e92cc2-1025-46e2-9e0f-02f340f1bae0.png)

```
void utilityFun(Napi::Env env,Napi::Function cb) {
  //here I want to execute the callback received from JS
  cb.Call(env.Global(), Napi::String::New(NULL, "Hello from utilityFun"));
}

void receiveCB(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  Napi::Function cb = info[0].As<Napi::Function>();

  //this works
  cb.Call(env.Global(), { Napi::String::New(env, "Hello from C++") });

  //need help in this call, how to achieve this ?
  utilityFun(env,cb);
}
```
I even tried passing the utilityFun arguments as references, tried many things, but still no success.

**Comment by JckXia** [comment]
I see that you are instantiating the string with a `NULL`  here on line `Napi::String::New(NULL, "Hello from utilityFun")`. From what I understand, the first parameter needs to be the environment, which is the first argument of `utilityFun`. This is probably why the compiler is telling you that none of the `String::New` overloads can be called when the first arg is NULL. This is my code snippet which seems to work as intended:

```
void utilityFun(Napi::Function cb, Napi::Env env) {
  //here I want to execute the callback received from JS
 // cb.Call(env, Napi::String::New(NULL, "Hello from utilityFun");
  cb.Call(env.Global(), { Napi::String::New(env, "Hello from C++") });
}
```
Please give this a shot and let me if it works! :)

**Comment by haoxi911** [comment]
Hello, you might want to take a look at the `node-addon-examples` repository, more specifically, [this](https://github.com/nodejs/node-addon-examples/blob/main/promise-callback-demo/node-addon-api/src/promise_callback_demo.cc) example seems to be what you're looking for.

**Comment by rahul7822** [comment]
Hi @JckXia @haoxi911 ,
I did not place curly braces ({}) around this 
` Napi::String::New(NULL, "Hello from utilityFun")`
this is where the main problem occurred. 

And the link about ThreadSafeFunctions shared by @JckXia was very helpful. I could use it in my application.

Thank you, guys!
