### ISSUE TITLE
Create new release for node-addon-api 5.1.0

### ISSUE THREAD

**Issue by KevinEady** [nodejs/node-addon-api#1217]
We discussed on the 7 Oct Node API meeting: There have been several PRs that have been merged (or waiting to be merged) that fix behavior of APIs. We should look into performing a new release.

Interesting PRs:
- #1216 
- #1209
- #1242 
- #1245

**Comment by mhdawson** [comment]
Seems like we should be ready to do a realease. @NickNaso would you like to do this one?

**Comment by NickNaso** [comment]
Yes I can make the release. Inviato da iPhoneIl giorno 6 gen 2023, alle ore 17:32, Michael Dawson ***@***.***> ha scritto:﻿
Seems like we should be ready to do a realease. @NickNaso would you like to do this one?

**Comment by NickNaso** [comment]
I'm starting to make a new release.

**Comment by NickNaso** [comment]
CI:
| Version | Job | Status |
|---:|---|:---:|
| v19.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/6864/ | ✓ |
| v18.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/6865/ | ✓ |
| v16.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/6866/ | ✓ |
| v14.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/6867/ | ✓ |

**Comment by NickNaso** [comment]
The release has been created.
