### ISSUE TITLE
node-addon-api is not support Context-aware addons, so electron14 or higher will crash(app.allowRendererProcessReuse = true)

### ISSUE THREAD

**Issue by Candylong** [nodejs/node-addon-api#1223]

**Comment by NickNaso** [comment]
Hi @Candylong,
I don't know electron, but `node-addon-api` should support the contex-aware addons thanks to `Napi::Addon` class and `NODE_API_ADDON` or `NODE_API_NAMED_ADDON` macros. You can find the documentation and a basic example here: https://github.com/nodejs/node-addon-api/blob/main/doc/addon.md#add-on-structure 
Let us know if this information helped you.

**Comment by Candylong** [comment]
> Thank you very much for your reply. I will try this scheme

**Comment by NickNaso** [comment]
Is it possible to close this issue or do you need other help?
