### ISSUE TITLE
std::exception not caught

### ISSUE THREAD

**Issue by froody** [nodejs/node-addon-api#1225]
The documentation states "On return from a native method, node-addon-api will automatically convert a pending C++ exception to a JavaScript exception." but in `InstanceMethodCallbackWrapper` when I call a C++ API that throws `std::exception`, `std::terminate` is called because no exception handler is installed. If I wrap my call in something like 

```
try {
   my_api();
} catch (const std::exception &e) {
  Napi::Error::New(info.Env(), e.what()).ThrowAsJavaScriptException();
}
```

Then the exceptions are passed up to javascript, but based on my reading of the documentation I shouldn't need to do this.

**Comment by mhdawson** [comment]
Do you have a simple recreate that we can turn into a test ?

**Comment by NickNaso** [comment]
Hi @froody,

you're right only the exception of type `Napi::Error`are autimatically converted to a JavaScript exception. 

```cpp
#include <napi.h>


Napi::Value MethodCppExcpetion(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  throw std::invalid_argument("Cpp exception.");
  return env.Undefined();
}

Napi::Value MethodNapiExcpetion(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  throw Napi::Error::New(env, "Napi exception");
  return env.Undefined();
}

Napi::Object Init(Napi::Env env, Napi::Object exports) {
  exports["MethodCppExcpetion"] = Napi::Function::New(env, MethodCppExcpetion);
  exports["MethodNapiExcpetion"] = Napi::Function::New(env, MethodNapiExcpetion);
  return exports;
}

NODE_API_MODULE(NODE_GYP_MODULE_NAME, Init)
```

If you call `MethodCppExcpetion` from your JavaScript code:

```js
'use strict'

const addon = require('bindings')('addon')

addon.MethodCppExcpetion()
```
you will get something like this:

```
libc++abi: terminating with uncaught exception of type std::invalid_argument
zsh: abort      node index.js
```

If you call `MethodNapiExcpetion` from your JavaScript code:

```js
'use strict'

const addon = require('bindings')('addon')

console.log(addon.MethodNapiExcpetion())
```
you will get something like this:

```
addon.MethodNapiExcpetion()
      ^

Error: Napi exception
    at Object.<anonymous> (/Users/nicoladelgobbo/Downloads/addon/index.js:6:7)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.0.0
```
We had some discusssion about this in the past in this issue https://github.com/nodejs/node-addon-api/issues/601. The proble is the we don't know what you want to do when a C++ exception will thrown and for now we leaved this respnsibility to the developer bucause we were unsure that trasform a Cpp exception could be the best option.

At least the documentation should be changed, do you want to make a PR?

**Comment by mhdawson** [comment]
Discussed in the Node-API team meeting today and @NickNaso is going to update the docs to make it clearer.

**Comment by NickNaso** [comment]
I'm closing we updated the documentation through this PR https://github.com/nodejs/node-addon-api/pull/1241.
