### ISSUE TITLE
Electron21.2.0 Calling native node crashes

### ISSUE THREAD

**Issue by tangjianfang** [nodejs/node-addon-api#1227]
- **Error message**

> -  `ERROR:**node_bindings.cc(146)**] Fatal error in V8: **v8_ArrayBuffer_NewBackingStore When the V8 Sandbox is enabled**, ArrayBuffer backing stores must be allocated inside the sandbox address space. Please use an appropriate ArrayBuffer::Allocator to allocate these buffers.
> - Waiting for the debugger to disconnect...
> - error Command failed with exit code 3221225477.`

- **Crash dump information:**'node-addon-api\napi-inl.h'
![image](https://user-images.githubusercontent.com/14011192/199389889-14c5f096-4a7a-4b50-9f88-619b04a088a3.png)

- **Electron Official website information:** _https://www.electronjs.org/blog/v8-memory-cage_
Electron 21 and later will have the V8 Memory Cage enabled, with implications for some native modules.

**When will a node-addon-api compatible version of electron 21 or later be released?**

**Comment by NickNaso** [comment]
Hi @tangjianfang,
thanks for reporting this. We are already working on this issue https://github.com/nodejs/abi-stable-node/issues/441 and now we have a PR to fix the crash on Electron 21 or later or in gerneral with all runtime that have the V8 memory cage enabled. See: https://github.com/nodejs/node/pull/45181.

**Comment by tangjianfang** [comment]
> 
@NickNaso Thank you very much.

**Comment by Bartel-C8** [comment]
https://github.com/nodejs/node/pull/45181 This has landed. 

Any idea when it will be merged and a new release could be created? Thanks!

**Comment by mhdawson** [comment]
@Bartel-C8 it is only going to help once Electron pulls in the updated code, versus new Node.js versions.  The PR will be backported in line with the Node.js release schedule but also requires Electron updates.
