### ISSUE TITLE
Using NAPI with SIMD and pthreads

### ISSUE THREAD

**Issue by gandharva26** [nodejs/node-addon-api#1229]
I am trying to convert a C++ project that uses SIMD into a Node.js Library using NAPI
I need to compile a C++ project using this command
`g++ -O3 -std=c++11 -mavx -mavx2 -msse -msse2 -msse4 -msse4.2 -mpclmul -o bin/example1 src/*.cpp example/example1.cpp -lpthread -mcmodel=medium -static-libstdc++`

This has pthread and SIMD flags that need to be used, is there an example where SIMD and pthread flags have been used with a Node API project that I can look for? or can anyone help me how to go about it?

**Comment by NickNaso** [comment]
Hi @gandharva26,
in your `binding.gyp` you should add the right `cflags` and `cflags_cc`. Es:
```
{
  "targets": [
    {
      "target_name": "addon",
      "cflags!": [ "-fno-exceptions" ],
      "cflags_cc!": [ "-fno-exceptions" ],
      "cflags": [
          "-03",
         # Here all your CFLAGS
       ],
       "cflags_cc": [
          "-03",
         # Here all your CPPFLAGS
       ],
      "sources": [ 
        "addon.cc",
      ],
      #// .....
   }
}

```

Hope this help you. Let me know if you need other help.

**Comment by gandharva26** [comment]
Thanks!

**Comment by NickNaso** [comment]
Hi @gandharva26 I'm closing the issue let me know if you need more help.
