### ISSUE TITLE
electron 18 uses context aware plugin Napi::Addon. Sometimes Devtools reload for electron will lead to render process crash. Is there any way to locate the problem？

### ISSUE THREAD

**Issue by Candylong** [nodejs/node-addon-api#1232]
electron prompt:
Devtools was disconnected from this page........

Console output：
libc++abi: terminating with uncaught exception of type Napi::Error: 
Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.

**Comment by KevinEady** [comment]
Hi @Candylong ,

Is it possible to provide some repository / minimal reproduction of your crash? It is difficult to diagnose why you are receiving a crash without knowing which Node API features / functions you are using.

Thanks, Kevin

**Comment by Candylong** [comment]
Hi， @KevinEady ，There is a problematic context here，https://github.com/nodejs/node-addon-api/issues/1224

**Comment by Candylong** [comment]
hello, @mhdawson ,I used node-addon-api@5.0.0

**Comment by NickNaso** [comment]
Hi @Candylong I think that @mhdawson asked also for the source code that causes the crash. Is it public? Could you report an example?

**Comment by Candylong** [comment]
@NickNaso ，addon.node uses a third party library called.DLL, which has multiple threads calling back to.node, and then using thread-safe functions, crashes occur in thread-safe functions when loading.node multiple times

**Comment by mhdawson** [comment]
What we were hoping for is a simple recreate, code that we can run to recreate the crash you were seeing. Is that something you can extract/provide?

**Comment by Candylong** [comment]
@mhdawson , It is in thread-safe functions that an exception is thrown, as shown below
![image](https://user-images.githubusercontent.com/76611653/205434030-ab3bda73-20c7-4bb9-8a6d-acdd6d8c3294.png)

**Comment by Candylong** [comment]
Hi, @NickNaso @mhdawson , I have arranged my demo and put it here(https://github.com/Candylong/napi-electron-demo). I mainly run it on windows, and it can be reproduced after about 5 operations. Can you have a try

**Comment by Candylong** [comment]
> I have arranged my demo and put it here(https://github.com/Candylong/napi-electron-demo). I mainly run it on windows, and it can be reproduced after about 5 operations. Can you have a try

@NickNaso , Hi, I have arranged my demo and put it here(https://github.com/Candylong/napi-electron-demo). I mainly run it on windows, and it can be reproduced after about 5 operations. Can you have a try

**Comment by Candylong** [comment]
The relevant questions are as follows，#1244

**Comment by gabrielschulhof** [comment]
I just tried to run your demo. It says "We are using Node.js 18.12.1, Chromium 110.0.5481.208, and Electron 23.2.2.", and it doesn not crash.
