### ISSUE TITLE
Get napi_callback_info from Napi::CallbackInfo?

### ISSUE THREAD

**Issue by erikjalevik** [nodejs/node-addon-api#1234]
Is there no way to get hold of the wrapped `napi_callback_info` from a `Napi::CallbackInfo`?

I need to call a function that's been written to accept the C NAPI type from one written with node-addon-api's C++ classes.

**Comment by legendecas** [comment]
It is not supported yet. But I believe it is reasonable to have a conversion method for `CallbackInfo` to `napi_callback_info` as that's how we dealt with other wrapper types.

**Comment by mhdawson** [comment]
@erikjalevik are you interested in submitting a PR?

**Comment by NickNaso** [comment]
I'm closing the issue because it has been solved by the PR https://github.com/nodejs/node-addon-api/pull/1253.
