### ISSUE TITLE
Class Env::CleanupHook should be public

### ISSUE THREAD

**Issue by julianmesa-gitkraken** [nodejs/node-addon-api#1238]
I have created a Cleanup hook using `env.AddCleanupHook(cleanup, this)` but I cannot store the hook in a member var because the class Env::CleanupHook is private.
So I cannot remove the hook calling to Remove function.
I make it public to test my app and works perfect the only issue is that I think it will be a good idea to create an empty default contructor so we can create a member class var without issue.
I can create a PR making this class public, but not sure why this class was designed to be private.

Also found an error in [line 361](https://github.com/julianmesa-gitkraken/node-addon-api/blob/main/napi.h#L361)
Then `#endif` should be betwen lines 359 - 360

**Comment by julianmesa-gitkraken** [comment]
PR made: [1240](https://github.com/nodejs/node-addon-api/pull/1240)

**Comment by NickNaso** [comment]
I'm closing the issue beacuse the PR https://github.com/nodejs/node-addon-api/pull/1240 has been merged.
