### ISSUE TITLE
Get Isolate object

### ISSUE THREAD

**Issue by theanarkh** [nodejs/node-addon-api#1248]
Hi, i write an addon by `node-addon-api`. Can i get the isolate object by `const Napi::CallbackInfo &args` insteadof `v8::Isolate::GetCurrent()`? Because the addon is also used by worker. Or i should write the addon by `NAN` or V8 Native API ?  Thanks !

**Comment by mhdawson** [comment]
node-addon-api does not expose any of the V8 API includding the isolate. If you need to use the V8 API directly then you should use NAN.

We discussed in the team meeting this week and was curious why you'd be using the isolate directly.

**Comment by theanarkh** [comment]
Thanks. I use the node-addon-api  to write some addons. But i use some V8 native APIs, such as `isolate->AddGCPrologueCallback` in addon. Maybe i should use NAN.

**Comment by mhdawson** [comment]
If you need to use those gc callbacks then NAN will be the way to go at this point.  We try to avoid anything engine specific. I can see that generically info about when gc starts/ends might not be engine specific but I'm guessing its a rare use case.

What do you do in those prologues?

**Comment by theanarkh** [comment]
I want to collect some memory information and cost time in gc callback, I think NAN might be more appropriate.
