### ISSUE TITLE
Adding some new methods

### ISSUE THREAD

**Issue by MaximeMRF** [nodejs/node-addon-api#1255]
Hello, I want to add somes methods to facilitate the development with the `node-addon-api`.
According to your contributing readme, you want that your header is thin and concise. And encourage contributer to create his proper header file.

Right now I just want to add two methods:
- the first one is a method for `Array` that check if all of items is numbers
- the second one is also a method for `Array` that check if items is strings

Can I create a pull request for these methods or create my proper header file ?

**Comment by KevinEady** [comment]
Hi @MaximeMRF ,

`node-addon-api` is generally a wrapper for the [Node-API C bindings](https://nodejs.org/docs/latest-v18.x/api/n-api.html), taking some influence from [NAN](https://github.com/nodejs/nan), with helper functions to facilitate integration. These type of user-land functions you are suggesting do not really warrant inclusion in `node-addon-api` in my opinion. These should be in your own application, or inside another helper library that you can publish yourself. 

Hope this helps.

Thanks, Kevin
