### ISSUE TITLE
Provide a new `Buffer::NewOrCopy` method

### ISSUE THREAD

**Issue by Julusian** [nodejs/node-addon-api#1257]
Background:
* https://github.com/nodejs/abi-stable-node/issues/441
* https://github.com/nodejs/node/pull/45181
* https://github.com/electron/electron/issues/35801

After https://github.com/nodejs/node/pull/45181 it is possible for `Buffer::new` to fail with `napi_no_external_buffers_allowed`. A helper method `Buffer::NewOrCopy` which would try to do a `Buffer::new` and fallback to doing a `Buffer::copy` would be helpful and encourage users to code in a way which provides compatibility for both electron and nodejs, without them having to implement the method themselves.

The npm package sharp has implemented this themselves already https://github.com/lovell/sharp/commit/584807b4f5e1b831785c79eef5367f737589f29b#diff-53a01d31aa585021f8f316c6613dadef86bf1f9ac2070d52daa68adbefbb6ef4.

**Comment by mhdawson** [comment]
We discussed in the team meeting today, and we agreed it would make sense to add. @legendecas volunteered to put together a PR.

**Comment by legendecas** [comment]
Landed in https://github.com/nodejs/node-addon-api/pull/1273.
