### ISSUE TITLE
Add API for working with Promises

### ISSUE THREAD

**Issue by koistya** [nodejs/node-addon-api#126]
How hard would it be to implement APIs allowing writing Promise-based N-API addons?

**Comment by jasongin** [comment]
A C API for promises was just recently implemented at https://github.com/nodejs/node/pull/14365

Now it definitely makes sense to expose that in the C++ wrapper. @gabrielschulhof are you planning to do that? Otherwise I might get to it eventually. Or someone else interested may pick it up.

**Comment by JamesMGreene** [comment]
This issue should be closed now.

**Comment by koistya** [comment]
It would be great to have some docs/examples ([`/doc/promises.md`](https://github.com/nodejs/node-addon-api/blob/e6430c2/doc/promises.md))

**Comment by NickNaso** [comment]
@koistya  We are working on documentation. Thanks for your feedback!

**Comment by NickNaso** [comment]
Hi @koistya,
now we documented the promise api https://github.com/nodejs/node-addon-api/blob/master/doc/promises.md 
What do you think should we close this issue?

**Comment by NickNaso** [comment]
I'm closing the issue because now the API to work with Promise has been added and documented.
