### ISSUE TITLE
AsyncWorker and HandleScope in the documentation example

### ISSUE THREAD

**Issue by lucakcustom** [nodejs/node-addon-api#1267]
In the documentation page of the AsyncWorker: https://github.com/nodejs/node-addon-api/blob/main/doc/async_worker.md there is an example that use HandleScope object inside the OnOK function:

```
void OnOK() override {
      HandleScope scope(Env());
      Callback().Call({Env().Null(), String::New(Env(), echo)});
}
```

I'm not 100% sure but it seems useless to me and also confusing. Why do we need an HandleScope around the Env object in this example?

In the documentation page https://github.com/nodejs/node-addon-api/blob/main/doc/object_lifetime_management.md it seems that the HandleScope is used to limit de lifespan of local objects:

`The Napi::HandleScope and Napi::EscapableHandleScope classes are provided by node-addon-api for creating additional scopes.`

Is in this case needed the HandleScope? If yes why? Otherwise can it be removed from the documentation to avoid boilerplate and make it more readable?

**Comment by JckXia** [comment]
Please correct me if I'm wrong, but from what I understand, `String::New(Env(), echo)` invokes underlying `node-api` methods to create a JS object in `v8`. I am not too sure what happens to that JS  object when the native C++ `OnOk` method is popped off from the call stack. It could be garbage collected right away, or at a later time if it's still ref'd somewhere.

 But by creating an `HandleScope`, said object will be guaranteed to be gc'd when `OnOk()` goes out of scope and `HandleScope::~HandleScope` gets ran.

**Comment by lucakcustom** [comment]
@JckXia that's exactly my doubt. But suppose now that on the method `OnOk` instead of calling a callback I resolve a promise:

```
void OnOK() {
    auto env = Env();
    auto outString= String::New(Env(), echo);
    deferred.Resolve(outString);
}
```

In this case the object outString should live after the method OnOk goes out of scope. So in this case `HandleScope` is going to be dangerous  because the output value can be piped into another promise with `then` (or used inside an async method).

Indeed when I saw the example in the documentation I thought that they wanted to force the garbage collection to get rid of echo string as soon as the OnOk method quits.
