### ISSUE TITLE
Native C++ callback function and threadsafe Segmentation fault

### ISSUE THREAD

**Issue by apiel** [nodejs/node-addon-api#1268]
Hi, I am trying to build a music addon for NodeJs, running a synthesizer engine in the background and using NodeJs to interact with it.

The synth engine is using RtAudio library to output the sound by using a callback function to generate the sound:
```C++
int audioCallback(void* outputBuffer, void* /*inputBuffer*/, unsigned int nBufferFrames,
    double /*streamTime*/, RtAudioStreamStatus status, void* data)
{
    Zic_Server::getInstance().sample((float*)outputBuffer, nBufferFrames);
    return 0;
}
//....
audio.openStream(&audioParams, NULL, FORMAT, SAMPLE_RATE, &bufferFrames, &audioCallback, (void*)data);
```
https://github.com/apiel/zicNode/blob/main/src/zic_server_audio.h#L56

To initiate this process, I am using [`ThreadSafeFunction`](https://github.com/apiel/zicNode/blob/main/src/zic.cc#L141). It is working well, as long I don't try to access `Zic_Server::getInstance()` from the NodeJs thread. But if I try to access it, for example to change the volume of the sound, or get the progress of the sound, I am getting a segmentation fault. I am guessing, this is because I am trying to access `Zic_Server::getInstance()` from both thread. I have been trying many different approach, as well using [`Napi::AsyncWorker`](https://github.com/apiel/zicNode/blob/main/src/zic.cc#L62) and [synchronous function](https://github.com/apiel/zicNode/blob/main/src/zic.cc#L112) but so far I am stuck.

Do you have any idea on how I could solve this?

**Comment by apiel** [comment]
So after debugging, it seem that it is coming from libpd, if I comment those line https://github.com/apiel/zicNode/blob/main/src/zic_audio_trackPd.h#L55,L39 that are calling libpd then it is stopping to crash. So I don't know what is going on that the libpd library is conflicting with with the NodeJs main thread.

**Comment by apiel** [comment]
The problem seem to come from the thread created by libpd when used in MULTI instance mode https://github.com/libpd/libpd/blob/master/CMakeLists.txt#L224

If I use libpd in single instance mode everything is working well. So how could I solve the problem of third party library using thread?

**Comment by KevinEady** [comment]
Hi @apiel ,

Thanks for the repo link. I was able to reproduce the issue. The exception is an `EXC_BAD_ACCESS`. Here's the call stack:

```
libpd.dylib!sys_lock (/Users/kevineady/Documents/Projects/zicNode/libpd/pure-data/src/s_inter.c:1729)
libpd.dylib!libpd_noteon (/Users/kevineady/Documents/Projects/zicNode/libpd/libpd_wrapper/z_libpd.c:536)
zic.node!Zic_Audio_Track::next() (/Users/kevineady/Documents/Projects/zicNode/src/zic_audio_track.h:58)
zic.node!Zic_Audio_Tracks::next() (/Users/kevineady/Documents/Projects/zicNode/src/zic_audio_tracks.h:67)
zic.node!Zic_Server::sample(float*, int) (/Users/kevineady/Documents/Projects/zicNode/src/zic_server.h:39)
zic.node!audioCallback(void*, void*, unsigned int, double, unsigned int, void*) (/Users/kevineady/Documents/Projects/zicNode/src/zic_server_audio.h:19)
librtaudio.6.dylib!RtApiCore::callbackEvent(unsigned int, AudioBufferList const*, AudioBufferList const*) (Unknown Source:0)
librtaudio.6.dylib!callbackHandler(unsigned int, AudioTimeStamp const*, AudioBufferList const*, AudioTimeStamp const*, AudioBufferList*, AudioTimeStamp const*, void*) (Unknown Source:0)
CoreAudio!HALC_ProxyIOContext::IOWorkLoop() (Unknown Source:0)
CoreAudio!invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) (Unknown Source:0)
CoreAudio!HALB_IOThread::Entry(void*) (Unknown Source:0)
libsystem_pthread.dylib!_pthread_start (Unknown Source:0)
libsystem_pthread.dylib!thread_start (Unknown Source:0)
```

s_inter.c:1729 corresponds to this line: https://github.com/pure-data/pure-data/blob/84e8ae4159068283380e974a6675405f59331a5e/src/s_inter.c#L1729 

See the comment above this function:
```cpp
/* routines to lock/unlock a Pd instance for thread safety.  Call pd_setinsance
first.  The "pd_this"  variable can be written and read thread-safely as it
is defined as per-thread storage. */
```

I believe you need to call `pd_setinstance()` in order to initialize this mutex. Please try this and let us know how it goes.

Thanks, Kevin
