### ISSUE TITLE
Possible breaking change in node-addon-api 5.1.0

### ISSUE THREAD

**Issue by JckXia** [nodejs/node-addon-api#1272]
Hello folks, it looks like we had some compilation issues related to the introduction of the `napi_callback_info` implicit conversion operator. [Issue link](https://github.com/nodejs/node-addon-api/pull/1253#issuecomment-1383239864).  Not too sure why this wasn't caught by our windows CI.

**Comment by JckXia** [comment]
(Just going to move our discussion over here for better visibility)

@mhdawson I think there might be a few options we can explore.

Remove the implicit conversion operator and declare the removal change a SemVer-major. Then, instead of using an implicit conversion operator, we can create an accessor function like GetCbInfo. This way people that need the raw napi_callback_info (hopefully not many since it's a fairly new change) still have a means of accessing that pointer. We also get to keep the existing API for [] overload, since a LOT of people (including us) are passing literals into info. The downside is that it seems to break conventions as we have been using implicit conversion operators to translate C++ NAPI objects to C node-API objects. But looking at std::string, there is an explicit getter c_str() function to acquire the C string equivalent makes me think if we should reconsider our approach.

Change the parameter type of the CallbackInfo::operator[](size_t index) to be int instead. I believe this way we should be able to avoid the ambiguity in question. But I don't know if this will be a breaking change for anyone because I don't understand all the nuances between size_t and int other than that size_t can potentially represent a greater range of values.

Remove the implicit conversion operator completely, but then people who might need the raw napi_callback_info is now out of luck if they had already written code around being able to access this pointer.

On a side note, I couldn't reproduce this error locally using MSVC 2019 C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe. Don't really know why that is. Going to take a deeper dive tomorrow.

**Comment by KevinEady** [comment]
Could we make the conversion function an explicit conversion only?

```cpp
explicit operator napi_callback_info() const;
```

Then the user would need to use a `static_cast<napi_callback_info>( cbInfo )` where `cbInfo` is an `Napi::CallbackInfo` object. A little more wordy but might work?

**Comment by KevinEady** [comment]
I forked the `sharp` repo at the commit where the issue was happening and pointed to my node-addon-api branch with the [explicit cast](https://github.com/nodejs/node-addon-api/compare/main...KevinEady:node-addon-api:fix-callback-info-cast-operator?expand=1). The compilation now succeeds (some job failed for what looks to be unrelated issues), eg. this successful job https://github.com/KevinEady/sharp/actions/runs/3944686124/jobs/6751171701 was failing before https://github.com/lovell/sharp/actions/runs/3924810417/jobs/6709314064 . Maybe this would be the best approach

**Comment by JckXia** [comment]
Some interesting find regarding the build issue not showing up in our current windows CI. I tweaked the `setup-node@v3` action by setting its `architecture` to x86 in this branch [node-addon-api windows CI with x86](https://github.com/JckXia/node-addon-api/commit/44a7a2f7e3d43b7632d87092870a36da4ad1b125) all a sudden this compilations error `c2666` is showing up.  [CI run results](https://github.com/JckXia/node-addon-api/actions/runs/3954928688).

Did some digging into `setup-node` and it appears by default it is running with a runner using x64 arch. What's interesting is that `sharp` didn't have an issue building with an [x64](https://github.com/lovell/sharp/actions/runs/3924810417/jobs/6709314064 ) agent. Not sure if this is a `setup-node` problem, or has to do with node itself, seeing as the other commentator didn't set the `architecture` option to x86 but opt'd to use the `--arch=ia32` cli flag instead. [node-sword-fish CI run](https://github.com/ezra-bible-app/node-sword-interface/actions/runs/3927988290/jobs/6715126782)

**Comment by mhdawson** [comment]
> Then the user would need to use a static_cast<napi_callback_info>( cbInfo ) where cbInfo is an Napi::CallbackInfo object. A little more wordy but might work?

This seems reasonable to me.

**Comment by mhdawson** [comment]
Any concerns with this suggestion? 

> Then the user would need to use a static_cast<napi_callback_info>( cbInfo ) where cbInfo is an Napi::CallbackInfo object. A little more wordy but might work?

If we are going to do this we might want to do it soon and then publish a 6.x

**Comment by kevinGodell** [comment]
I noticed breaking changes from 5.0.0 to 5.1.0 on my pi. It only occurred on the 32bit versions of pi os (tried buster and bullseye) and both failed to compile. 

just installed your latest commits directly from github `npm install nodejs/node-addon-api` and the 32bit pi is happy now and compiles ok. Thanks. Can't wait for the update to be published.

**Comment by NickNaso** [comment]
The new release v6.0.0 has been published I think that now it's possible to close thi issue if not please do not esitate to reopen.
