### ISSUE TITLE
Can Napi::Env be shared?

### ISSUE THREAD

**Issue by sunrongyi** [nodejs/node-addon-api#1282]
Can i set the Napi::Env global variable?

**Comment by JckXia** [comment]
Hi there. Do you mind share a bit more information/code about your use case? I believe `Napi::Env` is normally retrieved from the `Napi::CallbackInfo` function argument, and is not expected to be referenced as a global variable.

You could create utility functions and pass the `Napi::Env` as an argument so long as you aren't spawning native threads without using `ThreadSafeFunctions`. https://github.com/nodejs/node-addon-api/blob/main/doc/threadsafe_function.md

**Comment by sunrongyi** [comment]
#pragma once

#include <napi.h>

class ObjectWrapDemo : public Napi::ObjectWrap<ObjectWrapDemo> {
 public:
  ObjectWrapDemo(const Napi::CallbackInfo&);
  Napi::Value Greet(const Napi::CallbackInfo&);
  Napi::ArrayBuffer ReadFile(const Napi::CallbackInfo&) ;
  static Napi::Function GetClass(Napi::Env);

 private:
  std::string _greeterName;
  Napi::Env m_env;
};
Can i set Napi::Env member var?

**Comment by KevinEady** [comment]
Hi @sunrongyi ,

In general, it is not wise to store an `Env` variable. From the underlying [Node-API documentation](https://nodejs.org/api/n-api.html#napi_env):

> Caching the `napi_env` for the purpose of general reuse, and passing the `napi_env` between instances of the same addon running on different [Worker](https://nodejs.org/api/worker_threads.html#class-worker) threads is not allowed.

For your _particular_ example, `ObjectWrapDemo` extends `Napi::ObjectWrap`, which in turn extends `Reference<Object>`. References have an `Env()` member that will return the `Napi::Env`, so you could use this method on an instance of `ObjectWrapDemo` to get it.

Hope this helps. Let us know if you have any additional questions.

Thanks, Kevin

**Comment by gabrielschulhof** [comment]
@sunrongyi hopefully @KevinEady was able to answer your question. If you still need help, please reopen this issue.

**Comment by arun-mani-j** [comment]
Hii, sorry if it is the wrong place, but how do you do the same in C using `napi`? I would like to store a callback that will be called later. :)
