### ISSUE TITLE
AsyncProgressWorker not executing all .Send() calls / OnProgress() callbacks

### ISSUE THREAD

**Issue by ljp0101** [nodejs/node-addon-api#1284]
I'm using an AsyncProgressWorker to send periodic messages to the OnProgress() callback. If messages are oversized, I chunk them into multiple messages and call .Send() back-to-back as quickly as I chunk. This failed when I tried to send seven 250kb buffers. I only see one or two .Send() executions and OnProgress() callbacks, although my printf debug traces show my addon code made seven .Send() calls. If I put a 100ms delay between the .Send() calls everything works as expected.

I'm not sure if/when I'll have time to create a minimal reproducible example but happy to help if I'm able.

And last but not least, many thanks to the node-addon-api team. I've been using the project extensively and it's been a great experience, especially the documentation.

**Comment by KevinEady** [comment]
Hi @ljp0101 ,

Have you tried using `AsyncProgressQueueWorker`? In the [documentation](https://github.com/nodejs/node-addon-api/blob/main/doc/async_worker_variants.md):

> If you would like to guarantee that there is one invocation of `OnProgress` for every `Send` call, you should use the `Napi::AsyncProgressQueueWorker` class instead which is documented further down this page.

Let us know if this solves your issue.

Thanks, Kevin

**Comment by ljp0101** [comment]
Thanks @KevinEady.  Should have worked this out from the documentation. I'll probably switch over to AsyncProgressQueueWorker. I don't actually care about ordering though so if I continue to use AsyncProgressWorker the sends are consolidated and count in OnProgress() is the sum of the individual Send() counts?
