### ISSUE TITLE
why order of js func called different than order i call TypedThreadSafeFunction.BlockingCall ？

### ISSUE THREAD

**Issue by AceLearnGit** [nodejs/node-addon-api#1286]
I hava 2 js funcs(for example FuncA & FuncB) need to be called in c++
I passed these 2 js funcs to TypedThreadSafeFunction like this:
// Create a ThreadSafeFunction
  tsfn[A/B] = TSFN::New(
      env,
      info[0].As<Function>(), // JavaScript function called asynchronously,there is FuncA or FuncB
      "Resource Name",        // Name
      0,                      // Unlimited queue
      1,                      // Only one thread will use this initially
      context,
      [](Napi::Env, FinalizerDataType *,
         Context *ctx) { // Finalizer used to clean threads up
        nativeThread.join();
        delete ctx;
      });
so i get 2 tsfn objs for FuncA and FuncB named tsfnA and tsfnB
then i call tsfnA.BlockingCall first and call tsfnB.BlockingCall second immediately
I hope js funcs FuncA called first and FuncB second
but it's behaves different, some times FuncB was called first
Why? and how can i call js Func in order same like the order i call tsfn.BlockingCall

**Comment by AceLearnGit** [comment]
I also tried set maxQueueSize param as 1, but the order of  js funcs called still different than the order i call tsfn.blockingcall

**Comment by AceLearnGit** [comment]
I add some log in CallJs Func and found that callback.Call for js FuncB was called fisrt, why? Please help me.

**Comment by KevinEady** [comment]
Hi @AceLearnGit ,

According to the libuv maintainers, there is no ordering guarantee on the underlying `uv_async_*` mechanisms. Therefore, there can be no ordering guarantees for the threadsafe function either.

Please see https://github.com/libuv/libuv/discussions/3915 for info.

If this answers your question, please close the issue. Thanks!

**Comment by gabrielschulhof** [comment]
Consecutive calls to a single thread-safe function are guaranteed to result in calls to the JS functions in the same order. However, if you have two different thread-safe functions, they are independent of one another, so calls to one, followed by calls to the other, will not necessarily result in JS calls in the same order. You should use only one thread-safe function if you wish to ensure that calls happen in a certain order.

**Comment by KevinEady** [comment]
Open for three months without further feedback from OP, closing issue.
