### ISSUE TITLE
What is the intended usage of napi_get_value_string_utf8 with truncation

### ISSUE THREAD

**Issue by MSLaguana** [nodejs/node-addon-api#129]
I was looking at making some improvements to chakracore's utf8 handling, and when I came to fixing our implementation of `napi_get_value_string_utf8` I saw that it is permitted to call that function with a buffer that is too small to fit the utf8 string, and the expectation is that the string is truncated.

What is the reason for this, rather than returning an error? There is no way that I could see to request "the next N bytes" or anything similar, so it seems that the only way to pull out the whole string is all-at-once into a big-enough buffer, and if you ever pass in a buffer which is too small then you lose some information.

You can't even easily take a substring of the javascript string, since JS string indexing works based on utf16 and finding the character-offset from a byte-offset is non-trivial.

**Comment by addaleax** [comment]
Iirc that matches the behaviour that V8’s own methods for this expose. Not saying that’s a good or a bad thing, just, somebody already made the same call. :)

> You can't even easily take a substring of the javascript string, since JS string indexing works based on utf16 and finding the character-offset from a byte-offset is non-trivial.

Fwiw, that’s not true if the offset is zero…

**Comment by MSLaguana** [comment]
Sure, you can start from the start of the string again, but my first though at seeing that the result could be truncated was that there would be some form of pagination possible. It doesn't look like that is the case though.

Thanks for the quick response! Just wanted to make sure that I wasn't missing some use-case with my internal refactor.

**Comment by MSLaguana** [comment]
Yes, thanks.
