### ISSUE TITLE
Error dyld[49597]: missing symbol called, when using function from Go based C binary

### ISSUE THREAD

**Issue by jsoneaday** [nodejs/node-addon-api#1292]
Hello I'm using the Hello-world example and I've added a C header and binary compiled from a Go module. I only make two changes to the existing hello_world.cc file which is to add the include for my header and call the function from my Go module, as shown below.
I am able to build using `node-gyp configure build`. When I build without my Go module changes the existing test passes without issue. However as soon as I add those two lines, build, and run the test again (without changing the test function test_binding.js) it fails with the error given.
I have the cc extension installed in my vscode and I do not see any errors in the cc file and I am able to write click on the call to my function and it goes to the C header file export of the function.

hello_world.cc
```
#include <napi.h>
#include "../keyring.h"

using namespace Napi;

Napi::String Method(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  Get(); // my function call
  return Napi::String::New(env, "world");
}

Napi::Object Init(Napi::Env env, Napi::Object exports) {
  exports.Set(Napi::String::New(env, "HelloWorld"),
              Napi::Function::New(env, Method));
  return exports;
}

NODE_API_MODULE(addon, Init)
```

C header file
```
/* Code generated by cmd/cgo; DO NOT EDIT. */
/* package archwayhq/keyring-go/src/go */
#line 1 "cgo-builtin-export-prolog"
#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */
/* End of preamble from import "C" comments.  */

/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif
/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;
#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void Get();

#ifdef __cplusplus
}
#endif

```

**Comment by NickNaso** [comment]
Hi @jsoneaday,
I think that the error is in your `binding.gyp` file. I presume that you generated a `static c-archive` or `shered library` from Go then you should set the library in the `binding.gyp`.

Something like reported below:

```
{
  "targets": [
    {
      "target_name": "addon",
      "sources": [ "addon.cc" ],
      "include_dirs": ["."],
      "libraries": [
        "<(module_root_dir)/libgoaddon.a"
      ]
    }
  ]
}
```
Hope the could help yoou. Let me know if you need some other infotmations.

**Comment by jsoneaday** [comment]
Thank you for your help I tried it but I get the error shown. I've also included my entire gyp file.
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 45, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 654, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 621, in gyp_main
    [generator, flat_list, targets, data] = Load(
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 142, in Load
    result = gyp.input.Load(
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 3009, in Load
    LoadTargetBuildFile(
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 400, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 237, in LoadOneBuildFile
    build_file_data = eval(build_file_contents, {"__builtins__": {}}, None)
  File "binding.gyp", line 18
    "libraries": [
    ^
SyntaxError: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:284:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 22.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/davidchoi/Work/philabs/node-api/hello-world
gyp ERR! node -v v18.12.1
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 

```
{
  'targets': [
    {
      'target_name': 'hello-world-native',
      'sources': [ 'src/hello_world.cc' ],
      'include_dirs': ["<!@(node -p \"require('node-addon-api').include\")"],
      'dependencies': ["<!(node -p \"require('node-addon-api').gyp\")"],
      'cflags!': [ '-fno-exceptions' ],
      'cflags_cc!': [ '-fno-exceptions' ],
      'xcode_settings': {
        'GCC_ENABLE_CPP_EXCEPTIONS': 'YES',
        'CLANG_CXX_LIBRARY': 'libc++',
        'MACOSX_DEPLOYMENT_TARGET': '10.7'
      },
      'msvs_settings': {
        'VCCLCompilerTool': { 'ExceptionHandling': 1 },
      }
      "libraries": [
        "<!(pwd)/keyring.so"
      ]
    }
  ]
}
```

**Comment by jsoneaday** [comment]
Sorry missed the comma testing now

**Comment by jsoneaday** [comment]
Ok adding that entry did not change the error. I double checked my go build and its building to amd64, but I saw that the node build is for arm64. 
Not sure this is the issue, but would you know how to force go to compile to arm64?

**Comment by jsoneaday** [comment]
Yeah looks like that's the issue, https://gist.github.com/adrienjoly/e29a6e73fb7e701eefd80ff9bde9abeb, so will try and build my go module as arm64 and see what happens.
I will update here. Thanks again.

**Comment by jsoneaday** [comment]
Ok I forced the go module to compile as arm64 and it now works. Thanks!

`CGO_ENABLED=1 GOARCH=arm64 GOHOSTARCH=arm64 go build -trimpath -buildmode=c-shared -ldflags '-w -s -extldflags "-lresolv"' -o keyring.so -a ./src/go`
