### ISSUE TITLE
Missing Napi::Value::IsBigInt method

### ISSUE THREAD

**Issue by martingalvan-nordic** [nodejs/node-addon-api#1299]
Hi, I see `Napi::Value` has methods to determine the type of its underlying value, such as `IsNumber`, `IsObject`, etc. However, there's no such method for `Napi::BigInt`, which is a subclass of `Napi::Value`, at least according to https://github.com/nodejs/node-addon-api/blob/v6.0.0/doc/value.md

This needs to be corrected ASAP.

**Comment by mhdawson** [comment]
I'm not sure what version of node-api you are using but it exists for NAPI_VERSION 5 and greater. See https://github.com/nodejs/node-addon-api/blob/d01304437cd4c661f0eda4deb84eb34d7e533f32/napi.h#L442

**Comment by martingalvan-nordic** [comment]
@mhdawson I see. Why is this not documented in the link I posted?

**Comment by mhdawson** [comment]
@martingalvan-nordic probably just an oversight, PRs welcome
