### ISSUE TITLE
Any APIs related to V8::ScriptCompiler?

### ISSUE THREAD

**Issue by levimm** [nodejs/node-addon-api#130]
I'm trying to migrate an old addon using Nan to Napi. 

In Nan, there's API called Nan::CompileScript which will invoke v8::ScriptCompiler::Compile to compile the source javascript code. But I couldn't find any related to compile script in Napi. 

I guess I have to use both v8 part code and Napi part in the addon. However, I don't know how to convert v8::Value type to Napi::Value. 

Please advice.

**Comment by gabrielschulhof** [comment]
@nodejs/addon-api looks like we might need to implement https://github.com/nodejs/abi-stable-node/issues/51

**Comment by gabrielschulhof** [comment]
@levimm would a C++ wrapper around the API proposed in https://github.com/nodejs/abi-stable-node/issues/51 help you out?

**Comment by gabrielschulhof** [comment]
@levimm specifically, do you need support for simply executing a script, or do you need access to the intermediate step of compiling the script as well? Can you give us a link to the module you wish to port so we can have a look at your API usage pattern?

**Comment by levimm** [comment]
@gabrielschulhof Executing the script is enough for my situation. It's a self addon. Basically, related part of logic just compiles and runs the script. 
Btw, is it possible to convert construct the Napi object or value from v8 handle?

**Comment by gabrielschulhof** [comment]
@levimm we do not expose the details of the underlying engine. After all, you may not be running on V8 at all. For example, you may be running ChakraCore, or some other JavaScript engine.

**Comment by levimm** [comment]
@gabrielschulhof Thanks for your effort. Your commit helps me a lot.
