### ISSUE TITLE
What is the most efficient way to capture Napi::Function/Napi::Object into a lambda?

### ISSUE THREAD

**Issue by Pospelove** [nodejs/node-addon-api#1312]
Hey! Could you please tell me what is the most optimal way to capture a Napi::Function or Napi::Object into a lambda for later execution in a Node.js addon, and how can I ensure that the Napi::Persistent reference is being freed properly in my code example?

```c++
void ExecuteLater(std::function<void()> cb);

void Foo(const Napi::CallbackInfo &info) {
  // get a parameter
  auto function = info[0].As<Napi::Function>();
  
  // make Napi::Persistent
  std::shared_ptr<Napi::Reference<Napi::Function>> functionRef(
    new Napi::Reference<Napi::Function>(Napi::Persistent<Napi::Function>(function)));
  
  // pass to lambda to be called later
  auto callback = [functionRef] {
    functionRef->Value().Call();
  }
  ExecuteLater(callback);
}
```

Thank you!

**Comment by gabrielschulhof** [comment]
@Pospelove when you know that `functionRef` will no longer be used, you can call `functionRef->Reset()`. Then, it will be a reference to nothing at all. The `shared_ptr` semantics will then make sure that `functionRef` is destroyed when it passes out of scope.
