### ISSUE TITLE
FinalizerCallbacks and threads

### ISSUE THREAD

**Issue by audetto** [nodejs/node-addon-api#1314]
I have finally got my c++ addon to correctly memory manage wrapped objects.

What I learned is that the callbacks can only run when the main thread "yields" (e.g. via a `setTimeout` call) (there is a discussion here https://github.com/orgs/nodejs/discussions/47716).

In plain javascript, this is probably as far as one can go, but I was wondering if using the `node (addon) api` either of the following items are possible

1. flag the callback as "threadsafe" so node will run it immediately, rather than schedule it for later
    - no need to callback into node (I just need `delete ptr`)
2. tell node to "run all pending callbacks" via a *fast*er node api call
    - as opposed to a `await sleep(0)` which is not that fast, and makes everything into an `async`

?

**Comment by KevinEady** [comment]
This functionality would need to be addressed in the changes we're discussin to the SetImmediate finalizer functionality.

Relates: https://github.com/nodejs/node-addon-api/issues/1140
