### ISSUE TITLE
Jenkins failures on `osx1015` with node `21`

### ISSUE THREAD

**Issue by KevinEady** [nodejs/node-addon-api#1328]
The Jenkins environment for [osx1015](https://ci.nodejs.org/job/node-test-node-addon-api-new/nodes=osx1015/ws/) shows a file [node-v21.0.0-nightly202306061b4ce6981d-darwin-x64.tar.gz](https://ci.nodejs.org/job/node-test-node-addon-api-new/nodes=osx1015/ws/node-v21.0.0-nightly202306061b4ce6981d-darwin-x64.tar.gz) (8.81KB) but this is not a valid tgz: it's an HTML file with a "not found" contents, eg:

```html
<!DOCTYPE html>
<html>

<head>
    <meta charSet="utf-8" />
    <title>404 | Node.js</title>
.....
```

**Comment by richardlau** [comment]
I think this is a Build infrastructure issue: https://github.com/nodejs/build/issues/3378

**Comment by richardlau** [comment]
Should be fixed now, https://ci.nodejs.org/job/node-test-node-addon-api-new/7570/nodes=osx1015/
