### ISSUE TITLE
Short term conversion tool fix for known issues

### ISSUE THREAD

**Issue by anisha-rohra** [nodejs/node-addon-api#133]
For aspects of the conversion tool where it is known that the conversion is inaccurate, leave some form of an indicator for the user that changes are required.

Potential indicators can be as simple as a comment in the form of a TODO or whitespace where the change is expected.

An example of such a situation is the "Nan::New" conversion to "Napi::New" as a default when no concrete type match is found.

**Comment by NickNaso** [comment]
Hi @anisha-rohra,
what do you think can we close this issue?

**Comment by anisha-rohra** [comment]
Yes, this can be closed.

**Comment by anisha-rohra** [comment]
It can be closed, yes!
