### ISSUE TITLE
Add engines limitation into package.json?

### ISSUE THREAD

**Issue by Apollon77** [nodejs/node-addon-api#1339]
I just saw 7.0.0 and a changelog note about dropping Node.js 14 and 19 support ... I would have expected that this is also refelected in the package.json but there is no info at all.

Would it not make sense for less issues on developer and user side to have that in the package.json too?

**Comment by mhdawson** [comment]
We had a short discussion in the Node-api team meeting today and there was agreement this would be a good addition.  Would you like to PR that in?

**Comment by Apollon77** [comment]
Sure, I will do in text days
