### ISSUE TITLE
Operator overload

### ISSUE THREAD

**Issue by Vasile-Peste** [nodejs/node-addon-api#1341]
Hello,
I'm not sure if it's the right place, I'm sorry if it's not

Pure JavaScript doesn't have operators overloading yet, I would like to know if with a C++ add-on it's possible to create a JavaScript object that has overloaded operators

We have financial software exposing certain operations that would be easier to express with the classical +-*/ operators instead of methods, thank you

Regards,
Vasile

**Comment by KevinEady** [comment]
Hi @Vasile-Peste ,

JavaScript does not support operator overloading. The best you could do is define a [`Symbol.toPrimitive`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toPrimitive) property on your object to properly convert it from some encapsulated value to a numeric for use in numeric calculations as determined by the JavaScript engine.

Hope this helps

**Comment by gabrielschulhof** [comment]
@Vasile-Peste hopefully @KevinEady's answer helped you. If you still have questions about node-addon-api, please feel free to re-open this issue, or open a new one.
