### ISSUE TITLE
Obtain JavaScript function name from Napi::Function  instance ?

### ISSUE THREAD

**Issue by bsrdjan** [nodejs/node-addon-api#1361]
When JavaScript function passed as Napi::Function parameter to node-addon-api method, is it possible to obtain JS function name from Napi::Function instance?

**Comment by KevinEady** [comment]
Hi @bsrdjan ,

Just a guess: functions have a `name` property, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name

So maybe you can do something like:

```cpp
std::string functionName = funct.As<Napi::Object>().Get("name").As<Napi::String>().ToUtf8Value()
```

... where `funct` is a variable referencing the function (as an `Napi::Value` or `Napi::Function`)

Let us know if this works!

**Comment by bsrdjan** [comment]
Thanks, it works :)
