### ISSUE TITLE
Just a simple question.

### ISSUE THREAD

**Issue by Nhahan** [nodejs/node-addon-api#1373]
Is there a `NAPI` method to handle `ScriptOrigin` or `[[FunctionLocation]]` in `v8`?

Thank you very much for your response.

**Comment by KevinEady** [comment]
Hi @Nhahan ,

Node-API is meant to be engine-agnostic. The constructs you mentioned are V8-specific and do not have any API comparability with Node-API.

Hope this helps!

Thanks, Kevin

**Comment by Nhahan** [comment]
Thank you!
