### ISSUE TITLE
New SemVer Major release?

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#1381]
Node.js 16.x went EOL, do we want to do a SemVer major to bump the level of support?

**Comment by legendecas** [comment]
Might be a good timing to add breaking change to `node_api.gyp` at https://github.com/nodejs/node-addon-api/pull/1389

**Comment by mhdawson** [comment]
@legendecas lets discuss in the next team meeting.

**Comment by mhdawson** [comment]
@nodejs/node-api  any other changes we should get in before the next major?

**Comment by mhdawson** [comment]
Discussed in the team meeting today and the plan is to do a release in early Jan.

Suggestion was that we do a minor release with all of the up to date changes and then do a second release which bumps the major and drops support for 16.x
