### ISSUE TITLE
Request a c++ call js demo.

### ISSUE THREAD

**Issue by CancerQ** [nodejs/node-addon-api#1449]
Request a c++ call js demo. I already have some code, but c++ directly calls js code error, I do not know how to modify, can provide some help, the error location in callback.h:46 and 47, example_wrap.cxx:1476 has implemented DefineClass. Here is the code of my js:
```
class Call extends Callback{
   run(): void {
      console.log("Call Run");
   }
}
let c: Caller = new Caller();
let cb:Call  = new Call();
c.setCallback(cb);
c.call(); // There is an error in this line
```
I hope I don't want to change the c++ Callback, Caller.
Can be modified, SwigDirector, Swig_Callback, and example_wrap.cxx. Because of our need to transfer the existing c++ library out of js interface to use, the following is my c++ code:[code.zip](https://github.com/nodejs/node-addon-api/files/14329250/code.zip)

**Comment by NickNaso** [comment]
Hi @CancerQ in your example there is a lot of code autogenerated by SWIG and for me it's difficult to understand all of it and give you a seuggestion. Could you exaplain you use case so maybe I can try to create an example for you?

**Comment by CancerQ** [comment]
> Hi @CancerQ in your example there is a lot of code autogenerated by SWIG and for me it's difficult to understand all of it and give you a seuggestion. Could you exaplain you use case so maybe I can try to create an example for you?

I have modified my c++ code and it can be used normally. The following is my modified code. So that other people have the same problem in the future.
[code_adjust.zip](https://github.com/nodejs/node-addon-api/files/14429554/code_adjust.zip)

**Comment by CancerQ** [comment]
> 你好@CancerQ在您的示例中，有很多由 SWIG 自动生成的代码，对我来说，很难理解所有这些代码并给您提出建议。您能否解释一下您的用例，以便我可以尝试为您创建一个示例？

callback.h中的class CallBack和example.h中的Caller是我们的c++代码，是我们需要转换为js能调用的代码。example_wrap.cxx中的代码都是swig转换的代码，由于swig不支持callback的转出，所以callback.h除"class CallBack"之外的代码是我们为了使用swig而写的中间层代码。下面js代码：
class Call extends Callback{
run(): void {
console.log("Call Run");
}
}
let c: Caller = new Caller();
let cb:Call  = new Call();
c.setCallback(cb);
c.call(); // There is an error in this line

对应于c++的:
class Call : Callback{
void run() {
std::cout << "Call Run" << std::endl;
}
}

Caller c = new Caller();
Call cb = new Call();
c->setCallback(cb);
c->call();

**Comment by CancerQ** [comment]
> Hi @CancerQ in your example there is a lot of code autogenerated by SWIG and for me it's difficult to understand all of it and give you a seuggestion. Could you exaplain you use case so maybe I can try to create an example for you?

The class CallBack in callback.h and the Caller in example.h are our c++ code that we need to convert into code that js can call. The code in example_wrap.cxx is all swig conversion code, and since swig does not support CallBack roll-out, the code in callback.h other than "class CallBack" is the middle-tier code we wrote to use swig. The following js code:
`class Call extends Callback{
run(): void {
console.log("Call Run");
}
}
let c: Caller = new Caller();
let cb:Call  = new Call();
c.setCallback(cb);
c.call();  // There is an error in this line`

Corresponding to c++ :
`class Call : Callback{
void run() {
std::cout << "Call Run" << std::endl;
}
}

Caller c = new Caller();
Call cb = new Call();
c->setCallback(cb);
c->call();`
