### ISSUE TITLE
Alternative to creating references to non-objects

### ISSUE THREAD

**Issue by mika-fischer** [nodejs/node-addon-api#149]
https://github.com/nodejs/node/pull/15289 removed the possibility to create references to values that are not objects.

My use-case is the following. I want to store arguments given to my function persistently. Then some time later I want to call a callback function with those parameters. In the past I just used a `vector<Reference<Value>>`. Now I don't quite understand how I'm supposed to do it...

As an example, see this test: https://github.com/mika-fischer/napi-thread-safe-callback/blob/e03dda83fb1d2a63fb8332406e2436fc18a63fba/test/tests.cpp#L36-L51

**Comment by gabrielschulhof** [comment]
How about storing the arguments in a JS array and then creating a reference
to the array. Below is the pseudocode skeleton:

```c
napi_create_array();
for (index = 0; index < argc; index++) {
  napi_set_element(array, index, argv[index]);
}
napi_create_reference(array, &array_ref);
```

**Comment by mika-fischer** [comment]
OK, fair enough, that's slightly inconcenient, but not too bad...

But just so I understand: There's now no way at all to just hold onto say a string literal across calls into C++?

**Comment by gabrielschulhof** [comment]
There is. You can convert it to a `char *` and then pass the `char *` to
`napi_wrap()`. In general, you need to convert to a native type, store the
data in a heap-allocated buffer, and use `napi_wrap()`.

**Comment by mika-fischer** [comment]
Sure, I meant keeping the JS string without converting to C++. That seems impossible now, right?

And while converting a string to C++ by itself is not that bad, in cases like this where you get passed a `Value` and you don't care what it is, you just want to hold on to it for later use, things are a lot more complicated than before if you don't want to use this boxing trick...

**Comment by gabrielschulhof** [comment]
It is indeed more complicated. Nevertheless, it is necessary, because not
all engines support making references to non-object types.

**Comment by mika-fischer** [comment]
Ah I see, that makes sense then. Thanks for the explanations!
