### ISSUE TITLE
Failures with VS2022

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#1491]
I was just adding 23 to the matrix and noticed we should have added testing with VS2022 a while ago.

Seems like there are some failures - https://ci.nodejs.org/job/node-test-node-addon-api-new/nodes=win-vs2022/8773/

**Comment by mhdawson** [comment]
@vmoroz will take a look.

**Comment by vmoroz** [comment]
@mhdawson , the code uses `std::allocator` methods `construct` and `destroy`. They were deprecated in in C++17 and removed in C++20. See https://en.cppreference.com/w/cpp/memory/allocator/construct, https://en.cppreference.com/w/cpp/memory/allocator/destroy.
I will send a PR that fixes it.

**Comment by KevinEady** [comment]
Is this fixed by #1492?

**Comment by mhdawson** [comment]
We took a look at the CI runs in the meeting today and its fixed. Many thanks @vmoroz
