### ISSUE TITLE
Buffer finish callback with c type

### ISSUE THREAD

**Issue by sampsongao** [nodejs/node-addon-api#15]
Probably want to wrap napi_finalize as well to avoid mixing c api types with wrapper's.

    static Buffer<T> New(napi_env env, T* data,
                         size_t length,
                         napi_finalize finalizeCallback = nullptr,
                         void* finalizeHint = nullptr);

**Comment by jasongin** [comment]
Agreed. It should probably be a `std::function` like `Napi::FunctionCallback`.

**Comment by jasongin** [comment]
I'm working on updating all finalize callbacks to use a templatized callback similar to what @addaleax did for function callbacks.

**Comment by jasongin** [comment]
This was fixed a while ago, in ce9f0d98537ac8305fcd1ec8c2e348a32d6928f3
