### ISSUE TITLE
Arrays don't play nice with wrapped objects

### ISSUE THREAD

**Issue by facekapow** [nodejs/node-addon-api#150]
I'm not sure what's going on here, but when I try to set a wrapped object into an array (from native code), Node throws up an error: `Invalid pointer passed as argument`. I tried debugging it a bit and it appears that when the instance is fetched from the array, it's a non-type. `napi_typeof` on the result from `result.Get(i)` gives an `invalid_arg` error. So instances essentially disappear when they're assigned to the array?

My code:

`object.hpp`
```cpp
#include "napi.h"

class WrappedController: public Napi::ObjectWrap<WrappedController> {
  private:
    Napi::Value SetVibration(const Napi::CallbackInfo& info);
  public:
    Controller handle;
    static Napi::FunctionReference constructor;

    static void Init(Napi::Env& env, Napi::Object& exports);
    WrappedController(const Napi::CallbackInfo& info);
    static Napi::Object New(Napi::Env& env, Controller* controller);
};
```
`object.cpp`
```cpp
#include "napi.h"
#include "object.hpp"

Napi::FunctionReference WrappedController::constructor;

void WrappedController::Init(Napi::Env& env, Napi::Object& exports) {;
  Napi::HandleScope scope(env);

  Napi::Function ctor = DefineClass(env, "Controller", {
    InstanceMethod("setVibration", &SetVibration),
    InstanceMethod("setLEDs", &SetLEDs),
    InstanceMethod("toString", &ToString),
    InstanceMethod("on", &On),
    InstanceMethod("once", &Once),
    InstanceMethod("removeListener", &RemoveListener),
  });
  exports.Set("Controller", ctor);

  WrappedController::constructor = Napi::Persistent(ctor);
  WrappedController::constructor.SuppressDestruct();
};

WrappedController::WrappedController(const Napi::CallbackInfo& info): Napi::ObjectWrap<WrappedController>(info) {
  Napi::Env env = info.Env();
  Napi::HandleScope scope(env);

  if (info.Length() < 1 || (info[0].Type() != napi_external)) {
    throw Napi::Error::New(env, "Controllers can only be constructed by native code");
  }
  handle = *(info[0].As<Napi::External<Controller>>().Data());
};

Napi::Value WrappedController::SetVibration(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();

  if (info.Length() < 1 || !info[0].IsBoolean()) {
    throw Napi::Error::New(env, "Expected a Boolean!");
  }
  
  Napi::Boolean setVibration = info[0].As<Napi::Boolean>();
  handle.setVibration(setVibration.Value());

  return env.Undefined();
};

Napi::Object WrappedController::New(Napi::Env& env, Controller* controller) {
  Napi::HandleScope scope(env);

  return WrappedController::constructor.Value().New({
    Napi::External<Controller>::New(env, controller),
  });
};
```
`addon.cpp`
```cpp
#include "napi.h"
#include "object.hpp"

Napi::Value ScanForControllers(const Napi::CallbackInfo& info) {
  std::vector<Controller> controllers = scanForControllers();
  Napi::Env env = info.Env();
  Napi::Array result = Napi::Array::New(env);

  int size = controllers.size();
  for (int i = 0; i < size; i++) {
    Napi::Object val = WrappedController::New(env, &controllers[i]);
    result[i] = val;
  }

  return result;
};

Napi::Value InitController(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  bool calibrate = false;

  if (info.Length() < 1 || !info[0].IsObject()) {
    throw Napi::Error::New(env, "Expected a Controller!");
    return env.Undefined();
  }
  if (info.Length() >= 2 && info[1].IsBoolean()) {
    calibrate = info[1].ToBoolean().Value();
  }

  Napi::Object obj = info[0].ToObject();
  WrappedController* controller = WrappedController::Unwrap(obj);
  initController(&(controller->handle), calibrate);
  
  return env.Undefined();
};

Napi::Object Init(Napi::Env env, Napi::Object exports) {
  WrappedController::Init(env, exports);
  exports.Set("scanForControllers", Napi::Function::New(env, ScanForControllers));
  exports.Set("initController", Napi::Function::New(env, InitController));
  return exports;
};

NODE_API_MODULE(controllers, Init)
```
`test.js`
```js
'use strict';

const controllers= require('./');

const arr = controllers.scanForControllers();

for (const controller of arr) {
  controllers.initController(controller);
}
```
However, if I return a single controller in `ScanForControllers`, and then add the Controller to an array *in JavaScript*, everything works perfectly. Why don't arrays play nice with wrapped objects *only in native code*?

**Comment by jasongin** [comment]
```C++
Napi::Object val = WrappedController::New(env, &controllers[i]);
result[i] = val;
```

Change the assignment to: `result[i] = val.Value();`

The wrapped object instance in C++ is actually a _reference_ to the JavaScript value. References cannot be stored directly in arrays. The `Value()` method retrieves the referenced value.

I can understand the confusion, since this isn't documented well. We're planning to work on that.

**Comment by jasongin** [comment]
We might also consider updating array assignment (and property setters) to automatically dereference references. I'm not sure how well that would work though, without actually trying it out.

**Comment by facekapow** [comment]
Nope. Won't let me build, saying that  `.Value()` is not a method on `Napi::Object`. Thanks for the suggestion, though.

I can use the class if I directly unwrap the newly created instance, but I can't unwrap the instance you get from the array after assigning it to the array.

**Comment by jasongin** [comment]
Sorry, I skimmed the code too quickly before replying.

I think the problem is in the `WrappedController::New()` method. Because it declares a `HandleScope`, the object allocated within its scope will be released when the method returns. That's why it is invalid at the point of assigning to the array.

Assuming the number of controllers is going to be reasonably small, you can just delete that `HandleScope` because all N-API callbacks are automatically wrapped in a handle scope already. For a larger number of iterations, it could be slightly more efficient to declare a handle scope in each iteration of the loop -- but in the scope of the loop body, not in the `New()` method.

**Comment by facekapow** [comment]
Removed the HandleScope like you said and voila! It works perfectly. I guess I should've looked into *when* to use a HandleScope. I just saw it used throughout some of the examples but I didn't really know what for.

Anyway, thanks for your help.
