### ISSUE TITLE
ObjectWrapper with async methods?

### ISSUE THREAD

**Issue by corymickelson** [nodejs/node-addon-api#153]
Sorry, this is not really a bug or anything like that. I am trying to figure out how to, or if it's possible to add async methods to a class implementing ObjectWrap? 
``` cpp
class Foo: public ObjectWrap<Foo>
{
public: 
  void SomethingAsync(const CallbackInfo &info) {
    Function cb = info[0].As<Function>();
    AsyncWorker *worker = new AsyncWorker(cb);
    // do something
```

Can async methods exist within ObjectWrap? If not, what would be the best practice for creating an async method for an ObjectWrapped class?
Thank you.

**Comment by NickNaso** [comment]
Hi @corymickelson ,
I'm starting use node-addon-api and I had the same problem. If you want you can take a look here:
https://github.com/NickNaso/conf-ni-2017/blob/master/7-vedis-napi/ 
The code is not perfect, but works. Maybe you can take inspiration from it.
Please report me if it will useful for you.

**Comment by corymickelson** [comment]
@NickNaso  thank you, the examples you provided were very helpful.
