### ISSUE TITLE
Create a 7.1.1 branch backing out one commit

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#1532]
The commit to back out based on discussion in the node-api team meeting today is:

https://github.com/nodejs/node-addon-api/pull/1340#issuecomment-2192283145

**Comment by mhdawson** [comment]
@legendecas will do the release.

**Comment by legendecas** [comment]
Published https://www.npmjs.com/package/node-addon-api/v/7.1.1
