### ISSUE TITLE
What's the main purpose of making constructor function persistent? + How to have multiple ObjectWrap<T>'d classes in the same addon/env?

### ISSUE THREAD

**Issue by 0xFA11** [nodejs/node-addon-api#1591]
I'm following object wrap and object factory examples.

Here's my code for reference:

```c++
#include <napi.h>

#include <cstdlib>
#include <iostream>

#ifndef INLINE_LITERAL
#define INLINE_LITERAL(x) #x
#endif // INLINE_LITERAL

class Dummy : public Napi::ObjectWrap<Dummy>
{
public:
    static void Initialize(const Napi::Env& env, Napi::Object& exports)
    {
        Napi::Function creator = DefineClass(env, INLINE_LITERAL(Dummy), { /* no instance members for now */ });

		// Create a persistent reference to the class constructor. This will allow
		// a function called on a class prototype and a function
		// called on instance of a class to be distinguished from each other.
		Napi::FunctionReference* constructor = new Napi::FunctionReference();
		*constructor = Napi::Persistent(creator);
        exports.Set(INLINE_LITERAL(Dummy), creator);
    }

    Dummy(const Napi::CallbackInfo& info) : Napi::ObjectWrap<Dummy>(info), id(std::rand())
    {
        std::cout << "dummy ctor " << id << "\n";
    }

    void Finalize(Napi::Env env) override
    {
        std::cout << "dummy finalize " << id << "\n";
    }

    int id;
};

Napi::Object Bindings(Napi::Env env, Napi::Object exports)
{
    Dummy::Initialize(env, exports);

    return exports;
}

NODE_API_MODULE("example", Bindings)
```

Specifically, here:

```c++
// Create a persistent reference to the class constructor. This will allow
// a function called on a class prototype and a function
// called on instance of a class to be distinguished from each other.
Napi::FunctionReference* constructor = new Napi::FunctionReference();
*constructor = Napi::Persistent(creator);
exports.Set(INLINE_LITERAL(Dummy), creator);
```

I'm trying to understand what was meant by that and if there's an actual use-case example to illustrate it.

I'm also hesitant to store class constructor function reference as the environment instance data _(aka `env.SetInstanceData<Napi::FunctionReference>(creator)`)_ because that assumes we'll have only 1 class constructor function across the entire addon/env instance — that is simply not the case in most scenarios.

So, my question is: does my reference code above which doesn't create and store class constructor function reference on the environment instance correct?

If so, again, can we have a more illustrative example for the persistent function reference to class constructor?

If not, how can I have multiple different types of classes defined and wrapped in `ObjectWrap<T>` so that I could have `class Foo : public ObjectWrap<Foo>`, `class Bar : public ObjectWrap<Bar>`, `class Dummy : public ObjectWrap<Dummy>` and create them on the JavaScript end with `new Foo()`, `new Bar()` and `new Dummy()`?

_p.s. I'm also happy to contribute documentation, examples and code snippets as a follow-up to this issue._

**Comment by legendecas** [comment]
The reason to save the constructor function reference in the addon data is that with the constructor function reference, it is possible to construct an instance of the ObjectWrap in C++.

It is possible to save an arbitrary native strucuture pointer with [SetInstanceData](https://github.com/nodejs/node-addon-api/blob/main/doc/basic_env.md#setinstancedata), so multiple function references can be organized in a native struct, checkout the example test here: [link](https://github.com/nodejs/node-addon-api/blob/main/test/addon_data.cc).

**Comment by 0xFA11** [comment]
@legendecas thank you for clarification.

just to reiterate and confirm my understanding then:

```cpp
class Dummy : public Napi::ObjectWrap<Dummy>
{
public:
    static void Initialize(const Napi::Env& env, Napi::Object& exports)
    {
        Napi::Function creator = DefineClass(env, INLINE_LITERAL(Dummy),
        {
            InstanceMethod<&Dummy::Foo>(INLINE_LITERAL(Foo)),
            InstanceMethod<&Dummy::Bar>(INLINE_LITERAL(Bar)),
        });

        exports.Set(INLINE_LITERAL(Dummy), creator);
    }
}
```

2 things:

1. if I don't want to create Dummy objects in C++ and only expect them to be created from the JavaScript side with `new Dummy()`, this code snippet would be just OK and also wouldn't over-allocate or leak memory, correct?

2. more specifically, I was a bit unsure if `Napi::Function ctor = DefineClass(..)` would allocate some memory that wouldn't be free'd/GC'd automatically but sounds like my understanding of the persistent function reference was entirely wrong because it was there to store a function reference object at the addon level in order to later call it via that function to create a new instance, right?

**Comment by legendecas** [comment]
1. yes, if the function is not used in native land, exporting it to JS is sufficient.
2. Lifetime of non-Reference handles like `Napi::Function` and `Napi::Object` are managed by `Napi::HandleScope`. Typically this means that they are only valid on stack.

**Comment by 0xFA11** [comment]
@legendecas understood! it all make sense to me now. thank you so much, I really appreciate your time :)
