### ISSUE TITLE
Discussion: How to make `ObjectWrap`'s instance method async?

### ISSUE THREAD

**Issue by mkaivs** [nodejs/node-addon-api#1599]
```mermaid
sequenceDiagram
    autonumber
    actor user as User
    participant gui as GUI Process
    participant hardwareTest as Hardware Test Process
    create participant hardwareControl as Hardware Control Thread<br/>Web Worker
    hardwareTest->>hardwareControl: create
    user->>gui: click START-TEST
    gui->>hardwareTest: boardcast START-TEST event
    hardwareTest->>+hardwareControl: boardcast START-TEST event
    create participant interruptThread as Interrupt Thread
    hardwareControl->>+interruptThread: create
    hardwareControl->>-hardwareTest: done (acquire resources)
    user->>gui: click START-SHOT
    gui->>hardwareTest: boardcast START-SHOT event
    hardwareTest->>+hardwareControl: boardcast START-SHOT event
    user->>gui: click STOP-TEST
    gui->>hardwareTest: boardcast STOP-TEST event
    hardwareTest->>interruptThread: send STOP-TEST event
    interruptThread->>-hardwareControl: signal + return
    hardwareControl->>-hardwareTest: done (interrupted)
    hardwareTest->>+hardwareControl: boardcast STOP-TEST event
    hardwareControl->>interruptThread: join
    destroy interruptThread
    interruptThread->>hardwareControl: done
    hardwareControl->>-hardwareTest: done (release resources)
```

I have a GUI application for testing a device. I create a C++ class (`HardwareHandler`) that manages the resources required for testing the device and wrapped it using `ObjectWrap`. Some methods of `HardwareHandler` can take up to a few minutes and during that time the thread (`Hardware Control`) running that method is blocking as it needs to query the device for results. At the moment, since all instance methods of `HardwareHandler` are synchronous, I cannot running them in the background process's main thread (`Hardware Test Process`) to avoid blocking it, and must create a web worker thread (`Hardware Control`). I wonder if there is a way to make an instance method asynchronous to avoid the need of explicitly create a web worker? I found an example for `AsyncWorker` [here](https://github.com/nodejs/node-addon-examples/tree/main/src/5-async-work/napi-asyncworker-example/node-addon-api), but I'm not sure how to use it with `ObjectWrap` to achieve what I want.

**Comment by KevinEady** [comment]
Hi @mkaivs ,

>  I cannot running them in the background process's main thread ... I wonder if there is a way to make an instance method asynchronous to avoid the need of explicitly create a web worker? 

An "asynchronous method" is mostly syntactic sugar around `async`/`await` with support for `try`/`catch`. Adding `async` to a function in javascript does not make it "run in a background thread" automatically. It instead will always return a `Promise`, resolving to the return value of the function, or rejecting when an error is thrown. 

An approach would be to use both `ObjectWrap` and `AsyncWorker`: your `ObjectWrap`'d instance method can return a `Promise` that resolves when the `AsyncWorker` finishes work via the `OnOK` method. You can take a look at the `async_work_promise` example on node-addon-examples [here](https://github.com/nodejs/node-addon-examples/tree/main/src/5-async-work/async_work_promise/node-addon-api).

Hope this helps!

**Comment by mkaivs** [comment]
@KevinEady 

Thank you for the suggestion!
