### ISSUE TITLE
Documentation: Mention that Napi::Reference must not be stored in a global static instance

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/node-addon-api#162]
This must be avoided because `Reference` calls `napi_delete_reference()`, which in turn calls `Reset()` on the persistent stored inside, which ends up crashing because it runs from the library destructor, which in turn runs after the `Isolate` has already been disposed of.

See [the source](https://github.com/nodejs/node/blob/master/src/node_api.cc#L340-L348).

**Comment by jschlight** [comment]
The Reference `SuppressDestruct` method permits the user to set a private data member that avoids the `napi_delete_reference` call in `~Reference`. Would calling `SuppressDestruct` permit the Reference to be a global static instance?

**Comment by jschlight** [comment]
This issue can be closed when PR https://github.com/nodejs/node-addon-api/pull/243 lands.

**Comment by NickNaso** [comment]
@gabrielschulhof Is it possible to close this issue? The `Napi::Reference` documentation was landed with PR **[https://github.com/nodejs/node-addon-api/pull/243](https://github.com/nodejs/node-addon-api/pull/243)**

**Comment by NickNaso** [comment]
I'm closing this issue it was solved with PR **[#243](https://github.com/nodejs/node-addon-api/pull/243)**
