### ISSUE TITLE
Comprehensive node-addon-api test suite

### ISSUE THREAD

**Issue by anisha-rohra** [nodejs/node-addon-api#163]
- [ ] Array
  - [ ] Array
  - [x] TypedArray
  - [ ] TypedArrayOf
- [x] ArrayBuffer
- [x] AsyncWorker
- [ ] Boolean
- [x] Buffer
- [ ] CallbackInfo
- [ ] Constructor
- [ ] Conversions
- [x] Error
  - [x] Error
  - [x] RangeError
  - [x] TypeError
- [x] External
- [x] Function
- [ ] FunctionReference (@NickNaso) 
- [ ] HandleScope
- [x] Name
- [ ] Number
- [x] Napi Child
- [x] Object (@romandev)
- [ ] ObjectReference
- [ ] ObjectWrap
  - [ ] DefineClass
- [x] PropertyDescriptor
- [x] RangeError
- [ ] Reference (@anisha-rohra)
- [ ] String
- [ ] Symbol
- [ ] Value
- [ ] abi-stable-node-addon-examples imported

Would appreciate any input on test cases that need to added and/or removed from this list, attempting to make it as comprehensive as possible!

**Comment by jschlight** [comment]
I'm working on the documentation and it would be helpful for my work to have test cases for Reference.

**Comment by mhdawson** [comment]
@anisha-rohra can you prioritize adding the test for Reference ?

**Comment by mhdawson** [comment]
@jschlight talked to @anisha-rohra earlier in the week to get her up to speed on Reference, should be working on it now.

**Comment by romandev** [comment]
@mhdawson, @anisha-rohra Can I also work on this issue together? (but I don't want to get in the way)

**Comment by romandev** [comment]
Also, can we split a large test into smaller tests?
For example, if we are writing tests for Object wrapper, there are too many methods in Object class.
So, if we put all tests into one file, I think readability will be poor and complexity will increase.

**Comment by mhdawson** [comment]
@romandev absolutely.  Splitting out if there are a lot of tests also makes sense to me.  

To grab one of the sections, just post a comment here with the ones you are working on so that other people wont' work on them at the same time.  We'll try to periodically update the top part with that information as well.

**Comment by romandev** [comment]
@mhdawson Sure, if so, I'll start to write a test for Object first. It has been marked as complete but still missed many APIs.

**Comment by mhdawson** [comment]
@romandev sounds good.

**Comment by romandev** [comment]
Is anyone working on `Reference` test? If there is no one, can I take it?

**Comment by anisha-rohra** [comment]
@romandev I'm taking a look at it at the moment! Should be done in a couple of days.

**Comment by mhdawson** [comment]
@romandev I know you contributed a number of tests for Object. Should I mark it as complete above ?

**Comment by romandev** [comment]
@mhdawson Yep, I think we can mark it as complete :) Thank you.

**Comment by NickNaso** [comment]
Hi @mhdawson I think that we need to close this issue and use the new https://github.com/nodejs/node-addon-api/issues/332

**Comment by mhdawson** [comment]
@NickNaso I think that makes sense a as more detailed list.
