### ISSUE TITLE
NAPI_THROW_IF_FAILED -Wgnu-zero-variadic-macro-arguments - uses non standard syntax

### ISSUE THREAD

**Issue by guymguym** [nodejs/node-addon-api#174]
Hi

I'm compiling a c++ source file that includes "napi.h".
The compiler issues 19 warnings on lines with `NAPI_THROW_IF_FAILED(_env, status);`.
I use the compiler flag `-Werror` to fail on warnings.
I copied one message below.

Looking up this warning I learned that according to the standard, a macro with variadic arguments (...) is not allowed to be called without passing any arguments matching the ellipsis, see here:
https://stackoverflow.com/questions/21266380/is-the-gnu-zero-variadic-macro-arguments-safe-to-ignore

I think it would be better off fixed in this header to avoid including non-standard code.

My environment:
- Node.js: 6.11.5
- Clang: Apple LLVM version 9.0.0 (clang-900.0.38)
- MacOS: High Sierra 10.13

```
./node_modules/node-addon-api/napi-inl.h:715:36: error: must specify at least one argument for '...' parameter of variadic macro
      [-Werror,-Wgnu-zero-variadic-macro-arguments]
  NAPI_THROW_IF_FAILED(_env, status);
                                   ^
./node_modules/node-addon-api/napi-inl.h:26:9: note: macro 'NAPI_THROW_IF_FAILED' defined here
#define NAPI_THROW_IF_FAILED(env, status, ...)           \
        ^
```

**Comment by mhdawson** [comment]
Seems reasonable to me.  Would you like to submit a PR ? 

Based on these comments in the code:
```
// When C++ exceptions are enabled, Errors are thrown directly. There is no need
// to return anything after the throw statement. The variadic parameter is an
// optional return value that is ignored.
```

I think it would just be a matter of adding undefined as an additional parameter to the instances in question.

**Comment by guymguym** [comment]
Sure

**Comment by mhdawson** [comment]
@guymguym are you still planning to submit a PR to cover this ?

**Comment by guymguym** [comment]
I would love to but won't be able to do it in the next few weeks.

**Comment by mhdawson** [comment]
I'm going to close this since It's been a very long time since the last comment and a lot has changed between now and then. If this is still an issue in terms of warnings it would make sense for that to be captured in a new issue. Please let us know if you think that is not the right thing to do.
