### ISSUE TITLE
CI: Failures on Windows

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/node-addon-api#178]
https://ci.nodejs.org/nodejs/node-addon-api

On Windows the failure seems related to the build infrastructure because it's failing with
```
C:\Users\ADMINI~1\AppData\Local\Temp\jenkins3049146555514441742.sh: line 6: cd: too many arguments
```

**Comment by mhdawson** [comment]
Have fixed up the build related issues, tests pass on 8, 9 etc. but not 10.x nightlies see https://github.com/nodejs/abi-stable-node/issues/289 for more details.  I think we can close this issue and track the remaining problem in the issue in abi-stable-node.
