### ISSUE TITLE
CI: SmartOS: SIGABRT while running tests

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/node-addon-api#179]
On SmartOS the tests abort at test/error.js.

**Comment by mhdawson** [comment]
@cjihrig would you be able to help investigate this problem on SmartOS ?

**Comment by cjihrig** [comment]
I'll try to take a look tomorrow.

**Comment by cjihrig** [comment]
My current setup is:
- `uname -a` - 5.11 joyent_20170202T033902Z i86pc i386 i86pc Solaris
- `node -v` - v9.2.0
- Fresh clone of master of `node-addon-api`

`npm test` and `node test/error.js` both succeed for me. Any ideas on the configuration needed to trigger the abort?

**Comment by mhdawson** [comment]
This is the text from the job

ls
``` bash
export UNZIP_DIR=`ls |grep "node" |grep -v "gz"`
case $MACHINE in
  win*) cd $WORKSPACE\\$UNZIP_DIR;;
  *) cd $WORKSPACE/node-*/bin;;
esac

export PATH=$PWD:$PATH
cd $WORKSPACE
export NPM_CONFIG_USERCONFIG=$WORKSPACE/npmrc
export NPM_CONFIG_CACHE=$WORKSPACE/npm-cache
node -v
npm -v
export npm_loglevel=error
npm set progress=false
ls
git clone https://github.com/$GIT_REPO.git node-addon-api
cd node-addon-api
if [ $GIT_BRANCH != "master" ]; then
	git fetch origin $GIT_BRANCH:testBranch
	git checkout testBranch
fi
npm install

# This line needs to be updated to use the configuration string to test right version
# citgm -v verbose --tmpDir $WORKSPACE/tmp https://github.com/$NODEREPORT_REPO/archive/$NODEREPORT_BRANCH.tar.gz

npm test
```

**Comment by mhdawson** [comment]
Build on version 8 https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api/69/ to validate it is still failing.

**Comment by mhdawson** [comment]
Actually it runs every night and fails on the last v9 nightly although that should now b 10.  Fixed that.

**Comment by cjihrig** [comment]
@mhdawson I'm assuming [this comment](https://github.com/nodejs/security-wg/pull/57#issuecomment-350128923) was meant for this issue, so I'll repeat it here:

> I see its passed on smartos15 and smartos16, so maybe its just that the versions of Node.js that we are testing don't run on smartos14 and we should just remove that. @cjihrig what is the oldest version of Node.js that runs on smartos 14 ?

If that is intended for this issue, then @misterdjules comment [here](https://github.com/nodejs/node/issues/16528#issuecomment-341582318) might apply:

> The problem was probably that the node binary that was used was built on a version of SmartOS that was more recent (and not ABI compatible) with the version of SmartOS on which npm was running when the problem occurred.

Is the SmartOS 14 machine using a Node binary that is built on a newer version?

**Comment by mhdawson** [comment]
I see its passed on smartos15 and smartos16, so maybe its just that the versions of Node.js that we are testing don't run on smartos14 and we should just remove that. @cjihrig what is the oldest version of Node.js that runs on smartos 14 ?

**Comment by mhdawson** [comment]
@cjihrig yes was for this issue.  So main question is if we are ok just removing SmartOS 14 from the testing for N-API as N-API support will at most go back to 4.X (just not sure if SmartOS 14 supports 4.X or not)

**Comment by cjihrig** [comment]
> (just not sure if SmartOS 14 supports 4.X or not)

Based on the [CI run of the most recent Node 4.x release](https://github.com/nodejs/node/pull/17534#issuecomment-350093423), it appears that SmartOS 14 runs the Node test suite fine.

**Comment by mhdawson** [comment]
Ok updated job by taking logic from release job for smart os.  Should now only run node versions that are supported on SmartOS versions and otherwise just pass.
