### ISSUE TITLE
Publish a new 1.1.0 release with Promises

### ISSUE THREAD

**Issue by JamesMGreene** [nodejs/node-addon-api#181]
Since the Promise implementation was integrated into the current mainline branch via PR #137, I would really like to see a new minor release (`v1.1.0`) published to NPM.  That way, I would be able to change the dependency in one of my N-API example modules to use `"node-addon-api": "^1.1.0"` instead of `"node-addon-api": "rolftimmermans/node-addon-api#promise"`.

Please consider it.  Thanks!

**Comment by JamesMGreene** [comment]
I can wait.

**Comment by addaleax** [comment]
It might be nice if the process was documented somewhere (or maybe it even is)? Just got caught by `node-addon-api@1.0.0` not working on <= Node v6.x

**Comment by mhdawson** [comment]
@addaleax which process ?  The process for releases ?

**Comment by mhdawson** [comment]
My current goal is to do a release Monday Nov 20

**Comment by addaleax** [comment]
@mhdawson yes, exactly that :)

**Comment by mhdawson** [comment]
Release created/published.

**Comment by mhdawson** [comment]
@addaleax it has been pretty add-hoc so far in terms of creating release.  

I've created this PR as a first step to document the process: https://github.com/nodejs/node-addon-api/pull/187
