### ISSUE TITLE
getting promise result and state

### ISSUE THREAD

**Issue by devsnek** [nodejs/node-addon-api#193]
are there plans to expose a promise's result and state?

**Comment by mhdawson** [comment]
We are making additions to N-API based on need, so we don't have any plans to add new functions unless we find modules that need them or there is a use case that justifies their addition.

Do you have a use case in mind where APIs to get these are necessary and/or its hard to work around ?

**Comment by devsnek** [comment]
I made a "syncify" module while trying to learn v8 and node's apis. I wanted to do it with napi but I had to use raw v8 instead. more to the point is it that unlikely that at some point someone will need the state/result of a promise? when that happens they shouldn't have to wait for the next release of node.
