### ISSUE TITLE
napi_make_callback

### ISSUE THREAD

**Issue by simon-p-r** [nodejs/node-addon-api#199]
Hi

I cannot find any examples of napi_make_callback api, I would like to use it to invoke a js function on an event from native code.  Is this possible?

Thanks

**Comment by mhdawson** [comment]
@simon-p-r did you find your answer ? Sorry nobody responded more quickly.

**Comment by simon-p-r** [comment]
No not yet @mhdawson I am using the c api which is why I closed this issue.  My main problem is raising events from c and passing them to js, I believe I have to use uv_async_send however I think I now need to queue the callbacks as libuv doesn't fire them individually.  Hopefully I will be able to get napi_make_callback to work after that!

**Comment by JCMais** [comment]
Hey @KevinEady, thanks! After posting the above, I did some research, and I think in my case I don't think I need this. My addon only really uses libuv to poll on a socket, and if I use `uv_default_loop()` when initializing the socket, my assumption is that everything still happens on the same thread as the running Node.js environment, thus I can simply store the Persistent functions, and call them directly from the libuv callbacks.

Let me know if my reasoning here is wrong or not lol
