### ISSUE TITLE
Issues with the conversion tool

### ISSUE THREAD

**Issue by digitalinfinity** [nodejs/node-addon-api#201]
I was trying out the conversion tool to port an existing module and ran into a couple issues. I opened https://github.com/nodejs/node-addon-api/pull/200 to fix some of the easier issues but wanted to capture the one's that I didn't fix:
- Binding.gyp handling seems to be flaky. The import of node-addon-api's binding.gyp doesn't seem to work. Removing it unblocked me but it would be good to fix because gyp issues are a pain to debug and it's not ideal that it would be the first issue that folks using the tool would hit.
- env gets sprinkled in without being defined. I don't know how to fix it with the current regexp based approach.
- On a couple occasions, the script created a napi value but left expression using -> instead of .
- On a couple occasions, the generated code was just mangled. For example, the expression `std::string out_filename(*Nan::Utf8String(info[1]->ToString()));`  became `std::string out_filename(info[1].ToString(->As<Napi::String>().Utf8Value().c_str()));`

**Comment by anisha-rohra** [comment]
Can you point me to the module you were porting? Would like to replicate and attempt to fix the binding.gyp handling issue you ran into.

**Comment by digitalinfinity** [comment]
This one: https://github.com/pierreinglebert/node-zopfli - I have it ported and I'm investigating some performance issues with the port

**Comment by NickNaso** [comment]
Hi everyone,
is this issue still valid or is it possible to close it?

**Comment by anisha-rohra** [comment]
Hi @NickNaso, as far as I know it's still pending and definitely something I'll be working on as soon as possible!

**Comment by mhdawson** [comment]
Those who were involved in the original discussion/suggestion are no longer active in the node-addon-api project so I'm going to close out. Please let us know if that was not the right thing to don.
