### ISSUE TITLE
Build failure with Node v6.12.1 on CentOS 7

### ISSUE THREAD

**Issue by michaelfig** [nodejs/node-addon-api#206]
First, thanks for node-addon-api: it allowed me to port old code to v8.9.1.

I'm trying to backport my module to v6.12.1, and I'm getting compile errors after following the steps in the Setup guide (and having it work perfectly under Node v8.9.1).

They all seem related to async_context not existing in v6.

Your help is appreciated,
Michael.
[compile-errors.txt](https://github.com/nodejs/node-addon-api/files/1590357/compile-errors.txt)

**Comment by michaelfig** [comment]
BTW, I used node-addon-api@1.0.0 for both compiles.

**Comment by NickNaso** [comment]
Hi @michaelfig,
If I understood you had problem with version 1.1.0  of node-addon-api while with 1.0.0 all worked well for you. 
About that I'm curios so if your addon is a public addon please post the link at your code. I want try to take a look.
Nick

**Comment by mhdawson** [comment]
I can see that we define some of the functions reported as missing in:

**Comment by michaelfig** [comment]
Ah, thanks!

The installation and usage guide says to reference "1.0.0" in the package.json, but when I changed it to "^1.0.0" and npm update node-addon-api, I got 1.1.0 which adds the necessary support to v6.

Node-gyp has problems with v0.10 due to c++ flags, but at least 6.x works!

**Comment by NickNaso** [comment]
@mhdawson We need to change the reference in the installation and usage documentation.

**Comment by michaelfig** [comment]
I've tested it successfully for node v4.8.7 as well.

Thanks.

**Comment by mhdawson** [comment]
Sounds like we can close this.  If not please let me know and I'll re-open.
