### ISSUE TITLE
Make IsObject() allow functions?

### ISSUE THREAD

**Issue by addaleax** [nodejs/node-addon-api#207]
Hi everyone!

I’ve just received my first PR from somebody else on a N-API project 🎉 https://github.com/node-ffi-napi/weak-napi/pull/3

I’m wondering whether it makes sense to change `IsObject()` in the wrapper so that `napi_function` is also allowed, because functions are objects in the JS sense and any N-API operation that expects an object should also work on a function. What do you think?

**Comment by jasongin** [comment]
I agree, it seems like a bug. `IsObject()` should be true for functions.

**Comment by mhdawson** [comment]
I agree as well.  IsObject() should return true for a function.

**Comment by guymguym** [comment]
Hey, sounds good to me.
btw you might consider having the original IsObject meaning as IsObjectLike the same as done by lodash:
https://lodash.com/docs/4.17.4#isObject
https://lodash.com/docs/4.17.4#isObjectLike

**Comment by addaleax** [comment]
This has been fixed a while ago, the PR author just didn’t add a `Fixes:` tag. Closing! :)
