### ISSUE TITLE
Cast a c++ std::vector to a Napi::Array

### ISSUE THREAD

**Issue by kevinGodell** [nodejs/node-addon-api#219]
Is it possible to cast a vector created in C++ to be a compatible Napi Value that can be returned to JS? I have been stumped on this. I admit that I have very little experience with C++ and I am trying to learn as much as I can. In my code, I am iterating 2 buffers of pixels and measuring differences between them. If their difference exceeds the threshold, I add the  x, y values to a struct Point and add that to the vector<Point>. I cannot figure out the proper syntax to convert it to a value that can be returned. My code samples are listed below:

The code used to create the vector  based on the maximum number of pixels
```
std::vector<Point> vec(width*height);
```
When iterating the 2 pixel buffers, I add the x, y values,  with diffs keeping the count of changed pixels
```
vec[diffs].x = x;
vec[diffs].y = y;
diffs++;
```
Then after the loop is finished, I resize the vector to match the diffs count
```
vec.resize(diffs);
```
I can access the info of the vector, so I know it is there
```
std::cout<<vec[0].x<< " "<<vec[0].y<<std::endl;
```
And this is the point where I am stumped on returning this as a JS array. Ideally I wanted to return an array of arrays, but an array of x,y points will be just as good.

**Comment by bnoordhuis** [comment]
Short answer: you can't do that.

Long answer: use typed arrays if you want efficiency.  You won't be able to use compound types like your Point class, at least not easily.  Look at `napi_create_arraybuffer()` and `napi_create_typedarray()`.

Alternative long answer: you could turn each Point instance into a JS object with x and y properties but that's going to be exceedingly slow.

**Comment by kevinGodell** [comment]
Thanks for the clarification.
