### ISSUE TITLE
Version of Node.js Required

### ISSUE THREAD

**Issue by computerquip-streamlabs** [nodejs/node-addon-api#220]
I'm somewhat under the impression that this module was made to work with older versions of Node.js, but I can't seem to find any prerequisite information. Is it supposed to work with just any version of node?

**Comment by mhdawson** [comment]
It works with older versions of Node.js but you get a different level of support.

Currently, if you build against 8.X the binary will be able to run with 8.X, 9.X etc.

If you build with older versions, it will use the N-API API files built into the module.  This allows your module to compile/run with earlier versions but does not let the binary run with later versions which support N-API natively.  This is intended to help ease the transition to N-API as it allows you to have one version of your source code even if you don't get the benefit of not having to recompile for new versions.

@gabrielschulhof is also working on additional support that would dynamically load the API for older versions of Node.js that do not support N-API and natively for version of Node.js that support N-API, however, we have not proved out this approach yet.

**Comment by mhdawson** [comment]
I should have also mentioned that the support for older versions only goes back to the LTS lines (4.X at this point).

**Comment by computerquip-streamlabs** [comment]
Thanks, that cleared it up.
