### ISSUE TITLE
Add N-API to main CiTGM runs

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#234]
We should work on adding

    bcrypt-n-api - in Lexgenda Search engine
    node-zopfli in Microsoft Edge Developer Portal
    iotivity-node@1.3.1-0 in CANPIE

There is additional real world usage through:

    ffi-napi
    weak-napi
    ref-napi

to the main GiTGM runs

@addaleax can you confirm ffi-napi, weak-napi and ref-napi are suitable to add to CiTGM

@gabrielschulhof is it feasible to add iotivity-node.  I think the answer might be no but asking to make sure

@NickNaso do you think there will be any complications with adding bcrypt ?  Does the test need anything external or does an npm install/npm test just work ?

**Comment by mcollina** [comment]
@mafintosh has ported some of his modules to n-api too.

**Comment by NickNaso** [comment]
@mhdawson I think that for **bcrypt** npm install/npm test should work

**Comment by mafintosh** [comment]
https://github.com/mafintosh/turbo-net

**Comment by mhdawson** [comment]
N-API was taken out of experimental a long time ago and we seem to have been ok, closing
