### ISSUE TITLE
Call function from worker thread

### ISSUE THREAD

**Issue by NickNaso** [nodejs/node-addon-api#241]
Hi everyone,
I'm working on a native addon and from inside an **AsyncWorker** I need to call a function, in the specific I want call the function in the ```Execute``` method and I know that it's not possible. I want know if there's a simple way to do that and if my need is correlated with the following issue on **n-api**
https://github.com/nodejs/node/pull/17887
Thanks

**Comment by gabrielschulhof** [comment]
If you want to call into JS from another thread, then you definitely need
https://github.com/nodejs/node/pull/17887.

On Tue, Mar 20, 2018 at 12:35 PM, Nicola Del Gobbo <notifications@github.com

**Comment by NickNaso** [comment]
@gabrielschulhof Thank you for your quickly answer.

**Comment by NickNaso** [comment]
@gabrielschulhof Today I tried to call a JavaScript function from the ```Execute``` method of an ```AsyncWorker``` using ```uv_async_init``` and ```uv_async_send```.  All seems to work, but  I'm asking if the runtime is capable to well track my function call. What dou you think?

**Comment by gabrielschulhof** [comment]
In the `uv_async_cb` on the loop thread you need a HandleScope followed by
a CallbackScope before you can call into JS.

**Comment by jasonrsadler** [comment]
@NickNaso, Can you share an example of calling NAPI methods in the Execute function?

Thanks. :)

**Comment by gabrielschulhof** [comment]
@jasonrsadler the only N-API methods you can call from the `Execute()` function are the ones dealing with [thread-safe functions](https://docs.nodejs.org/dist/latest-v10.x/docs/api/n-api.html#n_api_asynchronous_thread_safe_function_calls). I don't believe those are covered by node-addon-api, so you would have to use them directly.

**Comment by jasonrsadler** [comment]
Thanks @gabrielschulhof. Could I bother you to show me a quick example?

**Comment by gabrielschulhof** [comment]
@jasonrsadler https://github.com/gabrielschulhof/abi-stable-node-addon-examples/tree/tsfn_async_work/async_work_thread_safe_function/node-api provides an example with plain N-API.
