### ISSUE TITLE
misleading description in doc about `napi_get_typedarray_info`

### ISSUE THREAD

**Issue by yw662** [nodejs/node-addon-api#244]
In https://nodejs.org/dist/latest-v9.x/docs/api/n-api.html#n_api_napi_typedarray_type

> [out] data: The data buffer underlying the typed array.
[out] byte_offset: The byte offset within the data buffer from which to start projecting the TypedArray.

It seems that the data is started from `&data[byte_offset]`, 

but actually in `node_api.cc`, 
````
if (data != nullptr) {
    *data = static_cast<uint8_t*>(buffer->GetContents().Data()) +
            array->ByteOffset();
}

if (byte_offset != nullptr) {
    *byte_offset = array->ByteOffset();
}
````

So, the doc should clarify that the out arg `data` actually points to `&data[byte_offset]`.

**Comment by mhdawson** [comment]
Thanks for catching this.  PR to fix https://github.com/nodejs/node/pull/20747.

.
