### ISSUE TITLE
Creating a JS object for already created C++ object using Node API 

### ISSUE THREAD

**Issue by kanujkumar** [nodejs/node-addon-api#247]
With the function definition set through `napi_define_class(...., new_instance_callback, &localFn)`, `napi_new_instance(...,localFn,....)` internally uses `v8::Function::newInstance()` to create the instance of the function, which will invoke the callback function new_instance_callback. I have defined `new_instance_callback` function to always create a new C++ object (i.e. `new AnotherObject()`). Since I already have a C++ instance of class `AnotherObject`, I do not want `new_instance_callback` to be triggered. In v8, I can achieve the same with `v8::FunctionTemplate::InstanceTemplate()::newInstance()` to avoid this callback. I couldnt find the equivalent in Node API to do the same.

**Comment by NickNaso** [comment]
Hi @kanujkumar,
could you take a look at these examples? Maybe they could be helpful to you **[https://github.com/nodejs/abi-stable-node-addon-examples/tree/master/7_factory_wrap](https://github.com/nodejs/abi-stable-node-addon-examples/tree/master/7_factory_wrap)**

**Comment by kanujkumar** [comment]
HI @NickNaso , I did go through examples and even went through node-api code, couldn't find a reference where `v8::FunctionTemplate::InstanceTemplate()::newInstance()` is used.

**Comment by ebickle** [comment]
@NickNaso A few months back I went through the documentation and examples carefully and it wasn't obvious how to accomplish this either. It's definitely something I need for my own code - I'm wrapping a C library that performs a network operation when creating a resource. Can't use a Javascript constructor, so I have to use a Promise that returns a new (C++) object in the result. 

The factory pattern shown above still exposes the C++ object's constructor to Javascript. Any way to have something akin to a private constructor with C++ objects exposed to Javascript?

**Comment by gabrielschulhof** [comment]
One way I can think of is if you call `napi_new_instance()` with an extra parameter that will be checked from the constructor and, if present, causes the constructor to short-circuit.

**Comment by verdie-g** [comment]
@kanujkumar Have you managed to solve your problem ?

**Comment by mhdawson** [comment]
I'm going to close this since it has been a long time since the last suggestions. Please let us know if you think that was not the right thing to do.
