### ISSUE TITLE
Memory Management

### ISSUE THREAD

**Issue by NickNaso** [nodejs/node-addon-api#260]
Hi everyone,
in my recent porting I had the need of using ```napi_adjust_external_memory``` See: [https://nodejs.org/dist/latest/docs/api/n-api.html#n_api_memory_management](https://nodejs.org/dist/latest/docs/api/n-api.html#n_api_memory_management) . What do you think if we add this function to **node-addon-api**? if you are agree I want try to add the function with some guide.

**Comment by mhdawson** [comment]
Agreed.  Everything in the C n_api should be usable through node-addon-api, we just have not gotten them all in.  Would be great if you add it in.

**Comment by NickNaso** [comment]
@mhdawson  @gabrielschulhof  I'm starting on this. I want add a function on Napi namespace as reported below:

```cpp
int64_t AdjustExternalMemory(napi_env env, int64_t change_in_bytes);
```

This is the same approach that I found on NAN. 
I don't know if could be useful create a class called for example **MemoryManagement** and attach to it a method **AdjustExternalMemory**.
What is your thinking about that?

**Comment by mhdawson** [comment]
It is an interesting question as we don't have any other Utility classes, and adding the method to any of the existing classes does not make sense to me.

At this point your suggestion seems like the best idea to me.

**Comment by NickNaso** [comment]
@mhdawson Thanks for your opinion later I will provide to add it with corresponding tests and documentation.

**Comment by NickNaso** [comment]
I close the issue because the PR with the feature was landed.
