### ISSUE TITLE
Get current environment?

### ISSUE THREAD

**Issue by bsrdjan** [nodejs/node-addon-api#261]
Is there a feature (planned?) to get the current environment and create escapable scope ? I try to migrate this:

```c++
 Isolate* isolate = Isolate::GetCurrent();
 EscapableHandleScope scope(isolate);
```
to something like this:

```c++
Napi::Env env = <get current>?
Napi::EscapableHandleScope scope(env);
```

**Comment by mhdawson** [comment]
This example shows how you can get the Env from the info object passed to all methods:

https://github.com/nodejs/abi-stable-node-addon-examples/blob/master/2_function_arguments/node-addon-api/addon.cc

```
Napi::Value Add(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
```

**Comment by bsrdjan** [comment]
Thanks. I have one older design using Isolate::GetCurrent(), without using info object. Passing the info object should not be a lot of redesign effort.
