### ISSUE TITLE
Invalid export in Init Method

### ISSUE THREAD

**Issue by gibranparvez** [nodejs/node-addon-api#264]
Hi,
Up until a few days ago a wrapper for a C++ function I had made a few months back was working great. Now, when I compile, I consistently get

```
node_modules/node-addon-api/napi-inl.h:161:54: error: invalid conversion from 'void (*)(Napi::Env, Napi::Object)' to 'Napi::ModuleRegisterCallback {aka Napi::Object (*)(Napi::Env, Napi::Object)}' [-fpermissive]
     return Napi::RegisterModule(env, exports, regfunc);   \
```

I see suggestions from @mhdawson  about simply removing the third parameter in the Init method but it doesn't seem to change anything.

The repo was originally using Node 6.11, bindings 1.3.0, node-gyp 3.6.2, and node-addon-api 0.6.3, and after upgrading to node 8 and addon-api 1.2.0, some other related errors go away but that one remains.

https://github.com/venicegeo/geotrans-mgrs-converter/blob/master/geotrans3.7/CCS/sampleCode/mgrsToGeodetic.cpp

This is the repository and the specific class. and all branches are currently failing, whether I build the docker file or whether I try to compile it natively.

**Comment by gabrielschulhof** [comment]
You also need to change your return value to return a Napi::Object. In the
implementation you normally return exports.

**Comment by NickNaso** [comment]
Hi @gibranparvez,
@gabrielschulhof is right and I just looked at your code and I made a PR [https://github.com/venicegeo/geotrans-mgrs-converter/pull/3](https://github.com/venicegeo/geotrans-mgrs-converter/pull/3)
I hope it will help you.

**Comment by mhdawson** [comment]
@gibranparvez had you had a chance to implement the suggestions and can we close this issue?
