### ISSUE TITLE
Creating new release - May 8 2018

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#266]
As an FYI - plan to create new release after landing PR 263 which enables the use of built in N-API for the latest version of 6.x

**Comment by NickNaso** [comment]
What do you think if we start writing the [CHANGELOG](https://github.com/nodejs/node-addon-api/blob/master/CHANGELOG.md) file? 
But we need to know all the improvements that are on this release.

**Comment by mhdawson** [comment]
@NickNaso would that just be the list of commits since the last release or something more ?

**Comment by mhdawson** [comment]
Looked at changelog for NaN and Node, will use the node changelog make utility and do something along the lines that Node.js uses.

**Comment by mhdawson** [comment]
have pushed changes for new release to repo and am just testing. @NickNaso if you can take a quick look at changelog that would be great.

**Comment by mhdawson** [comment]
There is a problem with one of the tests for 6.x on sunos.  Investigating.

**Comment by NickNaso** [comment]
@mhdawson It's ok for me maybe I think could be good add these information a the top of changelog

## Notable changes:

### Documentation
- Added documentation for Scopes
- Added documentation for migration from NAN
- Update documentation to better explain the use of NODE_ADDON_API

### API
- Implement data manipulation methods for dataview
- Use built-in N-API on Node.js >= 6.14.2
- Value
  - Added IsExternal()
  -  IsObject() allow functions
- String
  - Fixed initialization of std::string to nullptr


### Tests
- Fix test failures on linuxOne and AIX 
- Added basic tests for Scopes
- Fix MSVC warning C4244 in tests

**Comment by mhdawson** [comment]
@NickNaso updated

**Comment by mhdawson** [comment]
All tests passed, created the release.  Next step is to publish to npm.

**Comment by mhdawson** [comment]
published to npm, closing.

**Comment by NickNaso** [comment]
It' works I just downloaded and used on a native add-on. Great work!
