### ISSUE TITLE
Version Management

### ISSUE THREAD

**Issue by NickNaso** [nodejs/node-addon-api#274]
Hi everyone, I want add version management functions that are available on the N-API:
- `napi_get_node_version` [https://nodejs.org/dist/latest/docs/api/n-api.html#n_api_napi_get_node_version](https://nodejs.org/dist/latest-v10.x/docs/api/n-api.html#n_api_napi_get_node_version) 
- `napi_get_version` [https://nodejs.org/dist/latest/docs/api/n-api.html#n_api_napi_get_version](https://nodejs.org/dist/latest-v10.x/docs/api/n-api.html#n_api_napi_get_version)

It's my intention add these two functions on Napi namespace as I did for `AdjustExternalMemory` see: [https://github.com/nodejs/node-addon-api/issues/260](https://github.com/nodejs/node-addon-api/issues/260)

Are you agree or have some suggestions to help me?

**Comment by NickNaso** [comment]
Hi @devsnek you're right it's too simple use **NODE_VERSION** and **NAPI_VERSION**,  to access to these constant a developer needs only to import `node.h`. My thinking is to avoid as much as possible to import anything other than `napi.h`.

**Comment by mhdawson** [comment]
I agree that we want to avoid the need to import node.h as that makes it easy to take a dependency without palnning to.

**Comment by NickNaso** [comment]
Ok so in the next days I will try to add this feature.

**Comment by NickNaso** [comment]
I'm closing the issue because it's solved with **[https://github.com/nodejs/node-addon-api/pull/325](https://github.com/nodejs/node-addon-api/pull/325)**.
