### ISSUE TITLE
Is it possible to instantiate a global object?

### ISSUE THREAD

**Issue by eanders-ms** [nodejs/node-addon-api#275]
I'm sure this is a noob question, but I cannot find a way to instantiate a native global object that is then exported from my addon. Is this possible to do?

JavaScript side:

```js
const native = require('path/to/my/addon');
const app = native.app;
```

Where `app` is an instance of a native class:

```cpp
class App : public Napi::ObjectWrap<App> {
  ...
};
```

Then in my binding.cc file, keep a static instance:
```cpp
static App s_app;

static Napi::Object Init(Napi::Env env, Napi::Object exports) {

    addon::App::Init(env, exports);

    addon::s_app = new App(env); // <-- Doesn't work. How to do it?

    exports.Set("app", addon::s_app);

    return exports;
}

```

How would I instantiate a global object? I think I need a CallbackInfo to put it in. Maybe I shouldn't be doing it this way. I also want to disallow creation of new instances of `App`.

**Comment by NickNaso** [comment]
@eanders-MS Maybe the following examples could be useful to you 
https://github.com/nodejs/abi-stable-node-addon-examples/tree/master/7_factory_wrap/node-addon-api
https://github.com/nodejs/abi-stable-node-addon-examples/tree/master/8_passing_wrapped/node-addon-api

**Comment by eanders-MS** [comment]
Thanks @NickNaso. My App class needs to be a native object because it does some backend things, and I want to expose it as a global singleton to Node. It seems like I want to do something like:

```cpp
static Napi::Object s_app;

static Napi::Object Init(Napi::Env env, Napi::Object exports) {

    // Define the App class
    addon::App::Init(env, exports);

    // Something like this... I want to instantiate an App object during init.
    // How can I instantiate an App object right here?
    addon::s_app = Napi::Object::New<App>(env);

    // And then export it as a value
    exports.Set("app", addon::s_app);

    return exports;
}
```

**Comment by bnoordhuis** [comment]
Use an index.js wrapper and do `global.MyClass = require('my_addon').MyClass`.
