### ISSUE TITLE
objectwrap: except `InstanceMethod` no descriptor function supports symbol as name

### ISSUE THREAD

**Issue by DaAitch** [nodejs/node-addon-api#279]
At current we cannot define e.g. an accessor for `Symbol.toStringTag`, because we can only use symbols with `InstanceMethod`.

I'll provide a pull request for the following implementations + more/different tests:

- `StaticMethod`
- `StaticAccessor`
- `InstanceAccessor`
- `StaticValue`
- `InstanceValue`

**Comment by DaAitch** [comment]
@mhdawson can be closed with #280 landed

**Comment by NickNaso** [comment]
@DaAitch Yes we can close the issue. Thanks for your contribution! 👍
