### ISSUE TITLE
IsConstructCall missing in class CallbackInfo

### ISSUE THREAD

**Issue by sampsongao** [nodejs/node-addon-api#28]
I just realize we don't have something equivalent to IsConstructCall for our wrapper class.

**Comment by jasongin** [comment]
I had been thinking this was not needed because [`Napi::ObjectWrap` automatically does the check](https://github.com/nodejs/node-api/blob/master/napi-inl.h#L1925).

However, there could be scenarios not using `ObjectWrap` that may make use of this information. It will be easy to expose.
