### ISSUE TITLE
Supported platforms ?

### ISSUE THREAD

**Issue by bsrdjan** [nodejs/node-addon-api#291]
Documenting nodejs addon for SAP NW RFC SDK, I try to find out platforms on which node-addon-api and N-API are supported, to cross-check with [SAP NW RFC SDK supported platforms](https://launchpad.support.sap.com/#/notes/2573790). Is such list available or could it be compiled and published? 

Regarding nodejs supported platforms, is https://nodejs.org/en/download/ the right place to look for this information ?

**Comment by mhdawson** [comment]
I think this page best covers the supported platforms for Node.js itself which covers N-API.

https://github.com/nodejs/node/blob/master/BUILDING.md

The goal for node-addon-api is to support for the same platforms as Node.js does.

Note that if you want to build a single binary for linux (or other OS's) that will support different versions of linux you will need to take care to build on the lowest common denominator like we do for the Node.js binaries.

**Comment by bsrdjan** [comment]
Thanks, exactly what I was looking for.

Regarding platforms, I have two follow up questions.

For the time being I am still building three N-API binaries on Windows and three on Linux, for nodejs versions 6.14.3, 8.11.3 and 10.5.0 (ABI 48, 57 and 64). All tests show that each binary works with each node version and I could use one single binary per platform/arch.

1) Does it matter which nodejs version is used for building a single binary for platform? Should it be the latest node for example? I observe that ABI 48 and 57 binaries are diff identical and ABI 64 is 40 bytes longer on Ubuntu Linux. All behave the same however.

2) Thinking about scaling across platforms, npm install fetching platform specific binary is for users more comfortable than building from source. One single binary for Linux is not enough and even if platform builds are provided I am not sure if nodejs can on target machine find out if running on SuSE or Redhat or Ubuntu for example? Is this something that node/N-API projects could address? Or addon loaders eventually, like [bindings](https://github.com/TooTallNate/node-bindings), used in [abi-stable-node-examples](https://github.com/nodejs/abi-stable-node-addon-examples/blob/master/6_object_wrap/node-addon-api/addon.js) ?

**Comment by mhdawson** [comment]
1. You should use the earliest Node.js.  The contract is forward compatibility not backwards.

2. We do build a single Node.js binary which runs across the supported Node.js linux versions (which runs on Redhat, Ubuntu, etc. provided they meet the correct dependencies).  When you say one single binary for Linux (assuming a single architecture like x86) is not enough what specific problems are you running into.  For the Node.js binaries we build on the 'earliest' kernel/glibc to be supported as Linux seems to support forward compatibility as well.  If a single binary is not possible, then I think its probably best to address the need to select the binary based on OS in something like node-pre-gyp.

**Comment by bsrdjan** [comment]
Yes, thanks a lot.
