### ISSUE TITLE
node 6.x support plan?

### ISSUE THREAD

**Issue by bsrdjan** [nodejs/node-addon-api#302]
Considering node 6.x is no longer maintained, for how long will `node-addon-api` support that release?

**Comment by bsrdjan** [comment]
Thanks. It will support all node releases, in active maintenance, correct?

**Comment by NickNaso** [comment]
Hi @bsrdjan,
yes it will support all node releases actively maintained. LTS (6.x and 8.x) and 10.x.

**Comment by bsrdjan** [comment]
Thanks.
