### ISSUE TITLE
A way to pass a file descriptor to Node?

### ISSUE THREAD

**Issue by danielgindi** [nodejs/node-addon-api#304]
As compiling a NAPI module results in a library with a separate CRT, the state containing the FD table is different.
So if I have a situation where I have a HANDLE or an FD that I want to pass to Node - I find it problematic right now.
There's no API to accept a Windows' HANDLE, and no api to duplicate an FD into Node's namespace.

Anyone knows of a way to do that?

Thank you!

**Comment by danielgindi** [comment]
Basically what I'm looking for is the inverse of `uv_get_osfhandle`

**Comment by bzoz** [comment]
Duplicate of https://github.com/nodejs/node/issues/15433?

**Comment by bzoz** [comment]
i.e. are you looking for `uv_open_osfhandle` to get implemented?

**Comment by danielgindi** [comment]
Exactly! `uv_open_osfhandle`...

**Comment by bzoz** [comment]
Fixed by https://github.com/libuv/libuv/pull/1927 included in https://github.com/nodejs/node/pull/22365

**Comment by danielgindi** [comment]
Yeah I already am enjoying this :-)
