### ISSUE TITLE
Planning to create a new release

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#308]
Any other PRs that should land first ?

The ones we discussed in the last n-api team meeting have landed.

**Comment by NickNaso** [comment]
When do you think to create a new release?

**Comment by mhdawson** [comment]
I was thinking to do it tomorrow, possibly with after the regular n-api team meeting.

**Comment by NickNaso** [comment]
Good I will happy to help!

**Comment by mhdawson** [comment]
If you want to do the release that would be great :)

We have the instructions here: https://github.com/nodejs/node-addon-api/blob/master/doc/creating_a_release.md and it would be great to have somebody other than myself having validated them.

**Comment by NickNaso** [comment]
I'm excited about that. Tomorrow after the meeting I will try create the new release 1.4

**Comment by mhdawson** [comment]
Sounds good, I should be around so if you have questions/need help just let me know.

**Comment by mhdawson** [comment]
I forgot we were going to stay on the zoom after the meeting. I've started it again if you want to join back.

**Comment by NickNaso** [comment]
The release 1.4.0 has been created and published.
