### ISSUE TITLE
Support v8::String::MakeExternal For Napi::String

### ISSUE THREAD

**Issue by frankwillis42** [nodejs/node-addon-api#311]
Thank you for taking the time to build and maintain the node-addon-api. ABI stability is of huge value to my team.

I am in a situation where I want to add additional metadata to Napi::String objects, similar to how I might add additional metadata to Napi::Object objects via the Get and Set API. Unfortunately and understandably so, Napi::String exposes no such API. When reviewing the underlying v8::String API, I noticed a method called MakeExternal instructing the v8 engine to externalize the memory management of the corresponding v8::String. By converting Napi::String to v8::String and calling MakeExternal on v8::String using a data type that I control, I was effectively able to implement the tagging of Napi::String with arbitrary metadata. Unfortunately, the conversion to v8::String and subsequent use of its APIs (ex: MakeExternal) negates the ABI stability benefit provided by node-addon-api (assumption).

Are there plans to implement v8's "MakeExternal" functionality for "Napi::String"? Or is there another way to effectively tag/attribute Napi::String objects using pure node-addon-api?

Thank you in advance!

**Comment by kfarnung** [comment]
`JsPointerToString` is Windows-only, the cross-platform equivalents (`JsCreateString` and `JsCreateStringUtf16`) both copy the string.

**Comment by gabrielschulhof** [comment]
@kfarnung is there a chance that external strings will be supported?

**Comment by devsnek** [comment]
chakrashim having something isn't a very good excuse for napi supporting it (by the values of napi, chakra should be able to implement it without shimming any v8 behaviour)

there are also other engines not considered like jerryscript and spidermonkey. this doesn't seem like a wise thing to support in napi.

however i have been considering proposing an engine-specific `napi_get_engine_handle` sorta like
```c
#ifdef V8
v8::Local<v8::Value> handle;
napi_get_engine_handle(env, val, &handle);

// do something with `handle`
#endif
```

**Comment by gabrielschulhof** [comment]
@devsnek JerryScript has some pretty significant challenges before N-API can be fully implemented on it - mostly ES2015(IIRC) stuff like `MAX_SAFE_INTEGER`, `Symbol`, etc.

**Comment by frankwillis42** [comment]
>> Unfortunately, the conversion to v8::String and subsequent use of its APIs (ex: MakeExternal) negates the ABI stability benefit provided by node-addon-api (assumption).

Can someone on the team please confirm this assumption? There is no guarantee of ABI stability between Node 8 LTS and Node 10 with respect to v8::String / v8::Value / v8::Local, thus I'd need to build a version of my extension for both 8 and 10. Is that correct?

Thank you.

**Comment by gabrielschulhof** [comment]
@frankwillis42 I confirm. As soon as you go directly to V8 you lose the guarantee of ABI stability.

**Comment by frankwillis42** [comment]
@gabrielschulhof Thank you. Much appreciated.

**Comment by mhdawson** [comment]
I'm going to close this as its been a long time since the last comment and it looks like questions were answered. Please let us know if you think that was not the right thing to do.
