### ISSUE TITLE
Using an object created in js with N-API

### ISSUE THREAD

**Issue by jasonrsadler** [nodejs/node-addon-api#314]
Hello,

This is more of a question than an issue and am having trouble finding an example of what I'm trying to do.

I've been struggling with a particular scenario for a little too long and was hoping someone with more first-hand knowledge with N-API could offer some advice.

I have an object that is created in js:
```
jsObj = {
  loadMainState: (cb) => {
    //read the file in node and call cb(data) with the result
  },
  onLgrCreate: () => {
    console.log('returned from native')
  },
  generateGUID: () => {
    console.log('generate UUID')
  },
  onConcComplete: (result, viewingId) => {
    console.log('reconcile complete')
  },
  loadSecState: (cb) => {
    console.log('load publisher state')
  },
  saveSecState: (publisherState, cb) => {
    console.log('save publisher state')
  },
  loadURL: (url, headers, content, contentType, method, cb) => {
    console.log('load URL')
  }
}
```
and I have a native module defined in which I try to pass in the object to the native module's ctor:

```
const NativeObj = require('bindings')('addon').NativeObj
...
const obj = new NativeObj(jsObj)
```

The reason for this is that we will have many different platforms coordinating on the C++ side and need a way to bring in an already created js object that will match accordingly. 

I assume I'll need some operations to unwrap and work with `jsObj` on the native side. The problem I'm having is going about how to set this up? I have a 'match' on the C++ side for jsObj but have not been successful in unwrapping on native. Here is as far as I've gotten thus far on the C++ side:
```
NativeObjWrap::NativeObjWrap(const Napi::CallbackInfo &info) : Napi::ObjectWrap<NativeObjWrap>(info) {
  Napi::Env env = info.Env();
  Napi::Object jsObj = info[0].As<Napi::Object>();
  Napi::Function func = JSObjWrap::constructor.Value().As<Napi::Function>();
  if (!jsObj.InstanceOf(JSObjWrap::constructor.Value().As<Napi::Function>())) {
    Napi::TypeError::New(info.Env(), "A jsObj was expected").ThrowAsJavaScriptException(); //<-- so far, always throws
  }
```
Is what I'm trying to do possible?

Also, my terminology may not be completely accurate and I'm reintroducing myself to C++ after many years of not using it, so feel free to correct any misconceptions I have.

(cc @mhdawson @jasongin as I'm seeing that you have the lock on knowledge related to the node-addon-api, Thanks!)

**Comment by NickNaso** [comment]
Hi @jasonrsadler,
if I well understood you want call the functions in the `jsObj` from native side (C++). Is it right?

**Comment by jasonrsadler** [comment]
Hi @NickNaso,

I do, but with some caveats. 

In short, we have a library that we statically link to that does "a bunch of other things" that require the jsObj passed in from the js side without knowing the details of jsObj. This library also uses other versions of "jsObj" that aren't from JS (i. e. Android, iOS, etc) so the idea that we're trying to see is possible is if we can make sure that the implementation of jsObj can stay on the platform that it's on without recreating it in the addon library (recreating, as in, not redoing the logic. I assume we'll have to setup an object for wrapping/unwrapping). 

I'm not sure if I'm explaining this very clearly but I hope that defines our case clearer.

Thanks for responding! +1

Jason

**Comment by NickNaso** [comment]
Hi @jasonrsadler ,
my idea is to store the JavaScript object in a reference see: [Object Reference](https://github.com/nodejs/node-addon-api/blob/master/doc/object_reference.md) so you can use the object later and for example you can execute some function. In the following code i report a little and simple example and you can find all the project on the attached file called **try.zip**. I hope that this could be useful to your case.
[try.zip](https://github.com/nodejs/node-addon-api/files/2250904/try.zip)

```js
var MyObject = require('bindings')('addon').MyObject;

var opts = {
    loadMainState: (cb) => {
      //read the file in node and call cb(data) with the result
    },
    onLgrCreate: () => {
      console.log('returned from native')
    },
    generateGUID: () => {
      console.log('generate UUID')
    },
    onConcComplete: (result, viewingId) => {
      console.log('reconcile complete')
      console.log('result => ', result)
      console.log('viewingId => ', viewingId)
    },
    loadSecState: (cb) => {
      console.log('load publisher state')
    },
    saveSecState: (publisherState, cb) => {
      console.log('save publisher state')
    },
    loadURL: (url, headers, content, contentType, method, cb) => {
      console.log('load URL')
    }
}

var obj = new MyObject(opts);
obj.myMethod()
```
```cpp
#include "myobject.h"

Napi::FunctionReference MyObject::constructor;

Napi::Object MyObject::Init(Napi::Env env, Napi::Object exports) {
  Napi::HandleScope scope(env);

  Napi::Function func = DefineClass(env, "MyObject", {
    InstanceMethod("myMethod", &MyObject::MyMethod)
  });

  constructor = Napi::Persistent(func);
  constructor.SuppressDestruct();

  exports.Set("MyObject", func);
  return exports;
}

MyObject::MyObject(const Napi::CallbackInfo& info) : Napi::ObjectWrap<MyObject>(info)  {
  Napi::Env env = info.Env();
  Napi::HandleScope scope(env);
  Napi::Object obj = info[0].As<Napi::Object>();
  this->ref =  Reference<Napi::Object>::New(obj);
}

Napi::Value MyObject::MyMethod(const Napi::CallbackInfo& info) {

  Napi::Env env = info.Env();

  // Here you can call the js function and at the same time you can use your
  // C / C++ library
  
  Napi::Function onLgrCreate = this->ref.Get("onLgrCreate").As<Napi::Function>();
  // Call function whitout arguments
  onLgrCreate.Call({});

  Napi::Function onConcComplete = this->ref.Get("onConcComplete").As<Napi::Function>();
  Napi::Number result = Napi::Number::New(env, 11);
  Napi::String uid = Napi::String::New(env, "11IIXPRTKKIYAGH");
  // Call function with arguments
  onConcComplete.Call({result, uid});
  
  return info.Env().Undefined();
}
```

**Comment by jasonrsadler** [comment]
Yes!
That helps the majority of my problem. One last part is that I need the `opts` object to be converted to a C++ class that is used as an argument for another C++ object in a statically linked library.

Here's the link to the line and code in question if you have any ideas:
https://github.com/jasonrsadler/native-ledger-node/blob/master/src/c/node-addon-api/node_ledger_wrap.cc#L53-L54

Thanks so much for your help. It has solved one of the major problems I was faced with so far.

**Comment by NickNaso** [comment]
Hi @jasonrsadler ,
the `opts` object is an instance of `NodeLedgerClientWrap` and you use it in to `NodeLedgerWrap` . What you can do to retrieve the original `ledger::LedgerClient` is:
 
```cpp
NodeLedgerClientWrap* obj1 = Napi::ObjectWrap<NodeLedgerClientWrap>::Unwrap(info[0].As<Napi::Object>());
```
Now you can obtain the client calling the method `Client()`

```cpp
obj1->Client();
```
At the end you can pass the result to  `Ledger::CreateInstance()` method.

I just briefly looked at your code so my idea could be wrong.

**Comment by jasonrsadler** [comment]
Hi @NickNaso 
Thanks for responding.

I've tried the Unwrap several times and several different ways only to get back `napi_invalid_arg` status. 
I'm wondering if something special needs to be done to 'force' N-API to see the incoming js object as an object of that type.

Thanks again for your help.

**Comment by NickNaso** [comment]
Hi @jasonrsadler ,
I think that the error happen because you need to pass at `NodeLedger` an instance of `LedgerClient`  now you are simply passing a plain object.

```js
const NodeLedger = require('bindings')('addon').NodeLedger
const LedgerClient = require('bindings')('addon').LedgerClient
/*ledgerClient = {
  loadLedgerState: (cb) => {
    //read the file in node and call cb(data) with the result
  },
  onWalletCreate: () => {
    console.log('returned from native')
  },
  generateGUID: () => {
    console.log('generate UUID')
  },
  onReconcileComplete: (result, viewingId) => {
    console.log('reconcile complete')
  },
  loadPublisherState: (cb) => {
    console.log('load publisher state')
  },
  savePublisherState: (publisherState, cb) => {
    console.log('save publisher state')
  },
  loadURL: (url, headers, content, contentType, method, cb) => {
    console.log('load URL')
  }
}*/

console.log('beginning ' + NodeLedger);

const ledger = new NodeLedger(new LedgerClient());
ledger.createWallet();
```
This is the code I can see on your repo maybe you already tried this.

**Comment by jasonrsadler** [comment]
Exactly. That's what I want to know. Can we pass in a plain js object and unwrap it to a C++ object?

**Comment by NickNaso** [comment]
Hi @jasonrsadler,
I'm happy to listen this. Write us if you need other feedback and feel free to close the issue.

**Comment by jasonrsadler** [comment]
@NickNaso pointed me in the right direction.
🎊 👍

**Comment by jasonrsadler** [comment]
@NickNaso One more quick question regarding:
```
Napi::Function onConcComplete = this->ref.Get("onConcComplete").As<Napi::Function>();
  Napi::Number result = Napi::Number::New(env, 11);
  Napi::String uid = Napi::String::New(env, "11IIXPRTKKIYAGH");
  // Call function with arguments
  onConcComplete.Call({result, uid});
```
Is it possible to have a C++ function as an argument to the JS function (as a callback)? If so, what do you think is the best way to implement that?

**Comment by NickNaso** [comment]
Hi @jasonrsadler ,

in your class or in some part of your code you can create a function like reported below:

```cpp
#include <napi.h>
Napi::Value Fn(const CallbackInfo& info) {
  Env env = info.Env();
  // ...
  // Here you can use your C++ function and then return some result
  return ...
}
```
and then you can create a function and pass it as callback:

```cpp
Napi::Function onConcComplete = this->ref.Get("onConcComplete").As<Napi::Function>();
Napi::Number result = Napi::Number::New(env, 11);
Napi::String uid = Napi::String::New(env, "11IIXPRTKKIYAGH");
Napi::Function fn = Napi::Function::New(env, Fn);
// Call function with arguments
onConcComplete.Call({result, uid, fn});
```

This is the most simple thing the you can do. I hope that the example is good, if not keep me updated I will provide more explanation later when I will came back home.

**Comment by jasonrsadler** [comment]
Again, you have pointed me in the right direction. I was able to attach the callback to the callback with the following:
```
Napi::Value OnConcCompleteCallback
  (const Napi::CallbackInfo& info) {
    std::cout << "back in native" << std::endl;
}
...
Napi::Function onConcComplete = this->ref->Get("onConcComplete").As<Napi::Function>();

// The following line allowed me to attach a callback to the callback :)
onConcComplete.Set(Napi::String::New(jsClient->Env(), "callback"), 
    Napi::Function::New(jsClient->Env(), OnConcCompleteCallback));
  onConcComplete.Call({ onConcComplete.Get("callback").As<Napi::Function>() });
}
```

Thank you again @NickNaso for all your help. I think I'm starting to get the hang of this API now.

**Comment by bjeepka** [comment]
I'm interested in seeing this code without the node-addon-api support.  What is the best way to accomplish this?

thanks!
