### ISSUE TITLE
MakeCallback aborts poorly when a JS exception is thrown.

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/node-addon-api#319]
> libc++abi.dylib: terminating with uncaught exception of type Napi::Error

See https://gist.github.com/Fishrock123/a2b3aa37da332ca9dee88ed22825e03a

My `binding.gyp` has all this stuff so I **think** C++ exceptions are indeed properly enabled:

```
      "cflags!": [ "-fno-exceptions" ],
      "cflags_cc!": [ "-fno-exceptions" ],
      "xcode_settings": {
        "GCC_ENABLE_CPP_EXCEPTIONS": "YES",
        "CLANG_CXX_LIBRARY": "libc++",
        "MACOSX_DEPLOYMENT_TARGET": "10.7",
      },
      "msvs_settings": {
        "VCCLCompilerTool": { "ExceptionHandling": 1 },
      },
```

**Comment by mhdawson** [comment]
Does it make any difference if you remove  ` self->cb_ref_.Unref();` after the call to MakeCallback ?

**Comment by mhdawson** [comment]
Next question is which version of node-addon-api are you using?  This PR fixed one issue related to MakeCallback/Call on FunctionReference with respect to exceptions being thrown.

Also can't tell from the bit of code in the gist if you should be using Call for MakeCallback, many of the times Call is the right one of the 2 as explained here:  https://github.com/nodejs/node-addon-api/pull/299/files or specifically:

```md
With the `Function` class it is possible to call a JavaScript function object
from a native add-on with two different methods: `Call` and `MakeCallback`.
The API of these two methods is very similar, but they are used in different
contexts. The `MakeCallback` method is used to call from native code back into
JavaScript after returning from an [asynchronous operation](async_operations.md)
and in general in situations which don't have an existing JavaScript function on
the stack. The `Call` method is used when there is already a JavaScript function
on the stack (for example when running a native method called from JavaScript).
```

**Comment by gabrielschulhof** [comment]
@Fishrock123 having a complete minimum example that reproduces the failure would also be helpful.

**Comment by NickNaso** [comment]
Any news from this issue?

**Comment by Fishrock123** [comment]
No news. I haven't had time to look at it but I wasn't doing anything particularly exotic.

**Comment by mhdawson** [comment]
I'm going to close this since it looks like the discussion/investigation is not going to proceed. Please let me know if you think that was not the right thing to do.
