### ISSUE TITLE
FunctionReference is missing cargs overloads for Call and MakeCallback

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/node-addon-api#320]
https://nodejs.github.io/node-addon-api/class_napi_1_1_function_reference.html

FunctionReference doesn't have these but Function does. Seems strange. cargs are easier for not very C++ affluent people like me to use.

**Comment by NickNaso** [comment]
@gabrielschulhof  @mhdawson I think that we can add the method as proposed by @Fishrock123. In the specific we should add these in `napi.h` : 
```cpp
Napi::Value Call(napi_value recv, size_t argc, const napi_value* args) const;

Napi::Value MakeCallback(napi_value recv, size_t argc, const napi_value* args) const;
```
and these on `napi-inl.h`:

```cpp
inline Napi::Value FunctionReference::Call(
    napi_value recv, size_t argc, const napi_value* args) const {
  EscapableHandleScope scope(_env);
  Napi::Value result = Value().Call(recv, argc, args);
  if (scope.Env().IsExceptionPending()) {
    return Value();
  }
  return scope.Escape(result);
}

inline Napi::Value FunctionReference::MakeCallback(
    napi_value recv, size_t argc, const napi_value* args) const {
  EscapableHandleScope scope(_env);
  Napi::Value result = Value().MakeCallback(recv, argc, args);
  if (scope.Env().IsExceptionPending()) {
    return Value();
  }
  return scope.Escape(result);
}
```

if you agree I can work on it and at the same time start to create tests about `FunctionReference`.

**Comment by mhdawson** [comment]
Adding those make sense to me.  Makes it more consistent with the methods we have on Function.

**Comment by NickNaso** [comment]
OK I will take this.

**Comment by NickNaso** [comment]
I'm closing the issue because the requested feature is landed with **[https://github.com/nodejs/node-addon-api/pull/344](https://github.com/nodejs/node-addon-api/pull/344)**
