### ISSUE TITLE
How to handle LARGE INTEGER ?

### ISSUE THREAD

**Issue by fraxken** [nodejs/node-addon-api#324]
Hi,

I'm trying to handle a LARGE INTEGER for one of my native addon. I'm working with the following struct: https://docs.microsoft.com/en-us/windows/desktop/api/winioctl/ns-winioctl-_disk_performance

Not sure how i have to handle these with the API (since double is not valid). I have two cases in mind:

- Getting HighPart and LowPart (but i'm confused on how exactly i have to rebuilt the final result on JavaScript)
- Convert the LARGE INTEGER into Napi::String

My project is accessible here: https://github.com/SlimIO/WinDisk (method getDrivePerformance).

I'm a beginner with C/C++ and native node addon, so i'm open to any feedbacks.

Thanks for your time ! 

Best Regards,
Thomas

**Comment by fraxken** [comment]
Maybe QuadPart is what i need. I'm not sure :\

**Comment by devsnek** [comment]
you can also use the napi_bigint type

**Comment by fraxken** [comment]
Yes,

thank you I found a solution. I will take a look with napi_bigint too ! 

Best Regards,
Thomas
