### ISSUE TITLE
Bring in env cleanup hooks

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/node-addon-api#327]
We should bring in the env cleanup hooks, and mark the first version of v6.x that features the env cleanup hooks as the first version of Node.js to ship N-API.

I believe we have to do this, because that version of v6.x will be the first to truly have N-API v3.

**Comment by gabrielschulhof** [comment]
https://github.com/nodejs/node-addon-api/pull/397

**Comment by mhdawson** [comment]
@gabrielschulhof I know you've done a lot of work on the cleanup side. Is this still a gap?

**Comment by mhdawson** [comment]
@gabrielschulhof ping, I know you've done a lot of work on the cleanup side. Is this still a gap?
