### ISSUE TITLE
A couple of stream related questions

### ISSUE THREAD

**Issue by dmooney65** [nodejs/node-addon-api#336]
Hi,

I've written an [example Transform stream](https://github.com/dmooney65/napi-example-transformstream) implementation using this API. I basically took the [inherits_from_event_emitter](https://github.com/nodejs/abi-stable-node-addon-examples/tree/master/inherits_from_event_emitter/node-addon-api) example, did some renaming and modified it to inherit from streams.Transform instead of EventEmitter. It emits all the Transform events correctly.  All it does is pass back the input buffers unmodified so behaves like a PassThrough stream. 

It works just fine on Linux and Mac but I get an intermittent error from Windows (Win10 laptop and Win7 VM running on Linux) when passing the output to a write stream created with fs.createWriteStream().
{ Error: UNKNOWN: unknown error, write errno: -4094, code: 'UNKNOWN', syscall 'write' }
To be clear this error is emitted from the write stream, not the transform stream. Is this just Windows strangeness or am I doing something wrong in my code? I'm a bit of a noob with c++.

Also I'm using 2 plain Napi methods - napi_get_buffer_info and napi_get_element. Do these methods have wrappers in the API?

**Comment by NickNaso** [comment]
Hi @dmooney65,
I will take a look at your code after, in the mean time I'm super curios if your problem persist if you use the example at this link [https://github.com/NickNaso/addon-stream](https://github.com/NickNaso/addon-stream). It's just a passthrough stream example.

**Comment by dmooney65** [comment]
Thanks @NickNaso ,
In short - no my problem goes away!
I'll do some investigating tomorrow as both examples are very similar. Wish I'd found your example earlier, but then I wouldn't have "learned" eh?

**Comment by dmooney65** [comment]
OK now fixed by doing something with the input buffer before passing it back to JS.
Thanks
