### ISSUE TITLE
Failure on ubuntu 32  after latest lands

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#337]
First guess is that may have been caused by:https://github.com/nodejs/node-addon-api/pull/315 as I don't see changes in the napi-inl.h on line 798

https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api/MACHINE=ubuntu1404-32/675/console

```
  CXX(target) Release/obj.target/binding/object/set_property.o
../object/object.cc: In function 'Napi::Value CreateObjectUsingMagic(const Napi::CallbackInfo&)':
../object/object.cc:129:6: error: ambiguous overload for 'operator[]' (operand types are 'Napi::Object' and 'int')
   obj[42] = 120;
      ^
../object/object.cc:129:6: note: candidates are:
../object/object.cc:129:6: note: operator[](napi_value, int) <built-in>
In file included from /home/iojs/build/workspace/node-test-node-addon-api/MACHINE/ubuntu1404-32/node-addon-api/napi.h:1564:0,
                 from ../object/object.cc:1:
/home/iojs/build/workspace/node-test-node-addon-api/MACHINE/ubuntu1404-32/node-addon-api/napi-inl.h:786:41: note: Napi::Object::PropertyLValue<unsigned int> Napi::Object::operator[](uint32_t)
 inline Object::PropertyLValue<uint32_t> Object::operator [](uint32_t index) {
                                         ^
/home/iojs/build/workspace/node-test-node-addon-api/MACHINE/ubuntu1404-32/node-addon-api/napi-inl.h:798:14: note: Napi::Value Napi::Object::operator[](uint32_t) const
 inline Value Object::operator [](uint32_t index) const {
              ^
make: *** [Release/obj.target/binding/object/object.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by mhdawson** [comment]
@gabrielschulhof @mcheshkov

**Comment by gabrielschulhof** [comment]
This probably stems from the fact that an old version of gcc builds
node-addon-api on that machine. Still, if its a version of gcc supported by
Node.js, we need to accommodate it.

**Comment by gabrielschulhof** [comment]
@mhdawson I was able to build successfully on Ubuntu 14.04 with gcc 4.8.4 (4.8.4-2ubuntu1~14.04.3). What version of gcc is present on the test machine?

**Comment by mhdawson** [comment]
iojs@test-digitalocean-ubuntu1404-x86-1:~$ gcc --version
gcc (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE

**Comment by mhdawson** [comment]
Was the ubuntu you had 32 bit? That seems to be one thing that is different as well.

**Comment by gabrielschulhof** [comment]
Reproduced locally.
