### ISSUE TITLE
ObjectWrap is not type-safe

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/node-addon-api#357]
When using `ObjectWrap` the instance methods and accessors all use `napi_unwrap()` to retrieve the native object instance from the `this` parameter. This should not be done without first using `napi_instanceof()` to ensure that the `this` parameter is an instance of the JavaScript class corresponding to the `ObjectWrap` class.

After all, one can do the following:
```JS
const {MyClass1, MyClass2} = require('./build/Release/binding');
const myClass1Instance = new MyClass1();
const myClass2Instance = new MyClass2();
myClass1Instance.someMethod.apply(myClass2Instance);
```
Now the native implementation of `someMethod` will successfully unwrap its `this` argument, but the resulting pointer will be to an instance of `MyClass2`, not `MyClass1`, but it will be cast to a pointer to an instance of `MyClass1` with potentially segfaulty results.

The standard solution has been to store the `napi_value` resulting from `napi_define_class()` in a static class variable, and to perform `napi_instanceof()` before `napi_unwrap()`. However, in light of the ever-increasing likelyhood  of an addon getting loaded multiple times, using static variables to store persistent references to JavaScript values is no longer viable.

It seems like we need to introduce a second level of dynamism. Instead of a JavaScript class corresponding to a native class, a JavaScript class has to correspond to a native instance.

**Comment by mhdawson** [comment]
@gabrielschulhof is this still need now that the ObjectWrap methods are templated due to https://github.com/nodejs/node-addon-api/commit/ce91e14860ef6ee5c733e2a2e90263e30ac5038e

**Comment by mhdawson** [comment]
@gabrielschulhof ping, just wondering if we still need this be open?
