### ISSUE TITLE
Version management documentation

### ISSUE THREAD

**Issue by NickNaso** [nodejs/node-addon-api#358]
There is a little inconsistency on `Napi::VersionManagement` documentation.

Now the two static methods exposed by `Napi::VersionManagement` are documented like reported below:

```cpp
static uint32_t GetNapiVersion(Env env);
``` 

```cpp
static const napi_node_version* GetNodeVersion(Env env);
```

instead they will be fixed as reported below:

```cpp
static uint32_t Napi::VersionManagement::GetNapiVersion(Env env);
``` 

```cpp
static const napi_node_version* Napi::VersionManagement::GetNodeVersion(Env env);
```

**Comment by nadongguri** [comment]
Hi @NickNaso, I will take this issue.

**Comment by NickNaso** [comment]
I'm closing this issue because it has been solved with **[https://github.com/nodejs/node-addon-api/pull/360](https://github.com/nodejs/node-addon-api/pull/360)**
