### ISSUE TITLE
Implement iterable protocol using Symbol.iterator

### ISSUE THREAD

**Issue by dpasco** [nodejs/node-addon-api#373]
I am attempting to add the iterable protocol to an object. I can do this successfully by adding a method to the object manually in node but I cannot get it to work using Napi::Symbol::WellKnown().
I started with the 6_object_wrap example, adding two methods - iterable and next. I added next and iterable to the DefineClass() list. If I use a literal string as a symbol name then I can run the addon.js example but if I use Napi::Symbol::WellKnown(env,"Symbol.iterator") I get an error at module load time.
If I add the function manually (node session, instantiate object and define a function by setting obj[Symbol.iterator]) then it works as expected.

```C++
Napi::Object MyObject::Init(Napi::Env env, Napi::Object exports) {
  Napi::HandleScope scope(env);

  Napi::Function func = DefineClass(env, "MyObject", {
    InstanceMethod("plusOne", &MyObject::PlusOne),
    InstanceMethod("value", &MyObject::GetValue),
    InstanceMethod("multiply", &MyObject::Multiply),
    InstanceMethod("next", &MyObject::next),
    InstanceMethod(Napi::Symbol::WellKnown(env,"Symbol.iterator"),&MyObject::iterable),
    // InstanceMethod(Napi::Symbol::New(env,"foo"),&MyObject::iterable)
  });

  constructor = Napi::Persistent(func);
  constructor.SuppressDestruct();

  exports.Set("MyObject", func);
  return exports;
}

Napi::Value MyObject::next(const Napi::CallbackInfo& info) {
  Napi::Object iter = Napi::Object::New(info.Env());
  iter.Set("done",true);
  return iter;
}

Napi::Value MyObject::iterable(const Napi::CallbackInfo& info) {
  return info.This();
}
```
The error I see when attempting to add iterable in my addon is:
```Shell
node-addon-api danp$ node addon.js
/Users/danp/projects/examples/abi-stable-node-addon-examples/6_object_wrap/node-addon-api/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: A string or symbol was expected
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/Users/danp/projects/examples/abi-stable-node-addon-examples/6_object_wrap/node-addon-api/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/danp/projects/examples/abi-stable-node-addon-examples/6_object_wrap/node-addon-api/addon.js:1:94)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```
This is a simple example using an excerpt from my actual project (not the modified sample):
```JavaScript
    let lit = getIterator(...args);
    lit[Symbol.iterator] = function () {
        return this; 
      }

    for (v of lit) {
      console.log(v);
    }
```

Running this produces valid results (a few included here):
```Shell
$ node ittest.js
Zero
One
Two
Three
Four
Five
Six
Seven
Eight
Nine
Alfa
Bravo
Charlie
Delta
Echo
```
I appreciate any and all help.

**Comment by mhdawson** [comment]
You may have already tried this, but looking at the implementation of `Napi::Symbol::WellKnown` my first guess is that you should be using 

`InstanceMethod(Napi::Symbol::WellKnown(env,"iterator"),&MyObject::iterable)` 

Since `Symbol` is already included in the lookup in 

`
inline Symbol Symbol::WellKnown(napi_env env, const std::string& name) {
  return Napi::Env(env).Global().Get("Symbol").As<Object>().Get(name).As<Symbol>();
}
`

**Comment by dpasco** [comment]
Thanks - I just tried this and it works! Sorry for all the drama for such a simple problem.

I tried @@iterator but not iterator by itself.

On Oct 23, 2018, at 8:07 AM, Michael Dawson <notifications@github.com<mailto:notifications@github.com>> wrote:


You may have already tried this, but looking at the implementation of Napi::Symbol::WellKnown my first guess is that you should be using

InstanceMethod(Napi::Symbol::WellKnown(env,"iterator"),&MyObject::iterable)

Since Symbol is already included in the lookup in

inline Symbol Symbol::WellKnown(napi_env env, const std::string& name) {
  return Napi::Env(env).Global().Get("Symbol").As<Object>().Get(name).As<Symbol>();
}

**Comment by mhdawson** [comment]
Great to hear and glad I could help :).  I'll close this, let me know if that is not the right thing to do.

**Comment by dpasco** [comment]
If this project is successful we will be wrapping it up in the next two weeks with a planned deployment early next year. We aren’t doing anything crazy with it but you might see it appear somewhere in the near future.

Thanks for you help and - yes - closing it is the right thing to do. I’m a bit embarrassed because of an amateur mistake.



On Oct 23, 2018, at 8:54 AM, Michael Dawson <notifications@github.com<mailto:notifications@github.com>> wrote:


Great to hear and glad I could help :). I'll close this, let me know if that is not the right thing to do.
