### ISSUE TITLE
Membership review - still active?

### ISSUE THREAD

**Issue by jschlight** [nodejs/node-addon-api#375]
The N-API team decided to initiate a membership review during its October 4, 2018 meeting using the procedure established by the Node [Security](https://github.com/nodejs/security-wg/issues/302) and [Diagnostics](https://github.com/nodejs/diagnostics/issues/215) Working Groups. 

@addaleax - Anna Henningsen
@aruneshchandra - Arunesh Chandra
@kkoopa - Benjamin Byholm
@gabrielschulhof - Gabriel Schulhof
@digitalinfinity - Hitesh Kanwathirtha
@jasongin - Jason Ginchereau
@mhdawson - Michael Dawson
@NickNaso - Nicola Del Gobbo
@sampsongao - Sampson Gao
@boingoing - Taylor Woll

Please confirm by posting a comment on this issue if you plan to continue being active in the `node-addon-api` project. If we don't hear from you we will move you to emeritus status.

**Comment by NickNaso** [comment]
Hi everyone I want continue to contribute to this project.

**Comment by addaleax** [comment]
I’ll continue to engage on the code, but not necessarily in the working group (so, basically what I’m doing right now).

**Comment by gabrielschulhof** [comment]
I'll keep on contributing 🙂

**Comment by mhdawson** [comment]
I'm still around and active :)
