### ISSUE TITLE
How to save an Napi::Value in a Napi::ObjectWrap instance

### ISSUE THREAD

**Issue by verdie-g** [nodejs/node-addon-api#379]
Hi,

I have the following code:

```cpp
#include "lookup-wrapper.hh"

Napi::FunctionReference LookupWrapper::constructor;

Napi::Object LookupWrapper::Init(Napi::Env env, Napi::Object exports)
{
  Napi::HandleScope scope(env);

  Napi::Function ctor = DefineClass(env, "Lookup", {
      InstanceAccessor("n", &LookupWrapper::get_n, nullptr),
  });

  constructor = Napi::Persistent(ctor);
  constructor.SuppressDestruct();

  exports.Set("Lookup", ctor);
  return exports;
}

LookupWrapper::LookupWrapper(const Napi::CallbackInfo& info)
  : Napi::ObjectWrap<LookupWrapper>(info)
{
  Napi::Env env = info.Env();
  Napi::HandleScope scope(env);
  n = info[0];
}

Napi::Value LookupWrapper::get_n(const Napi::CallbackInfo& info)
{
  return n;
}
```

If I instantiate a Lookup and I try to get the value `n`, a random number is returned as if it was overwritten. I thought `n` was destroy at the end of the constructor so I have desperately tried things like using EscapableHandleScope or copying `info[0]` with Napi::Number constructor, but it is not what I am looking for. What am I missing ?

**Comment by gabrielschulhof** [comment]
You'll want to define `n` as `int32_t n;` and then, in the constructor, you would set
```C++
n = info[0].As<Napi::Number>();
```
and then, in the getter, you would
```C++
return Napi::Number::New(info.Env(), n);
```

**Comment by NickNaso** [comment]
Hi @verdie-g,
at the following link you can find an example that cover your use case:
**[https://github.com/nodejs/node-addon-examples/tree/master/6_object_wrap/node-addon-api](https://github.com/nodejs/node-addon-examples/tree/master/6_object_wrap/node-addon-api)**

**Comment by verdie-g** [comment]
Isn't it possible to stored a Napi::Value ? My code is more complex than my example and it would come handy.

**Comment by NickNaso** [comment]
You can store the your primitive C / C++ value or object in the private field of the object wrap class, but if you want store the `Napi::Value` you can do creating a  reference to that specific native object using  `Napi::Reference`, this means that you can use a private field of your class to store the `Napi::Reference`. In this case your `Napi::Value`will be stored in a  `Napi::Reference` and it will not be garbage collected after the function call. 
For more info about `Napi::Reference` take a look at its documentation here: [https://github.com/nodejs/node-addon-api/blob/master/doc/reference.md](https://github.com/nodejs/node-addon-api/blob/master/doc/reference.md)

**Comment by verdie-g** [comment]
Thank you, this it exactly what I was looking for
