### ISSUE TITLE
Object::GetPropertyNames() not const

### ISSUE THREAD

**Issue by AeromXundes** [nodejs/node-addon-api#380]
The method `Object::GetPropertyNames()` is not declared `const`.

The method [`napi_get_property_names()`](https://nodejs.org/dist/latest/docs/api/n-api.html#n_api_napi_get_property_names) cannot not modify any member fields as the variables `_env` and `_value` are passed by value and `result` is a local variable. Thus, the function should be declared as `const`.

This will add the ability to declare a `const Object` and still get the property names associated with the object.

**Comment by DaAitch** [comment]
@AeromXundes agree: PR created
