### ISSUE TITLE
ErrnoException isn't defined

### ISSUE THREAD

**Issue by computerquip-streamlabs** [nodejs/node-addon-api#382]
The converter script seems to use `ErrnoException` but I can't seem to find this anywhere. I've also seen it in other examples. Where is this supposed to be defined?

**Comment by mhdawson** [comment]
Do you have a link for one of the examples?

**Comment by computerquip** [comment]
I figured out why this is done. Napi doesn't have an ErrnoException. So I have this: 
```
	auto exception = Nan::ErrnoException(
		ec.value(),
		context_msg,
		ec.message().c_str()
);
```
this converts to:
```
	auto exception = Napi::ErrnoException(
		ec.value(),
		context_msg,
		ec.message().c_str()
	);

	Napi::Error::New(env, exception).ThrowAsJavaScriptException();
```

The regex that finds this is here: https://github.com/nodejs/node-addon-api/blob/master/tools/conversion.js#L177

Seems manual intervention is needed here. Sorry for the confusion.
