### ISSUE TITLE
New release 1.6.1

### ISSUE THREAD

**Issue by NickNaso** [nodejs/node-addon-api#396]
Hi everyone,
I want publish a patch release v1.6.1 when the following PRs will be landed:
- [x] src: guard CallbackScope with N-API v3  **[395](https://github.com/nodejs/node-addon-api/pull/395)**
- [x] src: remove unused CallbackScope member **[391](https://github.com/nodejs/node-addon-api/pull/391)**

If anyone want insert other updates or fixes in this release please comment this issue.

**Comment by mhdawson** [comment]
@NickNaso landed those 2 today.

**Comment by NickNaso** [comment]
@mhdawson Thanks I will provide to create the release as soon as possible.

**Comment by NickNaso** [comment]
I'm starting working on publish new release.

**Comment by NickNaso** [comment]
I'm closing the issue because I just published the release.

**Comment by mhdawson** [comment]
@NickNaso thanks !
