### ISSUE TITLE
Factor out C++ wrappers to target js-native-api

### ISSUE THREAD

**Issue by bghgary** [nodejs/node-addon-api#399]
Following the work from https://github.com/nodejs/abi-stable-node/issues/354, it would be ideal if the code in the C++ wrappers can also be factored out.

CC @gabrielschulhof @mhdawson

**Comment by bghgary** [comment]
Hi @gabrielschulhof @mhdawson,

It's been a while, but we are finally ready to push some changes. @syntheticmagus has created a draft PR (#569) with some changes that will suit our needs. Do you mind taking a look? Thanks.

**Comment by mhdawson** [comment]
The referenced PR was closing so I think this issue can be closed as well until those involved have time to move it forward again. Please let us know if you think that was not the right thing to do.
