### ISSUE TITLE
Internal/external selection broken for latest 6.x release

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#401]
Looks like this logic in https://github.com/nodejs/node-addon-api/commit/437514e75b47dcb2335d4958deb5954b35e8b8e2

Is not quite right: 

``` 
var isNodeApiBuiltin = (
  versionArray[0] > 8 ||
  (versionArray[0] == 8 && versionArray[1] >= 6) ||
  (versionArray[0] == 6 && versionArray[1] >= 14 && versionArray[2] >= 2));
```

**Comment by mhdawson** [comment]
Branch with test fix here: https://github.com/mhdawson/node-addon-api/tree/fixselection

**Comment by mhdawson** [comment]
PR for fix: https://github.com/nodejs/node-addon-api/pull/402

@NickNaso if you have time we probably want to plan a release with this fix.  As of the security releases earlier this week and the  bump of 6.14 -> 6.15 node-addon-api is broken for the 6.X line.

**Comment by NickNaso** [comment]
Hi @mhdawson I will provide to open an issue with the intention on making new release v1.6.2.

**Comment by mhdawson** [comment]
@NickNaso thanks.  Landed PR and just running CI job to validate all is resolved: 

https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-LTS%20versions/

**Comment by mhdawson** [comment]
CI run looks good closing.
