### ISSUE TITLE
New release 1.6.2

### ISSUE THREAD

**Issue by NickNaso** [nodejs/node-addon-api#403]
Hi everyone,
I want make a new release v1.6.2. 
This is necessary because of the releases of new security version of Node.js, now node-add on-api is broken for the 6.X. 
Before to start creating the new release it’s necessary execute the following tasks:

- [x] Land the PR [https://github.com/nodejs/node-addon-api/pull/402](
https://github.com/nodejs/node-addon-api/pull/402) 

If someone want add other things on this release please comment on this issue or simply edit the list above.

**Comment by NickNaso** [comment]
I'm starting to prepare release.

**Comment by NickNaso** [comment]
I'm closing the issue because I just made the new release.

**Comment by mhdawson** [comment]
@NickNaso thanks
