### ISSUE TITLE
How do I throw events from a c++ event handler function ?

### ISSUE THREAD

**Issue by sudhakar3697** [nodejs/node-addon-api#404]
Hi,
How do I emit event from the "Watcher_EventArrived" function ?
//call2 isn't working

#include <napi.h>
#include <msclr\marshal_cppstd.h>
//#using <../Hello.dll>
using namespace System;
using namespace Management;
using namespace Threading;

#pragma managed

 Napi::Function emit;
 void Watcher_EventArrived(Object^ sender,EventArrivedEventArgs^ e)
{
	 IO::File::CreateText("C:\\Users\\Sudhakar_r_R\\Desktop\\tenpi"+(x++)+".txt");
	 IO::File::CreateText("C:\\Users\\Sudhakar_r_R\\Desktop\\tenpi" + (x) + ".txt");
	 emit.Call({ Napi::String::New(emit.Env(), "Detected") }); //call 2
}
 void Detect_USB() {
	 ManagementEventWatcher^ watcher = gcnew ManagementEventWatcher();
	 WqlEventQuery^ query = gcnew WqlEventQuery("SELECT * FROM Win32_VolumeChangeEvent WHERE EventType = 2 or EventType = 3");
	 watcher->EventArrived += gcnew EventArrivedEventHandler(Watcher_EventArrived);
	 watcher->Query = query;
	 watcher->Start();
	 watcher->WaitForNextEvent();
 }

Napi::String SaySomething(const Napi::CallbackInfo& info){
	Napi::Env env=info.Env();
	//iex = info.Env();
	emit=info[0].As<Napi::Function>();
	Thread^ t = gcnew Thread(gcnew ThreadStart(Detect_USB));
	t->Start();		
		emit.Call({ Napi::String::New(info.Env(), "Detected") }); //call 1
	return Napi::String::New(env,"Ran");
}

#pragma unmanaged

Napi::Object init(Napi::Env env, Napi::Object exports) {
		exports.Set(Napi::String::New(env, "SaySomething"), Napi::Function::New(env, SaySomething));
    return exports;
};

NODE_API_MODULE(usbaddon, init);

**Comment by NickNaso** [comment]
Any news from this issue?

**Comment by sudhakar3697** [comment]
Sorry for replying late @NickNaso  :).

#include <napi.h>
#include <msclr\marshal_cppstd.h>
using namespace System;
using namespace Management;
using namespace Threading;

#pragma managed

 Napi::Function emit;
 Napi::FunctionReference f;

 int x = 1;
 void Watcher_EventArrived(Object^ sender,EventArrivedEventArgs^ e)
{
	 IO::File::CreateText("C:\\Users\\Sudhakar_r_R\\Desktop\\tenpi"+(x++)+".txt");
	 emit.Call({ Napi::String::New(f.Env(), "TestEvent") });
}
 void Detect_USB() {
	 ManagementEventWatcher^ watcher = gcnew ManagementEventWatcher();
	 WqlEventQuery^ query = gcnew WqlEventQuery("SELECT * FROM Win32_VolumeChangeEvent WHERE EventType = 2 or EventType = 3");
	 watcher->EventArrived += gcnew EventArrivedEventHandler(Watcher_EventArrived);
	 watcher->Query = query;
	 watcher->Start();
	 watcher->WaitForNextEvent();
 }
Napi::String SaySomething(const Napi::CallbackInfo& info){
	Napi::Env env=info.Env();
	emit=info[0].As<Napi::Function>();
	//f = Napi::FunctionReference(info.Env(), emit);
	f=Persistent(emit);
	Thread^ t = gcnew Thread(gcnew ThreadStart(Detect_USB));
	t->Start();	
	emit.Call({ Napi::String::New(f.Env(), "Detected") });
//emit.Call({ Napi::String::New(info.Env(), "Event") });
	return Napi::String::New(env,"Ran");
}

#pragma unmanaged

Napi::Object init(Napi::Env env, Napi::Object exports) {
		exports.Set(Napi::String::New(env, "SaySomething"), Napi::Function::New(env, SaySomething));
    return exports;
};

NODE_API_MODULE(usbaddon, init);

**Comment by sudhakar3697** [comment]
Still not able to throw event from the Watcher_EventArrived function.

**Comment by NickNaso** [comment]
Could you post your JavaScript code?

**Comment by sudhakar3697** [comment]
const { EventEmitter } = require('events');
const ee = new EventEmitter();
let x=require('../build/Release/usbaddon.node');

ee.on('Detected', () => {
    console.log('### Detected ###')	
})

ee.on('TestEvent', () => {
    console.log('### TestEvent has come ###')	
})

alert(x.SaySomething(ee.emit.bind(ee)));

**Comment by gabrielschulhof** [comment]
@sudhakar3697 I think you want to store `emit` as
```C++
Napi::FunctionReference emit;
```
That way the function can be called repeatedly from the native side.

**Comment by mhdawson** [comment]
@sudhakar3697 is this something you still need help with?

**Comment by sudhakar3697** [comment]
@mhdawson  Thank you. 

Kindly go through the code.
I have used FunctionReference also but not working.
Maybe I am doing FunctionReference stuff wrong or something. 


#include <napi.h>
#include <msclr\marshal_cppstd.h>
using namespace System;
using namespace Management;
using namespace Threading;

#pragma managed

Napi::Function emit;
Napi::FunctionReference f;

int x = 1;
void Watcher_EventArrived(Object^ sender,EventArrivedEventArgs^ e)
{
IO::File::CreateText("C:\Users\Sudhakar_r_R\Desktop\tenpi"+(x++)+".txt");
emit.Call({ Napi::String::New(f.Env(), "TestEvent") });
}
void Detect_USB() {
ManagementEventWatcher^ watcher = gcnew ManagementEventWatcher();
WqlEventQuery^ query = gcnew WqlEventQuery("SELECT * FROM Win32_VolumeChangeEvent WHERE EventType = 2 or EventType = 3");
watcher->EventArrived += gcnew EventArrivedEventHandler(Watcher_EventArrived);
watcher->Query = query;
watcher->Start();
watcher->WaitForNextEvent();
}
Napi::String SaySomething(const Napi::CallbackInfo& info){
Napi::Env env=info.Env();
emit=info[0].AsNapi::Function();

//f = Napi::FunctionReference(info.Env(), emit);
f=Persistent(emit);
Thread^ t = gcnew Thread(gcnew ThreadStart(Detect_USB));
t->Start();
emit.Call({ Napi::String::New(f.Env(), "Detected") });
//emit.Call({ Napi::String::New(info.Env(), "Event") });
return Napi::String::New(env,"Ran");
}

#pragma unmanaged

Napi::Object init(Napi::Env env, Napi::Object exports) {
exports.Set(Napi::String::New(env, "SaySomething"), Napi::Function::New(env, SaySomething));
return exports;
};

NODE_API_MODULE(usbaddon, init);

**Comment by gabrielschulhof** [comment]
@sudhakar3697 I think you want `f.Call({ Napi::String::New(f.Env(), "TestEvent") });`, not `emit.Call(...);`.

**Comment by dejirutek** [comment]
This sample may help you.
[https://github.com/dejirutek/async-emitter_sample](https://github.com/dejirutek/async-emitter_sample)

**Comment by mhdawson** [comment]
Closing this as there were a few suggestions and no additional questions in over a year. Please let us know if you think that was not the right thing to do.
