### ISSUE TITLE
How to unwrap a ArrayBufferView  using addon-api

### ISSUE THREAD

**Issue by GhostFlying** [nodejs/node-addon-api#408]
As the docs said, I can unwrap typedarray or dataview individually.

But if the param type of one function  is ArrayBufferView  in javascript, how should I do to unwrap it?

As

`info[0].As<Napi::ArrayBuffer>().Data()`

Or

`info[0].As<Napi::TypedArray>().ArrayBuffer().Data()`

or and any other method?

**Comment by GhostFlying** [comment]
I found another way like this:

`input.IsDataView() ? input.As<Napi::DataView>().Data() : input.As<Napi::TypedArray>().ArrayBuffer().Data();`

It seems correct but not so stright forward. In v8, there's a class called DomArrayBufferView as the super class of DataView and any TypedArray but no such one in napi.

**Comment by DaAitch** [comment]
@GhostFlying did you test it?
From JS you always have a Napi::Value at first and then discover the type with `.Is***` then cast and use it.
You should try and ask again if sth. unexpected happening.

**Comment by mhdawson** [comment]
@GhostFlying is this something you still need help with?

**Comment by GhostFlying** [comment]
sorry to miss this, I've no problems. Thx.
