### ISSUE TITLE
.defines instead of isNodeApiBuiltin

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/node-addon-api#41]
Would it make more sense to have a `require( "node-addon-api" ).defines` instead of `.isNodeApiBuiltin`? Conditionally adding the `EXTERNAL_NAPI` preprocessor directive is my only use case for examining the value of `.isNodeApiBuiltin`, and on Windows the define is required, otherwise there will be unresolved symbols.

**Comment by gabrielschulhof** [comment]
Also, all the other `node-addon-api` exports can be added unconditionally to either the `"include_dirs"` or `"dependencies"` of a dependent target, because the conditionality is encapsulated in `index.js`.

**Comment by gabrielschulhof** [comment]
I guess it doesn't really cost that much to keep `.isNodeApiBuiltin` so we export something that can be used as a condition statement for unforeseen use cases, but we should definitely have the `.defines` in addition.

**Comment by jasongin** [comment]
The `.isNodeApiBuiltin` export was meant to be exposed as a runtime flag in case anybody wanted to write code to check that. But it's not used anywhere today, and there should be no need to use it at build time.

Did you follow the instructions in the README? You shouldn't need to define `EXTERNAL_NAPI` anywhere in _your_ module's `node.gyp`. That is taken care of by these two lines to be added to your `node.gyp`:

```
  'include_dirs': ["<!(node -p \"require('node-addon-api').include\")"],
  'dependencies': ["<!(node -p \"require('node-addon-api').gyp\")"],
```

Then when you `#include "napi.lh"` that should get `src/napi.h` that has `#define EXTERNAL_NAPI` at the top.

**Comment by gabrielschulhof** [comment]
I don't use the C++ API.

**Comment by gabrielschulhof** [comment]
https://github.com/gabrielschulhof/iotivity-node/blob/node-addon-api/binding.gyp#L221-L232

**Comment by gabrielschulhof** [comment]
OK, I guess I can include `napi.h` directly, because I'm doing C++ anyway.

**Comment by gabrielschulhof** [comment]
I can't use napi.h because that requires exception handling to be enabled, which, for the plain C API I don't need.

**Comment by jasongin** [comment]
Hmm... using only the C APIs via this package wasn't a scenario I considered.

**Comment by gabrielschulhof** [comment]
Well, adding `.defines` and a mention in the `README.md` should cover plain C.

**Comment by jasongin** [comment]
Yes that will work. I had wanted to minimize the amount of stuff you have to add to your `.gyp` file. But one more line won't hurt.

**Comment by gabrielschulhof** [comment]
Although perhaps you could do the path juggling as you do now, but instead of including `napi.h` after defining EXTERNAL_NAPI, you include `node_api.h`.

**Comment by gabrielschulhof** [comment]
... and then, when napi.h includes node_api.h, it will receive it from the appropriate directory.
