### ISSUE TITLE
ObjectWrap and JSON.stringify

### ISSUE THREAD

**Issue by atoy40** [nodejs/node-addon-api#410]
Hello,

I' like to know if it is possible to get something from a JSON.stringify() call on an "ObjectWraped" instance ?
Do I have to implement specific methods into my object code (i"ve try to implement getOwnPropertyNames and set property enumerable) ?

Anthony.

**Comment by NickNaso** [comment]
Hi @atoy40 ,
you coluld retrieve `JSON.stringify` from the global object like reported below:

```cpp
// In your native function
Napi::Object json = env.Global().Get("JSON").As<Object>();
Napi::Function stringify = json.Get("stringify").As<Function>();

// Use stringify function
stringify.Call(json, { /*your json object*/ }).As<String>();
``` 
Hope to be helpful.

**Comment by atoy40** [comment]
@NickNaso thanks, but that's not what i'm searching for :)
My problem is this : I've a c++ object wrapped into a node object through ObjectWrap<MyObject>. this object expose some acccessors. Then, in my javascript code, if I try ```JSON.stringify(an_instance_of_myobject);```, i only get ```MyObject {}```

The question, is it possible to get properties of my object into the json return value ?.

**Comment by NickNaso** [comment]
@atoy40  Sorry I misunderstood your need. I try later to create an example for you. I will start from this example https://github.com/nodejs/node-addon-examples/blob/master/6_object_wrap/node-addon-api/myobject.cc 
is it good for you?

**Comment by atoy40** [comment]
@NickNaso yes, I started from this kind of example to define my object, so it is looking like this one ... but with accessors instead of methods.

**Comment by atoy40** [comment]
@NickNaso I've found some results. By implementiing to function : toJSON for the json stringify, and a function set to the symbol "nodejs.util.inspect.custom" for console.log display.

**Comment by DaAitch** [comment]
@atoy40 You need to go through [the rules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description) what `JSON.stringify(...)` is doing with the `value` parameter.
`toJSON` seems to be the first check so simply [implement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior) that function.

**Comment by sziraqui** [comment]
@atoy40 can you share your implementation of those two methods?

**Comment by vpaladino778** [comment]
> Hi @atoy40 ,
> you coluld retrieve `JSON.stringify` from the global object like reported below:
> 
> ```c++
> // In your native function
> Napi::Object json = env.Global().Get("JSON").As<Object>();
> Napi::Function stringify = json.Get("stringify").As<Function>();
> 
> // Use stringify function
> stringify.Call(json, { /*your json object*/ }).As<String>();
> ```
> 
> Hope to be helpful.

Unrelated to this issue, but I had a question for @NickNaso 

I'm trying to utilize your method here to converting a Napi::Object into a string containing json

```c++
void my JSFunc(const Napi::CallbackInfo& info) {
  Napi::Object myObject = info[0].As<Napi::Object>();

  Napi::Object json = env.Global().Get("JSON").As<Napi::Object>();
  Napi::Function jsonStringify = json.Get("parse").As<Napi::Function>();

  Napi::String stringValue = jsonStringify.Call(json, {myObject }).As<Napi::String>();

  cout << stringValue.Utf8Value();;
}
```
For some reason i'm receiving "FATAL ERROR: Error::New napi_get_last_error_info" as an error

**Comment by vpaladino778** [comment]
I was able to figure out my issue. For anyone else that comes across this, I realized this line:
```javascript
Napi::Function jsonStringify = json.Get("parse").As<Napi::Function>();
```

Should have been:
```javascript
Napi::Function jsonStringify = json.Get("stringify").As<Napi::Function>();
```

Silly mistake on my part, but just wanted to share.

**Comment by NickNaso** [comment]
Hi @vpaladino778,
I'm happy to see that you solved the problem. i prepare an example on which I illustrate the use of `JSON.parse` and `JSON.stringify`

```cpp
#include <napi.h>

Napi::String JSONStringify(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  Napi::Object json_object = info[0].As<Napi::Object>();
  Napi::Object json = env.Global().Get("JSON").As<Napi::Object>();
  Napi::Function stringify = json.Get("stringify").As<Napi::Function>();
  return stringify.Call(json, { json_object }).As<Napi::String>();
}

Napi::Object JSONParse(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  Napi::String json_string = info[0].As<Napi::String>();
  Napi::Object json = env.Global().Get("JSON").As<Napi::Object>();
  Napi::Function parse = json.Get("parse").As<Napi::Function>();
  return parse.Call(json, { json_string }).As<Napi::Object>();
}

Napi::Object Init(Napi::Env env, Napi::Object exports) {
  exports["jsonStringify"] =  Napi::Function::New(env, JSONStringify);
  exports["jsonParse"] = Napi::Function::New(env, JSONParse);          
  return exports;
}

NODE_API_MODULE(json, Init)
```

```js
'use strict'

const assert = require('assert')
const addon = require('bindings')('json');

const jsonObj = { a: 1 }
const jsonString = JSON.stringify(jsonObj)

assert.strictEqual(addon.jsonStringify(jsonObj), jsonString)
assert.deepStrictEqual(addon.jsonParse(jsonString), jsonObj)
```
I provide to attach the code complete code example. 
[json.zip](https://github.com/nodejs/node-addon-api/files/4067711/json.zip)

**Comment by vpaladino778** [comment]
@NickNaso 

Hi Nick,

Thanks so much for this, it was helpful to me. It was very kind of you to take the time to put together this example.
