### ISSUE TITLE
Wonderful docs

### ISSUE THREAD

**Issue by bmacnaughton** [nodejs/node-addon-api#418]
I know you don't need random issues clogging up your workflow. You can just close this without comment. But the improvement this has undergone since I first used Nan about 15 months ago is monumental. Documents like [object-lifetime-management](https://github.com/nodejs/node-addon-api/blob/master/doc/object_lifetime_management.md) provide the concepts that really put the pieces together.

Please thank everyone for their work. Oh yeah, and the c++ node-addon-api rocks too.

**Comment by NickNaso** [comment]
Hi @bmacnaughton,
thank you for this wonderful feedback. I'm really happy that you appreciated the documentation. All the N-API team worked hard trying to write something that is more than just a reference and your feedback confirm me that we are in the right direction. 
Furthermore we want improve our documentation like reported in the following issue:
**[https://github.com/nodejs/node-addon-api/issues/368](https://github.com/nodejs/node-addon-api/issues/368)**.  Please if you have some ideas or feedback about that feel free to propose them and if you want contribute in any way you are welcome.

**Comment by NickNaso** [comment]
I'm closing the issue. @bmacnaughton Thanks again for your appreciation.
