### ISSUE TITLE
Returning arrays from the add-on

### ISSUE THREAD

**Issue by alandefreitas** [nodejs/node-addon-api#423]
How do I return an array of strings from my addon? I tried to follow the examples and the tests but the elements in my array are still undefined. Is there anything wrong with the code below?

```cpp
Napi::Array Companies(const Napi::CallbackInfo &info) {
    Napi::Env env = info.Env();
    Napi::Array companies = Napi::Array::New(env, pm.number_of_companies());
    int i = 0;
    for (std::map<portfolio_manager::stock_code,portfolio_manager::stock_name>::iterator it = pm.companies_begin();
    it != pm.companies_end(); ++it) {
        Napi::String company_name = Napi::String::New(env,it->second);
        companies[i++] = company_name;
    }
    return companies;
}
```

Thanks,

**Comment by DaAitch** [comment]
LGTM, maybe you're just missing an `i++`

**Comment by alandefreitas** [comment]
Thanks for noting the `i++`. That's how I had it in a previous version. I put the `i++` back but it still doesn't work. I registered the function like all other functions (all other functions work) and when I call it from javascript:
```javascript
    var companies = addon.companies()
    for (let i = 0; i < companies.length; i++) {
        console.log('Company ' + i + ': ' + companies[i])
    }
```
I get:
```
Company 0: undefined
Company 1: undefined
Company 2: undefined
Company 3: undefined
Company 4: undefined
Company 5: undefined
Company 6: undefined
Company 7: undefined
Company 8: undefined
...
Company 63: undefined
Company 64: undefined
Company 65: undefined
```
(I fixed the `i++` in the original question in order to avoid confusing other people)

**Comment by alandefreitas** [comment]
@DaAitch Thank you so much. I'll check some of these possibilities.

**Comment by ShaniWaterS** [comment]
to avoid memory leak, Is there a need to delete Napi::Array company_array? or the JS GC handle it?

**Comment by DaAitch** [comment]
@ShaniWaterS no memory leaks possible

- either you return an object with a handle inside which is unwrapped and passed to the node runtime, or
- you throw an exception and the handle is destroyed
