### ISSUE TITLE
Reference Persistent and Weak shortcuts incorrect in documentation

### ISSUE THREAD

**Issue by DuBistKomisch** [nodejs/node-addon-api#427]
Hi, just trying converting some code from nan to n-api using this library and the docs have been pretty good except for this.

`Napi::FunctionReference::Persistent` is listed here: https://github.com/nodejs/node-addon-api/blob/44f0695533327a12548a5015c444a3a5d731bb5c/doc/function_reference.md#persistent

However the actual method is `Napi::Persistent` overloaded to take a `Napi::Function` as seen in the source code here: https://github.com/nodejs/node-addon-api/blob/44f0695533327a12548a5015c444a3a5d731bb5c/napi.h#L1130

The mistake seems to have been introduced a few months ago in a docs tidy up: https://github.com/nodejs/node-addon-api/commit/fc11c944b2e1e828a9baadfc3807a6d9c52535ba#diff-9562158c05ed3ee744cdc12bad121e87L39

The same mistake seems to exist for all Persistent and Weak across Reference and its subclasses.

This could be part of the confusion in https://github.com/nodejs/node-addon-api/issues/392.

**Comment by mhdawson** [comment]
@DuBistKomisch thanks for the report.  Do you want to submit a PR to fix this up?

**Comment by DuBistKomisch** [comment]
@mhdawson sure

**Comment by mhdawson** [comment]
Closing this issue as a PR to fix has landed (Thanks @DuBistKomisch).
