### ISSUE TITLE
error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found

### ISSUE THREAD

**Issue by iffy** [nodejs/node-addon-api#440]
I'm getting the following error when trying to build on a Windows VM with `yarn`:

```
C:\proj\myproject\node_modules\node-addon-api\src\nothing.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

I don't see `nothing.vcxproj` anywhere in this repo, so I'm not sure how it's made or why it's made incorrectly.  Line 20 of the file is this:

```
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props"/>
```

- Assuming I need to, how do I set VCTargetsPath to something?
- And what is `nothing.{c,vcxproj}` even for?

```
> yarn --version
0.27.5
> npm --version
6.4.1
> node --version
v8.14.0
```

- `msvs_version` is `2015`
- Windows 10

**Comment by mhdawson** [comment]
@digitalinfinity could ou help since this is windows?

**Comment by iffy** [comment]
Looks like setting `VCTargetsPath` environment variable to `C:\Program Files (x86)\MSBuild\Microsoft.cpp\v4.0\v140` *and* installing `windows-build-tools` with the `--vs2015` flag made that part work (e.g. `npm install --global --production windows-build-tools --vs2015`)
