### ISSUE TITLE
Error is thrown as "Unknown failure"

### ISSUE THREAD

**Issue by maierfelix** [nodejs/node-addon-api#444]
I'm throwing an Error like this:
```cpp
Napi::Error::New(env, "Test").ThrowAsJavaScriptException();
```

where `env` is taken from an `ObjectReference` like this:
```cpp
Napi::Env env = this->property.Value().Env();
```

but instead of `Test`, the error shows `Unknown failure`.

**Comment by addaleax** [comment]
Do you think you could share a full reproduction, so that this is easier to debug?

**Comment by maierfelix** [comment]
I had a bug in my code, it's working now
