### ISSUE TITLE
Natvis file for debugger variable visualization

### ISSUE THREAD

**Issue by raffaeler** [nodejs/node-addon-api#451]
When working with Visual Studio it would be extremely useful to use a natvis file to visualize the internal nodejs structures (this can be used even if debugging on Linux).
The natvis specifications are here: https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2017

The natvis file is easy to create as long as you have the structures. Since the API use opaque pointers, it is not easy to know the memory shape for each structure.
For example `napi_value` is just a `void *`.

Since Microsoft worked in this area for Chakra, I guess they already created the natvis file to debug the internals.
Any chance to commit the nativis definition here?

**Comment by mhdawson** [comment]
@digitalinfinity, @aruneshchandra could either of you two comment?

**Comment by mhdawson** [comment]
Since we did not get answers from collaborators on the Windows side and Chakra is no longer supported, closing out. Please let us know if that is not the right thing to do.

**Comment by raffaeler** [comment]
@crowder-pw yes it is and this is why I posted this question, but I understand that IBM is not interested in that.
