### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#454]
It might be time for a new release. The last one was just over 3 months ago.

Some PRs/issues we might want to address first:
- [x] nodejs/node-addon-api#407
- [x] https://github.com/nodejs/node-addon-api/pull/458
- [x] https://github.com/nodejs/node-addon-api/pull/459
- [x] https://github.com/nodejs/node-addon-api/pull/460
@nodejs/n-api Please suggest others if you think we should address them before the next release.

**Comment by mhdawson** [comment]
Possibly https://github.com/nodejs/node-addon-api/pull/442 if it is ready.

**Comment by extmchristensen** [comment]
Would really be super nice with an update soon for #442 + update the bundled N-API headers for "C" (#463).

**Comment by NickNaso** [comment]
Hi everyone like discussed in the last meeting I will provide to make a new release (v1.6.3).

**Comment by NickNaso** [comment]
I'm closing the issue because the new version v1.6.3 has been released. 
@extmchristensen this is a minor release, but in the next we will add the implementation of thread safe function that is currently on progress.
