### ISSUE TITLE
Promise::Deferred in C callback function

### ISSUE THREAD

**Issue by k2la** [nodejs/node-addon-api#457]
I'm trouble about the following code:

```
void my_callback(result res, void *ctx) {
    Napi::Promise::Deferred *deferred = (Napi::Promise::Deferred *)ctx;
    Napi::Env env = deferred->Env(); // segmentation fault
    if (res == RESULT_OK) {
        deferred->Resolve(Napi::String::New(env, "Success"));
    } else {
        deferred->Reject(
          Napi::Error::New(env, std::string("Failed")).Value());
    }
}

Napi::Value MyClass::Do(const Napi::CallbackInfo &info) {
    Napi::Env env = info.Env();
    Napi::Promise::Deferred deferred = Napi::Promise::Deferred::New(env);

    do_async(my_callback, &deferred);
    return deferred.Promise();
}
```

This code:
1. `MyClass::Do` is called by Nodejs code directly.
2. After `do_async` ends in another thread,  `my_callback` begins.
3. `my_callback` sees `res` and executes `deferred->Resolve` or `deferred->Reject`.

I want to run this code as above but segmentation fault occurs in `my_callback`.

With the following restriction, How should I use `deferred` without errors in `my_callback`?
- Declaration about `my_callback` cannot be changed.

FYI: [That I tried in order to solve this problem](https://gist.github.com/k2la/c3492ffbdc9db8e46a937d0fe7b31a41).

**Comment by mhdawson** [comment]
I think we need to see the implementation of do_async. My first guess is that you might need to use https://github.com/nodejs/node-addon-api/blob/master/doc/async_worker.md

and ensure that  my_callback is invoked in the OnOK method to ensure it runs on the main thread.

**Comment by mhdawson** [comment]
The key point above is that node-addon-api code interacting with JavaScript must run on the main thread, not on any other thread.

**Comment by k2la** [comment]
Thank you for your reply.

> I think we need to see the implementation of do_async. 

I want to use the following `Producer::SendAsync` as `do_async`.

```c++
void pulsarProducerSendCallbackProxy(pulsar_result res, pulsar_message_t *message, void *ctx) {
    Napi::Promise::Deferred *deferred = (Napi::Promise::Deferred *)ctx;
    Napi::Env env = deferred->Env(); // segmentation fault
    if (res == RESULT_OK) {
        deferred->Resolve(Napi::String::New(env, "Success"));
    } else {
        deferred->Reject(Napi::Error::New(env, std::string("Failed")).Value());
    }
}

Napi::Value Producer::SendAsync(const Napi::CallbackInfo &info) {
    Napi::Env env = info.Env();
    Napi::Promise::Deferred deferred = Napi::Promise::Deferred::New(env);

    pulsar_message_t *cMessage = Message::BuildMessage(info[0].As<Napi::Object>());
    pulsar_producer_send_async(this->cProducer, cMessage, pulsarProducerSendCallbackProxy, $deferred);
    return scope.Escape(deferred.Promise());
}
```

We register `pulsarProducerSendCallbackProxy` which operates `deferred` with [pulsar_producer_send_async](https://github.com/apache/pulsar/blob/dd5d05197a9352aba392ae30e7c60e05fc52be0b/pulsar-client-cpp/lib/c/c_Producer.cc#L44-L49) in [Pulsar C++ client library](https://github.com/apache/pulsar/tree/master/pulsar-client-cpp).

`pulsar_producer_send_async` sends messages asynchronously by using [boost::asio::async_write](https://www.boost.org/doc/libs/1_51_0/doc/html/boost_asio/reference/async_write/overload1.html).

Reigstered `pulsarProducerSendCallbackProxy` executes as a handler by `boost::asio::async_write`.

Can we operate `deferred`  by using a function registered with `boost::asio::async_write` ?

FYI: From `pulsar_producer_send_async` to `boost::asio::async_write`, following functions are called.

1. [pulsar_producer_send_async](https://github.com/apache/pulsar/blob/dd5d05197a9352aba392ae30e7c60e05fc52be0b/pulsar-client-cpp/lib/c/c_Producer.cc#L44-L49)
2. [ProducerImpl::sendAsync](https://github.com/apache/pulsar/blob/dd5d05197a9352aba392ae30e7c60e05fc52be0b/pulsar-client-cpp/lib/ProducerImpl.cc#L330-L417)
3. [ProducerImpl::sendMessage](https://github.com/apache/pulsar/blob/dd5d05197a9352aba392ae30e7c60e05fc52be0b/pulsar-client-cpp/lib/ProducerImpl.cc#L422-L442)
4. [ClientConnection::sendMessage](https://github.com/apache/pulsar/blob/285d16ebe00bfdb5d131b57134d76e5181849164/pulsar-client-cpp/lib/ClientConnection.cc#L1135-L1149)
5. [ClientConnectino::asyncWrite](https://github.com/apache/pulsar/blob/1d14680c8bcdae4159afc230b12c22545f855a58/pulsar-client-cpp/lib/ClientConnection.h#L218-L224)
6. [boost::asio::async_write](https://www.boost.org/doc/libs/1_51_0/doc/html/boost_asio/reference/async_write/overload1.html)

**Comment by mhdawson** [comment]
I think you'll need to use AsyncWorker or more likely https://nodejs.org/dist/latest-v11.x/docs/api/n-api.html#n_api_asynchronous_thread_safe_function_calls to ensure that you are only making the N-API calls on the main thread.   We don't have a wrapper in node-addon-api yet but you can mix node-addon-api and the native C calls to N-API

**Comment by k2la** [comment]
I understood that.
Thank you. I'll do some more research.

**Comment by mhdawson** [comment]
Closing this out as the question was answered. Please let us know if that was no the right thing to do.
