### ISSUE TITLE
Cannot get callbacks to trigger immediately in long running call

### ISSUE THREAD

**Issue by Aerrus** [nodejs/node-addon-api#461]
I have a button in Javascript that passes in a function that modifies the UI to my NAPI module, which will use it multiple times over a long running task.

Basic setup:

Javascript:
```
    let $ = require('jquery')
    var myModule = require('myModule') //defined in package.json
    function addToText(msg) {
        $('#outputTxt').prepend(msg + "<br/>") // h3
    }

    $('#myBtn').on('click', () => {
        myModule.napiTest(addToText);
    })
```
In my NAPI wrapper:

```
    void napiTextCallback(const char* charRet, napi_value cb, napi_env env, napi_value global) {
        napi_value args[1];
        NAPI_CALL_WITH_CHECK(napi_create_string_utf8, env, charRet, NAPI_AUTO_LENGTH, args);
        napi_value result;
        NAPI_CALL_WITH_CHECK(napi_call_function, env, global, cb, 1, args, &result);
    }

    napi_value napiTest(napi_env env, napi_callback_info cbinfo) {
        size_t argc = 1;
        napi_value argv[1];
        NAPI_CALL_WITH_CHECK(napi_get_cb_info, env, cbinfo, &argc, argv, nullptr, nullptr);
        napi_value cb = argv[0];
        napi_value global;
        NAPI_CALL_WITH_CHECK(napi_get_global, env, &global);

        string text = "Immediate";
        napiTextCallback(text.c_str(), cb, env, global);

        usleep(5000000);

        text = "Post delay";
        napiTextCallback(text.c_str(), cb, env, global);

        return nullptr;
    }
    //exporting and all that omitted
```
When I run the code, upon clicking the button, it simply freezes for the full 5 seconds, and then prints `Immediate` and `Post delay` together.

How do I make it print `Immediate` immediately, sleep/do a long running task (http request), and then print `Post delay` after?

**Comment by NickNaso** [comment]
I see the `jquery` code which is your execution runtime?

**Comment by Aerrus** [comment]
Electron app (Node.js)

**Comment by gabrielschulhof** [comment]
@Aerrus AFAICT you end up passing the string "Immediate" to jQuery so that it might append it to the DOM. The DOM may not be updating itself synchronously, meaning that `$('#outputTxt').prepend(msg + "<br/>") // h3` returns before the DOM actually reflects the change that was made to it. Since it returns early, it immediately goes to sleep, so that the change in the DOM is reflected only after it wakes up.

As a test, can you add `console.log('Appending ' + msg + ' to the DOM');` before the actual call that inserts into the DOM and check whether the delay works correctly between the `console.log()` and the final message?

**Comment by Aerrus** [comment]
@gabrielschulhof you're right, it's just sleeping before the change is reflected. The console updates before the sleep. Not sure how to avoid this though. Since my long running task has to be on the UI thread as well. I used usleep to simulate the UI thread being taken up by my long task.

This relates to another problem that I've been having actually, I have a C++ function in a library that pops up UI (and the library requires it to be run on the UI thread), and they take a lambda for what to do on-complete, where I would like for it to make a callback to JS. I realized soon that I couldn't just capture napi_env for reuse, and I couldn't use async_work since it launches it on a different (non-UI) thread.

**Comment by gabrielschulhof** [comment]
@Aerrus if you have control over the long-running task, you should re-factor it to run as an idle loop.

You should actually be OK to capture the `napi_env` if the call to the C++ function is synchronous, because synchronous execution should be like this:
```
From JS...
 |
 v
[ binding receives valid napi_env ]
  |
  | runCPlusPlusUI(void (*callback)(void *), { napi_env env, napi_value cb })
  |
  [ C++ UI ]
    |
    | callback({env, cb})
    |
    [ callback receives napi_env and napi_cb ]
      |
      | CallIntoJS(env, cb) <-- env here is still valid because the binding is
      |                         still running
    <return>
    |
  <return>
  |
<return> <-- env potentially becomes invalid after this, but that's OK, because
             the callback has already completed
```

**Comment by gabrielschulhof** [comment]
Of course, if the C++ UI takes over the event loop, the Node.js event loop will hang, so some things may be unresponsive.

**Comment by gabrielschulhof** [comment]
@Aerrus hopefully we have addressed your concerns. If the problem persists, please feel free to re-open this issue or open a new one.
