### ISSUE TITLE
node-addon-api Call js Object's method fail

### ISSUE THREAD

**Issue by mythicsr** [nodejs/node-addon-api#466]
I pass a javascript object to c++ code, c++ code call this object's method "readdata1", but the object's second method (readdata2) didnt called;

the console tell me that "readdata2" is undefined;

js code:

    const testfunc = require('./index').testfunc;

    class reader{
        constructor(){
            this.readdata2=function(){
                console.log('js:readdata2')
                return 222
            }
            this.readdata1=function (){
                console.log('js:readdata1')
                let ret = this.readdata2()
                return ret;
            }
        }
    }

    let n = testfunc(new reader());
    console.log('n=',n)
c++ code:

    Napi::Value testfunc(const Napi::CallbackInfo &info) {
    LOG("C++:testfunc()!!");
    Object r = info[0].As<Napi::Object>();
    return r.Get("readdata1").As<Function>().Call({});
    }
output:

C++:testfunc()!!
js:readdata1
/Users/chentingfeng/cpp_proj/decodeDLL/test.js:17
let n = testfunc(new reader());
        ^

TypeError: Cannot read property 'readdata2' of undefined
    at readdata1 (/Users/chentingfeng/cpp_proj/decodeDLL/test.js:11:28)
    at Object.<anonymous> (/Users/chentingfeng/cpp_proj/decodeDLL/test.js:17:9)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! Test failed.  See above for more details.

Process finished with exit code 1
javascript node.js node-addon-api

**Comment by NickNaso** [comment]
Hi @mythicsr,
the problem here is that you need to specify the `this` object so your code will became something like this:
```cpp
#include <napi.h>

Napi::Value Execute(const Napi::CallbackInfo& info) {
    Napi::Object obj = info[0].As<Napi::Object>();
    Napi::Function fn = obj.Get("readdata1").As<Napi::Function>();
    // obj is your this object
    return fn.Call(obj, {});
}

Napi::Object Init(Napi::Env env, Napi::Object exports) {
    exports["execute"] = Napi::Function::New(env, Execute);
    return exports;
}

NODE_API_MODULE(NODE_GYP_MODULE_NAME, Init)
```
See at `Napi::Function` documentation`  [here](https://github.com/nodejs/node-addon-api/blob/master/doc/function.md#call-3)

Furthermore I post here a full example that I created based on your reported problem.
[issue466.zip](https://github.com/nodejs/node-addon-api/files/3050962/issue466.zip)
Hope that this will work for you. Keep me updated.

**Comment by NickNaso** [comment]
@mythicsr any  news?

**Comment by NickNaso** [comment]
Hi everyone,
is it possible close this issue or there is something that I can do to help?

**Comment by gengjiawen** [comment]
> Hi everyone,
> is it possible close this issue or there is something that I can do to help?

I think you can close this. 
@mythicsr If you have further questions, feel free to reopen this.
