### ISSUE TITLE
Array subscript operator question

### ISSUE THREAD

**Issue by mathiask88** [nodejs/node-addon-api#467]
Hey, I do programming for fun, and while I wrote something like this
```c++
Napi::Array data_arr = info[0].As<Napi::Array>();
int len = data_arr.Length();
for (int i = 0; i < len; i++) {
  if (!data_arr[i].IsObject()) {
    ...
  }
}
```
MSVS complains about `class "Napi::Object::PropertyLValue<uint32_t>" has no member "IsObject"` 
The compiler uses the non-const lvalue overload which is correct I think?!
And I was wondering what is the intended solution for this case?
```c++
Napi::Array data_arr = info[0].As<Napi::Array>();
int len = data_arr.Length();
for (int i = 0; i < len; i++) {
  if (!static_cast<Napi::Value>(data_arr[i]).IsObject()) {
    ...
  }
}
```

```c++
const Napi::Array data_arr = info[0].As<Napi::Array>();
int len = data_arr.Length();
for (int i = 0; i < len; i++) {
  if (!data_arr[i].IsObject()) {
    ...
  }
}
```

```c++
Napi::Array data_arr = info[0].As<Napi::Array>();
int len = data_arr.Length();
for (int i = 0; i < len; i++) {
  if (!data_arr.Get(i).IsObject()) {
    ...
  }
}
```

**Comment by gabrielschulhof** [comment]
@mathiask88 I believe the simplest way around this error is to do
```C++
Napi::Value val = data_arr[i];
if (val.IsObject()) {
  ...
}
```

**Comment by gabrielschulhof** [comment]
@mathiask88 AFAICT the `static_cast<Value>(data_arr[i])` also works.

**Comment by sziraqui** [comment]
@mathiask88 Look at all overloads of Array. The operator [] returns Napi::Value when the Array is const and index is unsigned int. So use this to get your desired result:
```
const Napi::Array arr = info[0].As<Napi::Array>();
Napi::Value val = arr[(uint)0];
```
Check [this](https://github.com/sziraqui/napi_samples/blob/master/handle_vectors/src/funcs.cpp) for more ways of handling arrays.
