### ISSUE TITLE
.travis.yml: The 'sudo' tag is now deprecated in Travis CI

### ISSUE THREAD

**Issue by cclauss** [nodejs/node-addon-api#469]
[Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).

"_If you currently specify __sudo: false__ in your __.travis.yml__, we recommend removing that configuration_"

**Comment by gabrielschulhof** [comment]
@mhdawson AFAIK we're not actually using Travis, so we should probably remove the `.travis.yml` file entirely.

**Comment by mhdawson** [comment]
PR to remove: https://github.com/nodejs/node-addon-api/pull/850

**Comment by mhdawson** [comment]
Removed, closing
