### ISSUE TITLE
How to use Proxy to allow overriding arbitrary properties

### ISSUE THREAD

**Issue by darknoon** [nodejs/node-addon-api#476]
I am trying to create a Python binding in the new Node N-API, akin to node-python / [python.js](https://github.com/monkeycz/python.js) / [python3.js](https://github.com/shiningnight/python3.js), which use V8 directly.

Since `node-addon-api` doesn't let you make an "arbitrary" property handler like V8 does, I'm trying to follow the advice here https://github.com/nodejs/node/issues/17367 to use `Proxy` to overcome that limitation.

I tried creating an `External<PyObject>` to hold onto the python object and then pass that as the `target` of the `Proxy`. However, I can't then figure out how to grab the original `External` when I get passed one of the JS `Proxy` objects.

I had an idea to make a secret `Symbol` that could be indexed by and check for it in my `get(…)`, returning the `Object` that corresponds to the C++ `External` so I can ask `node-addon-api` to convert it over for me.

Does anyone have experience with this issue or another idea?

**Comment by devsnek** [comment]
i'd do something like this:

```js
const myExternal = native.get_external_somehow();
new Proxy(myExternal, {
  get(t, p, r) {
    return native.get_property(t, p);
  },
});
```
