### ISSUE TITLE
Is there a way to pass null in JS to have object freed?

### ISSUE THREAD

**Issue by oz-** [nodejs/node-addon-api#479]
I'm fairly new to N-API, sorry if this question is inappropriate.

What I want to do is to pass null in Javascript to call the destructor on an object (or make it available to garbage collection?).

I'm not really sure about the way the destructor of my internal class would/should be called. The thing is that my C++ class wraps a C object that I have to 'unref' (GLib). For the time being I'm calling the unref function on the C object in the C++ destructor, but it's never called. 

Is there a way to call it manually by passing null to its JS variable?

My code would be something like this
```
var obj = new myAddon.MyObject();

// Do stuff with obj

obj = null; // Free the resources: calls destructor on Napi::ObjectWrap that calls destructor on MyObject
```

(Sorry for the bad English...)

**Comment by legendecas** [comment]
GC on objects are depends on VM's GC strategy. If there is any intentional explicit destruction operation it could be achieved with an explicit method to do so.

```js
var obj = new myAddon.MyObject();

// Do stuff with obj

obj.close() // do as same as what was expected to be done on destructor
```

**Comment by oz-** [comment]
Thank you !
Does that mean that there’s no way to “catch” null, either to send the object to garbage collection or to call the destructor on the C++ side?

**Comment by devsnek** [comment]
there's no way to tell js to explicitly drop an object. what people generally do is call `v8::AdjustAmountOfExternalAllocatedMemory` to increase the memory pressure which will cause v8 to gc your object faster, and when v8 gc's it napi will call the destructor. that being said, i don't think we have a way of doing `v8::AdjustAmountOfExternalAllocatedMemory` in napi.

**Comment by gabrielschulhof** [comment]
This N-API is available:

```C
// Memory management
NAPI_EXTERN napi_status napi_adjust_external_memory(napi_env env,
                                                    int64_t change_in_bytes,
                                                    int64_t* adjusted_value);

```

**Comment by NickNaso** [comment]
Hi everyone this feature is also available in `node-addon-api`:
```cpp
static int64_t Napi::MemoryManagement::AdjustExternalMemory(Napi::Env env, int64_t change_in_bytes);
``` 
Here the reference to the documentation:
https://github.com/nodejs/node-addon-api/blob/master/doc/memory_management.md

**Comment by oz-** [comment]
Thanks all.
So, what I understand is that I have to explicitely call a method on the JS side (eg. `myObject.myMethodToCallThe MemoryAdjustment()` or `myObject.close()`), am I right?
I'll try both to understand better...
A side question would be: what is the effect on internal memory management of passing `null` in a pure JS framework?

**Comment by mhdawson** [comment]
Going to close this out since the original question was answered. Please let us know if that is not the right thing to do.
