### ISSUE TITLE
Ugly hack for error codes in class JAsyncWorker errors - alternative ?

### ISSUE THREAD

**Issue by extmchristensen** [nodejs/node-addon-api#480]
I need to return both a string and an error code in the javascript exception thrown by JAsyncWorker in case of failures. I got it to work using this hack by extending and at a point also breaking the JAsyncWorker contract. I would like a better way to do it. Any suggestions?

My current approach:
1) Add errorCode member my JAsyncWorker subclass:
```  int errorCode; ```

2) Inside Execute(), each time there is an error, catch it and call "SetError(errorMsg)" followed by manual code assignment 

```
  SetError(errorMsg);
  errorCode =  42; // example.
```
3) Override "void OnError(const Napi::Error& e)" like this:
```
 void OnError(const Napi::Error& e) 
    {
       Napi::Env env = e.Env();
       // Ugly code here: Unfortunately "e" is const, so we need to cast it away to modify the error:
       Napi::Error& mutableError = const_cast<Napi::Error&>(e);
       mutableError.Set(Napi::String::New(env, "code"), (Napi::Number::New(env, errorCode)));
       Callback().Call(Receiver().Value(), std::initializer_list<napi_value>{ mutableError.Value() });
   }
```

**Comment by addaleax** [comment]
I think there’s no technical reason for `e` to be a const reference – Do you maybe just want to open a PR that changes it to a regular one?

**Comment by mhdawson** [comment]
Going to close this out as there was no follow on question after Anna's question. Please let us know if that is not the right thing to do.
