### ISSUE TITLE
Calling require from inside a node addon

### ISSUE THREAD

**Issue by elwyos** [nodejs/node-addon-api#482]
Is this possible? I've tried using eval but it says that "require is not defined"

**Comment by gabrielschulhof** [comment]
You can do this:
```JS
const native = require('./build/Release/native_addon.node');
native.receiveRequire(require);
```
IOW you write a native function that receives `require()` as a parameter. You can store a persistent reference to this function in your native addon and use it afterwards.

**Comment by gabrielschulhof** [comment]
@elwyos does this answer your question?

**Comment by elwyos** [comment]
Sorry for the late reply - only checked this now. I've actually done something different instead : 

`blah = require; const addon = require('./build/Release/some_addon')`

and then accessing the variable `blah`. That seems to work on the Init function. Is there anything special with receiveRequire?

**Comment by gabrielschulhof** [comment]
@elwyos how do you mean "and then accessing the variable `blah`"? There is nothing special about `receiveRequire()`. As long as you can get a reference to `require()` into your native addon, you're all set.

**Comment by mhdawson** [comment]
Closing this out as looks like the original question was answered and there has not been a response to Gabriel's last comment for a long time. Please let us know if that is not the right thing to do.
