### ISSUE TITLE
Make error message for linked libraries not present more helpful

### ISSUE THREAD

**Issue by Suhail** [nodejs/node-addon-api#483]
## Problem

This error is not as helpful as it could be:
```
$ node index.js --client 
internal/modules/cjs/loader.js:840 
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified procedure could not be found.
```

It generally means that some function was not actually able to be found on runtime.

The reason it's not helpful is because your application will compile but you won't know until you run it that you're missing some sort of .dll necessary.

It would be nice to be able to make this better since it leads to a lot of trial & error to figure out what you're missing.

If there's an easy way to debug it, I've not been able to find a way googling around or via stackoverflow.

## Specific use-case

I am making a native C++ node module and using ffmpeg. Since there are many .dlls possibly required to run the application, it's difficult to know which one I am missing.

Another example is that I am attempting to compile my application using static libraries but for some reason I don't know why it's not working and what specifically the node module, while run, is missing. Is it just one library or many?

## What I am expecting

Ideally, it tells me the function, dll, etc. that's missing so I can go hunt it down.

If it is possible to do this already maybe there's a way to improve finding it.

## Other info

I am compiling code on Windows 10 and using the node module in an electron app.

**Comment by gabrielschulhof** [comment]
@Suhail when we build a native addon, we intentionally build it such that some symbols are undefined, because the library needs to link to Node.js, but only at runtime. So, if other symbols are also missing, then we can only find out at runtime that they are missing.

We also cannot identify the library that is missing because it may be a transitive dependency of the addon. On Linux and OSX at least it tells you the name of the symbol that is missing.

Unfortunately, I don't believe there is a better answer than this.

**Comment by burakkp** [comment]
Hi,

I faced same kind of error. How can i fix this?

**Comment by gabrielschulhof** [comment]
If you're on Windows, you can try
```
dumpbin /dependents filename.dll
```

in a "x64 Native Tools Command Prompt".

https://stackoverflow.com/questions/1993673/what-is-the-equivalent-of-linuxs-ldd-on-windows

On Linux you can do
```
ldd filename.so
```

**Comment by mhdawson** [comment]
I'm going to close this as it looks the the discussion has run its course.  Please let us know if you think closing this was not the right thing to do.
