### ISSUE TITLE
Convert multi-dimensional array of known type to primitive array?

### ISSUE THREAD

**Issue by sziraqui** [nodejs/node-addon-api#491]
I am passing image pixels as Uint8Arrays from node to C++. The C++ side needs the pixel data as cv::Mat object. To convert to cv::Mat I need to convert Napi::Array or Uint8Array to a primitive int array of 3 dimensions. Is there an efficient way to do this without looping through every value? Reading through the C api, I can see a way to access underlying array buffer. Can I use that to convert to int array?

**Comment by NickNaso** [comment]
Hi @sziraqui,
to avoid the conversion you have to use [Napi::TypedArray](https://github.com/nodejs/node-addon-api/blob/master/doc/typed_array.md) or [Napi::ArrayBuffer](https://github.com/nodejs/node-addon-api/blob/master/doc/array_buffer.md) API.

Here you can find a simple example:
https://github.com/nodejs/node-addon-examples/tree/master/array_buffer_to_native/node-addon-api

Hope that this help you.

**Comment by sziraqui** [comment]
Closing it since NickNaso's link solved my problem.
