### ISSUE TITLE
Memory leaks on Windows

### ISSUE THREAD

**Issue by Suhail** [nodejs/node-addon-api#496]
Is there a good way to find memory leaks in a C++ N-API addon if you're building on Windows?

I tried following these directions but `_CrtDumpMemoryLeaks()` never outputted anything to my output window:

https://docs.microsoft.com/en-us/visualstudio/debugger/finding-memory-leaks-using-the-crt-library?view=vs-2017

**Comment by mhdawson** [comment]
@digitalinfinity, @aruneshchandra do you have any good suggestions for memory investigation on Windows?

**Comment by Suhail** [comment]
I managed to get _CrtDumpMemoryLeaks but its output format was fairly unreadable so I gave up. It didn't seem to help better than manual inspection.

**Comment by mhdawson** [comment]
@digitalinfinity any suggestions?

**Comment by mhdawson** [comment]
Going to close this out as it is not node-addon-api specific and we did not get any suggestions for the collaborators who know Windows.  Please let us know if this is not the right thing to do.
