### ISSUE TITLE
Property assignment that looks like method call?

### ISSUE THREAD

**Issue by mcow** [nodejs/node-addon-api#499]
I'm working on a Node add-on with node-addon-api that connects to a Windows OLE (COM) library. One of the properties in this library takes advantage of an OLE capability to expose a property thru a method-like interface. That is, the library's internals use GET and PUT actions, but the caller writes something like:
```
item = Container.Item(5)   // GET
Container.Item(6) = otheritem   // PUT
```
I've implemented the getter as a method call, and that works fine. It's not clear to me how I can implement the setter: I need both the index value and the new value to be passed to me via the `NapiCallbackInfo` structure. I could create a two-argument method; but is there a way to make the syntax as shown work?

**Comment by mhdawson** [comment]
You might be able to put something together with arrays, with an object in the array representing each element along with an accessor set through property descriptors, but I think it would add a lot of complexity versus just have 2 arguments.

**Comment by devsnek** [comment]
a call expression cannot be on the left hand side of an assignment expression. i'd suggest using two arguments.

**Comment by mcow** [comment]
@devsnek @mhdawson thank you, this confirms my suspicions. One followup: what about if I used bracket syntax, such as `Container[6] = otheritem`. Is that something node-addon-api can (or could) package up into the info structure?

**Comment by mhdawson** [comment]
@mcow that is what I was referring to in "You might be able to put something together with arrays, with an object in the array representing each element along with an accessor set through property descriptors".  I  think you'd have to pre-populate the array and overall I don't think it would be worth it.

**Comment by mhdawson** [comment]
Since there has not been any follow on for quite some time since the last response I'm going to close this one. Please let us know if that was not the right thing to do.
