### ISSUE TITLE
How to convert Napi::Number to unsigned char?

### ISSUE THREAD

**Issue by Arcticon** [nodejs/node-addon-api#504]
Hey guys,

im trying to port my companies internal node addon from nan to n-api...
So far im doing well, but im struggeling with something.

Im passing an Array of Hex Values to this addon like so: [0x20, 0x11, ...].
And i need to convert each of them to an unsigned char, because i need to pass an unsigned char* to a function which i dont control.

What i was trying to do is:
Getting the Uint32Value of each element and then convert the value to an unsigned char.

But this just wont work for me...
Can someone give me some advice on how i could accomplish this?
Thanks :)

If you need more information please let me know.

**Comment by gabrielschulhof** [comment]
A really efficient way of doing it would be to pass a `Uint8Array` into your addon:
```C++
#include "napi.h"

void AcceptUint8Array(const Napi::CallbackInfo& info) {
  fwrite(
    info[0].As<Napi::Uint8Array>().Data(),
    info[0].As<Napi::Uint8Array>().ByteLength(),
    1,
    stdout);
}

Napi::Object Init(Napi::Env env, Napi::Object exports) {
  exports["acceptUint8Array"] =
    Napi::Function::New(env, AcceptUint8Array);
  return exports;
}

NODE_API_MODULE(NODE_GYP_MODULE_NAME, Init)
```

and then you can use it like this:

```JS
nativeAddon.acceptUint8Array(new Uint8Array([
  0x78, 0x79, 0x7a, 0x7a, 0x79, 0x0a
]));
```

**Comment by gabrielschulhof** [comment]
If you cannot change the interface to accept a `Uint8Array` then what you're doing, to accept a plain JS array, and convert each value to `unsigned char` is the only way to go.

**Comment by gabrielschulhof** [comment]
To accept a plain JS array you can do this:

```C++
void AcceptPlainArray(const Napi::CallbackInfo& info) {
  Napi::Array array = info[0].As<Napi::Array>();
  size_t length = array.Length();
  unsigned char string[length];
  for (size_t idx = 0; idx < length; idx++) {
    Napi::Value val = array[idx];
    string[idx] = (val.As<Napi::Number>().Uint32Value() & 0xff);
  }
  fwrite(string, length, 1, stdout);
}
```

**Comment by gabrielschulhof** [comment]
@Arcticon ran a quick benchmark.js on the two functions:
```
Uint8Array x 11,219,847 ops/sec ±0.57% (92 runs sampled)
Plain array x 2,007,478 ops/sec ±0.98% (96 runs sampled)
```

**Comment by gabrielschulhof** [comment]
I suspect the discrepancy between the two numbers will increase dramatically with the length of the array 😉

**Comment by gabrielschulhof** [comment]
Indeed ...
```
Uint8Array@6 x 11,518,035 ops/sec ±0.71% (95 runs sampled)
Plain array@6 x 2,056,765 ops/sec ±0.82% (98 runs sampled)

Uint8Array@12 x 11,420,588 ops/sec ±1.39% (94 runs sampled)
Plain array@12 x 1,103,699 ops/sec ±0.70% (95 runs sampled)

Uint8Array@24 x 11,636,024 ops/sec ±0.95% (93 runs sampled)
Plain array@24 x 565,515 ops/sec ±0.32% (95 runs sampled)
```

I guess the discrepancy grows because, in the case of the `Uint8Array`, the data can be obtained in constant time, whereas in the case of the plain `Array`, it takes linear time in the number of elements.

**Comment by Arcticon** [comment]
@gabrielschulhof Thank you very much for the quick and super informative answer!

I will try this out and will notify you if everything works!

Thanks :)

**Comment by Arcticon** [comment]
@gabrielschulhof So ive just tested everything and both of your answers work for me.
Regarding changing the interface to pass an Uint8Array: I can do that, but since a lot of my colleagues wont understand low level data types i wont go that way.

But thank you sooo much for helping me!

One last quick question. Why do i have to cast a char to i.e. an int, to std::cout its value? When i just print the char it doesnt display any value. I was expecting either the ascii value of that int or just an int.

**Comment by gabrielschulhof** [comment]
I don't know much about `cout` because I always use `printf()`. If you didn't see anything then I suspect it's because it was printing out the character "raw". Such characters are usually not printable, because only characters in the range 0x20 - 0x7e are printable. So, for example, if you print out 0x0a you will get a new line. You also want to make sure that when you assign a value to a `char`, the value is between 0x00 and 0xff, so that's why I did the `& 0xff`.

I guess in terms of performance, the shorter the plain array over which you have to iterate, the better.

**Comment by Arcticon** [comment]
Dang it, thats true...

The array will always be of length 5;

**Comment by gabrielschulhof** [comment]
Not so bad then ...
