### ISSUE TITLE
How to require another built-in module?

### ISSUE THREAD

**Issue by thai6070** [nodejs/node-addon-api#505]
I need to use some modules like fs or crypto. It's easy for me to achieve that with Nan by using module varible.  Is there any way to do the same?

**Comment by gabrielschulhof** [comment]
You can write a function that accepts another module. Here's a [gist](https://gist.github.com/gabrielschulhof/fcfdf47703f9ee21a7eebbc1600c49c4) with an example.

**Comment by mhdawson** [comment]
Going to close this out as the question was answered and there was no follow on question. Please let us know if that was not the right thing to do.
