### ISSUE TITLE
Stopping AsyncWorker in the middle of process.

### ISSUE THREAD

**Issue by chadjfoster** [nodejs/node-addon-api#511]
Hello,

Is it possible to stop a single AsyncWorker after it has started the AsyncWorker::Execute() function? 

The reason I want this functionality is for a node server where user requests could potentially take longer than our HTTP timeout, once this time is reached there is no reason to continue processing the user request. However, from the documentation & issues I don't see any way to stop the process one it is running, only cancel the Queue. I think this must be  a somewhat common problem and I am missing something obvious, so if you could point me in the right direction I would greatly appreciate it.

**Comment by mhdawson** [comment]
There is no way in node-addon-api to stop the AsyncWorker after it has started running.  That will take communication/synchronization between the two threads.

You might be able to do what you need with the more sophisticated thread-safe API https://github.com/nodejs/node-addon-api/blob/master/doc/threadsafe_function.md

**Comment by mhdawson** [comment]
@chadjfoster just to note that the thread-safe API just landed and is not yet in a release (may also still be experimental pending backports)

**Comment by chadjfoster** [comment]
Thank you for the quick response, I'll look into the thread-safe API, but I don't think I will update until it is in release.
