### ISSUE TITLE
NAPI native module in C++ is executing partially (Included std::thread)

### ISSUE THREAD

**Issue by AtiqGauri** [nodejs/node-addon-api#516]
My Node-js native module written with NAPI is executing partially.
I have used multiple threads in it and for debugging i am using normal "std::cout".
While running module sometime it prints that thread is started but sometime it don't.
And in either way module never reach the end of c++ code.
I have tried my c++ code as a standalone application and works fine without any warning or error.
I have turned on exceptional handling in "CMakeList.txt"
C++ 17 support is on because I am using std::filesystem which is working fine.
I am using find_package(Threads REQUIRED) in "CMakeList"

**file CMakeList.txt=>**
```
cmake_minimum_required(VERSION 3.15)
# Name of the project (will be the name of the plugin)
project (addon)

set(CMAKE_CXX_STANDARD 17)
# Don't add this line if you will try_compile with boost.
set(CMAKE_CXX_STANDARD_REQUIRED ON)
option(USE_CXX_EXCEPTIONS "Enable C++ exception support" ON)
set(THREADS_PREFER_PTHREAD_FLAG ON)

find_package(Threads REQUIRED)
# Essential include files to build a node addon,
# you should add this line in every CMake.js based project.
include_directories(${CMAKE_JS_INC})

# Declare the location of the source files
file(GLOB SOURCE_FILES "cppsrc/*.cpp" "cppsrc/*.h")

# This line will tell CMake that we're building a shared library
# from the above source files
# named after the project's name
add_library(${PROJECT_NAME} SHARED ${SOURCE_FILES} ${CMAKE_JS_SRC})

# This line will give our library file a .node extension without any "lib" prefix
set_target_properties(${PROJECT_NAME} PROPERTIES PREFIX "" SUFFIX ".node")

# Essential library files to link to a node addon,
# you should add this line in every CMake.js based project.
target_link_libraries(${PROJECT_NAME} ${CMAKE_JS_LIB} ${CMAKE_THREAD_LIBS_INIT})


# Include N-API wrappers
execute_process(COMMAND node -p "require('node-addon-api').include"
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE NODE_ADDON_API_DIR
    )
string(REPLACE "\n" "" NODE_ADDON_API_DIR ${NODE_ADDON_API_DIR})
string(REPLACE "\"" "" NODE_ADDON_API_DIR ${NODE_ADDON_API_DIR})
target_include_directories(${PROJECT_NAME} PRIVATE ${NODE_ADDON_API_DIR})
```

**file package.json=>**
```
{
"name": "test-addon",
"version": "1.0.0",
"description": "",
"author": "",
"license": "ISC",
"scripts": {
"install": "cmake-js compile"
},
"cmake-js": {
  "runtime": "electron",
"runtimeVersion": "5.0.5",
"arch": "x64"
},
"devDependencies": {},
"dependencies": {
  "cmake-js": "^5.3.0",
  "node-addon-api": "^1.6.3"
}
}
```

**the c++ code which is executing partially =>**
```
while (file != filePaths.end()) {
start = timeStamp();
cout << "\n" << "File: " << *file << " \n";

//process Data
pres.readRawDataList(*file);
for (int i = 0; i < hwGuess; i++) {
    begint = (i * pres.rawDataList.size()) / hwGuess;
    endt = (i + (size_t)1) * pres.rawDataList.size() / hwGuess;
    CthreadObj[i].rawData.reserve(pres.rawDataList.size() / hwGuess);
    CthreadObj[i].rawData.insert(CthreadObj[i].Pcomparison::rawData.begin(), pres.rawDataList.begin() + begint, pres.rawDataList.begin() + endt);
threads.push_back(thread([&]() { ExpSub(CthreadObj[i], PthreadObj[i]); }));
}

for (int j = 0; j < hwGuess; j++) {
  cout<<"join total 4 threads\n";
  threads.at(j).join();
}
cout<<hwGuess<<" \n";

cout<<"thread Ends \n";
pfile.writeFile(pres.results, "cppsrc/Output/0.txt");
pres.rawDataList.clear(); pres.rawDataList.shrink_to_fit();
pres.results.clear(); pres.results.shrink_to_fit();
//Processed
cout<<"While ends \n";
file++;
```

**funtion ExpSub=>**
```
ExpSub(Pcomparison& ThreadObjC, Ppattern& ThreadObjP) {

vector<string>::iterator rawIt;

ThreadObjC.lowerCaseRawData();
cout<<"Inside Thread\n";
ThreadObjC.extractEmailAndPassword(":");
ThreadObjC.extractEmailNamesAndWebsites();
```

**hwGuess value is 4**

result should be print message "While ends" as in above code and this should happen every time not randomly (check image where it randomly execute "thread inside line").
![Screenshot (109)](https://user-images.githubusercontent.com/37737221/61589450-73bb3100-abc7-11e9-8796-18c980663e63.png)

My main problem is why it is partially running there are 4 threads in total but most of the time it runs 1-2 thread and sometimes not 1 at all.
I am calling these c++ function from a normal NAPI function

**Comment by KevinEady** [comment]
Hi @AtiqGauri ,

Have you tried compiling your addon in debug mode and debugging your application? In the past, I have had issues with a thread finishing abnormally and causing the whole application to terminate. Do you have any js code in index.js that runs _after_ your native addon function?

Also, just wondering from the code perspective... If you are creating threads and joining them within a single `Napi::Function` call on the main thread, please be aware this would block the event loop. Have you taken a look at the recently added [thread-safe functions](https://github.com/nodejs/node-addon-api/blob/master/doc/threadsafe_function.md)? Maybe this would help. The next release is being tracked here https://github.com/nodejs/node-addon-api/issues/514

**Comment by KevinEady** [comment]
Alternatively (and probably better for your use-case) you could use an [AsyncWorker](https://github.com/nodejs/node-addon-api/blob/master/doc/async_worker.md).

**Comment by AtiqGauri** [comment]
Thanks for response but I think it something else. As I found a workaround for it.
Previously I was using Lamba function (C++) to Initialize thread in c++. Which was causing the above issue. But once I removed that lambda function and intialized the thread by this way -></br>
std::thread(&namespace::function_name, this, args);
Now Everything works fine.

**Comment by AtiqGauri** [comment]
Still if use thread using lambda function in C++. then it works fine as c++ standalone application.</br> But shows unpredictable behavior in Node.js addon.

**Comment by KevinEady** [comment]
@AtiqGauri I see... I would guess it has something to do with the lifetime of the two variables that are being passed by-reference in your old lambda expression, `CthreadObj[i]` and `PthreadObj[i]` ? Just guessing

If your new solution works, 👍. Does that resolve this issue?

**Comment by AtiqGauri** [comment]
New solution is just calling thread function directly without lambda and arguments are referenced in this case too. I think it is related to lambda function.
Any way that was solved by new Syntex which I mentioned above

**Comment by KevinEady** [comment]
@AtiqGauri can we close this issue then?

**Comment by AtiqGauri** [comment]
Yeah
