### ISSUE TITLE
How to access database management system like MariaDB/MySQL, PostgresQL, etc using N-API?

### ISSUE THREAD

**Issue by hadihammurabi** [nodejs/node-addon-api#519]
I have tried to connect to MySQL Server using C++ MySQL driver. But, after compilation, i got an error that say, "cannot find mysql_real_connect".

I use C++ MariaDB connector.

**Comment by NickNaso** [comment]
Hi @hadihammurabi,
is your code public?

**Comment by hadihammurabi** [comment]
@nicknaso no. But, if you know how to do that. Please send to me some references. Thank you

**Comment by KevinEady** [comment]
Unable to find library methods... I guess you need to have the proper include directories inside your gyp file (if using gyp)? If you're getting a linker error, you need to add the right libraries.

**Comment by NickNaso** [comment]
Hi @hadihammurabi,
@KevinEady is right probably you need to change the configuration of your `binding.gyp` file. If you use `gyp` to build the native  add-on you can take a look at this https://github.com/mmod/nodamysql and in general to understand how to configure `binding.gyp` file you can refer to https://github.com/nodejs/node-gyp/wiki/%22binding.gyp%22-files-out-in-the-wild.

**Comment by hadihammurabi** [comment]
> Hi @hadihammurabi,
> @KevinEady is right probably you need to change the configuration of your `binding.gyp` file. If you use `gyp` to build the native add-on you can take a look at this https://github.com/mmod/nodamysql and in general to understand how to configure `binding.gyp` file you can refer to https://github.com/nodejs/node-gyp/wiki/%22binding.gyp%22-files-out-in-the-wild.

Thankyou, i use this source as example and now i have done with MySQL and N-API. Thankyou

**Comment by hadihammurabi** [comment]
> Hi @hadihammurabi,
> @KevinEady is right probably you need to change the configuration of your `binding.gyp` file. If you use `gyp` to build the native add-on you can take a look at this https://github.com/mmod/nodamysql and in general to understand how to configure `binding.gyp` file you can refer to https://github.com/nodejs/node-gyp/wiki/%22binding.gyp%22-files-out-in-the-wild.

Thankyou, i use this source as example and now i have done with MySQL and N-API.
