### ISSUE TITLE
node-addon-api-new CI failures on AIX

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#522]
Seems to be failing consistently on Master, is ok on other versions. For example:

https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-new/nodes=aix61-ppc64/406/console

Need to investigate to see if this is an issue with Node or node-addon-api

**Comment by bnoordhuis** [comment]
node-gyp tries to download from https://nodejs.org/download/ but it looks like the TLS connection can't be set up for some reason. Since the nightly build is used to run node-gyp, it might indicate an issue with the build.

**Comment by mhdawson** [comment]
Failure seems to be: 

```
gyp verb extracted file from tarball node-v13.0.0-nightly20190813a49b20d324/include/node/openssl/archs/linux64-s390x/asm_avx2/crypto/buildinf.h
gyp verb extracted file from tarball node-v13.0.0-nightly20190813a49b20d324/include/node/openssl/archs/linux64-s390x/asm_avx2/include/openssl/opensslconf.h
gyp verb extracted file from tarball node-v13.0.0-nightly20190813a49b20d324/include/node/openssl/archs/linux64-s390x/asm_avx2/include/progs.h
gyp verb extracted file from tarball node-v13.0.0-nightly20190813a49b20d324/include/node/openssl/archs/linux64-s390x/asm/include/openssl/opensslconf.h
gyp verb extracted file from tarball node-v13.0.0-nightly20190813a49b20d324/include/node/openssl/archs/linux64-s390x/asm/include/progs.h
gyp verb extracted file from tarball node-v13.0.0-nightly20190813a49b20d324/include/node/openssl/archs/linux64-s390x/asm/crypto/include/internal/bn_conf.h
gyp verb extracted file from tarball node-v13.0.0-nightly20190813a49b20d324/include/node/openssl/archs/linux64-s390x/asm/crypto/include/internal/dso_conf.h
gyp verb extracted file from tarball node-v13.0.0-nightly20190813a49b20d324/include/node/openssl/archs/linux64-s390x/asm/crypto/buildinf.h
gyp verb extracted file from tarball node-v13.0.0-nightly20190813a49b20d324/include/node/openssl/archs/VC-WIN64-ARM/no-asm/crypto/include/internal/bn_conf.h
gyp verb extracted file from tarball node-v13.0.0-nightly20190813a49b20d324/include/node/openssl/archs/VC-WIN64-ARM/no-asm/crypto/include/internal/dso_conf.h
gyp verb extracted file from tarball node-v13.0.0-nightly20190813a49b20d324/include/node/openssl/archs/VC-WIN64-ARM/no-asm/crypto/buildinf.h
gyp WARN install got an error, rolling back install
gyp verb command remove [ '13.0.0-nightly20190813a49b20d324' ]
gyp verb remove using node-gyp dir: /home/iojs/.cache/node-gyp
gyp verb remove removing target version: 13.0.0-nightly20190813a49b20d324
gyp verb remove removing development files for version: 13.0.0-nightly20190813a49b20d324
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at TLSWrap.onStreamRead (internal/stream_base_commons.js:183:27)
gyp ERR! System AIX 6.1
gyp ERR! command "/home/iojs/build/workspace/node-test-node-addon-api-new/nodes/aix61-ppc64/node-v13.0.0-nightly20190813a49b20d324-aix-ppc64/bin/node" "/home/iojs/build/workspace/node-test-node-addon-api-new/nodes/aix61-ppc64/node-v13.0.0-nightly20190813a49b20d324-aix-ppc64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "-C" "test"
gyp ERR! cwd /home/iojs/build/workspace/node-test-node-addon-api-new/nodes/aix61-ppc64/node-addon-api/test
gyp ERR! node -v v13.0.0-nightly20190813a49b20d324
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm verb lifecycle node-addon-api@1.7.1~pretest: unsafe-perm in lifecycle true
npm verb lifecycle node-addon-api@1.7.1~pretest: PATH: /home/iojs/build/workspace/node-test-node-addon-api-new/nodes/aix61-ppc64/node-v13.0.0-nightly20190813a49b20d324-aix-ppc64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/iojs/build/workspace/node-test-node-addon-api-new/nodes/aix61-ppc64/node-addon-api/node_modules/.bin:/home/iojs/build/workspace/node-test-node-addon-api-new/nodes/aix61-ppc64/node-v13.0.0-nightly20190813a49b20d324-aix-ppc64/bin:/home/iojs/gcc-6.3.0-1/opt/freeware/bin:/usr/bin:/etc:/usr/sbin:/usr/ucb:/home/iojs/bin:/usr/bin/X11:/sbin:.
npm verb lifecycle node-addon-api@1.7.1~pretest: CWD: /home/iojs/build/workspace/node-test-node-addon-api-new/nodes/aix61-ppc64/node-addon-api
npm info lifecycle node-addon-api@1.7.1~pretest: Failed to exec pretest script
npm ERR! Test failed.  See above for more details.
npm verb exit [ 1, true ]
npm timing npm Completed in 21569ms
```

**Comment by mhdawson** [comment]
So I think it looks like it is failing to get the headers but I'm not sure why that would only affect AIX.

**Comment by mhdawson** [comment]
This started failing Aug 7

**Comment by mhdawson** [comment]
Looks like it passed today.  Not sure what might have changed.

**Comment by mhdawson** [comment]
Ran another run and seems ok.  @miladfarca also validated that there are no problems running outside of CI.  Closing as it seems to have fixed itself whatever the problem was.

**Comment by miladfarca** [comment]
Attempting a fix in this PR (with some extra details on the issue):
https://github.com/nodejs/node-gyp/pull/1863

**Comment by miladfarca** [comment]
Ass an addition to the notes in this PR nodejs/node-gyp#1863, I looked some more into the origin of the issues.

I cam up with a simpler test case which doesn't use `tar`, in this test we download a stream and throttle it in a pipe which passes it to `/dev/null`:
```js
var Throttle = require('throttle');
const https = require('https');
var devnull = require('dev-null');
var t = new Throttle({ bps: 40000});
const options = {
    hostname: 'nodejs.org',
    path: '/download/nightly/v13.0.0-nightly20190822775048d54c/node-v13.0.0-nightly20190822775048d54c-headers.tar.gz',
}
const request = https.get(options, function(response) {
    response.pipe(t).pipe(devnull());
});
```
This way the stream speed matches to what we have on CI AIX. I managed to reproduce the same error on our internal AIX 6.1 and 7.2 machines.

More testing was done using `curl` to bypass nodejs. I created a custom app using this code:
https://superuser.com/questions/239893/how-to-rate-limit-a-pipe-under-linux

and called it `slow`, then used it in a pipe to create the same `throttling` effect as `tar` and eliminated tar:
```
curl -L -v -H 'Connection: close' https://nodejs.org/download/nightly/v13.0.0-nightly20190822775048d54c/node-v13.0.0-nightly20190822775048d54c-headers.tar.gz | slow 100000 -  > /dev/null
```
tail of the curl output looks like this:
```
< CF-RAY: 50e33aafcdf5e20e-ORD
< 
{ [832 bytes data]
100  643k  100  643k    0     0  37124      0  0:00:17  0:00:17 --:--:-- 38945
* Closing connection 0
} [5 bytes data]
```
running the same command without piping to `slow 100000` will create this tail:
```
{ [832 bytes data]
100  643k  100  643k    0     0  2992k      0 --:--:-- --:--:-- --:--:-- 2978k
* Closing connection 0
} [5 bytes data]
* TLSv1.2 (OUT), TLS alert, Client hello (1):
} [2 bytes data]
```
As you can see `TLSv1.2 (OUT), TLS alert, Client hello (1):` is a new string in the second output.
Doing a bit of research and I found the string is part of the `Closing call` curl is sending to the server as its final messages. If the string is not printed by curl it most likely means the connection is already closed by the server (immediately once the file transmission is done) so client stack doesn't need to and can't notify the server anymore.

Tracing back the original call stack from our `js` test file will include this as it's error stack from nodejs `lib/_http_client.js`:
```
...
  const parser = socket.parser;
  const res = req.res;
  if (res) {
    // Socket closed before we emitted 'end' below.
    if (!res.complete) {
      res.aborted = true;
      res.emit('aborted');
    }
...
```
Which also shows the connection may be getting closed before the client has a chance to say bye.

Both of the tests were executed with the same `tar` file hosted on a different server with https enabled. The js script downloaded the tar file with no errors and `curl` shows `TLSv1.2 (OUT)` correctly.

Test was also done by connecting to the nodejs server (which is behind Cloudflare proxies)
and the results were also successful.

It might be a good idea to open a ticket on `Cloudflare` and ask them if they have any output logs which might be helpful, or why their TLS connection might be cutting AIX off.

I have created the above PR which forces an open connection using `keep-alive` which eliminates this error.

In the meantime, we can also look into `libuv` and AIX and compare them with Linux to see if sockets are handled differently which might also cause this error.

**Comment by miladfarca** [comment]
A libuv fix has been committed: https://github.com/libuv/libuv/pull/2447

I have tested this solution manually by doing a `make install` on a `13.0.0-pre` nodejs source and the `ECONNRESET` error is not reproduced.

**Comment by miladfarca** [comment]
Changes in libuv have been merged with Nodejs master: https://github.com/libuv/libuv/issues/2457 and AIX builds seems to be constantly green now:
https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-new/nodes=aix61-ppc64/

**Comment by mhdawson** [comment]
@miladfarca thanks! Closing
