### ISSUE TITLE
cFatal error: context->isNativeContext()

### ISSUE THREAD

**Issue by SpiceyWolf** [nodejs/node-addon-api#523]
I cannot find any documentation anywhere that could help me trouble-shoot this error (or even find anything related to the context-isNativeContext() that node is complaining is broken.

Im using nodejs 10.16.0 (32-bit on windows, 64-bit on linux) and using an asyncworker object in an addon for a project I am apart of. The design is hooking up an emulator which has a callback system (in C) which I have fed a js function call using asyncworker. A majority of the time the app seems to run with no issues, however within the first 3 or so calls on some startup attempts the whole thing crashes with this error:

*
* Fatal error in , line 0
* Check failed: context->IsNativeContext().
*
*
*
* FailureMessage Object: 0x7f88f4b05180Illegal instruction

Should I make it beyond those first few calls the app can run stable for hours working as intended. I don't know if this is a flaw in asyncworker, a timing thing, or how I am handling it specificly and am desperate to get this fixed.

For specific use case (so my code may be inspected assuming it may be user error):
https://github.com/hylian-modding/ModLoader64-M64P-Npm/blob/master/src/node/callbacks.cpp

It is the latter half of this file (The first half is some thread shenanigans to track if the async worker ran a frame before allowing the C app [Mupen64Plus Emulator] to continue.

**Comment by mhdawson** [comment]
I'm guessing the problem is that Queue() is meant to be called on the Node.js main thread, and from my quick look at the code I don't think it is (assuming M64P_Callback_Frame is not run on the main thread)

Code which runs off thread with AsyncWorker should run in the Execute() method. 

You might want to look at the ThreadSafeFunction class instead.

**Comment by SpiceyWolf** [comment]
Thanks for the reply... I don't really see myself having a use for the Execute() method because the general process is the NodeJS will setup the Mupen to run on its own thread after assigning a node function to a callback variable (stored in the mupen). Every frame run in the game Mupen controls will stop and try to execute a function declared within node to manipulate stuff about the game before moving on... I do not believe there is anything in the layer between node and mupen that could actually be placed there to do anything meeningful.

I assume what you suggest with Thread-Safe Function is probably what I would need (more appropriately than the async worker) however the documentation for using NAPI is rather confusing. 

If I use the 'napi_create_threadsafe_function' am I supposed to do it when node feeds me a function to store, and is it retained until I choose to destroy it? (Unlike the asyncworker which in my experience seems to destroy itself after every time it runs)

**Comment by mhdawson** [comment]
I'd suggest you look at this example: https://github.com/nodejs/node-addon-examples/blob/master/async_work_thread_safe_function/node-api/binding.c

but yest threadsafe_functions are for when you need multiple interactions between a separate thread and the node main thread where JavaScript/N-API calls can run.

**Comment by mhdawson** [comment]
There is also this example as well https://github.com/nodejs/node-addon-examples/blob/master/thread_safe_function_round_trip/

**Comment by mhdawson** [comment]
The second one might be the better one to look at first.

**Comment by SpiceyWolf** [comment]
Sorry I havent been back sooner. Thanks for the links... Ive attempted to implement something here but I cant seem to gain access to the napi_create_threadsafe_function... It seems like a good chunk of functions are missing from other things Id found with async worker and a few other things I've attempted to use before. I assume I'm missing dependancies but not sure where to get them >.>

**Comment by SpiceyWolf** [comment]
nvm i found out why... the tutorial i used to setup the project had me using a REALLY old version of this xD Heck it might stop having the problems i was having on its own if im lucky... ill play with it, I appreciate your help so much though thank you!
