### ISSUE TITLE
Napi::ObjectWrap has significant memory bloat

### ISSUE THREAD

**Issue by jkao** [nodejs/node-addon-api#526]
I've been writing a Node.js C++ plugin (which I hope to open source soon) that has been running into some issues with memory.

If I create objects defined with `Napi::ObjectWrapper` in a tight loop, the GC is not able to catch up and leads to significant memory usage. 

In my plugin, if I return something besides `Napi::ObjectWrapper`, like Arrays of Strings or other primitive types, the memory usage is flat. If I create a functionally equivalent Class in JavaScript, I don't run in to high memory usage, either, though I imagine the interpreter is doing some optimizations.

I'm measuring this with `top | grep node`. I've created an example repository (with instructions to run in the README.md) to demonstrate this. Is there any way we can optimize this aspect of writing Node.js C++ libraries? 

Repository is here: https://github.com/jkao/node-addon-memory-bloat

It could also be that I'm writing things incorrectly, but this example is taken directly from the examples.

**Comment by jkao** [comment]
FWIW, in my production code, I'm not running a tight loop, but the process is processing millions of messages with my library. It was running into these memory issues when I returned an array of custom classes (memory shoots up), but not with an array (untyped) of primitive types (memory was flat).

**Comment by mhdawson** [comment]
@jkao one thing that would be interesting to understand is if the overhead is in node-addon-api or also appears when using N-API directly.  One guess I would have is that wrapping at all requires the gc to run finalizers which might be the expensive part.

Any chance you could write/run the same example using the N-API methods instead? https://nodejs.org/dist/latest-v12.x/docs/api/n-api.html#n_api_object_wrap

**Comment by mhdawson** [comment]
The other thing I'm wondering from your description is whether you believe it is just using a lot of memory (overhead) ie the gc can catch up if given enough time, or if you think there is a leak such that memory increases each time you create a new instance?

**Comment by jkao** [comment]
@mhdawson thanks for the quick reply!

Re: memory leak vs overhead, the issue is overhead. If I run the tight loops with a janky sleep delay between the loops, the memory eventually settles at a steady state of memory (albeit higher, but I suspect that is Node.js enforcing a larger heap size or something along those lines).

However, I've discovered that GC improvements to Node may have solved this problem.

I've been testing with different versions of Node on my 2019 MBP:
- node/10.16.0
- node/11.15.0
- node/12.9.0

It looks like Node 11+ is able to keep the memory flat (~150 MB on my 2019 MBP) in my example repository, whereas Node 10 and below seem to have trouble GCing while in the loop (peaking at ~2GB on the same laptop, but dropping after).

This looks like a GC implementation improvement of Node.js, so not directly an issue with this library. Given that, I'm going to close this issue.

**Comment by mhdawson** [comment]
@jkao great to hear :)
