### ISSUE TITLE
JS Code in the native node module

### ISSUE THREAD

**Issue by sudhakar3697** [nodejs/node-addon-api#528]
Is it possible to access the following variants of node modules inside the N-API addon code(C/C++).

1. Built-in Node module (like fs, http).
2. Node module written in Javascript.
3. Native node module written using (NAN or oth).
4. Native node module written using N-API.

Thank you.

**Comment by legendecas** [comment]
If I got it right, the key might be a module API in N-API to allow N-API modules to directly access other type of modules. Currently you have to pass `require` function or `module` instance to N-API modules on a setup phase from JS. With `require` there is no differences between these 4 types of modules AFAIK.

A module API is being proposed on https://github.com/nodejs/node/pull/28464.

**Comment by mhdawson** [comment]
@sudhakar3697 you can call JavaScript functions, but is up to you to get those to the N-API module.  For example if you pass the result of fs = require('fs') to an N-API function it can use N-API methods to get fields/functions on that an then call them.  

Having said that it might be easier to keep some of that functionality in JS and call a higher level function from the N-API C function as opposed to making many of those calls in the N-API functcion.  I also believe it would likely be better optimized with more of the calls together at the JS level as each back and forth adds overhead.

**Comment by sudhakar3697** [comment]
https://gist.github.com/gabrielschulhof/fcfdf47703f9ee21a7eebbc1600c49c4
