### ISSUE TITLE
Need help with basic callback return value

### ISSUE THREAD

**Issue by felipezacani** [nodejs/node-addon-api#535]
Hi,

sorry but I had to throw such a basic question. Probably making a simple mistake but I couldn't find any example with a similar implementation. I'm calling a JS callback from my cpp addon and I can't read the return value. Tried multiple return value types, all I get in the addon is undefined. The code is simplified here, but I'm using the same version for my tests:

ADDON code:
```
static Napi::Function g_callback;
static Napi::FunctionReference g_callbackRef;
const char *driverCallback(const char *jsonData)
{
  Napi::Value serverResponse = g_callbackRef.Call({Napi::String::New(g_callbackRef.Env(), jsonData)});
  std::string strResponse = serverResponse.ToString();
  g_callbackRef.Call({Napi::String::New(g_callbackRef.Env(), strResponse.c_str())});
  return "";
}
```

JS Callback:
```
onDriverCallback (data) {
    console.log(`Driver request received: ${data}`)
    console.log(`Returning to the addon: ${JSON.stringify({ test: 'ping' })}`)
    return 0 //JSON.stringify({ test: 'ping' })
}
```

**Comment by marco-ms** [comment]
Why you create serverResponse as Napi::Value then go to string and back to Napi::Value?

**Comment by NickNaso** [comment]
@felipezacani Is your code public? Could share it?

**Comment by felipezacani** [comment]
> @felipezacani Is your code public? Could share it? Or could explain your use case?

Hi Nick!
Unfortunately I can't share. But I can explain and show you parts of the code. My use case is:
- A server stores cached data (node.js)
- The server loads the addon upon starting. The addon loads an external DLL. The DLL needs data from the server, so it uses the callback to send commands to the server, such as "get" or "set", for retrieving or storing its configs in the server cache.
I believe its a simple use case of calling a js callback and retrieving data. The "return 0" in my js function is obviously for testing purposes, as I'm always getting "undefined" in the addon side, regardless of whats returned. Please let me know if you need more info.

**Comment by felipezacani** [comment]
> Why you create serverResponse as Napi::Value then go to string and back to Napi::Value?
> Also: `driverCallback` is always called on the main thread right?

I guess this code is "disfigured" after so many debugging attempts. Initially I was receiving the return value in a string, then I switched at some point. Just trying everything. I probably switched because I was getting an exception sayng "a string was expected".

**Comment by NickNaso** [comment]
Hi @felipezacani,
if you only need to load the data on starting the application you can do something like this:
```js
'use strict'

const http = require('http')
const cache = require('./cache.json')
const addon = require('bindings')('addon')

const hostname = '127.0.0.1'
const port = 3000

const server = http.createServer((req, res) => {
  res.statusCode = 200
  res.setHeader('Content-Type', 'text/plain')
  res.end('Node.js\n')
})


addon.callDriver(cache, (data) => {
    console.log(`My data sterd in the cache:`)
    console.dir(data)
    server.listen(port, hostname, () => {
        console.log(`Server running at http://${hostname}:${port}/`)
    })
})
```
```cpp
#include<napi.h>
#include <chrono>
#include <thread>

Napi::Value CallDriver(const Napi::CallbackInfo& info) {
    // Napi::Env env = info.Env();
    Napi::Object data = info[0].As<Napi::Object>();
    Napi::Function cb = info[1].As<Napi::Function>();
   
    // Here I'm simulating the execution of some operations
    std::this_thread::sleep_for(std::chrono::seconds(3));
      
    return cb.Call({data});
}

// Init
Napi::Object Init(Napi::Env env, Napi::Object exports) {
    exports.Set(Napi::String::New(env, "callDriver"), Napi::Function::New(env, CallDriver));
    return exports;
}

NODE_API_MODULE(NODE_GYP_MODULE_NAME, Init);
```
This example use a synchronous function so all happens on the main thread (event loop)  and it's not ideal, but you could you `Napi::AsyncWorker` to process all the thing in an asynchronous way.

I'm posting the complete example here: 
[www.zip](https://github.com/nodejs/node-addon-api/files/3588101/www.zip)

**Comment by felipezacani** [comment]
Hi @NickNaso 
Thanks for your example. My use case is actually very different: I need to be able to call a JS function at any time. I use the Driver DLL to create instances of drivers. The instances respond to commands. I saved the callback function using the FunctionReference class (remember our last talk here?) and I intent to use it. Everything works, except for the return value.

The worse thing is I modified the example (3_callbacks) in node-addon-examples to be almost equal to my implementation and **it works**. The only difference is the callback Call is being performed in the same function that stores it in the FunctionReference.

The big difference is, of course, my code is being triggered by a request (express).

Here is the modified example code (works): 
```
#include <napi.h>
#include <iostream>

/* The external driver callback function reference */
static Napi::Function g_callback;
static Napi::FunctionReference g_callbackRef;

void runCallback()
{
  Napi::Value serverResponse = g_callbackRef.Call({Napi::String::New(g_callbackRef.Env(), "test!")});
  std::string strResponse = serverResponse.ToString();
  std::cout << strResponse.c_str();
}

Napi::Value extSetHandler(const Napi::CallbackInfo &info)
{
  Napi::Env env = info.Env();
  g_callback = info[0].As<Napi::Function>();
  g_callbackRef = Napi::Persistent(g_callback);
  std::cout << "callback set" << std::endl;
  runCallback();
  return Napi::Boolean::New(env, true);
}

Napi::Object Init(Napi::Env env, Napi::Object exports)
{
  exports.Set(Napi::String::New(env, "extSetHandler"),
              Napi::Function::New(env, extSetHandler));
  return exports;
}

NODE_API_MODULE(addon, Init)
```
```
var addon = require('bindings')('addon');

function test(msg){
  return msg;
}
addon.extSetHandler(test);
```

**Comment by KevinEady** [comment]
Hi @felipezacani ,

> I need to be able to call a JS function at any time.

You can only call a JS function while you're on the main thread. Generally, you cannot have some other thread (eg. one created by `std::thread`) call your `runCallback()` method. If you want this behavior, you need to use some other mechanism, eg. [thread-safe functions](https://github.com/nodejs/node-addon-api/blob/master/doc/threadsafe_function.md), which will basically asynchronously add a "request to run this function" to the event loop.

Let us know if this helps.

**Comment by felipezacani** [comment]
> Hi @felipezacani ,
> 
> > I need to be able to call a JS function at any time.
> 
> You can only call a JS function while you're on the main thread. Generally, you cannot have some other thread (eg. one created by `std::thread`) call your `runCallback()` method. If you want this behavior, you need to use some other mechanism, eg. [thread-safe functions](https://github.com/nodejs/node-addon-api/blob/master/doc/threadsafe_function.md), which will basically asynchronously add a "request to run this function" to the event loop.
> 
> Let us know if this helps.

Hi @KevinEady 
You got it. I was trying to call the function out of the main thread. That was the main difference between my code and the sample code that worked. 

Thanks a lot for your support, everyone. I'm closing, another problem solved. Thanks @NickNaso and @KevinEady !
