### ISSUE TITLE
Development setup around QT Creator all the way to generating, maintaining and deploying node-red custom nodes

### ISSUE THREAD

**Issue by pcorner** [nodejs/node-addon-api#537]
Lately I have been diving into the world of node-addon-api, and become a hugh fan! I have been working towards have a setup with QT Creator ( using CMAKE-JS). 
https://github.com/cmake-js/cmake-js/wiki/TUTORIAL-02-Creating-CMake.js-based-native-addons-with-QT-Creator.
I plowed through this 
https://corymickelson.github.io/2018/01/27/Native-Nodejs-Development-Environment-Setup/
but found a few missing parts to have is all working. 
Ill be happy to share what I have and would appreciate further contributions, that would improve the workflow of setting up the framework around generating new, maintaining custom nodes.js nodes all the way to a node-red implementation.

**Comment by pcorner** [comment]
I trying to empower more people to benefit from the work you have done here, and I seeing a need for some work flow management tools and leverage of the e.i. QT Creator devl. environment like build and debugging, but Im not the best person to lead this.

**Comment by mhdawson** [comment]
We definitely want additional resources/docs blogs etc. to help people get up and running.  One Question -  Is it strictly tied to QT Creator.  A general resource that describes building addons with cmake would be interesting on its own and we might even setup a CI job to make sure we don't break that in-advertently.

We have discussed helping to surface share resources.  It might make sense to add a section to the README.md of this repo to list links to tutorials/resources like this @nodejs/addon-api what do you think?

**Comment by pcorner** [comment]
Dear Michael.
I'll be happy to help and thank you for driving this. I'll be speaking today on open robotics but I'll have some time later this week.
I'm improving my CMAKE and QT Cteator development setup and would like your feedback so I'll be sending this to you firstly
Secondly I have been surveying a lot around the subject here and found some great resources that I'll try to adjoin .
Great work
Best
Preben Hjorent.


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mhdawson** [comment]
I'm going to close this since there has not been a follow up in quite some time. Please let us know if you think that was not the right thing to do.
