### ISSUE TITLE
Help wanted : Passing large data between c++ addon and nodejs

### ISSUE THREAD

**Issue by veemex** [nodejs/node-addon-api#538]
Hi ! 

First of all thank you for this amazing project . 
I want to capture/create multiple images in the c++ addon and after that send this data as a Buffer to javascript using the "tsfn" function . Everything works all right, but  If I send an BMP it's size is ~10 MB , and it is sent at around 2.5 fps and the memory goes throught the roof . Can you recommend something ? 

Thank you !

**Comment by NickNaso** [comment]
Hi @veemex,
you are right using the buffer is not ideal, but if you are receiving a stream from your video source you can pass every single chunk of data to JavaScript. The idea is to use the Node.js Stream API to parse the data that canes from C++. 
You could see at this example, but I made only to understand some concepts so do not use my n production https://github.com/NickNaso/addon-stream 
Sorry but I’m out only with my phone and this is all that I can to help.

**Comment by veemex** [comment]
@NickNaso , Thank you for the instant reply :) . I will see and come back with what i've found.

**Comment by veemex** [comment]
@NickNaso , I have somewhat falsely identified this problem . The thing is that i was using my c++ addon in an electron application and for some reason when importing the module in the renderer process it is very slow to send data using the TSFN. I think the data is proxied first through the main process and it is very slow because of that. When i send data to the main process the send time is instant ~0 ms , which means the overhead is somewhere else . Anyway it would be very nice to have some documentation around this kind of questions (performance, datatypes , best practices etc...) . Thanks for all . Can I help contributing in some way ? Also this can be closed .

**Comment by NickNaso** [comment]
Hi @veemex,
sorry if I'm lazy to answer, but I'm in n vacation this week. Your contribution is really welcome. The N-API team has a meeting every monday through zoom https://zoom.us/j/363665824 . You can join us there are a lot of things to do. Hope to see you soon. 
You can find other information here: https://github.com/nodejs/abi-stable-node
