### ISSUE TITLE
Neutering ArrayBuffer

### ISSUE THREAD

**Issue by maierfelix** [nodejs/node-addon-api#541]
In v8, I see a method to [neuter/detach](https://v8docs.nodesource.com/node-0.12/d5/d6e/classv8_1_1_array_buffer.html) an ArrayBuffer. Is there a way to this in NAPI and also gets exposed here?

**Comment by mhdawson** [comment]
I think today the answer is no.  Is it part of the ES spec? We work to ensure that we avoid implementation-specific features which might not be available on all JavaScript runtimes?

If it is in the ES spec can you point us to the section in the spec?

**Comment by devsnek** [comment]
Neuter is a super super super old (that link is to node 0.12) method that is now better known as Detach: https://cs.chromium.org/chromium/src/v8/include/v8.h?l=4867&rcl=7720ac9d21ceeaa24715da66d11c0437010fbdee https://tc39.es/ecma262/#sec-detacharraybuffer

I agree this is a useful thing to have.

**Comment by mhdawson** [comment]
@devsnek same question then, is Detach part of the ES spec?

**Comment by devsnek** [comment]
@mhdawson yeah, second link there is the operation to detach an arraybuffer in the es spec.

**Comment by mhdawson** [comment]
@devsnek thanks for the pointers.  One more question. I can understand "useful" but wondering about how widely used it might be.  Do you think it would be widely used if available?

**Comment by devsnek** [comment]
In the ecosystem the operation exists for two reasons: 1) postMessage detaches arraybuffers that you pass to it, and 2) wasm memory is detached when it is resized. I can't really extrapolate that to anything specific, but I'm sure there are other use cases.

@maierfelix do you have a use case?

**Comment by maierfelix** [comment]
I found [this](https://github.com/cjbd/src/blob/91f69e5c58f5ba0fcf3df9195f437b338ec4bc60/third_party/blink/web_tests/webgpu/buffer_mapping.html#L313) test in webkit for webgpu buffer mapping. I work on a webgpu api for node and couldn't find a way to detach through napi, just by:

````js
let array = new Int8Array(new ArrayBuffer(100));
window.postMessage(array, "*", [array.buffer]);
````

**Comment by mhdawson** [comment]
We now have IsDetached() and Detach() support in N-API 7 closing.
