### ISSUE TITLE
Correct way to use Napi::Object with ThreadSafeFunction?

### ISSUE THREAD

**Issue by CraigMason** [nodejs/node-addon-api#542]
Hello,

I've been following the documentation and examples, which have been great.

My `ObjectWrap` class extends `EventEmitter` and creates instances of other `ObjectWrap`s (initialised in c++ from a hardware event).

At the point of making the callback, what is the correct means of transferring the newly created `Napi::Object` safely into the callback for the dispatch?

Also, is it at-all possible to use more than 1 value?

Thank you,

**Comment by gabrielschulhof** [comment]
I don't quite understand your question. Can you please illustrate with some source code?

**Comment by KevinEady** [comment]
I'm also not 100% sure what you mean @CraigMason ...

> At the point of making the callback, what is the correct means of transferring the newly created Napi::Object safely into the callback for the dispatch?

There are two steps of the total end-to-end flow where you can pass optional data:
- First, when executing the `callback` provided to `BlockingCall`/`NonBlockingCall`: this receives a pointer to your _C++ data object_ (the `DataType* data)`. This callback runs on the main thread, allowing you "transform" your C++ objects represented by `data` into JavaScript values.
- Second, the above callback _also_ receives the original javascript `Function callback` that you created the TSFN with. Now you can call this function via one of the [`callback.Call()`](https://github.com/nodejs/node-addon-api/blob/master/doc/function.md#call) implementations, passing to it your "transformed" objects as valid JavaScript values.

> Also, is it at-all possible to use more than 1 value?

If by the "1 value" you mean one `DataType*` parameter when using [BlockingCall/NonBlockingCall](https://github.com/nodejs/node-addon-api/blob/master/doc/threadsafe_function.md#blockingcall--nonblockingcall) ... Unfortunately you can only have one parameter here. The node-addon-api is just a wrapper around C napi, and uses the underlying [n_api_napi_call_threadsafe_function](https://nodejs.org/api/n-api.html#n_api_napi_call_threadsafe_function) method, which accepts only one parameter.

Does this help? Of course if you post some code we can probably help more concretely.

**Comment by CraigMason** [comment]
Thank you both for the quick reply. I'll try and get en example code block over shortly, but you've mostly answered it.

I had an `Napi::Array` created *outside* of the callback, but this quite obviously could be moved into the TSFN callback (actually, it should be anyway given that should happen on main thread). I was previously trying to pass some other pointers across threads, and doing some other things with the captures. 

One further point - the `Napi::Env`. I believe we are not supposed to store a reference to `napi_env` anywhere. But it looks like `node-addon-api` does indeed keep a copy of it. 

When my hardware callback happens from c++, I have no `Napi::CallbackInfo`, and thus have no `env`. So, I am using `Env()` which I pulled from the examples. Is that the correct place to grab `Napi::Env` from?

Thank you,

**Comment by gabrielschulhof** [comment]
@CraigMason there are specific circumstances under which you have no choice but to retain `napi_env`. For example, if you had a callback on the main thread coming in from an outside library, you would have no choice but to pass the `napi_env` when attaching the callback, and accepting it back when the callback gets called, so you might then make N-API calls.

The thread-safe function's implementation also keeps a copy of the environment internally, however, the thread-safe function's implementation is under our control, so we could and would have to modify it along with any changes we make to the `napi_env`'s life cycle.

The documentation's intent is to get developers to avoid retaining it arbitrarily, because we would like to retain some control over the `napi_env`'s life cycle.

**Comment by CraigMason** [comment]
> For example, if you had a callback on the main thread coming in from an outside library, you would have no choice but to pass the napi_env when attaching the callback, and accepting it back when the callback gets called, so you might then make N-API calls.

That's exactly what I have in one scenario. I am extending `EventEmitter` as per [this example](https://github.com/nodejs/node-addon-examples/blob/master/inherits_from_event_emitter/node-addon-api/src/native-emitter.cc). However, that example has the `emit` method originating from a JS-invoked call.

In my instance, this is coming from a `c` callback, so I need an `env`, and I also need to ensure `this` is correctly bound on the function. I am doing this in my class `Init` function:

```cpp
Napi::Function emit = info.This().As<Napi::Object>().Get("emit").As<Napi::Function>();
Napi::Function bound = emit.Get("bind").As<Napi::Function>().Call(emit, { info.This() }).As<Napi::Function>();
this->_emitRef = Napi::Reference<Napi::Function>::New(bound, 1);
```

Then later, in my C callback:

```cpp
Napi::Function emit = this->_emitRef.Value().As<Napi::Function>();
Napi::Object myObj = Napi::Object::New(Env());
// Prepare some args..
emit.Call(args); 
```

Should I be using `Env()`, or perhaps `this->_emitRef.Value().As<Napi::Function>().Env()` ?

Thank you,

**Comment by gabrielschulhof** [comment]
> Should I be using `Env()`, or perhaps `this->_emitRef.Value().As<Napi::Function>().Env()` ?

I would say the latter is better, since the `napi_env` has already been saved for you.

**Comment by CraigMason** [comment]
Great, thank you.
