### ISSUE TITLE
String::Concat functionality

### ISSUE THREAD

**Issue by sampsongao** [nodejs/node-addon-api#55]
Do we have any plan to implement String::Concat function?

**Comment by jasongin** [comment]
No plans. Obviously this can be done externally if needed. I guess it might be convenient to be part of the API? I don't see any string concat APIs in either V8 or ChakraCore, so there would be no performance benefit to adding it to the C API.

**Comment by NickNaso** [comment]
I started working on a module that extends `Napi::String` and  add some method like `String::Concat`. Here you can find the repo: https://github.com/NickNaso/stringn. I will updated the issue when I will finish the work.

**Comment by mhdawson** [comment]
There has been no progress on this in quite some time I'm going to close. Please let us know if you think that was not the right thing to do.
