### ISSUE TITLE
Question about ObjectWrap

### ISSUE THREAD

**Issue by marco-ms** [nodejs/node-addon-api#553]
I have read about this example:
https://github.com/nodejs/node-addon-examples/blob/master/7_factory_wrap/node-addon-api/myobject.cc

I still have to see a good example on how I could construct a wrapped object passing a c++ class instance reference that doesn't come from JavaScript.
Example:
1. JS calls a method on the node module
2. node module creates class A in the stack via async operation
3. node creates WA which is a ObjectWrap<WA>, node code would like to pass A to WA
4. node returns WA to JS

The problem here is 3, as it seems the constructor accepts only Napi::Value(s) squeezed into Napi::CallbackInfo and regular class instances has to go through extra layer of wrapping using Napi::External which however uses pointers *not* references.

So the question is, how is it possible to pass to a Napi::ObjectWrap class some C++ object by reference that doesn't come necessarily from JavaScript?

I tried to extend the constructor to accept class A as an extra parameter, but clearly node-addon-api ain't happy about it, throwing:
`MyObject::{ctor}': constructor initializer lists are only allowed on constructor definitions`

Any way to pass A to WA? There must be an obvious way that I am missing at the moment.

**Comment by marco-ms** [comment]
@mhdawson any hint here? Thank you!

**Comment by KevinEady** [comment]
So @marco-ms if I understand you correctly...

You have to be _on_ a node thread in order to construct a value that is usable in JS

> 2. node module creates class A in the stack via async operation
> 3. node creates WA which is a ObjectWrap, node code would like to pass A to WA

What are you using to perform your async operation? At some point, when you return to the node thread, you need to use `constructor.New({ ... })` , passing in JS values constructed by transforming your C++ data.

**Comment by mhdawson** [comment]
Does this fit your pattern?

1) Create your class which extends Napi::ObjectWrap and includes a field called A
2) Include a method called "setA()" which accepts A and stores it the field called A


Now the data in A will only be usable in native C++ methods in the wrapped object.  If you want to use that data from JS you will either need to convert it to JS objects.  Additional methods on the wapped object could get the data from A, use the appropriate N-API/node-addon-api methods to convert them to JavaScript objects and return those JavaScript objects.  That or pre-extract from A as opposed to getting them from A.  If the contents of A can be changed be a thread other than the main thread it would probably be better to look at the thread safe functionality: https://github.com/nodejs/node-addon-examples/tree/master/thread_safe_function_round_trip/node-api

**Comment by marco-ms** [comment]
> Does this fit your pattern?
> 
> 1. Create your class which extends Napi::ObjectWrap and includes a field called A
> 2. Include a method called "setA()" which accepts A and stores it the field called A

Yes, we ended up doing exactly like this, before reading your comment. Thanks for confirming.

**Comment by mhdawson** [comment]
@marco-ms can we close this issue?
