### ISSUE TITLE
Automatic generation of N-API wrapper from a C++ library

### ISSUE THREAD

**Issue by BotellaA** [nodejs/node-addon-api#554]
I am not sure if this is the right place but I created a project to generate a node addon using `node-addon-api` and I wanted to let you know about it. It is based on [nbind](https://github.com/charto/nbind) template strategy but using N-API.
Here is the repo https://github.com/Geode-solutions/genepi.

**Comment by NickNaso** [comment]
Thanks for sharing. It's always great see new projects that uses N-API and `node-addon-api`.  Well done @BotellaA .

**Comment by gabrielschulhof** [comment]
@jschlight you have a similar project in the works based on clang and AST analysis, right?

**Comment by mhdawson** [comment]
@BotellaA thanks for the heads up.  I'm wondering if you can share any info on where/how you are using so far?

**Comment by BotellaA** [comment]
@mhdawson of course! 

Our core project is [`OpenGeode`](https://github.com/Geode-solutions/OpenGeode), a C++ framework (made of several programming libraries) for representing and manipulating geometric models. In order to provide a GUI to this framework, we developed an `Electron` app. `Genepi` is used to create an addon for each framework library. These addons are dynamically loaded in the `Electron` app which offers command dialogs to execute the C++ framework features. All these projects are not accessible yet but will be by the end of the year.

Another use of `genepi` is C++ scriptability using JS. This allow quick prototyping.

**Comment by tofutim** [comment]
@BotellaA Arnaud, is there a list of outstanding issues for genepi?

**Comment by BotellaA** [comment]
@tofutim There is no such list. At the moment, it works very well for everything that I need which is to have a node interface of my other big project. I am working a lot on this other project right now. Feel free to participate to genepi!

**Comment by mhdawson** [comment]
Since this was an FYI, I think it can now be closed. Please let us know if that was not the right thing to do.
