### ISSUE TITLE
Enable travis ci for PRs

### ISSUE THREAD

**Issue by legendecas** [nodejs/node-addon-api#555]
With https://github.com/nodejs/node-addon-api/pull/534 landed on master, Travis ci could be enabled by someone with permissions to fast check new PRs.

Though I have no idea about this process on Node.js org repos.

@mhdawson maybe you could comment on this?

**Comment by mhdawson** [comment]
Ok, opened https://github.com/nodejs/admin/issues/417.

If there are no objections I can enable next week.

**Comment by mhdawson** [comment]
Enabled earlier today as commented in #417, closing.
