### ISSUE TITLE
Access parents env

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/node-addon-api#559]
I did not find a way to do this but I might be missing something.

If I have some js call like this:

```js
function A() {
  const x = 1;
  B();
}
```
and somewhere else, I define `B` that is calling a N-API native module.
Is there a way to access the napi_env that I would have got if `A` was calling the native module.

Or in other terms, is it possible to have the `napi_env` of something higher in the call stack?

**Comment by addaleax** [comment]
@vdeturckheim `napi_env` is not bound to call stack frames in any way … can you maybe expand a bit on what you’re looking for? Do you want the `napi_env` of an N-API *module* that has a function active higher up on the call stack?

**Comment by vdeturckheim** [comment]
@addaleax I was afraid it would be that way.

I am trying to intercept calls to `eval` and I was thinking about using `n_api_napi_run_script` to re-implement `eval` and use the original scope despite my monkeypatch.

In that case (compared to my example), `B` would be monkeypatched `eval` but it can't access `x`.

**Comment by addaleax** [comment]
@vdeturckheim Sorry, but yeah, `napi_env` is a fixed per-module structure and contains no information about JS variables or anything like that, and `napi_run_script()` works more like `require(...)`, i.e. has no access to any kind of outside scope.

For your use case, the [inspector API](https://nodejs.org/api/inspector.html) might be the best idea I’d have – it does allow synchronous read/write access to call stack frames.

**Comment by vdeturckheim** [comment]
Thanks @addaleax ! That's a very helpful clarification!

Indeed I looked this way but it has a performance impact a bit too big for me.
