### ISSUE TITLE
ThreadSafeFunction vs mutex

### ISSUE THREAD

**Issue by felipezacani** [nodejs/node-addon-api#560]
Hi,

I'm implementing a system using a node addon that loads a DLL. The DLL creates multiple threads. The threads get a pointer to a function implemented in the addon. This function receives a string and calls a javascript function (previously stored in a persistent reference), passing this string.

I was a little naive to test all this functionality and implemented it without thinking about thread safety, so now I believe I'm getting node crashes because of repeated calls to this function. Due to the complexity I would add to the whole logic by using ThreadSafeFunction, especially because I don't have total control over the DLL code, I'm considering using a mutex to isolate the calls to the JS function.

Any thoughts on this? Considering my use case is very simple (sending a string, returning a string), do you consider my approach safe?

Thanks!

**Comment by KevinEady** [comment]
Hi @felipezacani ,

The threadsafe function itself is thread-safe, in the sense that you do not need to "use a mutex to isolate the calls to the JS functions". Each thread that wants to call the function has its own access to it (via `Acquire()`) and when it's finished releases it (via `Release()`)

Does this help?

**Comment by felipezacani** [comment]
Hey @KevinEady thanks for the input.

Let me give you more details: the DLL is built by an ancient compiler, using the "Embarcadero C++ Builder" IDE. I can make small changes to it, but I'm avoiding it at all costs. It won't compile anything more advanced than Cpp11, and I already found bugs using Cpp11. So, my first choice was just giving it a function pointer. I don't have any control over its threads or the exact time/frequency of callback calls. 

The way I see, I could add thread-safety using TSFN in the addon side. However, I'm not certain about how to control the necessary resources, like when should I release the tsfn? I know I could send a signal from, say, a destructor inside the DLL (joining all the threads), but then again, its unnecessary complexity in my opinion. So, in theory, isn't a simple mutex the best solution for this? Or are there any other hidden variables I should consider in the addon -> node calling mechanism?

**Comment by felipezacani** [comment]
@KevinEady 
Thanks for your insight on this, it helped me to understand the problem as a whole. I'm implementing the solution with TSFN. The DLL creates "instances" of a class creating threads. This class has a destructor and this is the "i am done" I need, for all its threads. 

> Furthermore, since you are requesting to run JS code from another thread, the call will be asynchronous.

This is the "dangerous" part. I have two possible scenarios here: in the first, I'm in the same node thread: node sends the DLL a JSON containing a command. The DLL executes it, in the same thread, and returns. While it is executing the command, it could use the callback for running queries on the server (still the same thread). The second scenario is the DLL uses the callback reporting an alarm in the network (a random event). In this case, I don't need a reply, so, async is not really a problem (I'm just sending the alarm data to the server).

I'm leaving this open so I can post details of my solution here.

**Comment by felipezacani** [comment]
@KevinEady 
Could you share some light on this? I implemented a manual sync for the response to the function, but the problem is actually "callback" is not executed at all. tsfnStatis is ok afer "BlockingCall".

```
const char *driverCallback2(const char *jsonData)
{
  spdlog::debug("driverCallback2: {}", jsonData);
  std::string* serverResponse = new std::string("");
  std::thread callbackThread = std::thread([jsonData, serverResponse] {
    std::promise<std::string> *responsePromise = new std::promise<std::string>();
    std::future<std::string> responseFuture = responsePromise->get_future();
    auto callback = [responsePromise](Napi::Env env, Napi::Function jsCallback, const char *value) {
      spdlog::debug("callback");
      Napi::Value strResponse = jsCallback.Call({Napi::String::New(env, value)});
      responsePromise->set_value(std::string(strResponse.ToString().operator std::string()));
    };
    napi_status tsfnStatus = g_tsfn.BlockingCall(jsonData, callback);
    if (tsfnStatus != napi_ok)
    {
      spdlog::error("Error calling ThreadSafeFunction with data: {}", jsonData);
      return "";
    }
    spdlog::debug("BlockingCall = napi_ok");
    serverResponse->append(responseFuture.get());
    delete responsePromise;
  });
  callbackThread.join();
  return serverResponse->c_str();
}
```

**Comment by KevinEady** [comment]
Hmmm @felipezacani ,

When you say `callback` is never executed... Is your process finishing at all? Or is it hanging because `responseFuture.get()` blocks the new thread, meaning `callbackThread.join()` would block as well?

**Comment by felipezacani** [comment]
@KevinEady if I remove responseFuture.get(), nothing changes (except, of course, the thread finishes and the function returns an empty value). The "callback" log never shows up. I also got the exact same behavior without using a thread. By the way, I have another log line in the server, it should also show up when "jsCallback.Call" is executed (just in case you wonder if my log is working in the callback).

BTW, this is my "initialization" function, creating the TSFN:

```
Napi::Value extSetHandler2(const Napi::CallbackInfo &info)
{
  spdlog::debug("extSetHandler2");
  Napi::Env env = info.Env();
  g_tsfn = Napi::ThreadSafeFunction::New(
      env,
      info[0].As<Napi::Function>(), // JavaScript function called asynchronously
      "OrB",                        // Name for debug purposes
      0,                            // Unlimited queue
      1,                            // Only one thread will use this initially (not fixed)
      [](Napi::Env) {               // Callback called when the tsfn is released (destroyed)
        spdlog::info("ThreadSafeFunction is being released...");
      });
  return Napi::Boolean::New(env, true);
}
```

**Comment by KevinEady** [comment]
Are you calling `callbackThread.join();` on the main thread? If so, I believe this will block the event loop from processing the call queue for the TSFN.

In all the implementations I've seen, `thread.join()` goes in the TSFN's finalizer, see https://github.com/nodejs/node-addon-api/blob/master/test/threadsafe_function/threadsafe_function.cc#L119

**Comment by felipezacani** [comment]
@KevinEady  yes, the problem seems to be, in my test case, that I am in the main thread. However, even unlocking everything (removing thread.join() and not waiting for the promise), I still don't get to the callback code. Could this be related to the execution environment, somehow?

And I foresee another challenge ahead: I believe there is no way to sync this by "brute force", waiting for the result, without locking the main thread, thus locking node from responding. But... one problem at a time :)

**Comment by felipezacani** [comment]
@KevinEady  one more thing I'd like to have a better understanding on this subject is: my original implementation simply didn't consider the fact that I wouldn't be able to call anything in node from other threads. So, it was working, until I tried to do that. How did this work? Because I called a function from node, sending a command. While processing this command (in my driver DLL), I made several calls using a simple JS callback, a persistent function reference (NOT thread safe). All the calls ran and received the proper replies from node. This all happened in the main thread.

**Comment by KevinEady** [comment]
Hi @felipezacani ,

If I understand your original implementation correctly, you invoked your code synchronously on the main thread via some initial JS call into your node addon. If you continued synchronously running , it doesn't really matter _where_ the execution of code happens, whether it is in your addon cpp or the linked DLL. The call stack doesn't really _escape_ anything you control:

The initial JavaScript call -> node/v8 engine -> your native node addon -> your DLL performs several sync calls 

If this was your original implementation [correct me if I'm wrong], then it makes sense that it would work, as you are just passing data around to different parts of your own code _before_ it goes back up to the engine to possibly invalidate any values (garbage collection, env cleanup, ...) 

You need to use `Reference`s once you start having more complicated call-stacks. For example, the [`ObjectWrap` example](https://github.com/nodejs/node-addon-api/blob/master/doc/object_wrap.md#example) uses a reference for the constructor. The module initializer method creates a new `Value` that must persist across calls.

Once you start wanting to call JS from within your C++ code, that's when you need to use something like [`AsyncWorker`](https://github.com/nodejs/node-addon-api/blob/master/doc/async_worker.md) (initiate task on main thread, task executes on worker thread, task notifies node thread of success/failure) or [`ThreadSafeFunction`](https://github.com/nodejs/node-addon-api/blob/master/doc/threadsafe_function.md) (initialize tsfn on main thread, share access to tsfn with other threads, other threads async call into node via tsfn)

Does this make sense?

**Comment by felipezacani** [comment]
@KevinEady Perfect observations.

I'm resuming the implementation using ThreadSafeFunction and it was also a bonus to get interested in AsyncWorker, as I learned it will be very useful in the future. 

As I tried to use ThreadSafeFunction for the first time, my mistake was to think I would be able to use it for all my node calls. As I have two very different situations - the main thread sync calls and the different thread async calls, all I need to do now is implement two callbacks and use them accordingly. 

My main thread sync calls are used to retrieve configuration data and parameters for the driver DLL - they need to be replied by the server synchronously. The other calls will be made by network reading threads, to report equipment alarms, for example. They do not require an answer from the server.

**Comment by felipezacani** [comment]
Hey @KevinEady , I had some complications on my side and they delayed the implementation of a solution using ThreadSafeFunction. Everything is done now and apparently works (callback is called and the js function is executed). However, I just bumped into:
```
c:\ws\src\node_api.cc:1064: Assertion `(func) != nullptr' failed.`
```
This message shows up in my node server log, after the function is executed (it just returns an empty string).
I've been trying to find more about this during this afternoon without any success. Any thoughts?

**Comment by KevinEady** [comment]
I am guessing it's this error https://github.com/nodejs/node/blob/4187fcb2001581004280685e78ab0f249d8347e7/src/node_api.cc#L1064 which would only occur if you are calling `[Non]BlockingCall` on a `ThreadSafeFunction` wrapper that holds an invalid (ie. null) `napi_threadsafe_function` reference. Does this help at all?

**Comment by felipezacani** [comment]
Thanks again, @KevinEady 
There was a bug causing my initialization to split in a condition that wouldn't create the TSFN instance. 

It's basically working now. The only remaining challenge is to return a value to the thread waiting for it. I tried using std::promise, however, passing the promise to the callback seems to be impossible (since I have to use the lambda function reference list []). If I try to use the promise inside the callback, it ends up with an access violation (and the debugger seems to be unable to go in there).

**Comment by KevinEady** [comment]
Yeah @felipezacani you may need to use smart pointers to manage data lifecycle?

**Comment by gabrielschulhof** [comment]
There is an [example](https://github.com/nodejs/node-addon-examples/tree/master/thread_safe_function_round_trip/node-api) illustrating a TSFN round trip call.

**Comment by KevinEady** [comment]
Hi @felipezacani ,

Anything we can do to move this issue further?

**Comment by felipezacani** [comment]
> 
> 
> Hi @felipezacani ,
> 
> Anything we can do to move this issue further?

Hi @KevinEady , sorry, I totally forgot to close this issue. In the end, my last promise problem was caused by binary incompatibility. The driver I *have* to use is built by C++ Builder, and the node addon is built by msvc 2019. This makes it impossible to send (and use) a promise object from one to the other. So, what I did was to send a pointer to the promise. When the Addon finishes the async call, it calls a driver function, with any returning data and the promise pointer (since its still valid in the driver mem area).

I owe you big time on this one, I'm using this solution everyday now and its working like a charm. Thanks a lot!

Here is the final working function (still have to add some error handling, I know), might be helpful, who knows :)
```

void driverCallbackThread(const char *jsonData, std::promise<const char *> *asyncResponse)
{
    spdlog::debug("driverCallback2: {}", jsonData);
    auto callback = [asyncResponse](Napi::Env env, Napi::Function jsCallback, const char *value) {
        spdlog::debug("Running the ThreadSafeFunction callback...");
        Napi::Value strResponse = jsCallback.Call({Napi::String::New(env, value)});
        spdlog::debug("Server response to the callback: {}", strResponse.ToString().operator std::string().c_str());
        auto drv = g_drivers.begin();
        std::string driverResponse;
        drv->second->promiseCallback(asyncResponse, strResponse.ToString().operator std::string().c_str());
        spdlog::debug("promise->set_value done!");
    };
    napi_status tsfnStatus = g_tsfn.BlockingCall(jsonData, callback);
    if (tsfnStatus != napi_ok)
    {
        spdlog::error("Error calling ThreadSafeFunction with data: {}", jsonData);
    }
    spdlog::debug("BlockingCall = napi_ok");
}
```
