### ISSUE TITLE
HandleScope question

### ISSUE THREAD

**Issue by marco-ms** [nodejs/node-addon-api#564]
I apologize for the many issues I open with questions. Feel free to close this once clarified.
I read that HandleScope should prevent objects created in its life time to be garbage collected.
What happens though on different threading? Let's make an example assuming `SomeAsyncFunctionWithCallback` spawns a worker thread to do some work and call back the code with `SomeResult` and `DispatchToMainThread` goes back to the main thread. We haven't used `ThreadSafeFunction` because they are available only on N-API > 3.
If I capture `env` rather than `scope` does that mean that the Deferred created in that scope may be garbage collected by the time we call Resolve/Reject or maybe when `scope` goes out of scope and `napi_open_handle_scope` is called by its destructor, it'll fail and then leak memory?

So I wonder if instead I should capture `scope` rather than `env` and get env from `scope->Env()`
Answer may be obvious and maybe I missed some part of the documentation that says it, but asking anyway, maybe there is a way to clarify the docs even more.

```
Napi::Value MyFunction(const Napi::CallbackInfo &info) {
    Napi::Env env = info.Env();
    Napi::HandleScope scope(env);
    Napi::Promise::Deferred deferred = Napi::Promise::Deferred::New(env);

    SomeAsyncFunctionWithCallback([env, deferred](SomeResult *result) {
        auto callback = [env, deferred, result]() {
            if (result && result->IsSuccess()) {
                deferred.Resolve(Napi::Boolean::New(env, result->SomeFlag());
            } else {
                deferred.Reject(Napi::String::New(env, "Failed"));
            }
        }
        DispatchToMainThread(callback);
    });
    return deferred.Promise();
}
```

**Comment by legendecas** [comment]
Type `napi_deferred` is not an ordinary `napi_value` that its lifetime is delegated to handle scopes. `napi_deferred` would only be released by `napi_resolve_deferred()` or `napi_reject_deferred()`. So using `napi_deferred` out of the creating scope is safe as long as it has not been fulfilled yet.

HandleScope should not be captured to another execution stack AFAIK, though it's valid operation.

**Comment by marco-ms** [comment]
> Type `napi_deferred` is not an ordinary `napi_value` that its lifetime is delegated to handle scopes. `napi_deferred` would only be released by `napi_resolve_deferred()` or `napi_reject_deferred()`. So using `napi_deferred` out of the creating scope is safe as long as it has not been fulfilled yet.

Thanks, I now recalled reading the code, but clearly not stated in the documentation (requires reading code and understanding how napi works too):
https://github.com/nodejs/node-addon-api/blob/master/doc/promises.md

> HandleScope should not be captured to another execution stack AFAIK, though it's valid operation.
Is there a side effect?

**Comment by legendecas** [comment]
> I now recalled reading the code, but clearly not stated in the documentation.

It's documented in [n-api docs](https://nodejs.org/docs/latest/api/n-api.html#n_api_promises). It might be stated in doc of node-addon-api too.

> Is there a side effect? Is the above code correct or a new HandleScope should be created inside the callback?

Yes, there would be a runtime error if a handle scope been closed twice (which happens on the destructor of HandleScope). A new scope shall be opened in the callback with `CallbackScope`.

**Comment by marco-ms** [comment]
> Yes, there would be a runtime error if a handle scope been closed twice (which happens on the destructor of HandleScope). A new scope shall be opened in the callback with `CallbackScope`.

Sorry I may not have understood correctly, are you saying I should capture info in the lamdba and have one more `HandleScope scope(info.Env())`?

**Comment by marco-ms** [comment]
@legendecas ok you are talking about this doc (which maybe should also be linked from the Promises doc?)
https://github.com/nodejs/node-addon-api/blob/master/doc/callback_scope.md

It has two ctors and they accept as 2nd parameter:
```[in] scope: The pre-existing napi_callback_scope or Napi::CallbackScope.```
```[in] async_context: The pre-existing napi_async_context or Napi::AsyncContext.```

I tried to look for the examples, none seems using this.
I am modifying the code to understand if this is the right way to use this?
```
Napi::Value MyFunction(const Napi::CallbackInfo &info) {
    Napi::Env env = info.Env();
    Napi::HandleScope scope(env);
    Napi::Promise::Deferred deferred = Napi::Promise::Deferred::New(env);
    Napi::AsyncContext asyncContext(env, "async_context");

    SomeAsyncFunctionWithCallback([env, deferred, &asyncContext](SomeResult *result) {
        auto callback = [env, deferred, result, &asyncContext]() {
            Napi::CallbackScope scope(env, asyncContext);
            if (result && result->IsSuccess()) {
                deferred.Resolve(Napi::Boolean::New(env, result->SomeFlag());
            } else {
                deferred.Reject(Napi::String::New(env, "Failed"));
            }
        }
        DispatchToMainThread(callback);
    });
    return deferred.Promise();
}
```

**Comment by marco-ms** [comment]
Nope, this code is crashing with message:
```Exit code: 3221225477```

Clearly is the not right way to do this.

**Comment by rolftimmermans** [comment]
I believe you need to create `HandleScope` before creating a `CallbackScope` if you create any new JS objects/values (in your example booleans/strings).

**Comment by marco-ms** [comment]
> I believe you need to create `HandleScope` before creating a `CallbackScope` if you create any new JS objects/values (in your example booleans/strings).

Thanks, although I am still trying to understand if I also need CallbackScope and then what shall I pass it? I don't see CallbackScope used anywhere, not even by AsyncWorker, which indeed creates a new HandleScope under OnOK() in this example
https://github.com/nodejs/node-addon-examples/blob/master/async_pi_estimate/node-addon-api/async.cc

**Comment by gabrielschulhof** [comment]
@marco-ms you need a `CallbackScope` when the call stack leading up to the place where you must call into JavaScript does not have any JavaScript frames on it.

So, you would use a `CallbackScope`, for example, in an event loop handler.

**Comment by mhdawson** [comment]
Going to close this since it has been over a year since Gabriel's last suggestion. Please let us know if that is not the right thing to do.
