### ISSUE TITLE
Web Assembly

### ISSUE THREAD

**Issue by bsrdjan** [nodejs/node-addon-api#574]
Considering [Web Assembly support coming to NodeJS](https://www.joyent.com/blog/improved-wasm-support-coming-to-node), what could be the relevance/impact for N-API C++ add-ons and external lib wrappers? What would be benefits of porting NAPI add-on to WASM, some time in the future?

**Comment by devsnek** [comment]
I have some stuff that runs napi add-ons compiled to wasm. the main holdups are anyref and wasi.

**Comment by bsrdjan** [comment]
Could you please briefly describe the approach/toolchain for porting napi add-on wrapper of external c/c++ lib? 

To my understanding the external lib shall be ported first, using [emscripten](https://emscripten.org/) probably ?

**Comment by devsnek** [comment]
@bsrdjan compiling with clang+https://github.com/CraneStation/wasi-libc usually works.
