### ISSUE TITLE
N-API function to check a given napi_value of type napi_number is an integer or decimal

### ISSUE THREAD

**Issue by msatyan** [nodejs/node-addon-api#578]
This could be a feature request  

Please, we would like to have N-API function to check a given **napi_value** of type **napi_number** is an **integer** (a whole number) or **decimal** (a number with fractional value). Absence of this API can break the application code in different environment. 

Let us consider a scenario where we are calling a native addon function **f1()** from JavaScript by passing a JavaScript object as argument as shown in the snippet.

```
let obj = { n1: 123, n2: 123.45 };
myaddon.f1( obj );
```

The native function **f1()** want to extract value associated with the keys **n1** and **n2** by calling the best fit (c datatype) value extraction N-API function. For example to extract value of **n1** it may be good to use one of **napi_get_value_int*** and similarly for the **n2** the **double** is a better choice.

```
napi_get_value_double
napi_get_value_int32
napi_get_value_uint32
napi_get_value_int64
```
Unfortunately I could not find any N-API function to verify the derivative of napi_number property.

- [Here is the same scenario that I posted for help on StackOverflow](https://stackoverflow.com/questions/58586425/how-to-check-a-napi-value-of-type-napi-number-is-an-integer-or-decimal-by-using)

Thanks in Advance !!!
- Satyan

**Comment by legendecas** [comment]
While handling numbers with JavaScript, it is important to know that all [numbers](https://tc39.es/ecma262/#sec-terms-and-definitions-number-value) in JavaScript are [double-precision 64 bit IEEE 754](https://en.wikipedia.org/wiki/Floating-point_arithmetic) values (despite some engines like v8 might have additional represents on small integers, there is no such definition in ECMA spec and no way to determine these types of number in JavaScript). 

`napi_get_value_{double,int32,uint32,int64}` just convert these value to its desired one. There might be a precision loss in the conversion. If a determined number is required in the case, use [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) instead.

**Comment by msatyan** [comment]
Thanks very much, this information is very useful and good enough for me to proceed.
