### ISSUE TITLE
VS 2013 Support

### ISSUE THREAD

**Issue by mateodelnorte** [nodejs/node-addon-api#58]
Hi all. This issue is for VS 2013 support. 

I've got a client who has a number of 3rd party libraries that only compile under VS 2013. This is a continuation of https://github.com/nodejs/node-addon-api/issues/56. There are some additional notes there. 

Here's a gist of the build errors I get when building with `--msvs_version=2013`: https://gist.github.com/mateodelnorte/7ea8c72e3b2b664ba37da7a0e6ed6dd8. 

Thx

**Comment by mateodelnorte** [comment]
Looks like this issue quickly pooled some +1's. Any ideas on ETA of a PR landing? Trying to prioritize whether I should wait for this, or chug ahead using nan.

**Comment by nschonni** [comment]
I'm not sure if node-gyp still supports 2013 https://github.com/nodejs/node-gyp#option-2

**Comment by mateodelnorte** [comment]
I'd be *very* surprised if that was the case: https://github.com/nodejs/node-gyp/blob/f6eab1f9e4b160b60b2736bb01a09c83785ba979/gyp/pylib/gyp/MSVSVersion.py#L228-L255

Those are just default instructions for getting running.

**Comment by kfarnung** [comment]
@mateodelnorte I'm taking a look this, but I don't have a timeline for support.  I'll let you know when I have some further information.

**Comment by mateodelnorte** [comment]
awesome @kfarnung. thanks!

**Comment by kfarnung** [comment]
@mateodelnorte I think we're pretty close now, take a look at PR #65.

**Comment by mateodelnorte** [comment]
Fantastic! Thanks @kfarnung

**Comment by jasongin** [comment]
Merged as https://github.com/nodejs/node-addon-api/commit/617dbb69776fa937e6d4d2f7fba1580d7319e613, and published to npm as `node-addon-api@0.3.5`

**Comment by vijaykumbhani** [comment]
Hi  @jasongin 

as per comments, you have fixed the issue at [617dbb6](https://github.com/nodejs/node-addon-api/commit/617dbb69776fa937e6d4d2f7fba1580d7319e613). 
can you please say, will this fix include on **node-addon-api 3.1.0** later version? 
if yes then what will be the approx date of a new version of **node-addon-api 3.1.0**
Waiting for a reply from your end
