### ISSUE TITLE
Threads limit when using concurrent AsyncWorker ?

### ISSUE THREAD

**Issue by tomerb78** [nodejs/node-addon-api#598]
I'm using AsyncWorker to make very long (~60 min) c++ cpu intensive processing operation, expecting for callback on finish.
Doing that by calling a blocking c++ function from  the Execute() function and calling the JS callback from OnOk function.

The Node.JS process is calling this function concurrently for many processing tasks at a time, expecting for a callback for process job that is finished.

works great on 1-4 concurrent function calls while it utilize 1 thread on 100% cpu usage for each function call.
Above that (5 and more) -  only 4 cpus are fully utilized and the rest available cpus are idle. So I can see max of 400% cpu utilization even though I have more free cpus.

Is there any thread usage limitation?
Is something wrong with how I described that I use AsyncWorker? 

Thanks!

**Comment by KevinEady** [comment]
Hello,

Try increasing https://nodejs.org/api/cli.html#cli_uv_threadpool_size_size
, default is 4 so I guess that makes sense if you see  problems at 5+

**Comment by KevinEady** [comment]
Hello,

Try increasing https://nodejs.org/api/cli.html#cli_uv_threadpool_size_size , default is 4 so I guess that makes sense if you see  problems at 5+

**Comment by tomerb78** [comment]
Thanks @KevinEady ! that was the missing part...
