### ISSUE TITLE
Avoid extra memory allocation with templates

### ISSUE THREAD

**Issue by dmitryash** [nodejs/node-addon-api#602]
I suppose that it is possible to add methods in the following way to avoid extra memory allocation: 

Example:

```cpp
template <class T> 
class ObjectWrap {
    using MethodType = Value (T::*)(const CallbackInfo &info);

    template <MethodType method>
    static auto ObjectWrap<T>::InstanceMethod2(const char* utf8name) -> ClassPropertyDescriptor<T>; 
};

template <typename T>
template <typename ObjectWrap<T>::MethodType method>
inline auto ObjectWrap<T>::InstanceMethod2(const char* utf8name) -> ClassPropertyDescriptor<T>  {
    napi_property_descriptor desc = {};
    desc.utf8name = utf8name;
    desc.method = [](napi_evn env, napi_callback_info args) {
        return details:;WrapCallback([&]{
            CallbackInfo cb_info(env, args);
            T* instance = Unwrap(cb_info.This().As<Object>());
            return (instance->*cb)(callbackInfo);
        });
    };
    return desc;
}

// How to use
class Test: public Napi::ObjectWrap<Test> {
public:
    static auto define_class(Napi::Env env) -> Napi::Function {
        return DefineClass(env, "Test", {
            InstanceMethod2<&Test::get_value>("get_value");
        });
    }

    auto get_value(const Napi::CallbackInfo &args) -> Napi::Value;
};
```

**Comment by gabrielschulhof** [comment]
This does indeed work, and avoiding a memory allocation is definitely worth it. I'm not sure how to incorporate this, though. We should probably phase out the existing instance methods and accessors.

**Comment by dmitryash** [comment]
Let me take it

**Comment by gabrielschulhof** [comment]
@dmitryash we discussed this during today's team meeting. The best approach is to add an alternate set of methods to `ObjectWrap<T>` and encourage their use over the existing methods. We can deprecate the existing methods and eventually remove them. Not sure what the name should be though – `InstanceMethod2()` does not seem too expressive. OTOH `TemplatedInstanceMethod()` is way too long of a name. I dunno ... `InstanceMethodT()` 🤷 😕

**Comment by gabrielschulhof** [comment]
@dmitryash so if you would like to do a PR, then please, go right ahead 🙂
