### ISSUE TITLE
Number constructor with more types

### ISSUE THREAD

**Issue by fanatid** [nodejs/node-addon-api#606]
Currently [Number](https://github.com/nodejs/node-addon-api/blob/master/doc/number.md) can be constructed only from `double` (`int32`, `uint32` and `int64` missed). Is this intentional or just not was not used by anybody?

**Comment by NickNaso** [comment]
Hi @fanatid,
the reason behind this choice is that in JavaScript there is only **[Number Type](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-ecmascript-language-types-number-type)** data type to represents the number. Internally it is implemented as **[IEEE 754](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-terms-and-definitions-number-value)** double precision floating point number.

**Comment by devsnek** [comment]
In particular, if you have something that isn't a double and want to make a js number with it, the idea is that you should choose your own (potentially lossy) conversion, instead of napi shipping some potentially unsavory behaviour.

**Comment by fanatid** [comment]
Yeah, I know that internally Number is use double float, but I noticed that `n-api` have functions like [napi_create_int32](https://nodejs.org/api/n-api.html#n_api_napi_create_int32) (and `uint32`, `int64`), so was interested why `node-addon-api` not use it.

> In particular, if you have something that isn't a double and want to make a js number with it, the idea is that you should choose your own (potentially lossy) conversion, instead of napi shipping some potentially unsavory behaviour.

:point_up: This totally makes sense, thanks.
