### ISSUE TITLE
[Docs] missing Array docs page.

### ISSUE THREAD

**Issue by zander** [nodejs/node-addon-api#612]
If you go to https://github.com/nodejs/node-addon-api/blob/master/doc/object.md
you will see the sentence; 

> and extends [`Napi::Array`](array.md)

the 'array.md' is missing in the doc directory, though.

I can't find any docs on the normal arrays.

**Comment by NickNaso** [comment]
Hi @zander,
the right link is https://github.com/nodejs/node-addon-api/blob/master/doc/basic_types.md#array sorry for the mistake.

**Comment by mhdawson** [comment]
Believe this can be closed as PR #613 has laned.
