### ISSUE TITLE
ThreadSafeFunction delay, callback is not called "immediately"

### ISSUE THREAD

**Issue by 5cript** [nodejs/node-addon-api#622]
Given the following code, that is almost exactly one of the examples of the doc for TSFN:
```C++
/*I am within an exported class' member function, asyncConnect and connectThread are members of that class*/

asyncConnect = Napi::ThreadSafeFunction::New(
    env, // from Napi::CallbackInfo
    fn, // from Napi::CallbackInfo
    "AsyncConnector",
    0,
    1,
    [this](auto){
        log << "release\n";
        if (connectThread.joinable())
            connectThread.join();   
    }
);

// Why? because calling this function twice is impossible without, explaination below.
if (connectThread.joinable())
    connectThread.join();

connectThread = std::thread{[this, addr, sid, channel](){
    auto callback = [this]( Napi::Env env, Napi::Function jsCallback) {
        jsCallback.Call( {Napi::String::New( env, "success" )} );
    };
    log << "blocking call\n";
    // If I comment this out, my issue vanishes.
    std::this_thread::sleep_for(2s);
    // for(int i = 0; != 100; ++i) // adding this loop just does that the callback doesnt get called,
    // but gets called 200 times the entire function is called again.
        asyncConnect.BlockingCall(callback);
    log << "blocking call over\n";
    asyncConnect.Release();
}};
```

The callback is never called and the "release" string is never found in the log.
Only when I call the entire function again The callback gets called, but twice!

This is what the log shows:
```
blocking call
blocking call over
blocking call
blocking call over
release
release
```
And I have no idea why. 
When I add another TSFN that I call every something milliseconds, I can force the callback to be called.
Is there something I am missing about how asynchronous function calling works?

I am using electron 7.1.2 (newest) & react btw, This might be very relevant.
That should be node 12.8.X and I am using node-addon-api 2.0.0

**Comment by zander** [comment]
(not a maintainer, just a co-user here)

Javascript's engine is completely single-threaded. Async works there by scheduling an event on the JS main thread.

It is required that any and all interactions you do with the JS engine is done from the main thread.

This means that if you want to do a callback it is a multi-step affair.

1. on your private thread you acquire and then call a threadsafe function, pointing it to a single global method.
2. this global (native) method is called on the main thread. You can use 'Call' from there.
3. the JS callback you called in 2 is actually run.

Your coding example doesn't make much sense to me, sorry. Many things seem wrong.

The correct way is then to create the ThreadSafeFuntion, but without your last arg.

Then you have to realize that the acquired() has to be called the first time before you use the asyncConnect from another thread. After a successful call, you can call it as many times as you want (resulting in point 2 above).

You need to Release is exactly once. So the following is a simplified version that assumes you call it once. Use bools if you want to do more complex stuff.

```
void helperMethod(Napi::Env env, Napi::Function jsCallback, std::string *str)
{
    // I'm too lazy to construct a string object here, but you could pass that as arg.
     jsCallback.Call({});
    delete str;
}

/// the following is done somewhere in your (non JS) thread:
 if (asyncConnect.Acquire() == napi_ok) { 
    std::string *str = new std::string("success");
    asyncConnect.f.NonBlockingCall(str, helperMethod);
    asyncConnect.Release();
}
```

Hope that helps.

**Comment by 5cript** [comment]
I have added the Acquire() in my code, its missing in the example:
https://github.com/nodejs/node-addon-api/blob/master/doc/threadsafe_function.md#example

yet still, the queued event does not fire if I dont do anything else with TSFNs.
I am currently creating calling and destroying TSFNs on a loop someplace else to get all my other stuff to acutally get processed close after completion.

**Comment by KevinEady** [comment]
Hi @5cript ,

Regarding the example: It is _not_ missing a call to `Acquire()` because the only thread that makes use of the TSFN is the native thread -- the `tsfn` is not used outside of the native thread's entry method. The TSFN's initial thread count is `1`, so that means it will require only one call to `Release` to finalize.

Also, I am not sure why you would ever see multiple `release` messages in your log. The TSFN's finalizer is ran only once, when all threads have called `Release()` (notwithstanding an `Abort()`ed situation). Do you have some funky static variable state being overwritten or something?

Can you extract your code to a runnable example?

**Comment by 5cript** [comment]
exportable_client.hpp
```C++
#include <napi.h>
#include <thread>
#include <string>

// dummy
class Client {
    void connect(std::string const&) 
    {
        std::this_thread::sleep_for(5s);
    }
}

class ExportableClient : public Napi::ObjectWrap <ExportableClient>
{
    public:
        ExportableClient(const Napi::CallbackInfo& info);

        static Napi::Object Init(Napi::Env env, Napi::Object exports);

    private:
        void connect(const Napi::CallbackInfo& info);
        std::thread connectThread;
        Client client;
}
```
exportable_client.cpp
```C++
Napi::Object ExportableClient::Init(Napi::Env env, Napi::Object exports)
{
    Napi::HandleScope scope(env);
    Napi::Function func = DefineClass(env, "Client", {
        InstanceMethod("connect", &ExportableClient::connect),
    });

    constructor = Napi::Persistent(func);
    constructor.SuppressDestruct();

    exports.Set("Client", func);
    return exports;
}


void ExportableClient::connect(const Napi::CallbackInfo& info)
{
    Napi::Env env = info.Env();
    Napi::HandleScope scope(env);
    /*skipping checks for brevity*/

    Napi::Function fn = info[1].As<Napi::Function>();
    auto addr = info[0].As<Napi::String>().Utf8Value();

    asyncConnect = Napi::ThreadSafeFunction::New(
        env, 
        fn,
        "AsyncConnector",
        0,
        1,
        [this](auto){
            //log << "release\n";
            if (connectThread.joinable())
                connectThread.join();   
            }
    );

    if (connectThread.joinable())
        connectThread.join();

    connectThread = std::thread{[this, addr, sid, channel](){
        auto callback = [this]( Napi::Env env, Napi::Function jsCallback) {
            // Transform native data into JS data, passing it to the provided 
            // `jsCallback` -- the TSFN's JavaScript function.
            jsCallback.Call( {Napi::String::New( env, "success" )} );
        };
        auto callbackError = [this]( Napi::Env env, Napi::Function jsCallback, std::string* err = nullptr) {
            // Transform native data into JS data, passing it to the provided 
            // `jsCallback` -- the TSFN's JavaScript function.
            std::string e = "unknown error";
            if (err != nullptr) {
                e = *err;
                delete err;
            }
            jsCallback.Call( {Napi::String::New( env, e.c_str() )} );
        };

        try 
        {
           client.connect(addr);
           for (int i = 0; asyncConnect.Acquire() != napi_ok && i != 20; ++i)
                std::this_thread::sleep_for(50ms);
           asyncConnect.BlockingCall(callback);
        }
        catch(std::exception const& exc)
        {
            std::string* err = new std::string{exc.what()};
            asyncConnect.Acquire();                
            asyncConnect.BlockingCall(err, callbackError);
        }
        asyncConnect.Release();
}
```

main.cpp
```C++
#include <napi.h>

Napi::Object Init(Napi::Env env, Napi::Object exports) {
    try {
        ExportableClient::Init(env, exports);
    }
    catch(...) {        
    }
    return exports;
}
```

from script:
```JavaScript
/* ... */
// this is within a button press event:
// my module is named blueback:
client = require('bindings')('blueback.node');
client.connect('someAddress', (msg) => {
    // I only see this AFTER PRESSING THE BUTTON A SECOND TIME! then twice.
    console.log(msg);
});
```
