### ISSUE TITLE
Scheduling an C++ event on the main thread

### ISSUE THREAD

**Issue by zander** [nodejs/node-addon-api#626]
Imagine an add-on that supplies a Search() method which is handled async in a native code using existing threads there.
It returns a Promise.

In the native code I at one time finish the search and want to call ` m_promise.Resolve(mainObject());`

I get an error from nodejs if I call that in one of my search-engine threads, I don't get any error when I call this in the nodejs main thread.

The problem I'm trying to solve is to get an event planned on the JS main thread, which calls my native code and can do the `Resolve()` from above.

I may not get any `Napi::Function` from the user, so I can't use a threadsafefunction for this. I think.

Is there a simple way to schedule a call to a native method that I want to be executed on the main JS thread?

Thanks for any help you can give.

**Comment by legendecas** [comment]
`ThreadSafeFunction` is not necessarily to be created with a `Function` -- it's optional, and we could use `ThreadSafeFunction` as an async handle to trigger some event on JS thread. Unfortunately, right now we have no constructors that receive no `callback` arguments. A workaround might be:

```cpp
tsfn = Napi::ThreadSafeFunction::New(env,
    Function(), /** an empty `Napi::Function` */
    resource,
   resourceName,
   maxQueueSize,
   initialThreadCount,
   context,
   finalizeCallback,
   data);

tsfn.BlockingCall([=](Napi::Env env, Function callback /** callback is empty and shall not be used */) {
  /** Do anything you'd like on JS thread and do not use the `callback` parameter. */
});
```

Related: https://github.com/nodejs/node-addon-api/issues/544

**Comment by KevinEady** [comment]
Be aware that the optional function callback is only supported in N-API 5. It is required in N-API 4. See "History" under the napi_create_threadsafe_function [docs](https://nodejs.org/api/n-api.html#n_api_napi_create_threadsafe_function)

**Comment by zander** [comment]
Thanks, this seems to work on my nodejs13.0

I don't really know how to test on different versions. Looks like ubuntu/debian have really old versions of NodeJS in their stable releases, making testing on their platforms a bit of a no-go.
