### ISSUE TITLE
ObjectWrap construction flow

### ISSUE THREAD

**Issue by sampsongao** [nodejs/node-addon-api#63]
In node-sqlite3, they have code call Ref() on Database in the Database::New. Similar to node-canvas port, I change the Database::New to Database::Database. So the problem is in the ConstructorCallbackWrapper, Ref() is called before the ref is set in the ObjectReference.
```
  T* instance;
  napi_value wrapper;
  details::WrapCallback([&] {
    CallbackInfo callbackInfo(env, info);
    instance = new T(callbackInfo);
    wrapper = callbackInfo.This();   // ==> calling db->Ref() here
    return nullptr;
  });

  napi_ref ref;
  status = napi_wrap(env, wrapper, instance, FinalizeCallback, nullptr, &ref);
  if (status != napi_ok) return nullptr;

  Reference<Object>* instanceRef = instance;
  *instanceRef = Reference<Object>(env, ref);
```

So I guess better way to go is to have Database::Database() for creating napi_ref and then call a Database::New (callbackInfo) to initialize?
```
  T* instance = new T();
  napi_value wrapper;
  details::WrapCallback([&] {
    CallbackInfo callbackInfo(env, info);
    wrapper = callbackInfo.This();
    return nullptr;
  });

  napi_ref ref;
  status = napi_wrap(env, wrapper, instance, FinalizeCallback, nullptr, &ref);
  if (status != napi_ok) return nullptr;

  Reference<Object>* instanceRef = instance;
  *instanceRef = Reference<Object>(env, ref);

  details::WrapCallback([&] {
    CallbackInfo callbackInfo(env, info);
    instance->New(callbackInfo);
    return nullptr;
  });
```

**Comment by sampsongao** [comment]
So the idea here is that the whatever function the original code use to initialize a new instance (in this case is the Database::New) should be the last thing get called in the ConstructoCallbackWrapper. By the time we call it, all preparation should have been done.

**Comment by sampsongao** [comment]
To clarify this problem:
So in [Database::New()](https://github.com/mhdawson/node-sqlite3/blob/master/src/database.cc#L137) it creates a new Baton, which calls [ObjectWrap->Ref()](https://github.com/mhdawson/node-sqlite3/blob/master/src/database.h#L42). However, if we change Database::New to be Database::Database (similar to what is done in Canvas), then in the [ConstructorCallbackWrapper](https://github.com/nodejs/node-addon-api/blob/master/napi-inl.h#L2434), the napi_ref haven't be created by the time Ref() is called.

So I think we should create napi_ref before calling the object-wrapped class constructor.
@mhdawson @jasongin Please tell me if this issue is still not make sense.

**Comment by jasongin** [comment]
This is tricky. The `napi_ref` is created by the `napi_wrap()` call, and _that_ can't be called until the class instance is constructed (or at least allocated).

I think the fix should be to move the call to `napi_wrap()` and reference assignment from `ObjectWrap::ConstructorCallbackWrapper()` to the `ObjectWrap::ObjectWrap()` constructor, where it would execute after the instance is allocated but before the subclass constructor. If `napi_wrap()` returns an error status there, it should be thrown as an exception, which will be caught by the `details::WrapCallback()` wrapper in `ConstructorCallbackWrapper()`.

@sampsongao Do you want to implement this change or should I?

**Comment by sampsongao** [comment]
Sure, I can try to implement it.

**Comment by mhdawson** [comment]
Unrelated to fixing the current issue, Sampson mentioned that because it does not support the 2 step flow used with Nan, the conversion script cannot make the substitutions automatically and it takes some work to do it manually.  Would it make sense to support that flow in addition or instead to make conversion easier ?

**Comment by sampsongao** [comment]
Commited https://github.com/nodejs/node-addon-api/commit/d45ba728340e1a06e54f5b827273b23deef4e6ac
