### ISSUE TITLE
ExecutionProgress not defined

### ISSUE THREAD

**Issue by mupchurch-verys** [nodejs/node-addon-api#630]
Trying to create a sample of AsyncProgressWorker (using sample)...  When I try and compile (Visual Studio 2017 using cmake-js)...  It's telling me ExecutionProgress is not defined.  Is this something I need to write or did I miss something?

**Comment by legendecas** [comment]
May I ask you to provide a small snippet to reproduce the error? If I could guess, the mose possible cause might be that `ExecutionProgress` is a member of namespace `AsyncProgressWorker` -- i.e. `Napi::AsyncProgressWorker::ExecutionProgress`.

**Comment by mupchurch-verys** [comment]
That was the issue...  I'm trying to get the sample for async worker to "work"
