### ISSUE TITLE
How to wrap AsyncWorkerProgress in a promise

### ISSUE THREAD

**Issue by mupchurch-verys** [nodejs/node-addon-api#634]
I'm trying to figure out how to wrap AsyncWorker or AsyncWorkerProgress in a promise.  Any examples...  Can't see to find any.

**Comment by gabrielschulhof** [comment]
@mupchurch-verys @legendecas mentioned during today's team meeting that he'll work on an example illustrating the use of `AsyncWorker` and `AsyncProgressWorker` in conjunction with a `Promise`/`Deferred`.
