### ISSUE TITLE
Getting the size of a string for napi_get_value_string_utf16

### ISSUE THREAD

**Issue by zandaqo** [nodejs/node-addon-api#64]
Hi guys,

`napi_get_value_string_utf16` expects to a buffer of fixed size to fill with the string from JS engine. I'm wondering if there is a method to get the size of the string before creating that buffer. My current workaround does the job so far, but I'm sure if it portable or correct in general:
```C++
        // where args[0] is a JS string passed into the C++ function
	size_t bufSize = sizeof(args[0]) / 2;
	char16_t value0[bufSize];
	size_t copied0;
	status = napi_get_value_string_utf16(env, args[0], value0, bufSize, &copied0);
	assert(status == napi_ok);
```

**Comment by addaleax** [comment]
You can call `napi_get_value_string_utf16` with the `buf` argument set to `NULL` – in that case, `copied0` would still be filled with the size of the string.

(In your example, `sizeof(args[0])` doesn’t seem correct – it will give you the size of `args[0]` as a pointer, not of the JavaScript value that it refers to.)

**Comment by zandaqo** [comment]
@addaleax So in that case I do two calls to `napi_get_value_string_utf16`, the first one with buf set to NULL to get the size of the string, and the second one get the string itself, correct?
```C++
        // where args[0] is a JS string passed into the C++ function
	size_t strSize;
	status = napi_get_value_string_utf16(env, args[0], NULL, NULL, &strSize);
	assert(status == napi_ok);
	char16_t value0[strSize];
	size_t copied0;
	status = napi_get_value_string_utf16(env, args[0], value0, bufSize, &copied0);
	assert(status == napi_ok);
```

**Comment by addaleax** [comment]
@zandaqo In C++ that should work, yup. :) You don’t need the extra `copied0`, though, since you already know the string size.

**Comment by zandaqo** [comment]
@addaleax Thank you! That's a lot of code to get a string, to be honest, but NAPI is still more readable than  v8 bindings, I guess.

**Comment by addaleax** [comment]
@zandaqo Keep an eye on the C++ wrapper API in this module here (https://www.npmjs.com/package/node-addon-api) – it’s a lot more readable than the raw C APIs exposed by NAPI, and much more so than the V8 API itself.

**Comment by zandaqo** [comment]
@addaleax I didn't notice that his repository was for a different API :) Google led me hear when I was looking for N-API. The wrapper API seems quite nice, if I understand it correctly, getting a string with it should be as simple as `new Napi::String::String (env, args[0])` and it can be then converted with `std::u16string()`. That's nice indeed. Thank you!

```

**Comment by addaleax** [comment]
> if I understand it correctly, getting a string with it should be as simple as `new Napi::String::String (env, args[0])`

If you’re creating your functions using this wrapper API it gets even easier than that. :) Something like this should work:

```c++
void Foobar(const CallbackInfo& info) {
  assert(info[0].IsString());
  std::string arg = info[0].As<String>().Utf8Value();
}

void Init(Env env, Object exports, Object module) {
 exports.Set("foobar", Function::New(env, Foobar)); 
}

NODE_API_MODULE(addon, Init)
```

**Comment by zandaqo** [comment]
@addaleax Now that's impressive! It took me some 50 locs of N-API  to expose a single function that takes two strings and returns an integer; this API reduces that to mere handful locs. it's almost too easy.
