### ISSUE TITLE
Using AsyncProgressWorker for an OpenGL render loop

### ISSUE THREAD

**Issue by chrispytoes** [nodejs/node-addon-api#642]
I'm trying to get GLFW running in an `AsyncProgressWorker`.

Here's how I'm doing this. I have an Napi class `Window` exposed to nodejs, which has the property `renderer`, which is my `AsyncProgressWorker` instance. The progress worker thread is the only thing calling OpenGL code. The render loop within `Execute` calls `progress.Send()` each frame, passing the current time delta to nodejs.

Here's my issue now. It 99% works. My OpenGL window opens, the render loop runs and is clearing the buffer each frame, and nodejs is able to `console.log` the delta time each frame perfectly fine. BUT Windows thinks the program has crashed. I get a "not responding" window immediately on startup, even though the loop is still clearly running and logging output. Commenting out all OpenGL code except for the window initialization gives the same result but with a white screen instead of black, still crashing.

Here's the `AsyncProgressWorker` renderer class:
```
#include <chrono>
#include <cstdio>
#include <list>
#include <napi.h>
#include <glfw/glew.h>
#include <glfw/glfw3.h>
#include "../drawing/drawing.h"

using namespace std::chrono;
using namespace Napi;

class GLRenderer: public AsyncProgressWorker<double> {
  public: double fps = 60;
  double dt = 1;
  double elapsed = 1;
  long timestep = 1000000000 / 60;
  long lastFrameTime = duration_cast<nanoseconds> (steady_clock::now().time_since_epoch()).count();;
  GLFWwindow* window;
  std::list <Drawing*> drawings;

  GLRenderer(Function & callback, double fps): AsyncProgressWorker(callback),
  fps(fps) {
    if (!glfwInit()) {
      throw "GLFW Init Failed";
    }
    glfwSetErrorCallback(error_callback);
    this -> window = glfwCreateWindow(1280, 720, "Wowerino", NULL, NULL);
    if (!this -> window) {
      glfwTerminate();
      throw -1;
    }
    glfwMakeContextCurrent(this -> window);

    this -> timestep = 1000000000 / fps;
  }~GLRenderer() {}

  void Execute(const ExecutionProgress & progress) {
    while (!glfwWindowShouldClose(window)) {
      glClear(GL_COLOR_BUFFER_BIT);

      long currentFrameTime = duration_cast <nanoseconds> (steady_clock::now().time_since_epoch()).count();
      long renderLength = currentFrameTime - lastFrameTime;
      lastFrameTime = currentFrameTime;
      dt = renderLength / (double) timestep;

      for (std::list<Drawing*>::iterator it = drawings.begin(); it != drawings.end(); ++it) {
        (* it) -> render();
      }

      glfwSwapBuffers(this -> window);
      glfwPollEvents();

      progress.Send(&dt, 1);

      std::this_thread::sleep_for(nanoseconds(((lastFrameTime - duration_cast <nanoseconds> (steady_clock::now().time_since_epoch()).count() + timestep) / 1000000)));
    }
  }

  void AddChild(Drawing* newDrawing) {
    drawings.push_back(newDrawing);
  }

  void OnProgress(const double* dt, size_t) {
    HandleScope scope(Env());
    Callback().Call({
      Number::New(Env(), *dt)
    });
  }

  void OnOK() {
    HandleScope scope(Env());
    Callback().Call({});
  }

  static void error_callback(int error, const char* description) {
    printf("%s\n", description);
    glfwTerminate();
    throw -1;
  }
};
```

The method of `Window` called from nodejs which starts the renderer:
```
Napi::Value Window::startLoop(const Napi::CallbackInfo &info) {
	Napi::Env env = info.Env();
	Napi::Function callback = info[0].As<Napi::Function>();
	this->renderer = new GLRenderer(callback, this->fps);
	this->renderer->SuppressDestruct();
	this->renderer->Queue();
	return info.Env().Undefined();
}
```

The node.js implementation:
```
const { Window } = require('bindings')('engine');

const window = new Window(60);

window.startLoop(dt => {
  console.log(dt);
});
```

**Comment by KevinEady** [comment]
Hi @chrispytoes ,

Just a guess really... Do you need to handle window cleanup (DestroyWindow / Terminate) inside the destructor maybe?

**Comment by chrispytoes** [comment]
@KevinEady  Not as far as I'm aware. The glfw parts are taken directly from the basic tutorial.

**Comment by KevinEady** [comment]
Hi @chrispytoes ,

Just another thought, can you try moving the window creation inside the `Execute` method? I don't know, maybe there is some funkiness happening because you're creating the window under the main process' thread handle, but polling for events in the secondary worker thread?

**Comment by chrispytoes** [comment]
@KevinEady That was it! Thanks, I'm still a little new to C++ and didn't realize the constructor would be running in the main thread.

**Comment by nicholasc** [comment]
FYI: @chrispytoes 
macOS has a limitation for window and keyboard event polling. It has to be done on the main thread so you won't be to create a GLFW window on a separate thread.

[Reference 1](https://discourse.glfw.org/t/multithreading-glfw/573)
[Reference 2](https://github.com/glfw/glfw/issues/136)
