### ISSUE TITLE
Main Thread: Can a render loop + Javascript co-exist?

### ISSUE THREAD

**Issue by nicholasc** [nodejs/node-addon-api#647]
I am working on an add-on that has a rendering loop that _must_ execute draw calls on the main thread. Of course, the problem here is that the main thread is hanging in the loop therefore blocking anything from happening in JS land.

Is there is a way from c++, using Napi or anything, to tell libuv's event loop to poll events in order to "share" the main thread?

Any other suggestion is appreciated.

Thanks!

**Comment by NickNaso** [comment]
Hi @nicholasc,
you could use one of these two APIs:
- `Napi::AsyncWorker` see:  https://github.com/nodejs/node-addon-api/blob/master/doc/async_worker.md
- `Napi::ThreadSafeFunction` see: https://github.com/nodejs/node-addon-api/blob/master/doc/threadsafe_function.md

Usually the `Napi::AsyncWorker` is used to execute a task on a thread out of the main thread and at the end of the execution you can take the result that you obtained and call a function callback on the main thread. 

If you need to call a JavaScript function (that needs to be executed on the main thread ) while you are on a separate thread you shlould use the `Napi::ThreadSafeFunction`.

Furthermore recently we introduced a new async worker `Napi::AsyncProgressWorker` that implements the same interface of `Napi::AsyncWorker`, but allow you to reports the progress of your task from the external thread to the main thread (event loop).
For more info see:  https://github.com/nodejs/node-addon-api/blob/master/doc/async_progress_worker.md
Hope that this information will help you.

**Comment by nicholasc** [comment]
Hi @NickNaso,

Thank you for the quick reply.

I already tried using AsyncWorker but I quickly realized that in my case it would not be sufficient. I am using an external library and don't have access to the draw calls themselves and the loop setup. I just execute a "run app" function and the rest is done automatically. I can hook myself into setup, update, draw calls and execute javascript callbacks during but if I need to use a setTimeout or setInterval, or anything async for that matter, they are blocked because of this.

I found how to recuperate the uv_loop object using the Napi but I'm not sure what to do with it.

**Comment by NickNaso** [comment]
@nicholasc is your code public? Could post an example of your code? I’m this way I and other could understand in a better way how to help you.

**Comment by nicholasc** [comment]
The code is not public at the moment but I can give you a better understanding of the context and copy-paste elements.

Basically, I'm fiddling around trying to create openFrameworks bindings for node.js. A basic setup for openFrameworks consists of setting up OpenGL and running an instance of an app:

```
ofSetupOpenGL(800,600, OF_WINDOW);  
ofRunApp(new ofApp());
```

The call to `ofRunApp` was designed to have its draw calls be made on the main execution thread. I tried `AsyncWorker` and `std::thread` and both end up failing when the first draw call is made. 

This leads to a problem because Node's event loop also runs on the same thread. Once openFrameworks main loop is fired, the main thread will not be able to update Node's event loop anymore. As a result, asynchronous javascript calls do not work as expected. 

The execution goes something along those lines:
```
node_event_loop_start()
  of_rendering_loop_start()
     App code runs here. 
     Looking for a way to poll node events outside this loop.
  of_rendering_loop_stop()
node_event_loop_stop()
```

**Comment by nicholasc** [comment]
This seems to be the limitation: https://discourse.glfw.org/t/multithreading-glfw/573/4

**Comment by KevinEady** [comment]
Hi @nicholasc ,

Instead of running the full rendering loop to completion, can you instead do "one run" of the loop instead? If so, I imagine something like this might work:

```js

function execute() {
    return new Promise(resolve => {
        const loop = () => {
            // do work, return true if more work to do
            if (binding.work()) 
                setImmediate(loop);
            else
                resolve();
        };
        // begin
        loop();
    });
}

void async function main() {
    await execute();
}();
```

**Comment by nicholasc** [comment]
I’m afraid openFrameworks does not provide that granularity. I would have to manually implement GLFW functions to call them from a loop in JS like you posted. 

Interesting suggestion but not quite what I’m after although I might have to fall back to that if nothing can be done.

**Comment by nicholasc** [comment]
I take it back. openFrameworks has that granularity and I have managed to manually call the rendering loop from javacript and have everything run smoothely.

Thank you all for your input!
