### ISSUE TITLE
Passing a pointer via the data argument

### ISSUE THREAD

**Issue by sauleanf** [nodejs/node-addon-api#651]
I have been messing around with objects and functions.
```
Napi::Value position(const Napi::CallbackInfo& info) {
  float* a = (float*) info.Data();
  return Napi::Number::New(info.Env(), a);
}

void myClass::getStuff(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();

  float* a = new float(As<Napi::Number>().FloatValue());
  Napi::Function cb = info[3].As<Napi::Function>();

  auto function1 = Napi::PropertyDescriptor::Function("function1", function1, napi_default, a);
 
  Napi::Object obj = Napi::Object::New(env);
  obj.DefineProperties({ function1 });

  cb.Call(env.Global(), { obj });
}
```
When I try to call function1 in javascript, I get nothing. I was able to verify that (int*) info.Data() returns nullptr even though I passed a pointer to an integer on the heap. Am I doing this wrong? How should I approach this?

**Comment by KevinEady** [comment]
Hi @f-s-plus-plus ,

I noticed that our CI tests do not include a test for a function property descriptor with user data. I have since created a PR to add one. Take a look at the [files changed](https://github.com/nodejs/node-addon-api/pull/652/files), maybe that will help?

**Comment by alexisfrjp** [comment]
Can be done using External, example: #584

**Comment by gabrielschulhof** [comment]
@sauleanf please have a look at #652, which adds a test to ensure that passing external data to a binding works correctly. The test can also serve as an example of how to do that. If you are still having trouble, please feel free to re-open this issue or open a new one!
