### ISSUE TITLE
Napi::Env::RunScript is missing.

### ISSUE THREAD

**Issue by H1X4Dev** [nodejs/node-addon-api#655]
Hello,

When installing the latest version (`npm install node-addon-api@2.0.0`) seems like the RunScript function is missing entirely.

Error reported from compiler:
```
error C2039: 'RunScript': is not a member of 'Napi::Env' 
```

Sample code:
```
Napi::Value execute_code(const Napi::CallbackInfo& info)
{
	Napi::Env env = info.Env();

	// If there is no info passed, do not execute the code.
	if (info.Length() < 1)
		return Napi::Boolean::New(env, false);

	try
	{
		Napi::Value result = env.RunScript(info[0].As<Napi::String>());
	}
	catch(std::exception&)
	{
		// will be denied by further return anyway.
	}

	return Napi::Boolean::New(info.Env(), false);
}
```

The docs do say that it exists: https://github.com/nodejs/node-addon-api/blob/master/doc/env.md#runscript
The Napi header says it exists: https://github.com/nodejs/node-addon-api/blob/master/napi.h#L188

HOWEVER

The downloaded version via npm does not seem to reflect the same version as it is here on github.
![image](https://user-images.githubusercontent.com/10332146/72829416-058f1e00-3c7f-11ea-80e1-71d7cfc3098d.png)

From github:
![image](https://user-images.githubusercontent.com/10332146/72829443-12ac0d00-3c7f-11ea-9085-12d8327fc724.png)

How come the npm version is mismatching so much even tho it says that they are the same "version"?

Those who are affected by this issue, you are free to install the actual latest version using `npm install @h1x4dev/node-addon-api` (include in gyp changes to `require('@h1x4dev/node-addon-api').include`) until the issue is resolved here.

**Comment by richardlau** [comment]
The change (https://github.com/nodejs/node-addon-api/pull/616) landed on master in December. The most recent release (2.0.0) was at the end of November so there is no current release that contains RunScript. Discussion about the next release is in https://github.com/nodejs/node-addon-api/issues/646.

For version 2.0.0:
https://github.com/nodejs/node-addon-api/blob/2.0.0/doc/env.md
https://github.com/nodejs/node-addon-api/blob/2.0.0/napi.h

**Comment by H1X4Dev** [comment]
Oh! Makes sense.

Thank you for the clarification. Will be closing this.
