### ISSUE TITLE
Add JSON APIs

### ISSUE THREAD

**Issue by jasongin** [nodejs/node-addon-api#66]
Add JSON APIs to provide a migration path from `v8::JSON` / `Nan::JSON`.

For now, it will have to be implemented by calling into JS. Eventually N-API could add more optimized versions if there is a need.

**Comment by kkoopa** [comment]
What about a header-only json library, e.g. https://github.com/kazuho/picojson?

**Comment by addaleax** [comment]
I am not so sure about this either – it’s not that hard to call the `JSON.stringify` and `JSON.parse` JS functions with N-API, so this is reasonably easy to do in userland.

**Comment by kkoopa** [comment]
My only concern with that is the cost of transitioning from C++ to JS and back to C++ for every call, but perhaps it is not significant compared to the time requried for parsing?

**Comment by jasongin** [comment]
> it’s not that hard to call the JSON.stringify and JSON.parse JS functions with N-API, so this is reasonably easy to do in userland

Yes. From the Node.js point of view, everything in `node-addon-api` _is_ userland. My suggestion is that we could add convenience methods in the C++ API here, that just call into those JS functions. Then if it is a performance problem we can later consider adding N-API functions and switching the implementation here.

**Comment by mhdawson** [comment]
Starting with methods that just call into the JS functions to start sounds like the right first step to me.  I expect the parsing will be more significant in terms of cycles than the transitions.

**Comment by mhdawson** [comment]
We've not done this and have not had complaints in a few years. Going to close out for now. Please let us know if that is not the right thing to do.
