### ISSUE TITLE
Napi::Object to C++ struct

### ISSUE THREAD

**Issue by afulsamet** [nodejs/node-addon-api#668]
Can I create C++ struct with Napi::Object I get from arguments?

```cpp
#include <napi.h>

using namespace Napi;

Void Init(Env env) {

  // I created an object as an example.
  Object obj = Object::New(env);

  obj.Set("hello", "world");
  obj.Set("Douglas Adams", true);

  // Convert obj to struct

}
```

I want the output to be this way.

```cpp
struct a { 
  std::string hello;
  bool Douglas_Adams;
  a() {
    hello = "world";
    Douglas_Adams = true;
  }
}
```

Is there a way to achieve this?

**Comment by KevinEady** [comment]
I don't think this is possible to achieve in the way you want. In JS, the keys are dynamic (eg. the `"Douglas Adams"` token is a string accessor), whereas in C++ the struct members need to be known as compile time (eg. the `Douglas_Adams` token is an identifier describing the struct). You can't "transform" the dynamic JS object into some unknown C++ structure.

What is your use-case? I think `ObjectWrap` may work for what you're doing, but I'm not entirely sure.

**Comment by afulsamet** [comment]
[Windows API]
I want to write with C++ struct to any address in memory.
```cpp
bool ret = Memory::WriteMemory<Napi::Object>(address);
```
There will be any C++ struct instead of Napi::Object.

**Comment by mhdawson** [comment]
@afulsamet did you take a look at ObjectWrap as @KevinEady suggested?
