### ISSUE TITLE
Is it possible to create a Napi::Function from a FunctionReference?

### ISSUE THREAD

**Issue by TCourtneyOwen** [nodejs/node-addon-api#671]
I see that I can create a Napi::FunctionReference from a Napi::Function:

     static Napi::FunctionReference Napi::Persistent(const Napi::Function& value);

Is it possible to do the reverse - create a Function from a FunctionReference? I couldn't find any documentation that shows if that's possible.

Thanks,

Courtney

**Comment by KevinEady** [comment]
You can get the _existing_ `Function` that a `FunctionReference` refers to via [`Value()`](https://github.com/nodejs/node-addon-api/blob/7f56a78ff7eab77f1316696aef1de3304b70e639/napi.h#L1148). Does this help?

**Comment by TCourtneyOwen** [comment]
That seems to work for me, thanks!
