### ISSUE TITLE
Javascript inheritance of an ObjectWrap

### ISSUE THREAD

**Issue by nicholasc** [nodejs/node-addon-api#673]
So I have a basic `ObjectWrap` named `Drawable` that my addon exports. I want to be able to extend it in Javascript and call the `setup`, `update` & `draw` methods from the `ObjectWrap` itself. 

So, for example, in Javascript:
```js
class MyDrawable extends Drawable {
  setup() {
    console.log("Setup from MyDrawable");
  }

  update() {
    console.log("Update from MyDrawable");
  }

  draw() {
    console.log("Draw from MyDrawable");
  }
}
```

And the `Drawable` `ObjectWrap` source looks like this: 
```c++
#include <napi.h>

class Drawable : public Napi::ObjectWrap<Drawable> {
  public:
    static Napi::Object Init(Napi::Env env, Napi::Object exports);
    Drawable(const Napi::CallbackInfo &info);
    void setup();
    void update();
    void draw();

  private:
    static Napi::FunctionReference constructor;
};

Napi::Object Drawable::Init(Napi::Env env, Napi::Object exports) {
    Napi::Function func = DefineClass(env, "Drawable", {});

    constructor = Napi::Persistent(func);
    constructor.SuppressDestruct();

    exports.Set("Drawable", func);
    return exports;
}

Drawable::Drawable(const Napi::CallbackInfo &info) : Napi::ObjectWrap<Drawable>(info) {
}

void Drawable::setup() {
  // call MyDrawable setup method if it exists
}

void Drawable::update() {
  // call MyDrawable update method if it exists
}

void Drawable::draw() {
  // call MyDrawable draw method if it exists
}

Napi::FunctionReference Drawable::constructor;
```

The `Drawable` objects are added to a render loop inside the addon that triggers the `ObjectWrap`'s `setup`, `update` and `draw` and I want them to be able to call MyDrawable's `setup`, `update` and `draw` methods if they exist.

How would I be able to achieve this?

**Comment by nicholasc** [comment]
I'm starting to think that this kind of inheritance is currently impossible. I might resort to a workaround with object composition instead. Will post it here if I find a suitable solution.

**Comment by NickNaso** [comment]
Hi @nicholasc ,
in my opinion the composition could be the best approach, but I want try to access to the prototype chain from the ObjectWrap and verify if I can able to call the right method and then discover if there are some issues on doing that. I hope to update you soon.
