### ISSUE TITLE
Heap corruption when using ifstream / stringstring (ios_base)

### ISSUE THREAD

**Issue by bromix** [nodejs/node-addon-api#682]
I encountered a strange problem while using ifstream or stringstream. I'm implementing a function to read settings for an application from an ini file and return the settings as an object.
But as soon as the stringstream is declared, I get a heap corruption when leaving the scope of the function. Has this to do with threading and if so, how can I secure this? The documentation is not clear for me how to accomplish this. Below is a simplified implementation of my problem.

I'm working with Node **13.10.1**

```c++
#include <sstream>

Napi::Value load_from_ini_string(const Napi::CallbackInfo& info)
{
	const Napi::Env env = info.Env();
	if(info.Length() != 1)
	{
		Napi::TypeError::New(env, "Wrong number of arguments").ThrowAsJavaScriptException();
		return env.Null();
	}

	if (!info[0].IsString())
	{
		Napi::TypeError::New(env, "Wrong arguments").ThrowAsJavaScriptException();
		return env.Null();
	}

	auto ini_content = info[0].As<Napi::String>().Utf8Value();

	std::stringstream ss;  // <- this is the problem
	// as soon as this line exists and we leave the scope of this function,
	// we get a heap corruption.
	
	return Napi::String::New(env, "Hello");
}

void init(Napi::Env env, Napi::Object exports)
{
	exports.Set("load_from_ini_string", Napi::Function::New(env, load_from_ini_string));
}
```

**Comment by bromix** [comment]
Found the problem after a day of testing... cmake-js may miss some settings under Windows.
[cmake-js/issues/208](https://github.com/cmake-js/cmake-js/issues/208)

**Comment by begmec** [comment]
I encountered the same issue but without using cmake-js. Actually it is quiet strange and in my opinion the issue isn't fixed.

As far as I know, node.js relies on a pure C-API that aims to be ABI compatible. That means, it shouldn't matter if I generate my node plugin code with \MD or \MT. As long as I compile my plugin with VS 2015, this statement is true. But when I compile my node addon with VS 2017 and above, you will get a heap corruption if you try to build your plugin with \MD. \MT instead works always fine. To me, it seems that it is whether a bug in node.js or problem with msvc.

Our node.js plugin relies on a big c++ code base where everything is compiled with \MD. Therefore, it would be great if we could compile our plugin using \MD. Maybe somebody from Node.js or @bromix has some insights or ideas?

The build that breaks the \MD compatibility is found at git hash e783475412a315d28dde17d23492c867bf546dc2
It is the switch from VS 2015 to VS 2017.
