### ISSUE TITLE
Choice between NAN and node-addon-api

### ISSUE THREAD

**Issue by legendecas** [nodejs/node-addon-api#684]
I've heard complaints that it's not clear which one is recommended in _one specific scenario_(NAN is still very useful if add-on is going to use v8's or libuv's APIs that are not exposed through N-API) to persons who are completely new to Node.js add-on development.

Searched on either node-addon-api's README and NAN's, also on google, there is no clear statement about this topic.

**Comment by mhdawson** [comment]
There is a recommendation in https://github.com/nodejs/node/blob/master/doc/api/addons.md#c-addons to use N-API unless you need functionality that it does not expose.

**Comment by mhdawson** [comment]
In discussion in the last N-API team meeting suggestion from @legendecas was that we take some of the text  from the existing Node doc and to the node-addon-api repo.

**Comment by mhdawson** [comment]
PR to address: https://github.com/nodejs/node-addon-api/pull/849

**Comment by mhdawson** [comment]
PR landed closing.
