### ISSUE TITLE
Next release of node-addon-api

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#689]
Release will be 3.0.0

# PRs to land.

- [x] find places were we document which versions of Node.js are support and remove all lower than 
  10.x  [709](https://github.com/nodejs/node-addon-api/pull/709)

- [x]  src: add support for addon instance data [663](https://github.com/nodejs/node-addon-api/pull/663)

- [x] Added badge section to documentation - [688](https://github.com/nodejs/node-addon-api/pull/688)

- [x] Fix minor typo in object_lifetime_management.md [692](https://github.com/nodejs/node-addon-api/pull/692)

- [x] src: change guards to NAPI_VERSION > 5 [697](https://github.com/nodejs/node-addon-api/pull/697) - (3 approvals) 

- [x] support bigint64/biguint64 in TypedArray::ElementSize() [705](https://github.com/nodejs/node-addon-api/pull/705)

# Possibly also include:

- [ ] Added Object::New() taking a list of properties [628](https://github.com/nodejs/node-addon-api/pull/628)

- [ ] doc: add instance data APIs [708](https://github.com/nodejs/node-addon-api/pull/708)

**Comment by NickNaso** [comment]
I'm starting to make the new release. If I will not have problem with CI it will go out very soon.

**Comment by NickNaso** [comment]
I'm closing the issue because the new version of `node-addon-api` has been released.
