### ISSUE TITLE
Call Javascript Class Instance Sub-Methods 

### ISSUE THREAD

**Issue by rsispal** [nodejs/node-addon-api#704]
Hi,

I'm hitting some trouble trying to call a Javascript class constructor's sub methods from the C++ code. Specifically use the JavaScript `Date` class and sub methods in the NAPI code.

My first example was to try return a UNIX timestamp, mimicking `(new Date()).getTime() / 1000`, but with the code below, I receive an `Error: Invalid Argument` error which I cannot explain. I believe to have followed the documentation, as the code does compile. 

Where am I going wrong?

### Attempt 1:

```cpp
Napi::Number TestClass::DateTime_Now(const Napi::CallbackInfo &info) {
    Napi::Env env = info.Env();
    Napi::Function Date = env.Global().Get("Date").As<Napi::Function>();
    Napi::Function getTime = Date.Get("getTime").As<Napi::Function>();

    return getTime.Call({}).As<Napi::Number>();
}
```

### Attempt 2 (persisting the response from the `Date` function, hoping to also contain the submethods):

```cpp
Napi::Number TestClass::DateTime_Now(const Napi::CallbackInfo &info) {
    Napi::Env env = info.Env();
    Napi::Function Date = env.Global().Get("Date").As<Napi::Function>();
    Napi::Object DateRes = Date.Call({}).As<Napi::Object>();
    Napi::Function getTime = DateRes.Get("getTime").As<Napi::Function>();

    return getTime.Call({}).As<Napi::Number>();
}
```

I have successfully called other global Javascript functions that don't require a class instance, such as `JSON` for the `stringify` and `parse`.

**Comment by KevinEady** [comment]
Hi @rsispal ,

Since Date#getTime is an _instance_ member, you need to call it on an instance of a `Date` object:

### 1. Create instance: 
```cpp
Napi::Object dateInstance = Date.New({});
```

### 2. Get reference to `Date#getTime`
```cpp
// Goes through dateInstance's property chain, eg if 
// `getTime` was "overriden" elsewhere
Napi::Function getTime = dateInstance.Get("getTime").As<Napi::Function>();
```
or
```cpp
// Get directly from `Date.prototype`
Napi::Function getTime = Date.Get("prototype").As<Object>().Get("getTime").As<Napi::Function>();
```

### 3.  Call `getTime` with the `dateInstance` as the receiver (ie, the `this` object):

```cpp
getTime.Call(dateInstance, {}).As<Napi::Number>();
```

All together:
```cpp
Napi::Value DateTimeNow(const CallbackInfo &info) {
  Napi::Env env = info.Env();
  Napi::Function Date = env.Global().Get("Date").As<Napi::Function>();
  Napi::Object dateInstance = Date.New({});
  Napi::Function getTime = dateInstance.Get("getTime").As<Napi::Function>();

  return getTime.Call(dateInstance, {}).As<Napi::Number>();
}
```

Does this help?

**Comment by KevinEady** [comment]
Note that if your _specific_ example is to "get the unix timestamp", you can use the _static_ method [`Date.now`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now):

```cpp
Date.Get("now").As<Napi::Function>().Call({});
```

**Comment by rsispal** [comment]
> Since Date#getTime is an _instance_ member, you need to call it on an instance of a `Date` object:
> 
> ...
> 
> 
> Does this help?

Thank you so much @KevinEady for resolving my problem so swiftly. I was misunderstood on precisely what the Get() method was doing. I’m very new to NAPI but didn’t see any specific example detailing how to accomplish this

I was also unaware of the native Date method you refer to - where is this detailed in the documentation? Clearly missed it!

**Comment by rsispal** [comment]
> Since Date#getTime is an _instance_ member, you need to call it on an instance of a `Date` object:
> 
> ...
> 
> 
> Does this help?

Thank you so much @KevinEady for resolving my problem so swiftly. I was misunderstood on precisely what the Get() method was doing, wrongly thinking it created the instance for me.
