### ISSUE TITLE
Example usage for existing napi addon binaries

### ISSUE THREAD

**Issue by cosinusoidally** [nodejs/node-addon-api#71]
Would it be possible for you to please provide some documentation explaining how to use this compatibility code to load napi modules into older node.js versions? I'm on Ubuntu 14.04 x64. I'm having a bit of trouble using the code here to add support for napi module binaries to node.js 4.X.

For example, I have built the hello world example napi module from here: https://github.com/nodejs/abi-stable-node-addon-examples/tree/2f8495dd287c3e04bf92b971c0ebe918b8ea9311/1_hello_world/napi

I built the hello world napi module using node.js 8.1.3 as follows:
```
cd abi-stable-node-addon-examples/1_hello_world/napi/
node-gyp configure
node-gyp build
```
This then gives me the ``hello.node`` binary in ``build/Release/`` . I then move the ``hello.node`` module binary to another directory.

To test the hello.node binary I use the following script (``test.js``)
```
a=require("./hello.node");
console.log(a.hello());
```
I then run ``test.js`` as follows:
```
(trusty)ljw@localhost:~/stuff/node/example$ node --napi-modules ./test.js
world
(node:24355) Warning: N-API is an experimental feature and could change at any time.
```
This works fine with node.js 8.1.3. I would like to be able to load that module into node.js 4.x using the compatibility layer from this repo.

I can see that your napi compatibility code lives in ``src/node_api.cc``, but in that directory there does not appear to be a ``binding.gyp`` file. I created the following ``binding.gyp`` file based on your ``node_api.gyp`` file:
```
{
  'targets': [
    {
      'target_name': 'node-api',
      'sources': [
        'node_api.cc'
      ],
      'defines': [
         'EXTERNAL_NAPI'
      ]
    }
  ]
}
```
I then build the ``node-api`` module with node.js 4.x using:
```
node-gyp configure
node-gyp build
```
I then copied the ``build/Release/node-api.node`` module to the same directory as my ``hello.node`` module. Next I modified my ``test.js`` file as follows:
```
b=require("./node-api.node");
a=require("./hello.node");
console.log(a.hello());
```
But when I run ``test.js`` with node.js 4.8.3 I get the following backtrace:
```
(trusty)ljw@localhost:~/stuff/node/example$ node ./test.js
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ljw/stuff/node/example/test.js:1:65)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```
The ``node-api.node`` module does not seem to load.

Is there a correct way to do this? I see that your test code statically links to ``node-api.a``, but that would not be possible with prebuilt napi module binaries (the modules would need to be rebuilt).

**Comment by jasongin** [comment]
The backward compatibility provided by this library for node versions < 8 is only *source*-level compatibility. Binary compatibility is only possible with node versions that have N-API built-in, so that is node 8.x *and above*. (N-API _may_ get back-ported to node 6.x LTS eventually, but probably only after it is no longer experimental.) **You'll need to rebuild the module when switching from Node 8.x to an older version.**

Please follow the instructions in the README for configuring a module that depends on the `node-addon-api` package. That automatically does the right thing depending on the node version it is being built with. On versions without N-API built-in, it statically links the functions in `node_api.cc` into your module.

**Comment by cosinusoidally** [comment]
Thanks for the info, I understand.

I think I'll try and convert the existing compatibility code into a shared library. Incidentally has this previously been attempted? If so, were there any technical issues that meant that it was not feasible? For Linux, I think I could probably build the compatibility code as a shared library and then load it in to node with a small addon that ``dlopen``s the shared library with the flags ``RTLD_NOW`` and ``RTLD_GLOBAL``. Loading the shared library in that way would expose the ``napi_*`` symbols to any napi module loaded after that point.

**Comment by jasongin** [comment]
I don't recommend using N-API via a shared library that way. We actually considered that approach. The problem is you need to consider versioning of the library. Different native add-ons may be built using different versions of the N-API library. While there should never be breaking changes between versions, new APIs will be added. So if one module loads an older version of the library as shared, and another tries to use the shared library but expects a newer API to be present, that will fail.

**Comment by cosinusoidally** [comment]
I've created a repository containing an implementation of N-API as a shared libary (using a slightly tweaked version of the code in this repo). The repo is  https://github.com/cosinusoidally/node-napi-compatibility-module . In my repo I have a wrapper script (node-napi) that allows users to start up node.js with N-API support loaded. This would allow users of node.js 4.X and 6.X to load unmodified N-API binary modules.

Sorry, I'm not quite sure I understand you rationale regarding versioning. Is that rational documented anywhere? I can see some discussions in places like https://github.com/nodejs/abi-stable-node , but there doesn't seem to be any concrete statement on versioning. If a new version of N-API comes along I can simply update the compatibility code and rebuild the shared library containing the implementation of N-API. Obviously whilst the API is experimental there is no guarantee of ABI/API compatibility, but once the API is declared stable each new version should be a strict superset of the last version (and so I should be able to just install the latest version of the N-API shared library to provide compatibility to all N-API binary modules).

**Comment by jasongin** [comment]
With a shared library, all N-API modules in a process must use the same version of the library, even if some of them were built against a different version. Without a way to guarantee that the single selected version is >= all referenced versions, there can be compatibility problems.

> I should be able to just install the latest version of the N-API shared library to provide compatibility to all N-API binary modules

How is it installed? If it's installed separately, how is it kept up to date? If it's pulled in as a dependency by packages with N-API modules, then how is only the latest version loaded?

**Comment by cosinusoidally** [comment]
For my purposes I think I'll just try and work towards supporting the 1st stable release of N-API (whenever that may be). I'll keep an eye on this repo (and the main node.js repo) and port across patches as necessary. It might not make sense to retrofit any subsequent versions of N-API to node.js 4.X or 6.X . That would neatly sidestep versioning issues since any future versions of the API would simply be unsupported. The user would just get symbol not found errors if they attempted to use a module built against a newer version of the API. Having said that, I don't know what the official plan is regarding versioning. I assume that the 1st stable release will come out in some major node.js version Y (say with version 1.0 of N-API). I would then assume that for node.js version Y+1 we would have N-API version 1.1 (where N-API 1.1 is a strict superset of N-API 1.0). I would also assume that the N-API version shipped with a given major release of node.js would not change across the lifetime of that major release (much like how NODE_MODULE_VERSION does not change across the lifetime of a major (stable) release). If that is the case, any binary N-API module that wants to target every supported version of node.js would need to target the lowest supported version of the API.

> How is it installed? If it's installed separately, how is it kept up to date? If it's pulled in as a dependency by packages with N-API modules, then how is only the latest version loaded? Keep in mind additional modules can be loaded at any time during a process lifetime.

In terms of installing/keeping up to date I think ``git pull`` and then a ``./mk`` should work reasonably well (I may also eventually ship binaries for node.js 4.X and 6.X). I was planing to keep the installation/updating as a manual process outside of npm.  In terms of being a bit more friendly to npm, again I'm not sure what the official plan is, but I assume some version check could be added to npm. This check could be similar to the "engines" field, so you'd have something like ``{"napi_modules":">=1.0"}``. Or possibly include a npm install script in the package.json file that checks for the supported version of N-API (maybe by checking ``process.versions``).

**Comment by mhdawson** [comment]
It looks to me that this discussion has run it's course and there has not been any follow-ons in the last few years so I'm going to close. Please let us know if you think that was not the right thing to do.
