### ISSUE TITLE
Upgrade gcc on the CI

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/node-addon-api#710]
In https://github.com/nodejs/node-addon-api/pull/687#issuecomment-619574600 @KevinEady mentioned that he has reimplemented `ThreadSafeFunction` as a subclass of `ThreadSafeFunctionEx` but that doing so requires gcc >= 6, whereas our CI is at gcc 4.8.4. Would it be possible to
* upgrade our CI's gcc, and
* Mention for our upcoming major release that it requires gcc >= 6

Since Node.js itself requires gcc >= 6.3.1 (IINM) it might make sense for us to follow suit.

@mhdawson WDYT?

**Comment by richardlau** [comment]
FWIW Node.js 10's minimum supported toolchain is 4.9.4 (https://github.com/nodejs/node/blob/v10.x/BUILDING.md#unix).

**Comment by mhdawson** [comment]
Right now it should be using the same version of the compiler as the version of Node.js. Having said that it may be ok to use a newer compiler for addons with an older version of Node.js.  We'll just need to think through if there are any gotchas and what it would mean for node-addon-api to need a newer compiler than the oldest Node.js LTS.

**Comment by mhdawson** [comment]
We discussed in last weeks N-API team meeting. For now we agreed to change the Ex code so that it does not need the new compiler, we'll reduce the code duplication once 10.x goes out of service and the current LTS versions all require a higher version of the compiler.
