### ISSUE TITLE
Question about binding factory static methods

### ISSUE THREAD

**Issue by AlexAltea** [nodejs/node-addon-api#712]
I've been following the [object_wrap.md](https://github.com/nodejs/node-addon-api/blob/master/doc/object_wrap.md) guide but was unable to create bindings for static methods to factory methods (ones that construct the class itself, or its derived types, and return a pointer). E.g.:

```cpp
class Base {
public:
    Base* create(const std::string& type);
};
```

After failing to use `<napi.h>`, I ended up using `<node_api.h>` instead and manually crafting some helpers that wrap *Base::create* and create a new object via `napi_create_object` and then `napi_wrap` the returned pointer into that object.

Finally, to take care of properties, I called `napi_define_properties` as well. Something feels unsettling about this: Is this the optimal way of accomplishing this? And if so, how could I accomplish the same using just `<napi.h>`? Thank you.

**Comment by gabrielschulhof** [comment]
@AlexAltea IIUC you would like to create JS classes at runtime. If that is the case, and without having tested this, you could probably do the following:

```C++
class Base : public Napi::ObjectWrap<Base> {
...
  static Napi::Object Init(Napi::Env env, const char* name) {
    return DefineClass(env, name, {...});
  }
...
};
```
and then call `Base::Init` any number of times to create new JS classes.

**Comment by gabrielschulhof** [comment]
@AlexAltea does this solution address your problem? If not, please feel free to re-open this issue and/or open a new one.

**Comment by AlexAltea** [comment]
> @AlexAltea does this solution address your problem?

@gabrielschulhof Yes! Thank you very much. Sorry that I didn't give an answer earlier. Your suggestion seems to match what I was doing with `<node_api.h>` C API, but using `<napi.h>` C++ API instead, which is what I was looking for.
