### ISSUE TITLE
Crash when accessing some ArrayBuffers from a node addon

### ISSUE THREAD

**Issue by rconde01** [nodejs/node-addon-api#713]
I'm using electron-nightly with WebGPU. One of the WebGPU functions returns an ArrayBuffer. When I pass this ArrayBuffer to my node addon it crashes when retrieving the ByteLength after a few iterations. Passing an ArrayBuffer created manually on the js side appears to work fine.

Here is a minimal reproduction case: https://github.com/the-ocho/webgpuArrayBufferNodeAddonCrash

I'm talking to the chrome WebGPU team about this. If the addon team has any guidance on what I may be doing wrong, or they may be doing wrong, I would appreciate it.

**Comment by codebytere** [comment]
@rconde01 can this be closed?

**Comment by rconde01** [comment]
they merged a potential fix, but the required version of chromium hasn't been yet released in an electron nightly...so i haven't been able to test if it actually fixes the issue. Although I'm not sure if this issue was ever appropriate for the addon repo itself. If that fix doesn't work then i'll be following up on the electron side I guess...so it's up to you if you want to close this issue.

**Comment by codebytere** [comment]
sgtm - let's circle back after you get a chance to test :)

**Comment by rconde01** [comment]
I did a local build with the fix from the webgpu team and now things are working as expected...so closing.
