### ISSUE TITLE
Tips for integration with managed c# code (offtopic) ?

### ISSUE THREAD

**Issue by mmc41** [nodejs/node-addon-api#717]
I have an off-topic question: 

Does anyone know of similar technology to node-addon-api that allow node.js to call into managed C# code (dot net core) instead of c++ code ?

**Comment by NickNaso** [comment]
Hi @mmc41,
I don't know any library that allow you to implement native add-ons for Node.js using **C#**. There are some work in progress project that will allow you to write native add-ons with:
- **Rust** 
- **Go**
- **Swift**

I don't know **C#**, but in general you should be able to export your **C#** code like C static or dynamic library and at that point you could call **C#** functions from **C/C++** code. So this will allow you to implement the business logic of your add-on in **C#**, but you need to use C/C++ api to create the binding.

**Comment by mhdawson** [comment]
Going to close this out as there was an answer and no follow on question. Please let us know if this is not the right thing to do.

**Comment by NickNaso** [comment]
Hi @mmc41,
I know that it's a closed issue, but toady I found a work here https://github.com/EYHN/napi-cs that could help you and other developers to use C# instead C++ to implement native addon for Node.js.

**Comment by delebash** [comment]
Try Edgejs.  A maintained version of  of Edgejs is here https://github.com/agracio/edge-js.  I am just starting to play with it

**Comment by mikey0000** [comment]
https://github.com/microsoft/node-api-dotnet

**Comment by mjm918** [comment]
> https://github.com/microsoft/node-api-dotnet

May you live long. Don't know why google was hiding this from me
