### ISSUE TITLE
WASM_COMPAT ?

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#719]
Was talking to @tniessen who was trying to compile a module that used node-addon-api with WASM. One problem is that the use of mutexes is not currently supported in WASM.

Opening issue to discuss if we might add a WASM_COMPAT flag or something like that which would remove the problematic includes related code if it was defined.

**Comment by devsnek** [comment]
Since a good libc impl like https://github.com/WebAssembly/wasi-libc provides such things, I'm not sure we need to specialize.

Also @tniessen I'm curious what this module is. I've got some node-addon-api stuff running with wasm locally, might be fun to sync up.

**Comment by tniessen** [comment]
> Since a good libc impl like https://github.com/WebAssembly/wasi-libc provides such things, I'm not sure we need to specialize.

Oh, you are right, I forgot I had a compiler option enabled that was incompatible with the mutex search path 🤦

> might be fun to sync up.

Sure, just send me a twitter DM or an email! :)

**Comment by mhdawson** [comment]
@tniessen I guess I can close it since its not going to be needed right?

**Comment by tniessen** [comment]
I think this particular issue is not needed then. (It might still make sense to conditionally exclude features that compile but won't work, but we can discuss that separately.)

**Comment by tniessen** [comment]
@devsnek I would love to sync up, could you send me a DM on Twitter (same handle as on GitHub) or an email (&lt;github handle&gt;@tnie.de)?
