### ISSUE TITLE
Reference:  copy-initialization miss _suppressDestruct(false)

### ISSUE THREAD

**Issue by langxiong** [nodejs/node-addon-api#72]
`Reference` member variable `_suppressDestruct` is only initialized in default constructor.
It should be initialized in other constructor. 
See [code](https://github.com/nodejs/node-addon-api/blob/master/napi-inl.h#L1619)

If `_suppressDestruct` is not initialized to `false`, the destructor may not call `napi_delete_reference`, then the gc is not work as expected.

**Comment by jasongin** [comment]
Fixed by https://github.com/nodejs/node-addon-api/commit/b0f2c6fe59d08f2b0c0bd44a43f3362640b84059
