### ISSUE TITLE
Uncaught Error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by yerkeyzet** [nodejs/node-addon-api#727]
Hi Team,

We are getting "A dynamic link library (DLL) initialization routine failed" with node-rfc NAPI module in Electron, on Windows 10. The module works just fine without Electron.

Environment is:
Windows 10
electron 8.2.5
electron-rebuild 1.10.1
node 12.13.0
npm 6.12.0

Reproducible with require('node-rfc') step in preload.js of electron-quick-start example.

**Comment by mhdawson** [comment]
@codebytere, any suggestions?

**Comment by codebytere** [comment]
@yerkeyzet could you perhaps provide a more thorough reproducible sample?

**Comment by yerkeyzet** [comment]
I prepared thorough steps on a pure Win10 virtual machine, to guarantee that it is reproducible anywhere.
But it needs a `sapnwrfc.dll` library file from SAP Software Download Center.

@bsrdjan is it ok to share `sapnwrfc.dll` file from SAP NW RFC SDK here?

**Comment by bsrdjan** [comment]
Sorry, that is not permitted. Are you maybe SAP or SAP customer/partner employee?

**Comment by yerkeyzet** [comment]
I am an SAP customer employee.

**Comment by bsrdjan** [comment]
Let see the progress with these two tickets. You can also reach me via Email in my GH profile or via LinkedIn, to check if more support could be provided by SAP.

**Comment by bsrdjan** [comment]
Please feel free to close this ticket and continue with this feature request: https://github.com/SAP/node-rfc/issues/144#issuecomment-717219893

**Comment by mhdawson** [comment]
@bsrdjan thanks, closing.
