### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by ieZaky** [nodejs/node-addon-api#733]
I'm quite new to node and addons. what am trying to do I got a c++ code which I need to convert into node js using addons. I'm following a step by step tutorial but there's this problem whenever I try to include<napi.h>. it's as follows " cannot open source file "node_api.h" (dependency of "napi.h")C/C++(1696)". I'm using visual studio code and I installed all dependencies including node_api and node.js as well as vs tools. if any further information is required please let me know and thanks in advance
also this is my binding.gyp file 
{
 "targets": [
    {
      "target_name": "addons",
      "cflags!": [ "-fno-exceptions" ],
      "cflags_cc!": [ "-fno-exceptions" ],
      "sources": [
        "./src/greeting.cpp",
        "./src/index.cpp"
      ],
      "include_dirs": [
        "<!@(node -p \"require('node-addon-api').include\")"
      ],
    'libraries': [

      ],
     'dependencies': [
            "<!(node -p \"require('node-addon-api').gyp\")"
      ],
      'defines': [ 'NAPI_DISABLE_CPP_EXCEPTIONS' ]
    }
  ]
}

**Comment by NickNaso** [comment]
Hi @ieZaky,
at first look your `binding.gyp` seems to be good.
Which Operating System and Node.js version are you using? 
Could you try to check the `node-gyp` version using the following command from the shell?
`node-gyp --version`?

**Comment by ieZaky** [comment]
> Hi @ieZaky,
> at first look your `binding.gyp` seems to be good.
> Which Operating System and Node.js version are you using?
> Could you try to check the `node-gyp` version using the following command from the shell?
> `node-gyp --version`?

Hi Nick, 
Thanks for your reply, I managed to fix it I had to redownload the packages. However, I got a new error now. I'm integrating a c++ function that simply prints "Hello Mike".  that's my index.js:
`onst addons = require('./build/Release/addons.node');

console.log('exports : ' , addons);
console.log();

console.log('addons.greetHello() : ', addons.greetHello() );
console.log();`
Whenever I try to debug,  I get the following error:
TypeError: addons.greetHello is not a function
    at Object.<anonymous> (F:\addons\index.js:6:46)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

and This is my main cpp:
`#include<napi.h>
#include <string>
#include "greeting.h"



Napi::String greetHello(const Napi::CallbackInfo& info)
{
    Napi::Env env = info.Env();
    std::string result = helloUser("Mike");
    return Napi::String::New(env ,result);
}
Napi::Object Init(Napi::Env env , Napi::Object exports)
{
    exports.Set
    (
        Napi::String::New(env, "Function"),
        Napi::Function::New(env, greetHello)
    );
    return exports;
}

NODE_API_MODULE(addons, Init)


`
Any ideas? thanks in advance
