### ISSUE TITLE
BigInt::ToWords docs not consistent with implementation 

### ISSUE THREAD

**Issue by adrian-gierakowski** [nodejs/node-addon-api#745]
first 2 args are swapped

the docs:
https://github.com/nodejs/node-addon-api/blob/cdb662506c001feed535d9d577f6c535826b8cf7/doc/bigint.md#L82

implementation:
https://github.com/nodejs/node-addon-api/blob/9c9accfbbe8c27f969d569f78758a8c47837321b/napi.h#L388

**Comment by NickNaso** [comment]
@adrian-gierakowski  Thanks for your feedback. I made a PR that fix the inconsistency with the documentation.

**Comment by NickNaso** [comment]
I'm closing the issue because https://github.com/nodejs/node-addon-api/pull/748 has been merged.
