### ISSUE TITLE
How to serialize or deserialize the napi_value?

### ISSUE THREAD

**Issue by samsha1971** [nodejs/node-addon-api#746]
For example, NodeJS v8 module:
  v8. Serialize (value)
  v8. Deserialize (buffer)

In the addon c++ section, how to implement?

**Comment by KevinEady** [comment]
Hi @samsha1971 ,

The v8 serialization API is provided by Node's built-in `v8` module: [Serialization API](https://nodejs.org/api/v8.html#v8_serialization_api).

If you want to use serialization within your native addon, you would have to either:
1. Pass in the `v8` module object as an argument to some method in your addon. Then, call the `serialize` and `deserialize` on it, or..
2. Pass in the individual `serialize` and `deserialize` functions and call them (make sure to bind the to the `v8` object, ie `v8.serialize.bind(v8)` -- I'm not 100% sure the internal methods require the receiver to be the v8 module)

[NB: Regardless of which method you choose, be sure to take care of the lifecycle of `v8` object and/or `[de]serialize` functions passed to your addon. If you do not plan on using them _immediately_ within the scope of the function it is passed in to, you will need to store an `ObjectReference` / `FunctionReference` to properly persist the value across calls to your addon.]

Let us know if you have any additional questions. 

Hope this helps,

Kevin
