### ISSUE TITLE
Is it possible to pass an array to/from Node and c++ rather than making a copy?

### ISSUE THREAD

**Issue by GeorgeNav** [nodejs/node-addon-api#747]
I want to pass an array reference to a c++ function from Node using node-addon-api. The way this node array came to be was dynamically creating an array with variables declaring the size and parsing through a buffer (I confirmed node holds the data that should be in the array) incrementally filling it up. How do I pass the array that is now in Node to c++ without creating a copy? Also, was there a way I could have transferred this array from c++ to Node without making a copy?

```cpp
float *parse_data(char *buffer, long int bufferSize, int resX, int resY, int resZ)
{
  float *data = new float[resX * resY * resZ * 3];

  char *pch;
  float value;
  pch = strtok(buffer, " ");

  int idx = 0;
  while (pch != NULL)
  {
    value = std::atof(pch);
    data[idx] = value;
    pch = strtok(NULL, " ");
    idx++;
  }

  return data;
}
```

The function above is called within the function below
```cpp
Array API_parse_data(const CallbackInfo &info)
{
  Env env = info.Env();
  char *buffer = info[0].As<Buffer<char>>().Data();
  long int bufferSize = info[1].ToNumber().Int32Value();
  long int resX = info[2].ToNumber().Int32Value();
  long int resY = info[3].ToNumber().Int32Value();
  long int resZ = info[4].ToNumber().Int32Value();
  float *result = parse_data(buffer, bufferSize, resX, resY, resZ);

  // Why does this need to be done or can I pass the reference to node?
  Array data = Array::New(env, resX * resY * resZ * 3);
  for (uint32_t i = 0; i < data.Length(); i++)
    data[i] = result[i];
  delete[] result;

  return data; // the array that is confirmed to be in node
}
```

This parse_data function is then called in Node successfully creating the array from a char buffer
```js
const streamlines = require('bindings')('streamlines') // c++ addon target
const coordDataBuffer = Buffer.from(fileBuffer.slice(startIndexOfCoords))
const coords = streamlines.parseData(
  coordDataBuffer,
  coordDataBuffer.length,
  ...result.dimensions,
)
```

Below is where I am trying to pass the array from Node to c++
```js
streamlines.thirdPartyLib(coords) // coords is a 1D array of floats
```

Here is what I have so far
```cpp
String API_third_party_lib(const CallbackInfo &info)
{
  Env env = info.Env();
  Array napiArray = info[0].As<Array>();
  // std::string result = thrid_party_lib(data);
  return String::New(env, "");
}
```

**Comment by NickNaso** [comment]
Hi @GeorgeNav,
what I understood is that you are passing a buffer from JavaScript side to C++ than you parse the buffer and create a new one in the native side through the function:
```cpp
float *parse_data(char *buffer, long int bufferSize, int resX, int resY, int resZ)
```
At the end of your process you have a new buffer of `float` and to return the result you are parsing the buffer to create an array. This could be very expensive task instead you could return the buffer to JavaScript like reported here:
```cpp
Napi::Env env = info.Env();
  char *buffer = info[0].As<Napi::Buffer<char>>().Data();
  long int bufferSize = info[1].ToNumber().Int32Value();
  long int resX = info[2].ToNumber().Int32Value();
  long int resY = info[3].ToNumber().Int32Value();
  long int resZ = info[4].ToNumber().Int32Value();
  float *result = parse_data(buffer, bufferSize, resX, resY, resZ);
  return Napi::Buffer<float>::New(env, result, resX * resY * resZ * 3);
```
Now you can parse your buffer form the JavaScript side using the Node.js buffer api https://nodejs.org/dist/latest-v12.x/docs/api/buffer.html

Hope this information could help you.

**Comment by GeorgeNav** [comment]
@NickNaso Thank you so much! I couldn't find anything on this topic online through around a week of research. This works like a charm.

**Comment by mhdawson** [comment]
@GeorgeNav I assume we can close this now. Please let me know if that is not the case and we can re-open.
