### ISSUE TITLE
BrowserWindow.getNativeWindowHandle from parameter

### ISSUE THREAD

**Issue by deshan** [nodejs/node-addon-api#751]
Hi 
I'm working on the OSX platform, current I'm getting the NSView* passed from JS as a method parameter to NAPI as below.

JS
```
const mainWindow = new BrowserWindow;
const handle = mainWindow.getNativeWindowHandle()
testAddon.testMethod(handle);
```
C++
```
void testMethod(const Napi::CallbackInfo& info) {
     Napi::Buffer<void *> wndHandle = info[0].As<Napi::Buffer<void*>>();
     NSView* view = static_cast<NSView*>(*reinterpret_cast<void **>(wndHandle.Data()));
}
```
This is working but is this the proper way of doing this? Any inbuild support?

Thanks

**Comment by mhdawson** [comment]
I think this would possibly be better asked in the electron repo - https://github.com/electron/electron since it asks about how to convert from an electron object on the JavaScript side to something you can use in native code.

**Comment by KevinEady** [comment]
What about using an [`Napi::External<NSView>`](https://github.com/nodejs/node-addon-api/blob/master/doc/external.md)?

**Comment by gabrielschulhof** [comment]
@deshan it [looks like](https://www.electronjs.org/docs/api/browser-window#wingetnativewindowhandle) the structure of the handle returned from `getNativeWindowHandle()`, is a `Buffer` containing an `NSView*` pointer. So, this looks correct for OSX.

It would be up to the Electron team to provide a native API for Electron bindings.

**Comment by deshan** [comment]
Thanks for all the responses. I am ok with the current method and it works. So closing now.

> What about using an [`Napi::External<NSView>`](https://github.com/nodejs/node-addon-api/blob/master/doc/external.md)?
Any hint to use this how?

**Comment by Lijian1122** [comment]
hello,  do you solve this with  Napi::External<NSView> ?
