### ISSUE TITLE
Weird problem with callbacks

### ISSUE THREAD

**Issue by amunhoz** [nodejs/node-addon-api#755]
The code below is called from a thread many times during the process.
In a stress test, i get "free() invalid pointer / Aborted (core dumped" with this code:
  ```
Napi::Env env = info.Env();    
    Napi::String channeln = info[0].As<Napi::String>();
    std::string channel = info[0].As<Napi::String>().Utf8Value();
    std::function<void(char *, int )> callBackCpp([this, channel ](char * buff, int size) {                                        
        tread_Callback->BlockingCall([channel, buff, size]( Napi::Env env, Function jCallback) {                   
            Napi::Buffer<char> data = Napi::Buffer<char>::New(env, buff,  size);                                       
            jCallback.Call( {Napi::String::New(env, channel), data});  
        });         
    });  
```

But, after i added a integer variable in the lambda scope (test), it works fine.
```
   Napi::Env env = info.Env();    
    Napi::String channeln = info[0].As<Napi::String>();
    std::string channel = info[0].As<Napi::String>().Utf8Value();
    int test = 999; //this variable prevents memory errors in the lambda scope
    std::function<void(char *, int )> callBackCpp([test, this, channel ](char * buff, int size) {                                        
        tread_Callback->BlockingCall([channel, buff, size]( Napi::Env env, Function jCallback) {                   
            Napi::Buffer<char> data = Napi::Buffer<char>::New(env, buff,  size);                                       
            jCallback.Call( {Napi::String::New(env, channel), data});  
        });         
    }); 
```

The tread_Callback variable is declared in the class scope with shared_ptr to prevents other thread problems.

Cant explain why this is happening.

gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
compiling a node addon for node v10.20.1
node-addon-api 3.0.0

**Comment by mhdawson** [comment]
I'd suggest trying to run under Valgrind. There is some info in https://github.com/nodejs/node/blob/master/doc/guides/investigating_native_memory_leak.md as it also provides some options to detect double frees etc.

Also do you have the stack trace from the core dump?

**Comment by gabrielschulhof** [comment]
@amunhoz do you think you could create a minimal example that reproduces the problem and give us a link to the resulting code?
