### ISSUE TITLE
Object Wrap for libseek-thermal

### ISSUE THREAD

**Issue by TannerGilbert** [nodejs/node-addon-api#756]
I want to build a native addon for the [libseek-thermal library](https://github.com/maartenvds/libseek-thermal), which is written in C++.  I took a look at the [object wrap example](https://github.com/nodejs/node-addon-examples/tree/master/6_object_wrap/node-addon-api), but I'm unsure how the same process can be applied to the libseek-thermal library, because it contains multiple classes/subclasses. Can someone give me some advice on how to get started?

**Comment by gabrielschulhof** [comment]
@TannerGilbert IMO it would be best to first decide the JS interface you wish to provide. Currently one cannot create inheritance among JS classes based on ObjectWrap, so the class hierarchy exported to JS would most likely have to be flat. How do you want users' code to look like when they use your library from JS?

Looking briefly at the libseek-thermal library it looks like the public interface consists of the two classes `SeekThermal` and `SeekThermalPro`. Those are the two classes you may wish to provide.

**Comment by TannerGilbert** [comment]
Yeah the ```SeekThermal``` and ```SeekThermalPro``` classes are the two classes that I want for the JS library. So because there is no option to inherite from the ```SeekCam``` class I will have to create the methods that aren't overwriten for both the ```SeekThermal``` and ```SeekThermalPro```?

**Comment by gabrielschulhof** [comment]
If you wish to expose them to JS, then yes.

**Comment by TannerGilbert** [comment]
Thanks for the information. I'll try it out and let you know if I run into any further problems
