### ISSUE TITLE
Documenting node-addon-api functions and classes

### ISSUE THREAD

**Issue by gotnone** [nodejs/node-addon-api#758]
Is there a way to document the functions and classes exposed by a node-addon-api package?  I could not find any examples containing JSdoc style comments.  Searching this repository as well as the node-addon-examples repository for `/**` provided no results.  Thanks for looking into this.

**Comment by mhdawson** [comment]
We discussed this in the N-API team meeting and the short answer is there is no good way that we know of to do what you want which we understood was JS documentation generated from C code.

@jschlight is going to do some investigation and comment as it was an area of interest for him.

**Comment by gotnone** [comment]
Thanks for the response.  If there were a way to document from c++, that would be ideal.  In the near term, is it possible to create JSdoc documentation in the javascript binding script or test script that many of the examples include?  Or do you think that maintaining synchronization between the c++ code and the javascript documentation in another file will be burdensome?

**Comment by jschlight** [comment]
I think the basic issue is that the documentation needs to be written in terms that are meaningful to the JavaScript programmer. This implies a format like JSDoc. But in the case of native addons, the code is written in C++. It's possible to add JSDoc comments to the C++ code. But since the source code is in C++, the programmer does not get the benefit of IDE plugins that facilitate the creation of JSDoc comments from JavaScript code. The JSDoc comments must be manually created by the programmer from scratch. But once created, they provide really helpful information and are straightforward to maintain. What's not clear to me is if there is tooling that is able to extract the JSDoc comments from C++ code in order to get the documentation into a form that is accessible to the JavaScript programmer. This is something I'd like to look into.

**Comment by jschlight** [comment]
The [Node Mapnik](https://github.com/mapnik/node-mapnik) project is embedding JSDoc comments in their NAN C++ files:

https://github.com/mapnik/node-mapnik/blob/699a2724d64bca6e1e50c44837d16b95da329124/src/node_mapnik.cpp#L71-L116

Here's the resulting generated documentation from these JSDoc comments:

http://mapnik.org/documentation/node-mapnik/3.6/

Apparently, the standard [JSDoc](https://github.com/jsdoc/jsdoc) project does not support parsing non-JavaScript files without some additional complexity. Node Mapnik is using [documentation](https://github.com/documentationjs/documentation) as an alternative.

So there is precedent for placing JSDoc comments in C++ binding files and generating documentation from them.

**Comment by jschlight** [comment]
I'd like to research the idea of adding JSDoc-style comments to the examples the next time they're reviewed.

**Comment by helio-frota** [comment]
hi, I read the comments in this issue then I tried to add `documentation` in a personal project, then I saw that c++ support was removed in version 4x (the current version is 13x), with apparent no plans to add support back.

But I added version 4.x in a personal project and this is the result I saw:

- when running we see some warnings like this:

```
$ npm run docs
(node:348692) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:348692) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:348692) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:348692) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
...
```

The resulting html (really basic docs from C code)

![2020-11-27_13-15](https://user-images.githubusercontent.com/6443576/100468465-3ae07580-30b3-11eb-8a19-409ac999f424.png)


When I pass the mouse over a function in vscode:

![2020-11-27_13-19](https://user-images.githubusercontent.com/6443576/100468492-4a5fbe80-30b3-11eb-8086-e3b404e19acf.png)

**Comment by jschlight** [comment]
This is still on my list. I'd like to keep this issue open until I've had the time to look at it.

**Comment by mmomtchev** [comment]
@jschlight @gotnone @helio-frota @mhdawson
I have published the new `documentation-polyglot` plugin :
<https://www.npmjs.com/package/documentation-polyglot>
It requires a plugin framework in `documentation` that has yet to be merged, so one has to use it with my own `@mmomtchev/documentation` until it gets merged (hopefully it will)

The first Node addon to use it is <https://github.com/mmomtchev/exprtk.js> - you can check it for an example
