### ISSUE TITLE
Next 3.x release 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#759]
It's been 2 1/2 months we should review the changes to see if we should do a release

**Comment by NickNaso** [comment]
It's my intention work to make a new release on the weekend and then if all will be good publish it on Monday. Is it good for everyone?

**Comment by mhdawson** [comment]
+1

**Comment by mhdawson** [comment]
NickNaso has mentioned that CI is green, ready to push release after meeting. No objections so @NickNaso will go ahead.

**Comment by NickNaso** [comment]
I'm closing the issue because the release has been published.
