### ISSUE TITLE
markdown docs

### ISSUE THREAD

**Issue by mcollina** [nodejs/node-addon-api#76]
I think documentation in markdown is more user-friendly than the autogenerated one. Given that the API in this modules would likely be very stable, we should probably put the effort.

**Comment by NickNaso** [comment]
Hi everyone,
I agree with @mcollina that have a markdown documentation is better than the autogenerated one. If you want in next month I'll available start writing the documentations. What do you think about? In case have you some specifications to follow?

**Comment by mhdawson** [comment]
There is an effort stated do add documentation. You can follow it here: https://github.com/nodejs/abi-stable-node/issues/280

**Comment by mcollina** [comment]
Definitely! Good work.
