### ISSUE TITLE
Issue taking an ObjectWrap as a paramater in C++ from JS (2.0.2)

### ISSUE THREAD

**Issue by mjmacleod** [nodejs/node-addon-api#761]
I updated to 2.0.2 in the hopes that it might resolve another issue I'm seeing, instead I can't even seem to get my code to work on 2.0.2

In electron my program is creating an instance of an `ObjectWrap`  class `js_foo` (inheriting cpp base class foo) and another instance of another `ObjectWrap` class `js_bar` (inheritinc cpp base class bar)
It calls a function on `js_foo` that takes `js_bar` and various other data as a parameters, it maps the other parameters to integer/boolean etc. fine but when it tries to map the instance of `bar` it ends up with a pointer to an invalid c++ object that crashes the program if manipulated in any way.
The code looks like this `std::shared_ptr<bar> arg_6(Napi::ObjectWrap<js_bar>::Unwrap(info[6].As<Napi::Object>()));`

This same code appears to work okay in 2.0.0 or 2.0.1 - is there something I might need to change to have it operate with 2.0.2, or any ideas what I might be doing wrong?

**Comment by mjmacleod** [comment]
I see now that my issue is springing from the inheritance.
If I have `class JSFoo: public ::Foo, public Napi::ObjectWrap<JSFoo> {...}` (where `Foo` is a pure abstract class) then `std::shared_ptr<Foo> arg_6(Napi::ObjectWrap<JSFoo>::Unwrap(info[6].As<Napi::Object>()));` seems to present problems.

If I drop the inheritance and have `class JSFoo: public Napi::ObjectWrap<JSFoo> {...}` then I can unwrap and have things work as expected, however I then have to modify my whole codebase to work with `JSFoo` and can't pass a pointer to the abstract interface around instead.

Is it the case that ObjectWrap simply doesn't work with inheritance like this, or am I doing something wrong, e.g. maybe the way I Unwrap isn't correct?

**Comment by mhdawson** [comment]
2.0.2 does have some changes related to objectwrap https://github.com/nodejs/node-addon-api/compare/2.0.1...2.0.2  @gabrielschulhof should any of those interacted with inheritance?

**Comment by gabrielschulhof** [comment]
We fixed multiple inheritance-related issues in ba7ad37 which was part of the 3.0.1 release. Unfortunately, we had to roll back that release because of Windows issues. We should have a release containing that fix out the door soon.

**Comment by mhdawson** [comment]
@gabrielschulhof not sure I follow, this issues is about version 2.0.2 introducing issues over 2.0.1?

**Comment by gabrielschulhof** [comment]
@mhdawson yes, however, multiple inheritance is involved, and, from @mjmacleod's [comment](https://github.com/nodejs/node-addon-api/issues/761#issuecomment-655783989) it looks like the multiple inheritance is of the form `class X: public super_X, public ObjectWrap<X>` which is precisely what the above-mentioned commit addresses: https://github.com/nodejs/node-addon-api/pull/732/files#diff-fd0325c3646730a23b399f0ecbc80350R10

**Comment by mjmacleod** [comment]
Okay good to know there is an issue/fix, that does look like exactly what I experienced, thanks!

**Comment by mhdawson** [comment]
@mjmacleod are you ok if we close this out now?

**Comment by mjmacleod** [comment]
Sure, thanks, I'll reopen if it continues in future releases
