### ISSUE TITLE
How to return a created ObjectWrap

### ISSUE THREAD

**Issue by major-mayer** [nodejs/node-addon-api#770]
Hi,
I'm trying to figure out how to return a ObjectWrap object that I would like to create inside the C++ wrapper.

Currently my workflow is like this:

Wrapper:
```
Napi::Value MeshToolKit::ReadFileSTL(const Napi::CallbackInfo& info) try
{
   // InputMesh has to be created before and passed as a parameter
    auto inputMesh =  MeshHandle::Unwrap(info[1].As<Napi::Object>()); 
    
   //Processing on the inputMesh
    inputMesh->setNative(mwMeshToolkit::ReadFileSTL(info[0].As<Napi::String>()));
    
    // Returning boolean works but not returning the created ObjectWrap
    return Napi::Boolean::From( info.Env(), true);
}
```

Javascript:
```
let input= new binding.MeshHandle();
binding.MeshToolKit.ReadFileSTL("test.stl", inputMesh);
```

As you can see i always have to create the the MeshHandle (which extends ObjectWrap) object seperatly, before i can pass it to the ReadFileSTL method.
What i would like to do, is that a new MeshHandle object is created in the ReadFileSTL method and then returned as a ObjectWrap/ Javascript-compatible object.

I already tried something like this (in the Wrapper), but it didn't work: 
```
MeshHandle inputMesh (info);
return inputMesh.Value();
```

Can someone point me out to the right documentation part/ example/ a quick explanation?

**Comment by mhdawson** [comment]
I think the problem may be is that you are not using ObjectWrap as intended.

The native ObjectWrap is tied to a JavaScript constructor so you should not be creating the ObjectWrap on its own, instead creating an instance of the JS object it is tied to.

In the method Init:: method you call DefineClass and that returns a Napi::Function which is the constructor. If you want to create instances on the native side instead of in JS you should use that constructor (see https://github.com/nodejs/node-addon-api/blob/master/doc/function.md#methods) to create a new instance.

The expected pattern is also that methods that need to unwrap are methods on the JS Object as opposed to some other object unwrapping it. In this case you don't need to call unwrap as that will be done for you when the native method is invoked on the JS Object. This is an example: https://github.com/nodejs/node-addon-examples/tree/master/6_object_wrap/node-addon-api

**Comment by major-mayer** [comment]
Sorry for my delayed response. I hadn't had time to try out your proposed workaround, but I will do it asap.
Thank you very much for the explanation.

**Comment by Ayzrian** [comment]
Hey. I am trying to create an ObjectWrap instance inside the C++ code. 
I am using the constructor function in the following way.
`Napi::Value v = NodeAppLaunchRequestMsg::constructor.Call(Napi::Object::New(env), {});`
But I still get the error that Constructor has to be called with a `new` keyword.

**Comment by NickNaso** [comment]
Hi @Ayzrian,
I think you should call the constructor like this:

```cpp
YourConstructor.New({ Napi::Object::New(env) });
```
if your constructor is a pointer you should call:

```cpp
YourConstructor->New({ Napi::Object::New(env) });
```

I hope this help.

**Comment by Ayzrian** [comment]
> Hi @Ayzrian,
> I think you should call the constructor like this:
> 
> ```c++
> YourConstructor.New({ Napi::Object::New(env) });
> ```
> 
> if your constructor is a pointer you should call:
> 
> ```c++
> YourConstructor->New({ Napi::Object::New(env) });
> ```
> 
> I hope this help.

I have tried to do `NodeAppLaunchRequestMsg::constructor.Call({ Napi::Object::New(env) });` 
Where constructor is a `FunctionReference`
The error is the following. 
`TypeError: Class constructors cannot be invoked without 'new'
    at Object.<anonymous> (C:\Projects\Epic Games\ipc-node-addon\index.js:28:23)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11`

**Comment by Ayzrian** [comment]
> Hi @Ayzrian,
> I think you should call the constructor like this:
> 
> ```c++
> YourConstructor.New({ Napi::Object::New(env) });
> ```
> 
> if your constructor is a pointer you should call:
> 
> ```c++
> YourConstructor->New({ Napi::Object::New(env) });
> ```
> 
> I hope this help.

Thank you. It works! )

**Comment by Ayzrian** [comment]
> Hi @Ayzrian,
> I think you should call the constructor like this:
> 
> ```c++
> YourConstructor.New({ Napi::Object::New(env) });
> ```
> 
> if your constructor is a pointer you should call:
> 
> ```c++
> YourConstructor->New({ Napi::Object::New(env) });
> ```
> 
> I hope this help.

I have another question, Is there is a way to pass extra args to constructor call?

**Comment by Ayzrian** [comment]
> > Hi @Ayzrian,
> > I think you should call the constructor like this:
> > ```c++
> > YourConstructor.New({ Napi::Object::New(env) });
> > ```
> > 
> > 
> > if your constructor is a pointer you should call:
> > ```c++
> > YourConstructor->New({ Napi::Object::New(env) });
> > ```
> > 
> > 
> > I hope this help.
> 
> I have another question, Is there a way to pass extra args to constructor call?
> Also another one. Is there a way to call native function once I constructed the instance.
> `Napi::Object res = NodeAppLaunchRequestMsg::constructor.New({ Napi::Object::New(env) }); res.As<ObjectWrap<NodeAppLaunchRequestMsg>>().Value(); // I want to call NodeAppLaunchRequestMsg::SetInternalInctance() method `

Okey, I have solved this one. The idea is that `constructor.New({})` accepts args, as a param, and you do not have to pass a new object to; 
My solution = `NodeAppLaunchRequestMsg::constructor.New({ Napi::External<FAppLaunchRequestMsg>::New(env, message) });`

**Comment by major-mayer** [comment]
Okay thanks for your help all of you :+1: 
I've finally managed to create an ObjectWrap inside the C++ method by using the constructor, as @mhdawson pointed out.
But i still don't really understand how to avoid using the unwrap function when i want to call a method of the wrapped object.

This is how i do it atm:
```
     // Create a Javascript MeshHandle wrapper and unwrap it to use it on c++ side
    auto v  = MeshHandle::constructor.New({Napi::Object::New(info.Env())});
    auto inputMesh = MeshHandle::Unwrap(v);

    // Load the STL file into the meshHandle
    inputMesh->setNative(mwMeshToolkit::ReadFileSTL(info[0].As<Napi::String>()));
    
    return v;
``` 
@mhdawson said, that it's not necessary to call the unwrap function, but without doing it I can't access the member functions of the MeshHandle object(-wrap).

**Comment by mhdawson** [comment]
My comment was that if you are using the ObjectWrap pattern as intended, calling the JavaScript method invokes the C++ method on the class instance and you can use `this` without having to do the unwrap yourself.  

If you are creating the wrapper and trying to get the wrapped C++ object when you've not called a method on that object from JavaScript you would still need to unwrap.

**Comment by major-mayer** [comment]
All right thanks for the clarification :)
