### ISSUE TITLE
add windows CI to Improve stability

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/node-addon-api#771]
Currently windows build is break due to 3.0.1 release.

This is also caught by our daily CI in [node-addon-examples](https://github.com/nodejs/node-addon-examples/actions) (I got the failed email notification everyday 4 days ago, I guess a good thing). 

I think add related CI for this repo like we did in `node-addon-examples`. Any thought ?

**Comment by mhdawson** [comment]
We do have testing her, but we obviously don't have a test that catches the problematic case: https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-LTS%20versions/

So first thing is to make sure we add some test cases that cover the different include use cases (spaces, multiple etc.)
