### ISSUE TITLE
Not able to access buffer from js after some processing done

### ISSUE THREAD

**Issue by srikanthkampati** [nodejs/node-addon-api#774]
Hi,
I am new to Napi and writing Napi wrapper to my .lib file. I am able to build .node file for my .lib library.
The main objective of the native code is it takes the input buffer from js and hold it until the entire buffer processing is done.
 after some iterations, the buffer is not visible to native code. but native code and Napi wrapper are working for small buffers of size less than 10kb internal native code copy a 10kb data from the buffer from js.

Is there any way I can make the lifespan of the buffer persistent or how to create persistent references for the buffer to have a lifespan longer than that of the native method.

**Comment by srikanthkampati** [comment]
code snippet 

Napi::Buffer<unsigned char> buffer = info[0].As<Napi::Buffer<unsigned char>>();
i have taken the buffer as above and passing it to a native class to hold the referance.

void process_api::Read(const Napi::CallbackInfo& info)
calls the native code read and return a object to js

**Comment by NickNaso** [comment]
Hi @srikanthkampati,
normally the lifespan of an object corresponds to the lifespan of a native method. At the end of the execution of your native method the object is ready to be collected. If you need to access to an object you need to store it like a reference through the `Napi::Reference` api. 

See:
 
- [`Napi::Reference`](https://github.com/nodejs/node-addon-api/blob/master/doc/reference.md) 
- [`Napi::ObjectReference`](https://github.com/nodejs/node-addon-api/blob/master/doc/object_reference.md)

Es.
```cpp
class Process {
    void Read(const Napi::CallbackInfo& info) {
        Napi::Buffer buffer = info[0].As<Napi::Buffer>();
        ref = Napi::ObjectReference::Persistent(buffer);
        // ...
    }
    private:
        Napi::Reference ref;
}
```

I hope that this is helpful to you.

**Comment by srikanthkampati** [comment]
I am getting the following error


1: 00007FF7AA5D538F napi_wrap+114751
 2: 00007FF7AA57FE26 v8::base::CPU::has_sse+66646
 3: 00007FF7AA580C26 v8::base::CPU::has_sse+70230
 4: 00007FF7AA580409 v8::base::CPU::has_sse+68153
 5: 00007FF7AA5A5A30 napi_fatal_error+160
 6: 00007FFD47DB4047 Napi::Error::Fatal+23 [c:\users\skampati\desktop\vs_2017_addon\node_modules\node-addon-api\napi-inl.h]:L2172
 7: 00007FFD47DB418E Napi::Error::ThrowAsJavaScriptException+318 [c:\users\skampati\desktop\vs_2017_addon\node_modules\node-addon-api\napi-inl.h]:L2246
 8: 00007FFD47DB5438 process::ReadMessage+1944 [c:\users\skampati\desktop\vs_2017_addon\lib\pimtpdecoder\src\process.cpp]:L83
 9: 00007FFD47DB7120 Napi::ObjectWrap<pimtp_api>::InstanceVoidMethodCallbackWrapper+176 [c:\users\skampati\desktop\vs_2017_addon\node_modules\node-addon-api\napi-inl.h]:L3815
10: 00007FF7AA5B1763 node::Stop+29907
11: 00007FF7AAD497D0 v8::internal::Builtins::builtin_handle+323456
12: 00007FF7AAD48D17 v8::internal::Builtins::builtin_handle+320711
13: 00007FF7AAD49058 v8::internal::Builtins::builtin_handle+321544
14: 00007FF7AAD48E5E v8::internal::Builtins::builtin_handle+321038
15: 00007FF7AB1EA19D v8::internal::SetupIsolateDelegate::SetupHeap+546893
16: 00007FF7AB16F04C v8::internal::SetupIsolateDelegate::SetupHeap+42748
17: 00007FF7AB16F04C v8::internal::SetupIsolateDelegate::SetupHeap+42748
18: 00007FF7AB16F04C v8::internal::SetupIsolateDelegate::SetupHeap+42748
19: 00007FF7AB16F04C v8::internal::SetupIsolateDelegate::SetupHeap+42748
20: 00007FF7AB16F04C v8::internal::SetupIsolateDelegate::SetupHeap+42748
21: 00007FF7AB16F04C v8::internal::SetupIsolateDelegate::SetupHeap+42748
22: 00007FF7AB16F04C v8::internal::SetupIsolateDelegate::SetupHeap+42748
23: 00007FF7AB16C581 v8::internal::SetupIsolateDelegate::SetupHeap+31793
24: 00007FF7AB16C16C v8::internal::SetupIsolateDelegate::SetupHeap+30748
25: 00007FF7AACA3813 v8::internal::Execution::CallWasm+1395
26: 00007FF7AACA3196 v8::internal::Execution::Call+182
27: 00007FF7AAD7421D v8::Function::Call+605
28: 00007FF7AA5A6F3C napi_unref_threadsafe_function+3068
29: 00007FF7AA5A9CCA node::Start+1146
30: 00007FF7AA5A9F07 node::Start+1719
31: 00007FF7AA5A855A node::LoadEnvironment+26
32: 00007FF7AA53682F v8::internal::UnoptimizedCompilationInfo::feedback_vector_spec+31679
33: 00007FF7AA5A9963 node::Start+275
34: 00007FF7AA416A9C RC4_options+340380
35: 00007FF7AB2A2188 v8::internal::SetupIsolateDelegate::SetupHeap+1300536
36: 00007FFDAA9881F4 BaseThreadInitThunk+20
37: 00007FFDACE8A251 RtlUserThreadStart+33

**Comment by gabrielschulhof** [comment]
@srikanthkampati 
> i have taken the buffer as above and passing it to a native class to hold the referance.
Can you share the code in which you pass it to the native class to hold the reference?

**Comment by srikanthkampati** [comment]
void process_buffer::Readbuffer(const Napi::CallbackInfo& info) {
	Napi::Env env = info.Env();
	Napi::EscapableHandleScope scope(env);

	StreamInterface* bis;
	Napi::Object js_obj;
	Napi::Object jsobj = Napi::Object::New(env);

	Napi::Function cb;

   Napi::Buffer<unsigned char> buffer = info[0].As<Napi::Buffer<unsigned char>>();
   
   ref = Napi::ObjectReference::New(buffer, 0);
   data = buffer.Data();
   unsigned int size = info[1].ToNumber();
   bis = new StreamInterface((UCHAR *)buffer.Data(), size, size);//passing buffer to native library class
   js_obj = info[2].As<Napi::Object>();
   cb = info[3].As<Napi::Function>();
   
    processbuffer *pProcess = new processbuffer(bis);
	
   do {

			bool status = pProcess->Read(&datastruc);//calling native library read function
      }while(status == false)
      
      //fill the js_obj;
      //call call_back function;
}

**Comment by srikanthkampati** [comment]
In my native c++ library, I have a stream interface class to hold the unsigned char pointer and have methods to read data from that char buffer.
Other classes in the library use the read stream method of stream interface to get data and process the data and fill a structure.

so my use case is node.js pass a buffer and a callback function to the native library, and now native library will process that and create a js object and return through a callback function.

can you suggest a good way to do this use case?

**Comment by srikanthkampati** [comment]
I tried in the following way it is able to process the data buffer of 300kb but when I pass a buffer more than 300kb it is giving fatal error, as above mentioned.

void tranportdata_api::ReadMessage(const Napi::CallbackInfo& info) {
	Napi::Env env = info.Env();
	Napi::HandleScope scope(env);

	int length = info.Length();
   
	InputStreamInterface* bis;
	Napi::Object js_obj;
	Napi::Object jsobj = Napi::Object::New(env);

	Napi::Function cb;

	if (info[0].IsBuffer() && info[1].IsNumber() && length == 4)
	{
		Napi::Buffer<unsigned char> buffer = info[0].As<Napi::Buffer<unsigned char>>();
		
		ref_b = Napi::Reference< Napi::Buffer<unsigned char>>::New(buffer, 1);
		ref_b = Napi::Persistent(ref_b.Value());
		ref_b.SuppressDestruct();
		data = ref_b.Value().Data();
		unsigned int size = info[1].ToNumber();
		bis = new InputMemoryStream(data, size, size);
		js_obj = info[2].As<Napi::Object>();
		cb = info[3].As<Napi::Function>();
	}

	transportdecoder *TP = new transportdecoder(bis);

	BaseTransportData *BTD = NULL;
	StreamReadStatus srs;
	int index = 1;
	do {
		

		try {
			srs = TP->ReadMessage(&BTD);
		}
		catch (...) {
		
			Napi::TypeError::New(env, "buffer not available").ThrowAsJavaScriptException();
		}
		//call a function to fill the js object
      if (srs.bEOS == false)// check for end of stream and call the call back function
		{
			dsrs.bEOS = false;
			cb.Call({ js_obj });
		}

	} while (srs.bEOS == false);
}
