### ISSUE TITLE
Refactor test/threadsafe_function/threadsafe_function.js with async/await

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/node-addon-api#776]
Doing so would increase clarity.

**Comment by iandrc** [comment]
@gabrielschulhof I would like to try this one

**Comment by gabrielschulhof** [comment]
Marking as "good first issue" because this does not involve changing the native code, but only the JS portion of the test.

**Comment by Velmisov** [comment]
@iandrc Are you still working on it, or can I take it?

**Comment by iandrc** [comment]
Hey @Velmisov 

It's WIP right now. I'll try to finish this one asap, just don't allocate enough time for this task right now.

**Comment by mhdawson** [comment]
Closing as its now complete
