### ISSUE TITLE
Question about memory usage/leak and AsyncWorker

### ISSUE THREAD

**Issue by manuel-arguelles** [nodejs/node-addon-api#780]
Hi,

I'm following the example of the use of the AsyncWorker, https://github.com/nodejs/node-addon-examples/blob/master/async_pi_estimate/node-addon-api/async.cc

I'm curious about how or when the object created on line 33 (piWorker) gets destroyed? At first glance, it seems like a memory leak.

**Comment by NickNaso** [comment]
Hi @manuel-arguelles,
the example should be good. When the `Napi:.AsyncWorker::OnWorkComplete` method will be called and inside it `Napi::AsyncWorker::Destroy` method will be called and will provide to delete the `Napi::AsyncWoerker` instance.
See: https://github.com/nodejs/node-addon-api/blob/master/napi-inl.h#L4318
Hipe that this is helpful to you.

**Comment by manuel-arguelles** [comment]
@NickNaso it does, thanks a lot!
