### ISSUE TITLE
Improvements to CONTRIBUTING.md

### ISSUE THREAD

**Issue by iandrc** [nodejs/node-addon-api#781]
I think it would be nice to add some more detailed guidelines on how to create issues/pull requests as the `node` repo does. May be helpful for future contributors and will help to unify the source code management. 

Still, correct me if I'm wrong. Just suggesting.

Refs: https://github.com/iandrc/node/blob/master/doc/guides/contributing/issues.md
Refs: https://github.com/iandrc/node/blob/master/doc/guides/contributing/pull-requests.md

**Comment by mhdawson** [comment]
Seems, reasonable, we'll need a volunteer..
