### ISSUE TITLE
How to create a array of object in Napi

### ISSUE THREAD

**Issue by srikanthkampati** [nodejs/node-addon-api#782]
Napi::Array Data = Napi::Array::New(env);
Napi::Object obj = Napi::Object::New(env);
for (int i = 0; i < 5; i++)
{
	obj.Set("value", i);
	Data[i] = obj;
}
local_obj.Set("Data", Data);

I tried the above code and i am getting the output as follow:
{"Data":[{"value":4},{"value":4},{"value":4},{"value":4},{"value":4}]}
but what i am expecting is
{"Data":[{"value":0},{"value":1},{"value":2},{"value":3},{"value":4}]}
why it is always over written with last value
how can in create a array of objects

**Comment by NickNaso** [comment]
Hi @srikanthkampati,
the behaviour that you reported is right. You are passing the same object to the array and at every iteration you are changing a property of that object. Maybe a possible solution could be:

```cpp
Napi::Array Data = Napi::Array::New(env);
for (int i = 0; i < 5; i++)
{
Napi::Object obj = Napi::Object::New(env);
obj.Set("value", i);
Data[i] = obj;
}
local_obj.Set("Data", Data);
```
If you think well what you reported is the same that happen in the following JavaScript code:

```js
const data = []
const obj = {}
for (let i = 0; i < 5; i++) {
    obj.value = i
    data.push(obj)
}
```
I hope that this help you.

**Comment by srikanthkampati** [comment]
Thank you it helped me.
