### ISSUE TITLE
gcc armhf build triggers cast-align warning

### ISSUE THREAD

**Issue by JulZimmermann** [nodejs/node-addon-api#783]
The member function `DataView::ReadData` in `napi-inl.h` uses reinterpret_cast to convert the `void*` `_data` object into type `T` at position `byteOffset`.

The code looks like this:

```
 return *reinterpret_cast<T*>(static_cast<uint8_t*>(_data) + byteOffset);
```

I try to build an application which is using node-addon-api with the arm-linux-gnueabihf-g++-8 compiler and `-Wcast-align` enabled.

I get the following warning:

```
../node_modules/node-addon-api/napi-inl.h: In instantiation of ‘T Napi::DataView::ReadData(size_t) const [with T = float; size_t = unsigned int]’:
../node_modules/node-addon-api/napi-inl.h:1417:36:   required from here
../node_modules/node-addon-api/napi-inl.h:1488:11: error: cast from ‘uint8_t*’ {aka ‘unsigned char*’} to ‘float*’ increases required alignment of target type [-Werror=cast-align]
   return *reinterpret_cast<T*>(static_cast<uint8_t*>(_data) + byteOffset);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The warning looks correct to me. Using reinterpret_cast this way can cause aligning problems on 32bit platforms (like armhf) as far as I know.

Should the `reinterpret_cast` be replaced with `memcpy`, or is this a false positive?

**Comment by mhdawson** [comment]
@JulZimmermann I don't think we want to replace a cast with a memcpy. Can you give a more complete example of the cast ending up with the wrong alignment?
