### ISSUE TITLE
how to call a function from thread safe call back function

### ISSUE THREAD

**Issue by srikanthkampati** [nodejs/node-addon-api#785]
I am calling a function from a thread safe function to process the data but unexpectedly tread is ending.
code snippet:
auto callback = [ ](Napi::Env env, Function jsCallback, process* value)
 {
 Object loc_obj = Object::New(env);
 Object js_obj = Object::New(env);
 DataToJSObj(env, loc_obj, value);
 js_obj.Set("Message", obj_ref.Value());
 jsCallback.Call({ js_obj });
};

but instead of calling a function if I convert the data in thread safe function thread was ending after the complete execution.

**Comment by mhdawson** [comment]
I think we'd need a more complete example to be able to investigate further.

Have you looked at this example: https://github.com/nodejs/node-addon-examples/tree/master/thread_safe_function_round_trip/napi ?
