### ISSUE TITLE
Do we need doc/working_with_javascript_values.md?

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/node-addon-api#797]
This file is referenced from README.md and consists of a small blurb and of links to a few classes:

[doc/working_with_javascript_values.md](https://github.com/nodejs/node-addon-api/blob/master/doc/working_with_javascript_values.md)

**Comment by gabrielschulhof** [comment]
At the very least it seems incomplete. It documents that node-addon-api provides some classes that help with manipulating JS values, and then lists some classes. Yet we have many more classes that help with manipulating JS values than that, and they are amply documented.

**Comment by mhdawson** [comment]
From discussion in the N-API team meeting today with https://github.com/nodejs/node-addon-api/pull/798, it seems like it well covered so this can be removed.
