### ISSUE TITLE
Napi runtime flag causing include path error for node-addon-api

### ISSUE THREAD

**Issue by sampsongao** [nodejs/node-addon-api#80]
After I `export NODE_OPTIONS=--napi-modules` and invoke `npm install` on module including node-addon-api module. npm always complain with this error message. 
```
gyp: Call to 'node -p "require('node-addon-api').include"' returned exit status 0
while in binding.gyp. while trying to load binding.gyp
```

**Comment by mhdawson** [comment]
I think this has been resolved, closing. Please let us know if this is not the right thing to do.
