### ISSUE TITLE
namespace "Napi" has no member class "Addon"

### ISSUE THREAD

**Issue by JKKGBE** [nodejs/node-addon-api#801]
At 3.0.0 I'm unable to follow [addon.md](https://github.com/nodejs/node-addon-api/blob/master/doc/addon.md) due to `Addon` missing. The message comes from Visual Studio Code.

When building with `node-gyp` I also get:
```
.cpp:5:34: error: expected template-name before ‘<’ token
    5 | class ExampleAddon : public Napi::Addon<ExampleAddon>
      |                                        ^
.cpp:5:34: error: expected ‘{’ before ‘<’ token
.cpp:5:34: error: expected unqualified-id before ‘<’ token
.cpp:28:22: error: expected constructor, destructor, or type conversion at end of input
   28 | NODE_API_ADDON(ExampleAddon)
      |                            ^
```

What am I missing here? `hello` example is working.

**Comment by gabrielschulhof** [comment]
@JKKGBE you must build against a version of Node.js that has at least N-API version 6.

The column labelled "6" at https://github.com/nodejs/node/blob/master/doc/api/n-api.md#n-api-version-matrix gives you the versions of Node.js that were the first to support N-API version 6. If you look at https://nodejs.org/docs/latest-v14.x/api/n-api.html#n_api_napi_set_instance_data it shows you earlier versions which had the API, but in which the API was marked as experimental. If you build against any version of Node.js between the one where it first appeared (as listed in the second link) and the one where it was first marked as stable (listed in the first link), then you must

```cpp
#define NAPI_EXPERIMENTAL
#include "napi.h"
```

That is, you must prefix your inclusion of `napi.h` with the definition of the `NAPI_EXPERIMENTAL` preprocessor directive.

**Comment by JKKGBE** [comment]
Thank you, all clear.
