### ISSUE TITLE
How to call a javascript object method from C++ code

### ISSUE THREAD

**Issue by simoneperelli** [nodejs/node-addon-api#802]
Hi, 
I am porting a medium-sized old native addon to NAPI. Inside of this addon there is an event emitter object (built similarly to @NickNaso examples) and native functions that call this event emitter's methods.

The existing implementation uses node::MakeCallback to call the "emit" on JS side.

Looking at the various examples and issues I couldn't figure out how to initiate such a call with NAPI from C++ since I would need to pass a reference to Env. Would it make sense to store Env as a property in the Event Emitter and reuse that once I need to call methods from C++ ?

**Comment by fholzer** [comment]
When you need to call the javascript function, is that as a result of javascript call to your addon? (ie. is there some other javascript on the stack?)

**Comment by simoneperelli** [comment]
Hi @fholzer thank you for answering. No unfortunately I do not have access to the CallbackInfo. 
We are mostly talking about system events like tracking the mouse movement so the call is going to be made by pure C++ code.

**Comment by fholzer** [comment]
I think you'll probably need to use [ThreadSafeFunction](https://github.com/nodejs/node-addon-api/blob/master/doc/threadsafe_function.md)

When talking about javascript calls from additional threads, that doesn't necessarily mean threads that you directly start yourself. Could also be threads started by some other library your addon uses.

**Comment by gabrielschulhof** [comment]
If you're calling from a non-N-API callback into JS on the same thread as JS, you can use [`MakeCallback`](https://github.com/nodejs/node-addon-api/blob/master/doc/function.md#makecallback).

If you're calling from a non-N-API callback into JS from a different thread, you can convert the `Napi::Function` you wish to call to a [`ThreadSafeFunction`](https://github.com/nodejs/node-addon-api/blob/master/doc/threadsafe_function.md) and call that from any thread.

**Comment by simoneperelli** [comment]
Thank you @fholzer and @gabrielschulhof. I believe MakeCallback will do. I see from the docs that I need to pass the `this` (as Napi Value) representing the object but I am not sure how would I obtain it in this case.

I have a class that inherits from EventEmitter similarly to [this example](https://github.com/NickNaso/addon-event-emitter/blob/master/01/src/native-emitter.cc). I can see that in there the `This` is obtained through the CallbackInfo but again I am not going to have that

**Comment by gabrielschulhof** [comment]
@simoneperelli do you need to have a `This`? If you have a `FunctionReference` you can call `MakeCallback` with `Napi::Env::Undefined()` as your `This`.

**Comment by gabrielschulhof** [comment]
... and if you need to have a `This` you can create a reference to it and pass it along to wherever you call `MakeCallback`.

**Comment by simoneperelli** [comment]
Thank you @gabrielschulhof will give it a try

**Comment by gabrielschulhof** [comment]
@simoneperelli hopefully my suggestion worked for you. If it did not, and you believe we need to change node-addon-api or add something to it to better support your use case, please re-open this issue!

**Comment by simoneperelli** [comment]
@gabrielschulhof Thank you !
