### ISSUE TITLE
Next release for node-addon-api

### ISSUE THREAD

**Issue by NickNaso** [nodejs/node-addon-api#809]
Release will be **3.0.2**

# PRs to land.

- [x] Introduce `include_dir` for use with gyp in a scalar context  **[766](https://github.com/nodejs/node-addon-api/pull/766)**

- [x] doc: add inheritance links and other changes **[798](https://github.com/nodejs/node-addon-api/pull/798)**

- [x] test: added test case to check the addon building process **[808](https://github.com/nodejs/node-addon-api/pull/808)**

- [x] test: fixed the execution for the threadsfafe function test **[807](https://github.com/nodejs/node-addon-api/pull/807)**

- [x] doc: remove a file **[815](https://github.com/nodejs/node-addon-api/pull/815)**

# Possibly also include:

- [ ] tsfn: implement ThreadSafeFunctionEx **[742](https://github.com/nodejs/node-addon-api/pull/742)**

This release will resolve some issues remember to close them:

- [769](https://github.com/nodejs/node-addon-api/issues/769)
- [765](https://github.com/nodejs/node-addon-api/issues/765)
- [796](https://github.com/nodejs/node-addon-api/issues/796)

**Comment by mhdawson** [comment]
Discussed in the meeting today, we'll leave 742 for 3.1 as we want to get out a SemVer patch to replace the broken 3.0.1

**Comment by mhdawson** [comment]
@NickNaso looks like we should be ready to do the release !

**Comment by NickNaso** [comment]
I'm starting to work on release **3.0.2**.

**Comment by NickNaso** [comment]
I'm closing because the v3.0.2 has been released.
