### ISSUE TITLE
Publish new version of NPM

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#81]
I've landed the outstanding PRs include the one to fix breakage due to the errors change in node core.  We should publish an update npm package

@kfarnung  @jasongin  we might want to get this one reviewed/landed as part of that:

https://github.com/nodejs/node-addon-api/pull/77

@sampsongao how do you usually test the conversion script ?

I'm done for today but if nobody beats me to it I'll look to see if I can publish on Monday.

**Comment by mhdawson** [comment]
@jasongin can you add me (mhdawson1 on npm) as a collaborator on https://www.npmjs.com/package/node-addon-api so that I can publish if necessary.  I could dig out the foundation id/password and do it myself but that would take me longer to do.

**Comment by jasongin** [comment]
@mhdawson I added you as a package owner. Sorry for the delay.

**Comment by mhdawson** [comment]
landed updated conversion script and published to npm
