### ISSUE TITLE
Cannot use Env::SetInstanceData

### ISSUE THREAD

**Issue by kaysonwu** [nodejs/node-addon-api#810]
[napi_set_instance_data](https://nodejs.org/dist/latest/docs/api/n-api.html#n_api_napi_set_instance_data) Added in: v12.8.0, v10.20.0 N-API version: 6.

The following is my version information：

nodejs: 12.14.1
NAPI_VERSION: 5

**Comment by kaysonwu** [comment]
Currently using NAPI_VERSION judgment, so I cannot use Env::SetInstanceData.

**Comment by NickNaso** [comment]
Hi @kaysonwu,
the function `napi_set_instance_data` was added for the first time in Node.js version v12.8.0 and v10.20.0. At that time the function was considered like experimental and then it has been promoted like stable api with N-API version 6. 
You should always refer to NAPI_VERSION to identify what function is available. 
In you specific case the function was available, but experimental so you can try to set `NAPI_VERSION` to `6` and define the `NAPI_EXPERIMENTAL`.
In your `binding.gyp` file:
```
{
   "targets": [
        {
            "defines": [ "NAPI_EXPERIMENTAL", "NAPI_VERSION=6" ],
        }
   ]
}
```
I hope that this help you.

**Comment by kaysonwu** [comment]
thanks!
