### ISSUE TITLE
Buffer Question

### ISSUE THREAD

**Issue by Alexander9673** [nodejs/node-addon-api#812]
Hi so im reading some docs for `node-addon-api` and i found this
```cpp
static Napi::Buffer<T> Napi::Buffer::New(napi_env env,
                     T* data,
                     size_t length,
                     Finalizer finalizeCallback);
```
i was thinking what `Finalizer` could be.
while i did find this
```
[in] finalizeCallback: The function to be called when the Napi::Buffer is destroyed. It must implement operator(), accept a T* (which is the external data pointer), and return void.\
```
i'm confused on how to implement it, i tried adding a function, where that function is 
```cpp
void buffer_finalizer(unsigned char* data, void* hint)
```
and it didn't work, anyone knows a fix?

**Comment by Alexander9673** [comment]
Also, may i ask is it possible to manually free the data of the buffer?

**Comment by mhdawson** [comment]
@Alexander9673 what do you mean by `it didn't work` .  The finalizer should be called only once the object is no longer referenced AND the gc runs and cleans it up.  There are generally no guarantees as to when the gc will run.  You can ask that it run, but it's still not 100% guaranteed it will clean up the object if it does run. 

You can look at the code in this test https://github.com/nodejs/node-addon-api/blob/master/test/buffer.js, lines 42-54 where it tests the buffer with finalizer functionality.

In terms of `Also, may i ask is it possible to manually free the data of the buffer?`, it's up to the gc to clean up the buffer, and you should do any native (C++) level cleanup in the finalizer.

**Comment by gabrielschulhof** [comment]
@Alexander9673 hopefully @mhdawson's suggestion helped you with the problem you were facing. Please re-open the issue if you believe that functionality needs to be added or changed in node-addon-api to better support your use case!
