### ISSUE TITLE
Requiring node.js modules from native code using N-API

### ISSUE THREAD

**Issue by IanMcCurdy** [nodejs/node-addon-api#817]
Hi, I'm writing an add-on using N-API and would like to use other modules from the C++ code. Specifically, I want to set up a socket using the net module, so I need a way to 'translate' the following into C++ using N-API:
```
var net = require('net');
```
In order to access the 'require' function I tried this:
```
napi_value global, require;
napi_get_global(env, &global);
napi_get_named_property(env, global, "require", &require);
```
But after some research, it seems that 'require' is not actually a global, but rather a 'pseudo-global' that can be accessed through the module object in node. Is there a way to access this module object or otherwise call require using N-API?

Thanks!

**Comment by devsnek** [comment]
I would suggest making a JS function which creates the socket, and calling that from c++.

```js
const net = require('net');

function createSocket() {
  return net.createSocket(opts);
}

initNativeAddonSomehow(createSocket);
```

**Comment by gabrielschulhof** [comment]
@IanMcCurdy hopefully @devsnek's suggestion has helped you. Please re-open this issue if you are still having problems!
