### ISSUE TITLE
Define iterator for `Napi::Array` for using with ranged for-loop or STL algorithms

### ISSUE THREAD

**Issue by aminya** [nodejs/node-addon-api#830]
Currently, the only way to loop over the `Napi::Array` is to maintain the index manually and loop over using traditional for loops:
```cpp
    auto napiArray = Napi::Array::New(info.Env());
	for (uint32_t i = 0, len = cppVector.size(); i < len; i++) {
        napiArray[i] = Napi::Number::New(info.Env(), cppVector[i]);
    }
```

However, I'd like to be able to use ranged for loop or STL algorithms:
```cpp
    auto napiArray = Napi::Array::New(info.Env());
    std::transform(cppVector.begin(), cppVector.end(), napiArray.begin(), 
	[&info](auto a) { return Napi::Number::New(info.Env(), a); });
```
or other similar examples

**Comment by RaisinTen** [comment]
@aminya perhaps you mean an iterator for `Napi::Object` because `Napi::Array` inherits from `Napi::Object`. What should the iterator invalidation rules be?

**Comment by aminya** [comment]
We shouldn't necessarily use the same iterator for these two types. I expect the `Array` to work the same as `std::vector`. But `Napi::Object` is more similar to `std::map`.

**Comment by aminya** [comment]
Unstale

**Comment by mhdawson** [comment]
We discussed in the Node-API team meeting today and it seems reasonable but it might be a more complicated due to sparse arrays etc. @aminya would you be able to submit a PR?

**Comment by RaisinTen** [comment]
PR to add an iterator for `Napi::Object`: https://github.com/nodejs/node-addon-api/pull/930

**Comment by aminya** [comment]
This isn't fixed yet, though.
