### ISSUE TITLE
Avoid precision loss of floating point numbers

### ISSUE THREAD

**Issue by justinkambic** [nodejs/node-addon-api#836]
I have an add-on that is returning data to its JS caller. In most cases, I supply an `Napi::Object`, and the data is fine.

In some cases, however, the data are of type `float`, and I am seeing precision loss in JS. I'm assuming this is because the values are coerced from 32- to 64-bit floating precision.

Example:

```c++
// floatVal == 0.0125
o.Set('myFloatVal', floatVal);
```

```js
const obj = addon.getObj();
console.log(obj.myFloatVal);
// 0.012500000186264515
```

I can do something like:

```c++
o.Set('myFloatVal', std::to_string(floatVal));
```

```js
const obj = addon.getObj();
console.log(parseFloat(obj.myFloatVal));
// 0.0125
```

I've also tried returning an `Napi::Buffer<float>` but the problem persisted in that case as well.

I've searched through documentation and haven't found an obvious recommendation for this, I'm hoping it's a solution I've overlooked.

**Comment by mhdawson** [comment]
I'd agree that it is mostly like due to conversion from JS to C++ float representation and back. I don't remember any discussion/reports of this issue so I don't think we have any solution/work around.

My first guess is that this will be the case for any addon (ie not N-API or node-addon-api specific).

**Comment by kgryte** [comment]
This behavior can be replicated in JavaScript. For example,

```
// Double-precision to single-precision:
In [1]: var arr = new Float32Array( [0.0125] )
Out[1]: Float32Array(1) [ 0.012500000186264515 ]

// Access array element as double-precision:
In [2]: arr[0]
Out[2]: 0.012500000186264515
```

One way of mitigating the conversion side-effects is by [rounding](https://github.com/stdlib-js/stdlib/tree/6d76329001e33bbc2c8a0d76a482aec0b36e8b16/lib/node_modules/%40stdlib/math/base/special/roundsd) to a specified number of significant digits. For example,

```
// Single-precision has about 7 digits of decimal precision:
In [3]: base.roundsd(arr[0], 7)
Out[3]: 0.0125
```

**Comment by justinkambic** [comment]
Thank you both for the replies and the suggestion. For a little more context, I’m wrapping a existing C lib for use in a node app I’m building. I create instances of `Napi::Object` and return the native lib’s output data to the JS caller. By setting the precision to 7 significants in JavaScript I can mitigate the fuzziness, but the objects the add-on returns have dozens of floats and a handful of doubles. Given that my JS code can’t delineate which fields were 32- or 64-bit in C, I’d prefer to keep JS ignorant to this issue if possible.

I was hoping to work around this by doing something simple like casting the floats to double in native code, but after fighting with it a bit it’s seeming the simplest solution is to write a helper function like:

```c++
double convertFloat (float f)
{
  std::string s = std::to_string(f);
  std::size_t offset = 0;
  return std::stod(s, &offset);
}
```

This feels contrived to me but it does yield the desired result. If there’s no cleaner workaround to take floats without the precision changing on the JS side, I’m probably just going to add the boilerplate to the add-on and move on.

**Comment by mechdrew** [comment]
> Thank you both for the replies and the suggestion. For a little more context, I’m wrapping a existing C lib for use in a node app I’m building. I create instances of `Napi::Object` and return the native lib’s output data to the JS caller. By setting the precision to 7 significants in JavaScript I can mitigate the fuzziness, but the objects the add-on returns have dozens of floats and a handful of doubles. Given that my JS code can’t delineate which fields were 32- or 64-bit in C, I’d prefer to keep JS ignorant to this issue if possible.
> 
> I was hoping to work around this by doing something simple like casting the floats to double in native code, but after fighting with it a bit it’s seeming the simplest solution is to write a helper function like:
> 
> ```c++
> double convertFloat (float f)
> {
>   std::string s = std::to_string(f);
>   std::size_t offset = 0;
>   return std::stod(s, &offset);
> }
> ```
> 
> This feels contrived to me but it does yield the desired result. If there’s no cleaner workaround to take floats without the precision changing on the JS side, I’m probably just going to add the boilerplate to the add-on and move on.

I know this is closed, but why does this even work? We just ran into this issue with our doubles and this was the only approach we tried that gave us the correct result. Emphasis on we already have doubles, but we have needed to resort to this trick to get them to transfer back to JS correctly without losing precision. Example: 59.28936 was an especially troublesome value.
