### ISSUE TITLE
Return Type error

### ISSUE THREAD

**Issue by mayank1608** [nodejs/node-addon-api#848]
Hi,

I am getting this error: 'return': cannot convert from 'json' to 'Napi::Value' while running node-gyp rebuild command.
I am calling the  function from the Object wrapper(test) which passes json to a function(testarg) in cpp and there is returning json which I am storing in variable 'res'. At this time I am getting the return type error.

CODE::

**INDEX.CPP**
#include <napi.h>
#include <iostream>
#include <string>

#include <sstream>
#include "greeting.h"
#include "nlohmann/json.hpp" 

using json = nlohmann::json;

Napi::Value test(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();
    std::string arg = (std::string) info[0].ToString();
    json res;
    res = testarg( arg ); //Function called Which is defined in CPP file
    return res;
}

Napi::Object Init(Napi::Env env, Napi::Object exports) {
    exports.Set(
        Napi::String::New(env, "test"),
        Napi::Function::New(env, test)
    );    
    return exports;
}
NODE_API_MODULE(greet, Init)

**GREETING.H**
#include <string>
#include "nlohmann/json.hpp"

using json = nlohmann::json;
json testarg( std::string arg );

**GREETING.CPP**
#include <iostream>
#include <string>
#include <array>

#include <sstream>
#include "nlohmann/json.hpp"
#include "greeting.h"

using json = nlohmann::json;

json testarg( std::string arg ){
	json jsonObj;
	jsonObj = json::parse(arg);
        return jsonObj;
};

**Comment by NickNaso** [comment]
Hi @mayank1608,
I think that the problem is in the return type, you are trying to return `nlohmann::json` in place of `Napi::Value`.  You should return a `Napi::Value` from a `Napi::Function` or one of its specializations es. `Napi::String`, `Napi::Number`.

**Comment by mayank1608** [comment]
Thanks for the quick reply @NickNaso 

Well I tried this as well in **index.cpp** :

Napi::Value test(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();
    std::string arg = (std::string) info[0].ToString();
    // json res;
    Napi::Value res = testarg( arg );
    return res;
}

now I am getting this error: 'initializing': cannot convert from 'json' to 'Napi::Value'

Should I have to use this for conversion from 'json' to 'Napi::Value'??

Napi::Function parse = json.Get("parse").As<Napi::Function>();
Napi::Value json_obj = parse.Call(json, { json_string });

Thanks in advance :)

**Comment by NickNaso** [comment]
Hi @mayank1608,
in the example that you posted you retireve the `JSON.parse` function from the the global env. The `parse` function require `Napi::String` as its parameter. 
The following code should work:
```cpp
Napi::Value test(const Napi::CallbackInfo& info) {
   // ... 
   Napi::Object njson = env.Global().Get("JSON").AsNapi::Object();
   Napi::Function parse = njson.Get("parse").AsNapi::Function();
   Napi::String json_string = Napi::String::New(env, res.dump());
   Napi::Value json_obj = parse.Call(njson, { json_string });
  return json_obj;
}
```
Let me know it this works for you. I'm cusrios about this, what is your specific use case?

**Comment by mayank1608** [comment]
@NickNaso ok thank you. Will try this

**Comment by mayank1608** [comment]
@NickNaso,  Its working now. **Thanks for the help bro** 🥇
