### ISSUE TITLE
For help,C++ third-party libraries call back to napi from a different thread, and napi calls back to js can cause runtime errors

### ISSUE THREAD

**Issue by lilong7676** [nodejs/node-addon-api#858]
I have a third-party C++ library that notifies napi when it receives a message through a callback. **Since the callback does not belong to the main thread of napi**, it will report an error when it runs

> Fatal error in v8: : HandleScope: : CreateHandle ()
Cannot create a handle without a HandleScope
zsh: illegal hardware instruction  node test.js

Is there a way to switch from a third-party library callback thread to the main thread of the NAPI?

**Comment by lilong7676** [comment]
The key is that this callback is sent from the third-party library, not from NAPI, so I am not able to send messages from this callback to JS, which gives me a headache

**Comment by mhdawson** [comment]
I think you want to look at https://github.com/nodejs/node-addon-api/blob/master/doc/threadsafe.md

**Comment by lilong7676** [comment]
> I think you want to look at https://github.com/nodejs/node-addon-api/blob/master/doc/threadsafe.md

Thank you. I'll try it on

**Comment by lilong7676** [comment]
Sorry, the last question is whether ThreadSafeFunction can be reused, which is the property stored as an object and then called back to JS every time a message is received
