### ISSUE TITLE
Object::PropertyLValue<>::operator= chooses wrong overload of Set for const char* argument

### ISSUE THREAD

**Issue by mika-fischer** [nodejs/node-addon-api#86]
`Object.Set(key_type, bool)` is called instead of `Object.Set(key_type, const char*)`.

**Comment by addaleax** [comment]
I assume you’re right about this but can you post an example piece of code since you seem to already have that?

**Comment by mika-fischer** [comment]
```
auto result = Napi::Object::New(env);
result["foo"] = "bar";
result["type"] = static_cast<double>(result.Get("foo").Type());
return result;
```

Yields
```
{ foo: true, type: 2 }
```

instead of

```
{ foo: "bar", type: 4 }
```

This is with node 8.2.0, node-addon-api 0.4.0 (can't use master because of the error API changes) and MSVC 2015 Update 3

**Comment by bnoordhuis** [comment]
I bet it's something like this:
```c++
std::string key("foo");
const char* value = "bar";
obj.Set(key, value);
```
There are Set() overloads that take `const char*` or `const std::string&` but not a mix of both.  Since pointers can be coerced to bool, the compiler will pick the overload that takes a bool as the second argument.

**Comment by mika-fischer** [comment]
@bnoordhuis Yes, that's probably it, `PropertyLValue` always uses `string` as key type...

**Comment by jasongin** [comment]
> Does this just mean we need another overload ?

Yes, I think so.

**Comment by addaleax** [comment]
I've suggested what I would consider a proper fix (rather than adding a gazillion more overloads) in #123, could you try that? :)
