### ISSUE TITLE
Fastest way to convert a Napi::Array to a vector of string

### ISSUE THREAD

**Issue by aminya** [nodejs/node-addon-api#862]
I have written an algorithm that works on a vector string. However, the way I am not sure if the way I convert a Napi::Array to a vector of the string is very efficient. There is no documentation on this topic.

The conversion part currently takes 22ms which is half of the whole execution time of the program!

Here is a simplified example.
```cpp
Napi::Value MyClass::makeVector(const Napi::CallbackInfo &info) {
  auto arr = info[0].As<Napi::Array>();
  const auto N = arr.Length();
  for (auto i = 0; j < N ; i++) {
      MyClass::myVector[i].emplace_back(static_cast<Napi::Value>(arr[j]).ToString().Utf8Value());
  }
  return Napi::Boolean();
}
```

**Comment by mhdawson** [comment]
I made this suggestion in an issue a while back which I think addresses the same question: https://github.com/nodejs/node-addon-api/issues/429#issuecomment-457639332

If you need to more efficiently transfer an array between JS and Native, then Napi::ArrayBuffer may be better than using Napi::Array.

**Comment by NickNaso** [comment]
Hi @aminya,
we  discussed about this in the documetation about `Napi::Array` here https://github.com/nodejs/node-addon-api/blob/master/doc/array.md.

> `Napi::TypedArray` and `Napi::ArrayBuffer` correspond to JavaScript data types such as `Napi::Int32Array` and `Napi::ArrayBuffer`, respectively, that can be used for transferring large amounts of data from JavaScript to the native side. An example illustrating the use of a JavaScript-provided` ArrayBuffer` in native code is available [here](https://github.com/nodejs/node-addon-examples/tree/master/array_buffer_to_native/node-addon-api).

In general the conversion from JavaScript type to native type has a cost. In your code for example I can imagine that your JavaScript code is something like this:
```js
// ...
const NUMBER_OF_ELEMENTS = 1000
const arr = []
for (let i = 0; i <NUMBER_OF_ELEMENTS; i++) {
    arr.push(${i})
}
addon.makeVector(arr);
// ...
```
On the native side when you call `Napi::String::Utf8Value()` method you are creating a new `std::string` so the value is **copied** from the underlying JavaScript value to the native `std::string`.
This clould be more clear if you take a look at the implementation of  `Napi::String::Utf8Value()`:
```cpp
inline std::string String::Utf8Value() const {
  size_t length;
  napi_status status = napi_get_value_string_utf8(_env, _value, nullptr, 0, &length);
  NAPI_THROW_IF_FAILED(_env, status, "");

  std::string value;
  value.reserve(length + 1);
  value.resize(length);
  status = napi_get_value_string_utf8(_env, _value, &value[0], value.capacity(), nullptr);
  NAPI_THROW_IF_FAILED(_env, status, "");
  return value;
}
```
I hope that this explanation is helpful to you.

**Comment by aminya** [comment]
Thanks for your suggestions. 

So, if I convert my JavaScript array of string to an ArrayBuffer, and then pass it to my native addon, that would improve the speed? 

I am not sure if I can change my interface to use ArrayBuffer from the beginning. It can be a new interface.

The code for my module is open-source, so you might want to take a look:
https://github.com/atom-ide-community/fuzzaldrin-plus-fast/blob/3d15b9988c5f0f70feb5f4b04402463e34f1f5c2/src/fuzzaldrin.cc#L28-L55

https://github.com/atom-ide-community/fuzzaldrin-plus-fast/blob/3d15b9988c5f0f70feb5f4b04402463e34f1f5c2/fuzzaldrin.js#L23-L38

**Comment by NickNaso** [comment]
Hi @aminya I'm closing the issue because it seems that you solved your problem. If you need some other suggestion or help feel free to reopen this issue or new one.

**Comment by aminya** [comment]
I didn't actually try [this suggestion](https://github.com/nodejs/node-addon-api/issues/862#issuecomment-749222595) as it required some changes to my code. But I will try and report.
