### ISSUE TITLE
How to import N-API node extension from mjs file?

### ISSUE THREAD

**Issue by vit1251** [nodejs/node-addon-api#866]
I compile my N-API module and try to import from .mjs source code. But no way to do this. Any idea how to do this?
Any additional changes in node-gyp should I make?

**Comment by NickNaso** [comment]
Hi @vit1251,
like reported from the documentation native modules are not currently supported with ES module imports. You can load them using [module.CreateRequire()](https://nodejs.org/dist/latest-v14.x/docs/api/module.html#module_module_createrequire_filename).
```js
import { createRequire } from 'module';
const require = createRequire(import.meta.url);

const addon = require('YOUR_ADDON_PATH');
```
I hope that this help you.

**Comment by vit1251** [comment]
@NickNaso thanks a lot.
