### ISSUE TITLE
Missing assert header

### ISSUE THREAD

**Issue by sampsongao** [nodejs/node-addon-api#87]
In the https://github.com/nodejs/node-addon-api/commit/28fad43c20d8fff69cfb47434a997344bf81aafa, the `cassert` header is removed. However, modules using assert now have to include this header. Should we include assert in module code or should we add that header back to napi-inl.h?

**Comment by jasongin** [comment]
The header was removed because `napi-inl.h` no longer calls `assert()`.

If module code still needs assert, it should include the header separately.

**Comment by jasongin** [comment]
Generally, `.c/.cpp` files should not rely on external headers including other headers for them anyway.
