### ISSUE TITLE
Methods of wrapper classes should be marked const

### ISSUE THREAD

**Issue by seishun** [nodejs/node-addon-api#870]
For example, `Object::Set` and `ThreadSafeFunction::Release`. They don't modify the object itself but only call functions on the N-API object they wrap. This is similar to how the constness of a pointer is orthogonal to the constness of the object it points to.

These methods being non-const means that if I have to call them in a lambda, I have to either capture the object by reference (unidiomatic and not always possible, e.g. with TheadSafeFunction) or mark the lambda as `mutable` (unusual and misleading since the lambda itself doesn't mutate).

**Comment by mhdawson** [comment]
@seishun is adding const going to break any existing code (I'm expecting not) and any interest in submitting a PR ?

**Comment by seishun** [comment]
>is adding const going to break any existing code (I'm expecting not)

`Object::operator[]` returns a different type depending on constness (Value or PropertyLValue), but PropertyLValue is implicitly convertible to Value, so I guess it's fine? 🤔

>any interest in submitting a PR

Sure, working on it.
