### ISSUE TITLE
Unable to call methods on an N-API object wrapped by a Proxy

### ISSUE THREAD

**Issue by kanthoney** [nodejs/node-addon-api#872]
Node version: v14.15.1
Platform: Fedora Linux 33, x86_64

[This gist](https://gist.github.com/kanthoney/8802e5abcba4e85e4562fca4ee1fe518) implements an N-API class `A` with the following properties:

* `value`, a property with a getter that returns the string `test`,
* `f`, a method that returns the first argument.

The bare object works fine. However, if wrapped by a `Proxy` the `f` method becomes inaccessible as any attempt to call it results in a `TypeError: Illegal invocation` error being thrown. The `value` property works normally. A pure Javascript implementation works as expected.

**Comment by KevinEady** [comment]
Hi @kanthoney ,

From what I recall, there are checks on class instance methods to ensure the receiver `this` is of the same class. You would, for instance, get the same error if you tried:

```js
A.prototype.f.call( {}, 1 )
```

Maybe @gabrielschulhof can illuminate some...? This type-checking came up when we were discussing the `napi_define_subclass` proposal. Should this error also occur for `Proxy`s?

**Comment by KevinEady** [comment]
FWIW, I believe the error is due to this flow: There is no `GetCompatibleReceiver()` for `Proxy`'ed objects.

https://github.com/nodejs/node/blob/606df7c4e79324b9725bfcfe019a8b75bfa04c3f/deps/v8/src/builtins/builtins-api.cc#L93-L99

https://github.com/nodejs/node/blob/606df7c4e79324b9725bfcfe019a8b75bfa04c3f/deps/v8/src/builtins/builtins-api.cc#L29-L30

**Comment by kanthoney** [comment]
@KevinEady Thanks for the quick response!

There seems to be a workaround, which is to define the class with no properties and then define them on the constructor's prototype instead:

```
napi_value A::Init(napi_env env, napi_value exports)
{
  napi_value cons, prototype;
  napi_property_descriptor props[2] = {
    { "f", nullptr, F, nullptr, nullptr, nullptr, napi_default, nullptr },
    { "value", nullptr, nullptr, Value, nullptr, nullptr, napi_default, nullptr }
  };
  if(napi_define_class(env, "A", NAPI_AUTO_LENGTH, Constructor, nullptr, 0, nullptr, &cons) == napi_ok &&
     napi_get_named_property(env, cons, "prototype", &prototype) == napi_ok &&
     napi_define_properties(env, prototype, 2, props) == napi_ok &&
     napi_create_reference(env, cons, 1, &ConstructorRef) == napi_ok &&
     napi_set_named_property(env, exports, "A", cons) == napi_ok) {
    return exports;
  }
  return nullptr;
}
```
Looking at the code for `napi_define_class`, I would guess this works because `napi_define_class` attaches a `v8::Signature::New` to any methods, whereas `napi_define_properties` doesn't. I would guess the hazard with bypassing the signature check is that malicious code could cause N-API to try and unwrap something that wasn't wrapped, so I should type_tag things if I'm going to use this.

**Comment by gabrielschulhof** [comment]
@kanthoney @KevinEady this is exactly what's going on. Type-tagging in lieu of napi_define_class is the solution.

**Comment by kanthoney** [comment]
@gabrielschulhof Thanks very much!
