### ISSUE TITLE
WrappedObject and Array seem to have memory issues

### ISSUE THREAD

**Issue by sigmasoldi3r** [nodejs/node-addon-api#877]
Hello! I'm trying to fill an array with wrapped objects, for later use. The problem is that when the array is returned, and passed around within the JS environment, the struct stored inside the wrapped object has garbage data, instead of the real data.

The array filling is done this way:
```c++
Napi::Value HorizonWad::ReadWADEntries(const Napi::CallbackInfo &info)
{
  auto env = info.Env();
  // read entries
  std::vector<WadEntry> heap;
  heap.resize(header.directoryCount);
  const auto count = heap.size();
  readWADEntries(wad, &header, &heap[0], count);
  // Feed to a JavaScript array and return it
  auto array = Napi::Array::New(env);
  for (int i = 0; i < count; i++)
  {
    Napi::HandleScope scope(env);
    array[i] = HorizonWadEntry::CreateInstance(env);
    auto ptr = Napi::ObjectWrap<HorizonWadEntry>::Unwrap(array.Get(i).ToObject());
    ptr->entry = heap[i];
  }
  return array;
}
```
At the moment of filling, the data is okay.

Later, at the javascript environment:
```js
  const entries = wad.getEntries();
  console.log(`Reading ${entries.length} entries:`)
  for (const entry of entries) {
    const info = wad.getInfo(entry);
    // Here
  }
```

If you unwrap the entry, you'll get garbage data. Any clue? What I'm missing?

The `wad#getInfo` function unwraps the object as follows:

```c++
Napi::Value HorizonWad::ReadWADTextureInfo(const Napi::CallbackInfo &info)
{
  auto param = info[0].ToObject();
  auto entry = Napi::ObjectWrap<WadEntry>::Unwrap(param);
  // ...
}
```

(Because `entry` is expected to be an object of WadEntry)

**Comment by mhdawson** [comment]
Does 

```C++
ptr->entry = heap[i];
```

create a copy?  If not since 

```C++
 std::vector<WadEntry> heap;
```

seems to be stack allocated, that might be the problem.

**Comment by sigmasoldi3r** [comment]
> 
> 
> Does
> 
> ```c++
> ptr->entry = heap[i];
> ```
> 
> create a copy? If not since
> 
> ```c++
>  std::vector<WadEntry> heap;
> ```
> 
> seems to be stack allocated, that might be the problem.

It should,  `entry` is a member of the class:

```c++
class EntryWrapper /* extends the NAPI wrapper */ {
  // ...
  WadEntry entry; // <- this
};
```

And `WadEntry` is a trivial struct with few fields.

**Comment by mhdawson** [comment]
Any chance this was related: https://github.com/nodejs/node-addon-api/pull/899/files

**Comment by sigmasoldi3r** [comment]
> 
> 
> Any chance this was related: https://github.com/nodejs/node-addon-api/pull/899/files

I'll take a look and report back!

**Comment by mhdawson** [comment]
@sigmasoldi3r thanks!

**Comment by sigmasoldi3r** [comment]
I cannot assure that the issue is fixed 100% but after the patch, reconfiguring and recompiling seems that the issue is gone.

Data now is alive without errors.

Thanks!!!
