### ISSUE TITLE
convert.js: FunctionCallbackInfo not converted to CallbackInfo in the header

### ISSUE THREAD

**Issue by mcollina** [nodejs/node-addon-api#88]
As titled, the conversion above is only done in the `.cc`  files, but not in `.h`.

**Comment by NickNaso** [comment]
Hi @mcollina,
this is a very old issue. What do you think should be possible to close it?

**Comment by mcollina** [comment]
This was fixed in https://github.com/nodejs/node-addon-api/pull/132.
