### ISSUE TITLE
No ability to compare ThreadSafeFunction and Function

### ISSUE THREAD

**Issue by kuzenko** [nodejs/node-addon-api#881]
As I see now there is not possibility to compare these two types (Function inherits Value, and ThreadSafeFunction don't), are there any solutions for that? Thanks.

**Comment by KevinEady** [comment]
Hi @kuzenko ,

You are correct. A `Napi::Function` holds a `napi_value`, whereas a `Napi::ThreadSafeFunction` holds a `napi_threadsafe_function`. They are inherently different, and you cannot compare them. Furthermore, not all TSFNs are created with a function passed to them: starting with N-API 5, the function parameter is optional.

If you want to compare the types, you will have to manually keep track of the `Function` passed to `TSFN::New` and compare that value instead.

Hope this helps.

**Comment by mhdawson** [comment]
There has been no additional questions since @KevinEady answered, closing. Please let us know if you think that was not the right thing to do.
