### ISSUE TITLE
How to check for uninitialised ThreadSafeFunction

### ISSUE THREAD

**Issue by kidneysolo** [nodejs/node-addon-api#883]
Hello everyone,
I have code setup in the following way:

```C++
static ThreadSafeFunction uglyGlobalCallback = nullptr;

// ...much later in the lifetime of the module
void SetCallback(const CallbackInfo &info) {
  auto callback = info[0].As<Function>();
  uglyGlobalCallback = ThreadSafeFunction(info.Env(), callback, "UglyGlobal", 0, 1);
}

// this is a not exposed C++ function
void TriggerCallback() {
  if (/* uglyGlobalCallback is not set */) {
    // bail out
   return;
  }
  
  // uglyGlobalCallback.Call etc...
}
```

I was able to just check for the global callback to be `!= nullptr` on MacOs but then I encountered a problem porting the code to Windows. On Windows the check is marked as error as no suitable operator matches the pair. 

I understand the global itself is not very clean code but this is legacy stuff I would prefer not to change too much so, is there a safe way to check if the ThreadSafeFunction is actually initialised before calling it ?

Thank you :)

**Comment by KevinEady** [comment]
Hi @kidneysolo ,

So without doing any actual testing, maybe you can [cast](https://github.com/nodejs/node-addon-api/blob/master/napi.h#L2404) the `ThreadSafeFunction` to a `napi_threadsafe_function`, and see if that value is `nullptr`? I guess this is what one compiler is doing automatically for you, whereas another is not, which is why you're having portability issues. Just a guess?

Let us know if this works.

**Comment by kidneysolo** [comment]
@KevinEady Thank you for your quick reply ! 

So if I understand correctly that operator enables me to do:
```C++
if ( static_cast<napi_threadsafe_function>(uglyGlobalTsfn) != nullptr)
```
Did I get you right ? vs2019 complains `no suitable conversion function from ThreadSafeFunction to napi_threadsafe_function exists` but since the operator is there I would imagine I am casting it in the wrong way.

**Comment by kidneysolo** [comment]
My bad @KevinEady not only your suggestion works but directly comparing with nullptr works too.

For some reason vs2019 was picking up a very old version of napi.h from another package in the project.

Thank you !
