### ISSUE TITLE
Call Emit inside a c++ Lambda fucnction

### ISSUE THREAD

**Issue by shadow111** [nodejs/node-addon-api#887]
**Hello This actually not an issue but i'm seeking some recommendation** 
I'm working on a N-API addon to capture video frame using windows graphic capture API , extract frame bytes and send it back to JavaScript. I have tried the event emitter but I can't get the data.

Here is my C++ code:

```cpp
#include <napi.h>
// my other include

Napi::Value startCapture(const Napi::CallbackInfo &info){
    Napi::Env env = info.Env();
    Napi::Function emit = info[0].As<Napi::Function>();
    emit.Call({Napi::String::New(env, "start")});
    auto framePool = winrt::Direct3D11CaptureFramePool::Create(
    device, //d3d device
    winrt::DirectXPixelFormat::B8G8R8A8UIntNormalized,
    2,
    itemSize);
    // capture session
    auto session = framePool.CreateCaptureSession(item);

    // Lambda Function 
    framePool.FrameArrived([session, d3dDevice, d3dContext, &emit, &env](auto &framePool, auto &) {
        auto frame = framePool.TryGetNextFrame();
        auto frameTexture = GetDXGIInterfaceFromObject<ID3D11Texture2D>(frame.Surface());
        // Extraction the byte and so on ...
        emit.Call({Napi::String::New(env, "data"), Napi::String::New(env, "data ...")});
    }
    
    session.StartCapture();
    emit.Call({Napi::String::New(env, "end")});
    return Napi::String::New(env, "OK");
}
```

here my JavaScript code calling the start capture function
```js
const EventEmitter = require('events').EventEmitter
const addon = require('./build/myaddon.node')
const emitter = new EventEmitter()

emitter.on('start', () => {
    console.log('Start Recording ...')
})
emitter.on('data', (evt) => {
    console.log(evt);
})

emitter.on('end', () => {
    console.log('Stop Recording ...')
})

addon.startCapture(emitter.emit.bind(emitter))
```

Normally my output should be an infinite loop of data messages until I stop it
**### 
Start Recording … 
data 
data 
. . . 
data**

But i just get 

**Start Recording …** 

After looking to the lambda function [framePool.FrameArrived](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.direct3d11captureframepool.framearrived?view=winrt-19041) it seems that it's running on a different thread than the startCapture function if I understand the lambda function concept correctly, I just wanna to found a way on how I can stream those messages to JavaScript using event Emitter or any other recommendation is well welcoming.

**Comment by kidneysolo** [comment]
Hi @shadow111 

If the lambda passed to framePool.FrameArrived is run on a different thread you cannot directly call javascript functions in it.

I recommend to take a look at the [ThreadSafeFunction API](https://github.com/nodejs/node-addon-api/blob/main/doc/threadsafe.md) which would enable you to safely call javascript functions from another thread.

**Comment by forthegithub** [comment]
``` warning: ‘static v8::Local<v8::ArrayBuffer> v8::ArrayBuffer::New(v8::Isolate*, void*, size_t, v8::ArrayBufferCreationMode)’ is deprecated: Use the version that takes a BackingStore. See http://crbug.com/v8/9908. [-Wdeprecated-declarations]
  v8::Local<v8::ArrayBuffer> v = v8::ArrayBuffer::New(isolate, (void*)isolate, 0);
                                                                                ^
In file included from ../main.cpp:1:
/include/node/v8.h:5221:29: note: declared here
   static Local<ArrayBuffer> New(
```

What about this one?




@addaleax @legendecas @gabrielschulhof @digitalinfinity @jschlight@ mhdawson @KevinEady @NickNaso

**Comment by shadow111** [comment]
> ```
> warning: ‘static v8::Local<v8::ArrayBuffer> v8::ArrayBuffer::New(v8::Isolate*, void*, size_t, v8::ArrayBufferCreationMode)’ 
> is deprecated: Use the version that takes a BackingStore. See http://crbug.com/v8/9908. [-Wdeprecated-declarations]
>   v8::Local<v8::ArrayBuffer> v = v8::ArrayBuffer::New(isolate, (void*)someptr, 0);
>                                                                                 ^
> In file included from ../main.cpp:1:
> /include/node/v8.h:5221:29: note: declared here
>    static Local<ArrayBuffer> New(
> ```
> 
> What about this one?
> 
> @legendecas @gabrielschulhof @jschlight @mhdawson @KevinEady @NickNaso

i don't understand can you explain please?

**Comment by addaleax** [comment]
I’ve hidden the off-topic comments here as off-topic, if you have another problem please open another issue (in e.g. https://github.com/nodejs/help/issues/). Also, pinging a bunch of people for no good reason is not cool and is not going to get your problem solved any faster.
