### ISSUE TITLE
NAN to N-API conversion guide

### ISSUE THREAD

**Issue by mcollina** [nodejs/node-addon-api#89]
As titled, a write would be highly useful to solve common errors and problems.

**Comment by mcollina** [comment]
I will do a writeup once I manage to complete the port of my little library.

**Comment by mhdawson** [comment]
Thanks, that would be super useful.

**Comment by Croydon** [comment]
@mcollina Ping? :)

**Comment by NickNaso** [comment]
Hi @mcollina ,
I think that the guid you want is here [https://github.com/nodejs/node-addon-api/tree/master/tools](https://github.com/nodejs/node-addon-api/tree/master/tools). If it's good to you maybe we can close this issue.

**Comment by mcollina** [comment]
Yes, that's perfect.
