### ISSUE TITLE
how to get the Napi::Function constructor of an object?

### ISSUE THREAD

**Issue by sezanzeb** [nodejs/node-addon-api#897]
I can't figure out how to get the `Napi::Function&` constructor of an object. I would like to use InstanceOf (https://github.com/nodejs/node-addon-api/blob/main/doc/object.md#instanceof)

It looks like a constructor is extracted from an object using Napi::Type::Type, like in https://github.com/nodejs/node-addon-api/blob/main/doc/function.md#constructor, but when I use Napi::Date::Date, I get the following problem:

```
error: cannot convert ‘<unresolved overloaded function type>’ to ‘const Napi::Function&’
   59 |       bool is_date = value.ToObject().InstanceOf(Napi::Date::Date);
      |                            
```

I don't know much about c++ by the way

**Comment by KevinEady** [comment]
There is no way to retrieve an object's constructor within Node API. You might be able to call `Object.getPrototypeOf()`, maybe like (untested):

```cpp
auto objGlobal = env.Global().Get("Object");
auto getPrototypeOf = objGlobal.As<Object>().Get("getPrototypeOf").As<Function>();
auto prototype = getPrototypeOf.Call(objGlobal, { value }); // where `value` is the object whose prototype you want to receive
```

**Comment by sezanzeb** [comment]
thanks.

How would you propose to check if an object is of type Date?

**Comment by NickNaso** [comment]
Hi @sezanzeb,
to check if a value is a JavaScript object you could use the `Napi::Value::IsDate` method see: https://github.com/nodejs/node-addon-api/blob/main/doc/value.md#isdate
Es. 
```cpp
Napi::Value Method(const Napi::CallbackInfo& info) {
  bool isDate = info[0].IsDate();
  return Napi::Boolean::New(env, isDate);
}
```

I hope tha this help you.

**Comment by mhdawson** [comment]
Closing since there as been no follow up since Nick's response.  Please let us know if that was not the right thing to do.
