### ISSUE TITLE
Prebuild story on Node 8 with flag

### ISSUE THREAD

**Issue by mcollina** [nodejs/node-addon-api#90]
If we do a prebuilt module using node-addon-api and Node 8.2.1, could this run without the flag?

Or do we always need a flag on Node 8 (until it's disabled)

**Comment by jasongin** [comment]
Yes, it could be made to work that way, though currently the scripts are set up to link to the built-in version of N-API on node >= 8.

**Comment by mhdawson** [comment]
@mcollina, since Node 8 is EOL I think we can close this, please let us know if that is not the right thing to do.
