### ISSUE TITLE
Add IsExecuting function for AsyncWorker.

### ISSUE THREAD

**Issue by Ayzrian** [nodejs/node-addon-api#900]
So my idea is to add the `IsExecuting` function for AsyncWorker, to have a way to determine whether the worker thread is working. It comes very useful in cases you want to delete the worker object, but deletion will cause exception as the worker resources are allocated.
Having such a function would allow resolving such a problem in a way, that if it is not running we can ask the Worker to destroy itself when it will do his work, if not we can destroy it right away.

**Comment by gabrielschulhof** [comment]
In general, checking what another thread is doing is not a good idea because it invites a race condition. `IsExecuting()` may return `true`, but in the next instant the thread may have finished executing. If you want to delete, the best place to do it is from the `Complete()` or `Error()` callback.
