### ISSUE TITLE
Passing Array from one object to another

### ISSUE THREAD

**Issue by markdirish** [nodejs/node-addon-api#901]
Hi All,

I'll preface by saying that I probably misunderstand how `Reference` works, and there is (hopefully) and easy solution.

I have a database connector written with node-addon-api. In the connector, a user can pass an `Array` to a function, that then converts some of the data in the Array to C value, calls an AsyncWorker, and then in `OnOk()` needs that initial Array that was passed in. To accomplish this, I have the Array converted to a `Napi::Reference`:
```
parameters = Napi::Persistent(parameterArray.As<Napi::Array>());
````
This Reference is then attached to the AsyncWorker so it can be used again unmodified in `OnOk()`, where it is returned as part of the function return value. If I don't wrap the Array in a reference, it appears to be cleaned up as soon as the AsyncWorker is called, causing a segfault in OnOk().

**This has worked great, and does exactly as I would expect**

The problem is, I now have a code path where instead of returning that Array at the end of the AsyncWorker, I need to generate a new instance of a class at the end of the AsyncWorker. I want to send the Array to that new class through its constructor. My naive solution doesn't seem to work: 

```
std::vector<napi_value> cursor_arguments;
cursor_arguments.push_back(Napi::External<StatementData>::New(env, data));
cursor_arguments.push_back(parameters.Value());

// create a new ODBCCursor object as a Napi::Value
Napi::Value cursorObject = ODBCCursor::constructor.New(cursor_arguments);
```

Passing the Array itself leads to a segfault as soon as I try to use it on the ODBCCursor object. However, I can't find a way to pass the Reference either. No matter how I pass the Reference, the Array never seems to survive the trip from the AsyncWorker to the ODBCCursor.

What am I doing wrong? How can I take my Array (that survived the AsyncWorker work) from OnOk and pass it to another Napi::Object (really, preferably, without having to convert all the values to C values and then back to Napi::Values).

Thanks!

**Comment by mhdawson** [comment]
I think what you really want to do is:

```C++
// create a new ODBCCursor object as a Napi::Value
Napi::Value cursorObject = ODBCCursor::constructor.New();
cursorObject.set("statementData", Napi::External<StatementData>::New(env, data));
cursorObject.set("array", parameters.Value());
```

That would ensure that there is a JS level reference from the ODBCCursor object that is kept alive beyond the onOK (as a parameter passed to the callback) to the External you created and the Array.

I can't tell since the key is what your code does with cursor_arguments but my guess is that although there may be C level references between the objects there is no JS level references keeping things alive.  

It would be possible to also use References in OBDCCursor  (with a reference count >0) to keep each of them alive and this would make sense if you only want to use them in the C/C++ code. In that case you would create a Reference for each of the two NAPI_VALUES , with an initial reference count >1, then have a finalizer for ODBCCursor which deletes the references

**Comment by markdirish** [comment]
Hi Michael,

Thanks for your response. For your first suggestion, I don't really want these to be properties on the ODBCCursor object, merely values stored on the object that I can pass back to the user when the time is right (after another round of AsyncWorker work). What `cursor_arguments` does is pass arguments to the constructor, but perhaps I might be using the JavaScript constructor as a C constructor, so maybe that's where the code looks off. Basically I have code I want to store on the object in C, but I still want a JavaScript object created that the user can use.

> It would be possible to also use References in OBDCCursor (with a reference count >0) to keep each of them alive and this would make sense if you only want to use them in the C/C++ code.

This is pretty much what I want to do. I want to store the Array (along with all of its JavaScript values) on the `ODBCCursor` object, and then after a user fetches some information, simply pass that Array back to them as part of the result. I thought I was doing it correctly:

1. When the Array comes in, I call:
```
parameters = Napi::Persistent(napiParameterArray.As<Napi::Array>());
````
2. This gives me a `Napi::Reference<Napi::Array>`, which survives the call through an AsyncWorker and into OnOk. 
3. I then try to pass this same reference through the ODBCCursor constructor. To pass it, I have to do so as a `<Napi::External<Napi::Reference<Napi::Array>>>`, because ODBCCursor constructor needs `napi_value` arguments.
4. In the ODBCConstructor, I call `.Value()` on the reference, which I thought should give me a still valid `Napi::Array`. But any attempt to use it causes a segfault.

I thought that the first call to `Napi::Persistent` I make would keep the Array alive forever until I specifically make a call to `Reset()`? Clearly somewhere along the way the Reference is failing me and the Array is being cleaned up.

**Comment by markdirish** [comment]
I think my issue may have been `Null` being passed instead of an `Array` in some cases, causing some errors when passing the `Array` instead of a `Reference`. Here is what worked for me:

* When going into an `AsyncWorker`, save off a `Reference<Array>`. The `Array` will survive the call, and can be used in `OnOk()`.
* When passing to a new object in `OnOk()` through that objects constructor, get the value from the `Reference` through `ref.Value()`.
* In the constructor of that new object, because I want the Array to exist in the C code (up to the point where I want to return it), I again cast to a reference (`ref = Persistent(array)`).
* Finally, when its time to return that `Array` to the user in the _next_ OnOk() from a separate function called by that object, I again call `object->ref.Value()`, and the `Array` is still alive.

Looks like it was developer error, thanks for the help @mhdawson and thanks for creating such a useful package!

**Comment by mhdawson** [comment]
Thanks for the update  and glad to see its resolved :)
