### ISSUE TITLE
Node buffer created from native module cannot be garbage collected

### ISSUE THREAD

**Issue by ggreco** [nodejs/node-addon-api#905]
### Short description

I cannot garbage collect in the node environment node buffers created in the native module through the C++ Napi API.

### Long description

The FinalizerCallback is called only when the native  module handler itself is destroyed, and not periodically during the lifetime of the javascript application.

This is a small example to highlight the problem, the real code is far more complex and use Napi::Buffer to share video frames, and ends up with filling the host RAM.

### Example

Full demo source is: https://github.com/ggreco/testNapi

Here is the highlights of the project, the native module exposes the following API:

```c++
Value doGet(const CallbackInfo &info) {
    uint8_t *data = new uint8_t[200];
    std::cerr << "Allocated buffer of 200 bytes at " << (void*)data << "\n";
    return Napi::Buffer<uint8_t>::New(info.Env(), data, 200,
         [](Napi::Env env, uint8_t *d) {
             std::cerr << "Releasing buffer at " << (void*) d << "\n";
             delete[] d;
         });
}
```

The test script is launched with:

`node --expose-gc index.js`

... and tries to periodically flush the garbage collector:

```javascript
console.log("Starting...");
for (let i = 1; i < 12; ++i) {
    const res = native.get();
    console.log("Got ", res.byteLength);
    if ((i % 3) === 0) {
        console.log("Calling GC...")
        global.gc();
        console.log("GC completed");
    }
}
console.log("Terminated");
```

### Actual output

```
node --expose-gc index.js 
Starting...
Allocated buffer of 200 bytes at 0x104711520
Got  200
Allocated buffer of 200 bytes at 0x1047117d0
Got  200
Allocated buffer of 200 bytes at 0x104711a20
Got  200
Calling GC...
GC completed
Allocated buffer of 200 bytes at 0x10501fff0
Got  200
Allocated buffer of 200 bytes at 0x1050203d0
Got  200
Allocated buffer of 200 bytes at 0x10501f700
Got  200
Calling GC...
GC completed
Allocated buffer of 200 bytes at 0x104638670
Got  200
Allocated buffer of 200 bytes at 0x104635ea0
Got  200
Allocated buffer of 200 bytes at 0x105208680
Got  200
Calling GC...
GC completed
Allocated buffer of 200 bytes at 0x105205fc0
Got  200
Allocated buffer of 200 bytes at 0x1052089b0
Got  200
Terminated
Releasing buffer at 0x104711520
Releasing buffer at 0x1047117d0
Releasing buffer at 0x104711a20
Releasing buffer at 0x1050203d0
Releasing buffer at 0x10501fff0
Releasing buffer at 0x10501f700
Releasing buffer at 0x104638670
Releasing buffer at 0x104635ea0
Releasing buffer at 0x1052089b0
Releasing buffer at 0x105205fc0
Releasing buffer at 0x105208680
```

### Expected output

I expected to have 2 or more:

`Releasing buffer at`

after every:

`Calling GC...`

I'm doing something wrong or there is a big problem with

**Comment by NickNaso** [comment]
Hi @ggreco,
in your test you don't give the time to the GC to collect the data. I updated your example like reported below:
```cpp
#include "napi.h"
#include <iostream>
using namespace Napi;

int finalizeCount = 0;

Value doGet(const CallbackInfo &info) {
    uint8_t* data = new uint8_t[200];
    // std::cerr << "Allocated buffer of 200 bytes at " << (void*)data << "\n";

    return Napi::Buffer<uint8_t>::New(info.Env(), data, 200,
         [](Napi::Env env, uint8_t* d) {
             // std::cerr << "Releasing buffer at " << (void*) d << "\n";
             delete[] d;
             finalizeCount++;
         });
}

Value getFinalizeCount(const CallbackInfo &info) {
    return Number::New(info.Env(), finalizeCount);
}

Object Init(Env env, Napi::Object exports) {
    exports["get"] = Function::New(env, doGet);
    exports["getFinalizeCount"] = Function::New(env, getFinalizeCount);
    return exports;
}

// register module
NODE_API_MODULE(testNapi, Init);
```

```js
const native = require("./build/Release/testNapi.node");
const assert = require('assert')

function tick(x) {
    return new Promise((resolve) => {
      setImmediate(function ontick() {
        if (--x === 0) {
          resolve()
        } else {
          setImmediate(ontick)
        }
      })
    })
  }

function createBuffer() {
    const res = native.get()
    assert.ok(res instanceof Buffer)
    assert.strictEqual(res.byteLength, 200)
}

async function callGC() {
    global.gc()
    await tick(10)
}

async function main() {
    for (let i = 1; i <= 10; ++i) {
        console.log('Iteration ', i, ' Finalizer called:', native.getFinalizeCount())
        assert.strictEqual(i - 1, native.getFinalizeCount())
        createBuffer()
        await callGC()    
        console.log('Iteration ', i , ' Finalizer called:', native.getFinalizeCount())
        assert.strictEqual(i, native.getFinalizeCount())
        console.log('***\n')
    }
}

main().catch(err => console.error(err))
```
Is this work for you?

**Comment by ggreco** [comment]
You are right, adding some delay (by the means of setImmediate or setTimeout) works as expected running the test program or the real code in the node environment, the problem is that in the real application is an electron application and there the buffers are never released, and since those buffers can also hold 4k video frames it can also fill the memory of a 32GB machine! I'm quite sure the application passes most of its time in a "wait" state that should give electron time to release the memory.
Anyway the bug is not here, you can close it, I will file a slightly modified version of the test program in the electron environment...

**Comment by ggreco** [comment]
The bug is in the electron renderer process implementation of node, I've updated the code to test the renderer process, and indeed there there is no way to garbage collect the buffers, here:

```
git clone https://github.com/ggreco/testNapi
npm install
npm start
```

there is already a bug filed in electron for that, but it's still open since december:

https://github.com/electron/electron/issues/27091

I'll close this leaving this comment as **reference**.
