### ISSUE TITLE
Time for next release?

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#907]
It will have been 2 months from the last release next week. We should probably start thinking about doing a release.

So far I think we'd want to address the following before releasin:

- [ ] https://github.com/nodejs/node-addon-api/issues/906

**Comment by mhdawson** [comment]
I'm thinking we should plan 2 releases. One fairly soon, and then one after April 30 to drop support for Node.js.  This would make sure the last 3.x version is up to date.  

@NickNaso what do you think of a release April 15th, and then a release May 6th with the only change being dropping support for 8.x?

**Comment by gabrielschulhof** [comment]
From today's Node-API meeting:

The APIs in `napi-inl.deprecated.h` are good candidates for removal in 4.0.0, however, how shall we announce that we are removing them? Can we even remove them? Some folks might still be using them.

We should likely also resolve the issue of what to do when we attempt to throw an exception during environment shutdown before making a release.

Another problem we might want to solve before the next release is https://github.com/nodejs/node-addon-api/issues/906.

**Comment by mhdawson** [comment]
I'm thinking we should still leave "napi-inl.deprecated.h". I don't think they have been causing us any maintenance issues and I think we probably want to discuss more/message more if we are going to do it in advance.

In my mind the main or possibly only thing that we need in 4.0.0 is dropping support for Node.js 10.x once it is out of LTS.

**Comment by mhdawson** [comment]
@nodejs/node-api  you can check out the discussion in  #906 but the conclusion I have is that the intermittent failures we are seeing in the CI are not related to node-addon-api, but instead changes that are needed in core.  Therefore we should be ok to move ahead with the releases we'd planned.

**Comment by NickNaso** [comment]
I'm starting to work on release 3.2.0.

**Comment by NickNaso** [comment]
CI:
| Version | Job | Status |
|---:|---|:---:|
| v16.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/4132/ |  |
| v14.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/4131/ |  |
| v12.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/4130/ |  |

| Job | Status |
|---:|:---:|
| [MultiJob Project node-test-node-addon-api-LTS versions](https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-LTS%20versions/1132/) |

**Comment by NickNaso** [comment]
The version **3.2.0** has been released. Enjoy.

**Comment by NickNaso** [comment]
I'm starting to prepare the release 3.2.1.

**Comment by NickNaso** [comment]
CI:
| Version | Job | Status |
|---:|---|:---:|
| v16.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/4188/ |  |
| v14.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/4187/ |  |
| v12.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/4186/ |  |
| v10.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/4185/ |  |

**Comment by NickNaso** [comment]
Hi everybody,
I'm startting to work on release 4.0.0 please don't merge anything until I will finish.

**Comment by NickNaso** [comment]
CI:
| Version | Job | Status |
|---:|---|:---:|
| v17.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/4264/ |  |
| v16.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/4265/ |  |
| v14.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/4266/ |  |
| v12.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/4267/ |  |

**Comment by NickNaso** [comment]
The release *4.0.0* has been published.

**Comment by NickNaso** [comment]
I think that I can close the issue, if not feel free to reopen it.
