### ISSUE TITLE
How to get the value of an asynchronous function

### ISSUE THREAD

**Issue by januwA** [nodejs/node-addon-api#908]
```js
addon.a(async function () {
  return 10;
});
```

```cpp
void a(const CallbackInfo& info)
{
  Env env = info.Env();
  Function asyncFunc = info[0].As<Function>();
  Promise p = asyncFunc.Call({}).As<Promise>();
  // p.Result(); // 10
}
```

**Comment by KevinEady** [comment]
Hi @januwA ,

Since async functions are indeed functions that return a `Promise`, you will need to pass a callback function to the functions returned from the `.then` and `.catch` properties. I'm not sure if there's an easier or more concise way, but I imagine something like this would have to work... [untested]

```cpp
void a(const CallbackInfo& info)
{
  Env env = info.Env();
  Function asyncFunc = info[0].As<Function>();
  auto p = asyncFunc.Call({}).As<Object>(); 
  auto thenFunc = p.Get("then").As<Function>(); 
  thenFunc.Call(p, Function::New(env, [](const CallbackInfo& info) {
    info[0]; // 10
  });
}
```

**Comment by januwA** [comment]
@KevinEady Your example is good, if you can get the value synchronously like this, it's not bad

```cpp
void a(const CallbackInfo &info)
{
  Env env = info.Env();
  Function asyncFunc = info[0].As<Function>();
  auto p = asyncFunc.Call({}).As<Object>();
  while(true)
  {
    if(p.State() == Promise::kFulfilled)
    {
      p.Result(); // 10
      break;
    }
  }
}
```

**Comment by KevinEady** [comment]
You cannot synchronously wait for a promise... What you want to do in C++ is the equivalent of "using `await` inside a non-`async` function" ... You need to use some threading mechanisms eg. futures. Can you describe your use-case more?
