### ISSUE TITLE
Missing documentation for C++ wrappers

### ISSUE THREAD

**Issue by mcollina** [nodejs/node-addon-api#91]
As titled, a node-style documentation is needed, also the current doxygen is empty.

**Comment by jasongin** [comment]
This package is not part of node core, so its documentation does not belong at https://nodejs.org/api. I'm not sure node-style markdown documentation is required.

The doxygen-generated docs are incomplete, but far from empty. We're definitely aware that the docs are incomplete. Contributions welcome. :)

See also #6

**Comment by mcollina** [comment]
If we want to get adoption, the documentation for this needs to be equal to the one of NAN. I think we should port things almost 1-1: https://github.com/nodejs/nan.

**Comment by addaleax** [comment]
> If we want to get adoption, the documentation for this needs to be equal to the one of NAN.

Can you be more specific? Equal documentation for different APIs doesn’t usually make sense.

> I think we should port things almost 1-1: https://github.com/nodejs/nan.

I’m going to disagree here. N-API has different goals than NAN does; in particular, NAN is and always has been very V8-specific, which means both that it won’t cover other engines as well, and also that it inherits a lot of the V8 API usability flaws. This C++ wrapper is already much more usable than the V8 API ever was.

**Comment by jasongin** [comment]
I assume @mcollina meant "equal in quality/completeness". And I agree that is necessary for broad adoption.

But @addaleax is correct that there are many APIs that don't have direct 1-1 equivalents between V8/NAN and N-API, almost always for good reasons. (That's part of why the automatic conversion script can't do a great job.)

**Comment by mcollina** [comment]
> Can you be more specific? Equal documentation for different APIs doesn’t usually make sense.

I am supposed to do *the same things* with them. So, yes, the documentation **should be very similar**.

> This C++ wrapper is already much more usable than the V8 API ever was.

You are right. However the benchmark here is against NAN, not against the V8 API. Currently this is definitely harder than NAN to use. I can't figure it out easily how to port things, while I built and maintained several modules using NAN. If we all want the ecosystem to update and move to n-api, then this should be a straightforward process. Currently it's not.

**Comment by mhdawson** [comment]
@mcollina a list of things you had trouble figuring out how to port from NaN would be useful.  We can prioritize documenting those cases, possibly using examples.

I think we can all agree we want complete and useful documentation, time is the main problem.  So if we can identify the things that will help the most it would be a great help in doing the right parts first.

**Comment by mcollina** [comment]
1. How to setup a class and export it to JS, i.e. `Napi::ObjectWrap`, which is also not covered by unit tests, and very scarcely documented.
2. Scopes: no-one understands them on first pass, and https://github.com/nodejs/nan/blob/master/doc/scopes.md is great.
3. Error handling, including all the flags in the README. Let's not assume the reader is a C++ expert.

**Comment by mhdawson** [comment]
Thanks, @nodejs/addon-api we should discuss in our next meeting how we get started on this.

**Comment by mcollina** [comment]
@mhdawson when is that happening? I'd like to join.

**Comment by mhdawson** [comment]
I think this is being covered in https://github.com/nodejs/node-addon-api/issues/91#issuecomment-323285659

@mcollina you can join the weekly meeting any time.  Its at 1:30 EST on Thursdays.  If you'd like an invite just ping @sampsongao

**Comment by sampsongao** [comment]
The event link is [here](https://plus.google.com/u/0/events/c0eevtrlajniu7h8cjrdk0f56c8?authkey=COH04YCalJS8Ug). And you can join directly through this hangout [link](https://hangouts.google.com/hangouts/_/event/c0eevtrlajniu7h8cjrdk0f56c8?hl=en&authuser=0).

**Comment by cjihrig** [comment]
Is there any chance of getting that information put on the official calendar?

**Comment by mhdawson** [comment]
I can add it

**Comment by NickNaso** [comment]
Hi @mcollina,
what do you think? Is it possible close the issue? You can find the requested documentation here: [https://github.com/nodejs/node-addon-api/blob/master/doc/object_wrap.md](https://github.com/nodejs/node-addon-api/blob/master/doc/object_wrap.md)

**Comment by mcollina** [comment]
Yes, definitely!
