### ISSUE TITLE
VS 2013 Compiler Support for node-addon-api

### ISSUE THREAD

**Issue by vijaykumbhani** [nodejs/node-addon-api#911]
Hi All

We are using **node-addon-api 3.1.0.**
We are integrating a custom logger static library which was built on VS 2013 compiler.
Would you please check and let us know, how can resolve the issue. 

**See the following error while compiling code.**
**node-addon-api\napi.h(1750): error C3646: 'noexcept' : unknown override specifier** 
**node-addon-api\napi.h(1757) : see reference to class template instantiation 'Napi::InstanceWrap<T>' being compiled**
**node-addon-api\napi-inl.h(4033): error C2244: 'Napi::ObjectWrap<T>::WrappedMethod' : unable to match function definition to an existing declaration**
**node-addon-api\napi-inl.h(4033): error C3646: 'noexcept' : unknown override specifier** 
**node-addon-api\napi-inl.h(5208): error C2668: 'Napi::Function::Call' : ambiguous call to overloaded function** 
**node-addon-api\napi-inl.h(3903): error C2244: 'Napi::ObjectWrap<T>::StaticAccessor' : unable to match function definition to an existing declaration**

**Comment by mhdawson** [comment]
The supported toolchains for Node.js are listed in https://github.com/nodejs/node/blob/master/BUILDING.md#supported-platforms. Master current shows VS 2019 as the minimum.

Looking at the oldest LTS (10.x) even that shows VS 2017 as the minimum level : https://github.com/nodejs/node/blob/v10.x/BUILDING.md

So for any of the currently supported Node.js versions you will need a newer compiler.

**Comment by richardlau** [comment]
For building addons, is https://github.com/nodejs/build/blob/master/doc/windows-visualstudio-supported-versions.md#for-building-nodejs-addons still up-to-date?
cc @nodejs/platform-windows

**Comment by mhdawson** [comment]
@richardlau I don't think I've ever come across that doc.  I don't see a link to it in https://github.com/nodejs/node/blob/master/BUILDING.md which I use as my reference. If we figure out that it is up to date we should add a link so that its more obvious.  

Either way I don't think VS 2013 is listed as supported for any current LTS version there either.

**Comment by mhdawson** [comment]
@vijaykumbhani do you have any additional questions. I think the specific question around VS 2013 is that is not supported.

**Comment by vijaykumbhani** [comment]
Hi All
Thanks for your support. 
closed the ticket.
