### ISSUE TITLE
Abort or update a Napi::AsyncProgressWorker / Napi::AsyncWorker once started?

### ISSUE THREAD

**Issue by dhdvn** [nodejs/node-addon-api#913]
I see you can call `Napi::AsyncWorker::Cancel();` to cancel work that hasn't yet been started but is there a way to abort a process that has been started? Or alternatively amend a running process?

As an example, say an AsyncProgressWorker is started up to run 1000 computations and through the OnProgress callback, you see it's at 200 and would like to stop it early or change the original 1000 to 300 to finish earlier. Is this possible?

**Comment by legendecas** [comment]
It is not safe to terminate a running worker thread. There are lots of resources claiming the reason why we should not do that, i.e. https://stackoverflow.com/questions/323972/is-there-any-way-to-kill-a-thread

You should insert your own checkpoints at "safe to abort" points in the worker code and check if the worker is safe to abort.

**Comment by dhdvn** [comment]
I wasn't really looking to kill the thread, more of a way to pass information after the worker was created in order to amend or end it earlier. I suppose just adding some method to the worker to tell it to break early, e.g.:

`
class SampleAsyncWorker : public AsyncWorker {
 public:
  SampleAsyncWorker(Function& callback, int iterations) : AsyncWorker(callback), iterations(iterations) { }
  ~SampleAsyncWorker() { printf("SampleAsyncWorker %p destructed\n", this); };

  void Execute() {
    for (int i = 0; i < iterations; i++) {
      if(shouldExit) return;
      std::this_thread::sleep_for(std::chrono::seconds(i)); // really some long process here...
    }
  }
  void TriggerEarlyExit() { shouldExit = true; }

 private:
  int iterations;
  bool shouldExit = false;
};
`
would work however is there a way to check the status of a worker that has finished? I suppose this could be yet another flag set at the end of Execute if not. I see the AsyncWorker destructs itself but part of it still remains and can be continued to be referenced. Is there a recommended or internal way to manage ended workers or does this need to be accounted for separately?

**Comment by legendecas** [comment]
@dhdvn you can try `AsyncWorker::SuppressDestruct` (https://github.com/nodejs/node-addon-api/blob/main/napi.h#L2003) to manage the lifetime of async worker by yourself.

**Comment by dhdvn** [comment]
Extending the AsyncWorker and utilizing SuppressDestruct solves my question. Thanks

**Comment by ShaMan123** [comment]
@dhdvn could you post here what you accomplished?
