### ISSUE TITLE
Is it possible to store buffers without copying?

### ISSUE THREAD

**Issue by timotejroiko** [nodejs/node-addon-api#916]
Hello!

Im trying to simulate a JS Map object with data stored on the c++ side, something like this:

```cpp
MyClass::MyClass(const Napi::CallbackInfo& info) : Napi::ObjectWrap<MyClass>(info) {
    (std::unordered_map<uint32_t, char *>) this->stdchar;
}

void MyClass::Set(const Napi::CallbackInfo& info) {
    uint32_t key = info[0].As<Napi::Number>().Int32Value();
    if(info[1].IsString()) {
        this->stdchar[key] = info[1].As<Napi::String>().Utf8Value().c_str();
    } else {
        this->stdchar[key] = info[1].As<Napi::Buffer>().Data();
    }
}
```

However, this way the data is lost when the function ends, and attempting to access it produces garbage data.

One way i found was to copy the data into the heap using strdup() or malloc(), but this is creating too many small allocations and bloating ram usage. Storing strings as std::string was even worse.

My goal is to be as memory-efficient as possible. Is there a way to do this without having to copy the data, for example somehow making it persistent until removed from the unordered_map? If not, what would be the most efficient way to do this? Using a pool allocator?

Thanks!

**Comment by legendecas** [comment]
You can try [`Napi::Reference`](https://github.com/nodejs/node-addon-api/blob/main/doc/reference.md) to save a persistent reference to JavaScript objects, and remove the reference once there is no direct usage on the c++ side.

**Comment by timotejroiko** [comment]
Hello, thanks for the suggestion.

I tried using Napi::Reference in many different ways and finally got it to work like this:

```cpp
MyClass::MyClass(const Napi::CallbackInfo& info) : Napi::ObjectWrap<MyClass>(info) {
    (std::unordered_map<uint32_t, Napi::Reference<Napi::Buffer<char>>*>) this->stdnapi;
}

void MyClass::Set(const Napi::CallbackInfo& info) {
    uint32_t key = info[0].As<Napi::Number>().Int32Value();
    Napi::Buffer<char> test = info[1].As<Napi::Buffer<char>>();
    Napi::Reference<Napi::Buffer<char>>* ref = new Napi::Reference<Napi::Buffer<char>>();
    *ref = Napi::Persistent(test);
    this->stdnapi[key] = ref;
}

void MyClass::Get(const Napi::CallbackInfo& info) {
    uint32_t key = info[0].As<Napi::Number>().Int32Value();
    return stdnapi[key]->Value();
}
```

However im sure im doing something wrong here, because while this solution works, it uses 3x more memory than copying with strdup()

**Comment by legendecas** [comment]
I'm not sure what case you are referring to of the memory usage. You can try taking heap-snapshots with the Chrome DevTools (or any other tooling that can take heap snapshots) to investigate if there are any memory leaks. 

One point you might be interested in is that the allocated buffer memory is bound with the JavaScript values. As JavaScript value garbage collection is not easy to be observed, those memory correlated to the JS value might not be released immediately on you release the Napi::Reference. The heap-snapshot will force a GC to be run before the heap was snapshotted, so this behavior will not be observable from the heapsnapshot.

**Comment by timotejroiko** [comment]
my test was to generate 10 million small buffers on the JS side and store them in the unordered_map on the c++ side, and then read the process's rss values and memory usage in the task manager over the next 15 minutes to account for gc runs.

When storing the buffers using strdup(buffer) the total memory usage was about 1100mb. When storing them using references as above, the total memory usage was about 2900mb.

Im assuming the Reference class has some additional overhead besides being a pointer to a memory region.

**Comment by mhdawson** [comment]
There is additional overhead (C++ objects, likely entries in linked list etc.) , but I don't think a copy of the data.  For larger buffers I think you would see a different result

**Comment by bl-ue** [comment]
@timotejroiko Did you ever resolve this satisfactorily?

**Comment by timotejroiko** [comment]
> @timotejroiko Did you ever resolve this satisfactorily?

Not exactly, but i'm not sure if my idea was ever possible in the first place.

What i had in mind was to somehow keep only the char array alive or somehow transferring it away from the js buffer instance and let the instance die, but it seems that using the reference method above i'm keeping the entire js buffer instance alive, hence the overhead.

Copying the char array and storing the copy is much more memory efficient because its stripping the raw data away from the class instance and letting the instance be garbage collected. Im not sure if there is any better way to accomplish this other than copying.
