### ISSUE TITLE
How to implement custom inspect into ObjectWrap class?

### ISSUE THREAD

**Issue by ThomasWeinert** [nodejs/node-addon-api#919]
I tried registering the an instance method for "nodejs.util.inspect.custom".

```
InstanceMethod(Napi::Symbol::New(env, "nodejs.util.inspect.custom"), &MyObjectWrap::Inspect)
```

But this doesn't get called by `console.log()`. It makes sense because it needs to be a public symbol, but how do I register a method for a public symbol? Here is no `Napi::Symbol::For()`.

**Comment by KevinEady** [comment]
Have you tried `Napi::Symbol::WellKnown`? Otherwise, you could either pass the JavaScript value of `Symbol.for(...)` to your addon so it can be used, or you can grab it from global, something like:
```cpp
auto Symbol = env.Global().Get("Symbol").As<Object>();
auto inspectSym = Symbol.Get("for").As<Function>().Call(Symbol, { Napi::String::New(env, "nodejs.util.inspect.custom") });
```

**Comment by ThomasWeinert** [comment]
`Napi::Symbol::WellKnown(env, "nodejs.util.inspect.custom")` returns `undefined`.

Fetching it from JS works. I put that into a utility function:

```
Napi::Symbol GetPublicSymbol(const Napi::Env &env, std::string name) {
    auto Symbol = env.Global().Get("Symbol").As<Napi::Object>();
    auto forSymbol = Symbol.Get("for").As<Napi::Function>().Call(
        Symbol, { Napi::String::New(env, name) }
    );
    return forSymbol.As<Napi::Symbol>();
}
```

And then 

```
InstanceMethod(GetPublicSymbol(env, "nodejs.util.inspect.custom"), &MyObjectWrap::Inspect),
```

Thank you.

**Comment by gabrielschulhof** [comment]
@KevinEady is it a problem with `Napi::Symbol::WellKnown` that it returns `undefined` in this case?

**Comment by KevinEady** [comment]
> @KevinEady is it a problem with `Napi::Symbol::WellKnown` that it returns `undefined` in this case?

@gabrielschulhof hmmm... the implementation for WellKnown is:
https://github.com/nodejs/node-addon-api/blob/8ef07251ecd090d078607bbcbaa22fee669d2386/napi-inl.h#L996-L998

This is the equivalent of:
```js
Symbol[name]
```
Which is different than
```js
Symbol.for(name)
```

Is the `WellKnown` implementation incorrect?

**Comment by KevinEady** [comment]
As discussed in the Node-API meeting, the implementation for `Symbol::WellKnown` is correct: it is used to retrieve values like [`Symbol.toStringTag`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag), which is a direct property on `Symbol`.

Closing issue.
