### ISSUE TITLE
Templated class instance based on JS constructor arguments

### ISSUE THREAD

**Issue by timotejroiko** [nodejs/node-addon-api#920]
Hello, I'm trying to create a class instance with different types depending on user input, something like this:

```js
// desired JS code
const MyClass = require("./build/release/myclass.node");
const myInstance = new MyClass({
    type: "string"
});
```

```cpp
// addon pseudo code
template<class T>
class MyClass : public Napi::ObjectWrap<MyClass> {
    private:
        T data;
}

MyClass::MyClass(const Napi::CallbackInfo& info) : Napi::ObjectWrap<MyClass>(info) {
    Napi::Object options = input[0].As<Napi::Object>();
    if(options["type"] == "string") {
        // turn this into MyClass<std::string> somehow based on options
        this->data = "abc";
    } else {
        // turn this into MyClass<int> somehow based on options
        this->data = 123;
    }
}
```
Can we somehow intercept the constructor function and return a different class template? I cant figure out how to accomplish this, would be nice to have an example for this or something similar.

**Comment by gabrielschulhof** [comment]
@timotejroiko since C++ templates are instantiated at compile time and `Napi::Value`s are created at runtime, there is no way to instantiate a C++ template at runtime. The only solution is to gauge what kinds of types may arrive into the constructor and do a switch for each type that can be handled:

```cpp
if (info[0].As<Napi::Object>()["type"].IsString()) {
  // Handle the case where it is a string
} else if (info[0].As<Napi::Object>()["type"].IsDate()) {
  // Handle the case where it is a date
} else if (info[0].As<Napi::Object>()["type"].IsNumber()) {
  // Handle the case where it is a number
} else if ...
```

Hopefully this gives you a way to move forward. I will close the issue, but if you have more questions on this topic, please feel free to re-open!

**Comment by timotejroiko** [comment]
Just in case anyone encounters a similar question, what i ended up doing was to create the class as a template, then export all possible templates in the exports object, for example:

```cpp
Napi::Object Init(Napi::Env env, Napi::Object exports) {
	exports["MyClassString"] = MyClass<std::string>::Init(env, exports);
	exports["MyClassNumber"] = MyClass<double>::Init(env, exports);
	return exports;
}
```
And then create a wrapper class on the JS side that picks the right one based on the constructor options.

Another way to do this would be creating an Napi::Function that returns MyClass::Init based on function arguments, and simply call it without the `new` keyword on the JS side
