### ISSUE TITLE
Confusion about instance data handling

### ISSUE THREAD

**Issue by martin5233** [nodejs/node-addon-api#921]
I am currently trying to build an addon using node-addon-api on Node version 14. However I'm completely confused about the ideas behind Env::SetInstanceData<T>:
1. SetInstanceData being a template suggests, that you could set multiple data items of different types for a single environment. Looking at the code shows, that this always calls the same underlying NAPI function napi_set_instance_data, so this cannot work for multiple different types. It's also not typesafe, as it's possible to call Env::GetInstanceData<T> with a different type, which will probably result in a segfault.
2. NODE_API_ADDON invokes Addon<T>::Init, which in turn calls SetInstanceData with the created addon. This means, that it is impossible to use SetInstanceData inside the constructor of the addon at all, because this would be overwritten by Init immediately afterwards. This makes the whole concept of opening up SetInstanceData to writers of addons useless from my understanding. Also the examples for ObjectWrap use instance data, which cannot work in conjunction with addons, if I understand things correctly.

Am I misunderstanding something completely?

**Comment by gabrielschulhof** [comment]
@martin5233 your understanding is correct. Only one data item may be set per each add-on instance. The idea of the `Addon<T>` class is that you set one instance as the instance data and you can add any number of data items to the instance data by making them instance members of the `Addon<T>` class.

Hopefully this will clarify and reinforce your understanding. I will close this issue, but please feel free to re-open if you run into any issues or if you have further questions on this topic.

**Comment by martin5233** [comment]
@gabrielschulhof : Thank you for your quick reply. 
This issue has cost me a lot of time, because the documentation is rather misleading. Nothing even hints at the fact, that you cannot use SetInstanceData in conjunction with an Addon<T>, because it uses this mechanism itself. Therefore I would strongly recommend to improve the documentation to contain a hint about this. Also the fact, that SetInstanceData can only be used with a single type is rather unexpected, the fact that this will produce a crash, if you use it with a different type deserves to be mentioned in the docs as well.
