### ISSUE TITLE
Hardware Events capture in Addon and send to Javascript code

### ISSUE THREAD

**Issue by RobinPratap** [nodejs/node-addon-api#922]
Hi,

I'm working on a project where I am writing a Node addon using C++ node-addon-api to capture the hardware events from my Native C++ code and the send that event and data to the node server.
My use case is like:
A Javascript function is passed to my addon code.
Store the function to be used as a callback.
Then in my addon i want to capture Hardware event for example i plug in a USB device or i unplug it. My Native code is capable of providing this event to me.Once i receive this Event then i want to call the javascript callback function.

My native application can pass me the event via a WinMSG and i can capture this in a Native thread. But after that i am blocked , how to pass this event to Node.
I am trying to learn how this can be done. So far my understanding is that it can be done only by using the Thread safe function to pass on this information to Addon API and then it can be send to Node via callback. I tried searching some examples on this but it is not clear how napi_create_async_work works. It creates a ExecuteWork function but i am not sure if this can work as a thread and i can keep it alive to capture real time events from my Native thread.

If anyone can help me with a sample code or any example where we have two threads(native C++ and Node Addon) running and communicating with the help of Thread safe function.

 Appreciate any comments too!

**Comment by gabrielschulhof** [comment]
@RobinPratap Hopefully https://github.com/nodejs/node-addon-examples/tree/main/thread_safe_function_counting/node-addon-api will provide the inspiration you seek.
