### ISSUE TITLE
Simplify means of constructing JS class with C++ arguments 

### ISSUE THREAD

**Issue by ekraihan** [nodejs/node-addon-api#934]
### Problem I'm Trying To Solve

I would like to construct a JS class from within C++ and said class must be constructed with C++ arguments.

### Current Solution 

Wrap the C++ types with Napi::External and pass those to the `New` method of the JS class where I then extract the Napi::External, *hoping* during the casting process that the correct type was passed in.

### Requested Solution

It would be very convenient if I could pass the C++ types *directly* to the constructor of the JS class. This would have the benefits
1) Get compile-time checking of C++ constructor arguments
2) No overhead with the garbage collector of allocating a new `Napi::External`
3) Less boilerplate code for converting to/from `Napi::External`

### Possible Implementation

Make an overload of `Napi::Function::New` that takes a variable number of args (ie. `ARGS_T&& .. args`) which then get forwarded to the class constructor. Possibly the CallbackInfo would still need to be passed to the constructor so `info` could be the first arg and ARGS_T could be the remaining ctor args.

**Comment by KevinEady** [comment]
I don't think this is possible.
> ... which then get forwarded to the class constructor. 

Only `Value`s can be passed to JS Functions, which is why it has to be wrapped in an `External<>`. If anything, there may be some node-addon-api helper wrapper to create `External<>` objects on the fly, but I don't think that is in scope.

If you think about it, your JS function will take a `CallbackInfo` like you mentioned, but these `.Args()` will be `Value`s, they are not ARGS_T random types.

**Comment by ikokostya** [comment]
I also face with with problem when use smart pointer for object construction. In this case `External<>` can't be used. Instead I create new js object without arguments and then assign needed member in factory method:

```c++
class Foo : public Napi::ObjectWrap<Foo> {
 public:
  static void Init(Napi::Env env);
  static Napi::Object NewInstance(std::unique_ptr<Bar> bar);

  explicit Foo(const Napi::CallbackInfo& info);

 private:
  static Napi::FunctionReference constructor_;
  std::unique_ptr<Bar> bar_;
};

Napi::Object Foo::NewInstance(std::unique_ptr<Bar> bar) {
  Napi::Object js_object = constructor_.New({});
  Foo foo = Unwrap(js_object);
  foo->bar_ = std::move(bar);
  return js_object;
}
```

Of course member must be default constructible class and declared as non-const.

Usage example:

```c++
Napi::Value Test(const Napi::CallbackInfo& info) {
  return Foo::NewInstance(std::make_unique<Bar>());
}
```

**Comment by kiddliu** [comment]
@ikokostya I like your way but it introduces another problem to my case: I'm exposing a cpp class that has a private constructor and can only be constructed with static functions like `Foo::createFoo`. It forces me to fall back with `External`s to distinguish between `let foo = new Foo()` and `constructor_.New({})`. `callbackInfo.NewTarget` won't help here. Do you have any better ideas?
