### ISSUE TITLE
[Test] Test Coverage for Function class

### ISSUE THREAD

**Issue by JckXia** [nodejs/node-addon-api#935]
| class                   | methods                                                                                                                          |
|-------------------------|----------------------------------------------------------------------------------------------------------------------------------|
| Function                | Function()                                                                                                                       |
|     See PR https://github.com/nodejs/node-addon-api/pull/928     (Covered)           |Value Call(const std::initalizer_list<napi_value>& args）const
|      See PR https://github.com/nodejs/node-addon-api/pull/928  (Covered)                         | Value Call(const std::vector<napi_value>&args ) const
|    See PR https://github.com/nodejs/node-addon-api/pull/928 (Covered)                     | Value Call(size_t argc, const napi_value* args) const                                                                            |
|   See PR https://github.com/nodejs/node-addon-api/pull/928  (Covered)  |Value Call(napi_value recv, const std::initializer_list<napi_value>& args)
|    See PR https://github.com/nodejs/node-addon-api/pull/928    (Covered)                     | Value Call(napi_value recv, size_t argc, const napi_value* args) const                                                           |
|        See PR https://github.com/nodejs/node-addon-api/pull/928 (Covered)                         | Value Call(napi_value recv,  const std::vector<napi_value>& args ) const                                   
|    See PR https://github.com/nodejs/node-addon-api/pull/928   (Covered)                        | Value MakeCallback(napi_value recv, const std::initializer_list<napi_value>& args) const                                         |
|    See PR https://github.com/nodejs/node-addon-api/pull/928      (Covered)                      | Value MakeCallback(napi_value recv, const std::vector<napi_value>& args) const                                                   |
|      See PR https://github.com/nodejs/node-addon-api/pull/928     (Covered)                  | Value MakeCallback(napi_value recv, size_t argc, const napi_value* args) const                                                   |
 
@NickNaso

**Comment by KevinEady** [comment]
Can we close this as #928  has been merged?

**Comment by NickNaso** [comment]
I'm closing this issue becasue all seems to be covered.
