### ISSUE TITLE
[Tests] Testing coverage for Objects

### ISSUE THREAD

**Issue by JckXia** [nodejs/node-addon-api#936]
| class                   | methods                                                                                                                          |
|-------------------------|----------------------------------------------------------------------------------------------------------------------------------|
| See https://github.com/nodejs/node-addon-api/pull/923 (covered)                        | Object New(size_t argc, const napi_value* args) const                                                                            |
| Object  (Covered under #923)                | Object()                                                                                                                         |
| See https://github.com/nodejs/node-addon-api/pull/923(covered)                        | Object(napi_env env, napi_value value)                                                                                           |
| Covered                 | PropertyLValue<std::string> operator [](const char* utf8name)                                                                    |
| Covered                       | PropertyLValue<std::string> operator [](const std::string& utf8name)                                                             |
| Covered                      | PropertyLValue<uint32_t> operator [](uint32_t index)                                                                             |
|See https://github.com/nodejs/node-addon-api/pull/923 (covered)                         | Value operator [](const char* utf8name) const                                                                                    |
| See https://github.com/nodejs/node-addon-api/pull/923 (covered)                        | Value operator [](const std::string& utf8name) const                                                                             |
| See https://github.com/nodejs/node-addon-api/pull/923     (covered)                  | Value operator [](uint32_t index) const                                                                                          |
| Covered                         | bool Has(uint32_t index) const                                                                                                   |
|See https://github.com/nodejs/node-addon-api/pull/194 (Covered)   |bool Has(napi_value key) const|
|See https://github.com/nodejs/node-addon-api/pull/194 (Covered)    | bool Has(Value key) const |
|See https://github.com/nodejs/node-addon-api/pull/194 (Covered)  | bool Has(const char* utf8name)|
|See https://github.com/nodejs/node-addon-api/pull/194 (Covered)  | bool Has(const std::string& utf8name)|
| Covered                     | Value Get(uint32_t index) const                                                                                                  |
|See https://github.com/nodejs/node-addon-api/pull/183 (Covered) | Value Get(napi_value key) const|
|See https://github.com/nodejs/node-addon-api/pull/183 (Covered) |Value Get(Value key) const |
|See https://github.com/nodejs/node-addon-api/pull/183 (Covered) |Value Get(const char* utf8name) |
|See https://github.com/nodejs/node-addon-api/pull/183 (Covered) |Value Get(const std::string& utf8name) |
| Covered                        | bool Delete(uint32_t index)                                                                                                      |
|See https://github.com/nodejs/node-addon-api/pull/183 (Covered) |bool Delete(napi_value key) |
|See https://github.com/nodejs/node-addon-api/pull/183 (Covered) |bool Delete(Value key) |
|See https://github.com/nodejs/node-addon-api/pull/183 (Covered) |bool Delete(const char * utf8name) |
|See https://github.com/nodejs/node-addon-api/pull/183 (Covered) |bool Delete(const std::string& utf8name) |
| See https://github.com/nodejs/node-addon-api/pull/1130 (Covered) | template <typename ValueType> void Set(uint32_t index, const ValueType& value)                                                   |
|See https://github.com/nodejs/node-addon-api/pull/183 (Covered)  |template<typename ValueType> void Set(napi_value key, const ValueType& value） |
|See https://github.com/nodejs/node-addon-api/pull/183 (Covered) |template<typename ValueType> void Set(Value key, const ValueType& value) |
|See https://github.com/nodejs/node-addon-api/pull/183 (Covered) |template<typename ValueType> void Set(const char* utf8name, const ValueType& value)|
|See https://github.com/nodejs/node-addon-api/pull/183 (Covered) |template<typename ValueType> void Set(const std::string& utf8name, const ValueType& value) |
|See https://github.com/nodejs/node-addon-api/pull/29 (covered)                         | void DefineProperty(const std::vector<PropertyDescriptor>& properties)                                                         |
|See https://github.com/nodejs/node-addon-api/pull/29 (covered) | void DefineProperties(const std::initializer_list<PropertyDescriptor>& properties) |
|See https://github.com/nodejs/node-addon-api/pull/29 (covered) |void DefineProperties(const PropertyDescriptor& property) |
|Covered                | bool InstanceOf(const Function& constructor) const                                                                               |
| Object::PropertyLValue (Uncovered)  | operator Value() const                                                                                                           |
| See https://github.com/nodejs/node-addon-api/pull/923 (covered)                       | template <typename ValueType> PropertyLValue& operator =(ValueType value)                                                        |
|See https://github.com/nodejs/node-addon-api/pull/551 (covered) | template<typename Finalizer, typename T, typename Hint> void AddFinalizer(Finalizer, finalizeCallback, T* data, Hint* finalizeHint) |
|See https://github.com/nodejs/node-addon-api/pull/551 (covered) |template<typename Finalizer, typename T> void AddFinalizer(Finalizer finalizeCallback, T* data);  |
|See https://github.com/nodejs/node-addon-api/pull/60 (covered) |Napi::Array Napi::Object::GetPropertyNames() const |

**Comment by 0xdw** [comment]
I'm interested in this.  But I have no idea where to start. Can someone guide me on where to start?

**Comment by JckXia** [comment]
Looks like we have full coverage for objects. Closing this issue
