### ISSUE TITLE
[Test] Add Testing Coverage for Number

### ISSUE THREAD

**Issue by JckXia** [nodejs/node-addon-api#943]
| class                   | methods                                                                                                                          |
|-------------------------|----------------------------------------------------------------------------------------------------------------------------------|
| Number  See PR https://github.com/nodejs/node-addon-api/pull/355                  | Number()                                                                                                                         |
|                         See PR https://github.com/nodejs/node-addon-api/pull/355  | Number(napi_env env, napi_value value)                                                                                           |
|   See PR https://github.com/nodejs/node-addon-api/pull/355                      | operator int32_t() const                                                                                                         |
|   See PR https://github.com/nodejs/node-addon-api/pull/355                      | operator uint32_t() const                                                                                                        |
|   See PR https://github.com/nodejs/node-addon-api/pull/355                      | operator int64_t() const                                                                                                         |
|   See PR https://github.com/nodejs/node-addon-api/pull/355                      | operator float() const                                                                                                           |
|   See PR https://github.com/nodejs/node-addon-api/pull/355                      | operator double() const                                                                                                          |

**Comment by KevinEady** [comment]
Landed as https://github.com/nodejs/node-addon-api/commit/779560f3973d587a4c0d60b46bfaf09c879957dc
