### ISSUE TITLE
[Test] Add test coverage for Boolean 

### ISSUE THREAD

**Issue by JckXia** [nodejs/node-addon-api#944]
| class                   | methods                                                                                                                          |
|-------------------------|----------------------------------------------------------------------------------------------------------------------------------|
| Boolean        See PR https://github.com/nodejs/node-addon-api/pull/354 (covered)        | Boolean()                                                                                                                        |
|  See PR https://github.com/nodejs/node-addon-api/pull/354 (covered)                     | Boolean(napi_env env, napi_value value)                                                                                          |
|  See PR https://github.com/nodejs/node-addon-api/pull/490  (covered)                     | operator bool() const                                                                                                            |
|  See PR https://github.com/nodejs/node-addon-api/pull/354   (covered)                    | bool Value() const                                                                                                               |

**Comment by KevinEady** [comment]
Landed as https://github.com/nodejs/node-addon-api/commit/4f76262a1083fe856412bf2b3a4f0dba8b0ff965
