### ISSUE TITLE
callback not registered  with node-addon-api

### ISSUE THREAD

**Issue by vijaykumbhani** [nodejs/node-addon-api#947]
Hi Team,

I am overriding the class methods for a callback. want to use a callback in JS. The NativeCallback is a library class.
could you please look at the sample code and let me know, please correct me if I am doing wrong

while registering a callback on **client.runCallback**, node executable closed without any error.

**Cpp Sample Code:**
`

            Napi::FunctionReference g_cbCallbackError;
            Napi::FunctionReference g_cbCallbackWarning;
            Napi::FunctionReference g_cbCallbackInfo;
	            
            class CustomCallback : public NativeCallback
            {
            public:
              void error(std::string errorString)
              {
	            if (g_cbCallbackError != nullptr)
	            {
	              Napi::Env env = g_cbCallbackError.Env();
	              Napi::String message = Napi::String::New(env, errorString);
	              std::vector<napi_value> args = { message };
	              g_cbCallbackError.Call(args);
	            }
              }
            
              void warning(std::string warningString)
              {
	            if (g_cbCallbackWarning != nullptr)
	            {
	              Napi::Env env = g_cbCallbackError.Env();
	              Napi::String message = Napi::String::New(env, warningString);
	              std::vector<napi_value> args = { message };
	              g_cbCallbackWarning.Call(args);
	            }
              }
            
              void info(std::string infoString)
              {
	            if (g_cbCallbackInfo != nullptr)
	            {
	              Napi::Env env = g_cbCallbackError.Env();
	              Napi::String message = Napi::String::New(env, infoString);
	              std::vector<napi_value> args = { message };
	              g_cbCallbackInfo.Call(args);
	            }
              }
            };
            
            void RunCallback(const Napi::CallbackInfo &info)
            {
	            Napi::Env env = info.Env();
	            std::cout << "RunCallback::" << info.Length() << std::endl;
	            if (info.Length() > 2)
		            g_cbCallbackInfo = Persistent(info[0].As<Napi::Function>());
            
	            if (info.Length() > 3)
		            g_cbCallbackWarning = Persistent(info[1].As<Napi::Function>());
            
	            if (info.Length() > 4)
		            g_cbCallbackError = Persistent(info[2].As<Napi::Function>());
	            NativeCallbackClient::getInstance()->setCallback(new CustomCallback());
            }
            
            Napi::Object Init(Napi::Env env, Napi::Object exports) {
	            exports.Set("runCallback", Napi::Function::New(env, RunCallback));
	            return exports;
            }
`

**JS sample code:**
`

           var client = require('./addon.node')
        
         client.runCallback([
	        function (paramsInfo: string) {
		        if (infoCallback !== undefined) {
			        console.log(`info-callback::- ${paramsInfo}`);
		        }
	        }, function (paramsWarning:string) {
		        if (warningCallback !== undefined) {
			        console.log(`warning-callback::- ${paramsInfo}`);
		        }
	        }, function (paramsError: string) {
		        if (errorCallback !== undefined) {
			        console.log(`error-callback::- ${paramsInfo}`);
		        }
	        }
        ]);
`

**Comment by KevinEady** [comment]
Is your `NativeCallbackClient` trying to execute `error`/`warning`/`info` on a separate thread? If so, you will need to look at [thread-safe functions](https://github.com/nodejs/node-addon-api/blob/main/doc/threadsafe.md).

**Comment by vijaykumbhani** [comment]
> Is your `NativeCallbackClient` trying to execute `error`/`warning`/`info` on a separate thread? If so, you will need to look at [thread-safe functions](https://github.com/nodejs/node-addon-api/blob/main/doc/threadsafe.md).

Hi 
NativeCallbackClient is executing on the main thread. can you please share a working example for node-addon-api?

**Comment by KevinEady** [comment]
Okay... Well, what are you expecting it to do? You call `NativeCallbackClient::setCallback` which sets the references, but... that's about it. The application will end because you aren't doing anything else. If your node process is exiting, that means there are no waiting tasks on the event loop.

**Comment by vijaykumbhani** [comment]
Hi Kevin,
This is a sample code from apps. we are not closing the application. write sample code from apps code, so people easily understand the problem.

**Comment by vijaykumbhani** [comment]
Hi All, 
Found the issue of an existing application and resolve the callback issue.

please find the working sample. if you have any issue on sample then please comment  

**Cpp Sample Code:**

`

**//Notes: 
// std::cout lead to crash electron**

Napi::FunctionReference g_cbCallbackError;
Napi::FunctionReference g_cbCallbackWarning;
Napi::FunctionReference g_cbCallbackInfo;
	
class CustomCallback : public NativeCallback
{
public:
  void error(std::string errorString)
  {
	if (g_cbCallbackError != nullptr)
	{
	  Napi::Env env = g_cbCallbackError.Env();
	  Napi::String message = Napi::String::New(env, errorString);
	  std::vector<napi_value> args = { message };
	  g_cbCallbackError.Call(args);
	}
  }

  void warning(std::string warningString)
  {
	if (g_cbCallbackWarning != nullptr)
	{
	  Napi::Env env = g_cbCallbackWarning.Env();
	  Napi::String message = Napi::String::New(env, warningString);
	  std::vector<napi_value> args = { message };
	  g_cbCallbackWarning.Call(args);
	}
  }

  void info(std::string infoString)
  {
	if (g_cbCallbackInfo != nullptr)
	{
	  Napi::Env env = g_cbCallbackInfo.Env();
	  Napi::String message = Napi::String::New(env, infoString);
	  std::vector<napi_value> args = { message };
	  g_cbCallbackInfo.Call(args);
	}
  }
};

void registerInfoCallback(const Napi::CallbackInfo &info)
{
	Napi::Env env = info.Env();
	if (info.Length() == 1)
		g_cbCallbackInfo = Persistent(info[0].As<Napi::Function>());

	NativeCallbackClient::getInstance()->setCallback(new CustomCallback());
}

void registerWarningCallback(const Napi::CallbackInfo &info)
{
	Napi::Env env = info.Env();
	if (info.Length() == 1)
		g_cbCallbackWarning = Persistent(info[0].As<Napi::Function>());
	NativeCallbackClient::getInstance()->setCallback(new CustomCallback());
}

void registerErrorCallback(const Napi::CallbackInfo &info)
{
	Napi::Env env = info.Env();
	if (info.Length() == 1)
		g_cbCallbackError = Persistent(info[0].As<Napi::Function>());
	NativeCallbackClient::getInstance()->setCallback(new CustomCallback());
}


Napi::Object Init(Napi::Env env, Napi::Object exports) {
	exports.Set("registerInfoCallback", Napi::Function::New(env, registerInfoCallback));
	exports.Set("registerWarningCallback", Napi::Function::New(env, registerWarningCallback));
	exports.Set("registerErrorCallback", Napi::Function::New(env, registerErrorCallback));
	return exports;
}


`


**JS sample code:**


`


var client = require('./addon.node')

function info(message) {
	console.log(message);
}

function warning(message) {
	console.log(message);
}

function error(message) {
	console.log(message);
}

client.registerInfoCallback(info)
client.registerWarningCallback(warning)
client.registerErrorCallback(error)



`
