### ISSUE TITLE
how to allow classes to be called without new

### ISSUE THREAD

**Issue by mcollina** [nodejs/node-addon-api#95]
This is currently possible with NAN, is it possible with N-api?

**Comment by jasongin** [comment]
It's certainly possible using the N-API C functions. But currently it is blocked in the C++ wrapper at https://github.com/nodejs/node-addon-api/blob/master/napi-inl.h#L2477. We could change that code to (optionally?) allow it.

**Comment by mcollina** [comment]
I'm conflicted on this. There is a substantial amount of code that use that pattern in the wild, however it will become less relevant while `class`  become more common.
