### ISSUE TITLE
How to map the inheritance relationship of C ++ classes to JavaScript

### ISSUE THREAD

**Issue by ApsarasX** [nodejs/node-addon-api#956]
I went over the issue about inheritance #229, have not found a valid way to implement inheritance.

It is 2021 now. What's the progress of node-addon-api supporting inheritance?

I would appreciate it if I could get a direct solution

**Comment by ApsarasX** [comment]
My C++ code
```cpp
class Base {
    void print() {
        cout << "Base::print" << endl;
    }
};

class Derived : public Base {
    
};
```

My JavaScript Code
```js
let derived = new Derived();

derived.print();
```

What I expect
```
Base::print
```

What actually happened
```
TypeError: Illegal invocation
```

**Comment by sambhavsaxena** [comment]
`NewDerived extends from Derived();
derived.print();`

This is the correct syntax i guess

**Comment by ApsarasX** [comment]
> `NewDerived extends from Derived(); derived.print();`
> 
> This is the correct syntax i guess

@sambhavsaxena  sorry, you guessed wrong😂

**Comment by sambhavsaxena** [comment]
Enlighten me then?

**Comment by ApsarasX** [comment]
Is there any progress on this issue now?
