### ISSUE TITLE
[Tests] Add test Coverage for Symbol class

### ISSUE THREAD

**Issue by JckXia** [nodejs/node-addon-api#957]
| class                   | methods                                                                                                                          |
|-------------------------|----------------------------------------------------------------------------------------------------------------------------------|
|Covered #972              | static Symbol New(napi_env env, const std::string& description)                                                                  |
|   Covered #972                      | static Symbol New(napi_env env, napi_value description)                                                                          |
| Covered  #972              | Symbol()                                                                                                                         |
|  Covered   #972                    | Symbol(napi_env env, napi_value description)                                                                                           |
|  Covered     #972                  |Symbol(napi_env env, Napi::String description) |
| Covered       #972                 |Symbol(napi_env env, const std::string& description) |
|  Covered         #972       |Symbol(napi_env env , const char* description) |
|  Covered #972 |Symbol::Wellknown(napi_env env, const std::string& name) |

**Comment by JckXia** [comment]
Will work on adding these tests soon.

**Comment by KevinEady** [comment]
I would add `Symbol::WellKnown` as well. There seems to be some discrepancy: https://github.com/nodejs/node-addon-api/issues/919

**Comment by JckXia** [comment]
@KevinEady Hey Kevin. For the `Symbol::Wellknown `function, should it return a symbol that we have registered via `Symbol.for`? In that if I call `Symbol.for("testSymbol")` on js side, I should receive the same symbol back with a call to `Symbol::Wellknown("testSymbol")` from Cpp? (Right now it will return undefined as stated in #919)

**Comment by ThomasWeinert** [comment]
I would suggest adding a separate `Symbol::For(napi_env env, const std::string& name)` for fetching global symbols.

**Comment by NickNaso** [comment]
Hi @JckXia ,
the PR https://github.com/nodejs/node-addon-api/pull/972 has been landed. Could you provide to update the matrix of methds that needs to be tested? In case you already covered all the ceses please provide to close the issue.

**Comment by JckXia** [comment]
@NickNaso Thank you for the reminder! I marked the test cases as covered and the issue is ready to be closed
