### ISSUE TITLE
[Tests] Add test coverage report for DataView

### ISSUE THREAD

**Issue by JckXia** [nodejs/node-addon-api#958]
| class                   | methods                                                                                                                          |
|-------------------------|----------------------------------------------------------------------------------------------------------------------------------|
| DataView                | DataView()                                                                                                                       |
|  Covered(#205)                | DataView(napi_env env, napi_value value)                                                                                         |
| Covered(#205)        |DataView::New(napi_env, Napi::ArrayBuffer arrayBuffer) |
| Covered(#205)        |DataView::New(napi_env , Napi::ArrayBuffer arrayBuffer, size_t byteOffset) |
|  Covered(#205)       |DataView::New(napi_env, Napi::ArrayBuffer arrayBuffer, size_t byteOffset, size_t byteLength) |
|  Covered(#205)     |DataView::ArrayBuffer() const; |
| Covered(#205)  |size_t DataView::ByteOffset() const |
| Covered(#205)   |size_t DataView::ByteLength() const; |
|Covered(#218)  |float DataView::GetFloat32(size_t byteOffset) const; | 
|Covered(#218) | double DataView::GetFloat64(size_t byteOffset) const;|
|Covered(#218)  | int8_t DataView::GetInt8(size_t byteOffset) const;|
|Covered(#218) |int16_t DataView::GetInt16(size_t byteOffset) const; |
|Covered(#218) |int32_t DataView::GetInt32(size_t byteOffset) const; |
|Covered(#218) |uint8_t DataView::GetUint8(size_t byteOffset) const; |
|Covered(#218) |uint16_t DataView::GetUint16(size_t byteOffset) const; |
|Covered(#218) |uint32_t DataView::GetUint32(size_t byteOffset) const; |
|Covered(#218) |void DataView::SetFloat32(size_t byteOffset, float value) const; |
|Covered(#218) |void DataView::SetFloat64(size_t byteOffset, double value) const; |
|Covered(#218) |void DataView::SetInt8(size_t byteOffset, int8_t value) const; |
|Covered(#218) |void DataView::SetInt16(size_t byteOffset, int16_t value) const; |
| Covered(#218) |void DataView::SetInt32(size_t byteOffset, int32_t value) const;|
| Covered(#218) |void DataView::SetUint8(size_t byteOffset, uint8_t value) const; |
|Covered(#218)  |void DataView::SetUint16(size_t byteOffset, uint16_t value) const; |
|Covered(#218)  |void DataView::SetUint32(size_t byteOffset, uint32_t value) const; |

**Comment by NickNaso** [comment]
I'm closing this issue because all seems to be covered.
