### ISSUE TITLE
Integrating mongocxx and node-addon-api

### ISSUE THREAD

**Issue by jmquilez** [nodejs/node-addon-api#959]
Hello:
I am currently trying to use the mongodb c++ drivers with a napi addon. However, when I try to compile the code using "node-gyp rebuild", I get the following error: 
[User]\desktop\latestaddon\officialaddon\src\addon.cpp(11): fatal error C1083: No se puede abrir  
el archivo incluir: 'bsoncxx/builder/stream/document.hpp': No such file or directory

Or in other words:

cannot open source file include: 'bsoncxx/builder/stream/document.hpp': No such file or directory

The problem is that I have been trying to include the libraries in the binding.gyp file, without any success. And I do not think that is the way to solve it. Here are the libraries I am trying to include: 

#include <fstream>
#include <iostream>
#include <vector>
#include <cstdlib>
#include <boost/filesystem.hpp>

#include <bsoncxx/builder/stream/document.hpp>
#include <bsoncxx/json.hpp>
#include <bsoncxx/oid.hpp>

#include <mongocxx/client.hpp>
#include <mongocxx/stdx.hpp>
#include <mongocxx/uri.hpp>
#include <mongocxx/instance.hpp>

I was wandering if it was an issue with the c++ mongocxx drivers, but I have tested the same in other projects where I know they are properly installed and the system does not recognize them either. I would be really grateful with any kind of help.

**Comment by mhdawson** [comment]
Can you provide the additions you made to the binding.gyp ?

**Comment by jmquilez** [comment]
Sure!
Here it is:

{
  "targets": [
    {
      "target_name": "module",
      "cflags!": [ "-fno-exceptions" ],
      "cflags_cc!": [ "-fno-exceptions" ],
      "sources": [ "./main.cpp" ],
      'include_dirs': [
        "<!@(node -p \"require('node-addon-api').include\")"
      , "boost_1_53_0", "bsoncxx", "mongocxx"],
    
      'dependencies': [
        "<!(node -p \"require('node-addon-api').gyp\")"
      ],
      'defines': [ 'NAPI_DISABLE_CPP_EXCEPTIONS' ],
  
    }
  ]
}

The problem is that I have tried to include some bson and mongocxx libraries, but the system doesn't seem to recognize them at all. I am probably doing it wrong. If that is the case, could you please provide a way to include them? I have looked everywhere and haven't been able to find anything. @mhdawson thanks for your help!

**Comment by NickNaso** [comment]
Hi @jmquilez,
at first look seems that you only have set the inlude directories, but you need to set the libraries that you need. You can do this using `libraries` like reported below:
```gyp
'libraries': [
  '-L<some library directory>',
  '-l<some library>', 
]
```
Before to implement the addon yu should compile and install the c++ driver forllowing the following guide http://mongocxx.org/mongocxx-v3/installation/
You could use the source code of mongocxx driver and compile it from your `.gyp` file.
I hope that this information help yuo.

**Comment by jmquilez** [comment]
Hello @NickNaso :
Thanks for the information! I am working on a Windows machine, so I understand that I should install the drivers using the Ubuntu bash shell. Once I install the drivers, please let me know if this is what I have to do:
1) I add the path of the mongocxx driver to the "include dirs" section of the binding.gyp file
2) Then, I add the library directory (which should be the same as the previous one) to the libraries section and I also add the name of the library in the same section.

About the installation of the drivers, can I install them via docker, and if I can, would this make them available for all the directories of the computer?

The problem is that when I use the tar xzf command to build the mongo c driver using the ubuntu bash, I get an error that says "Permission denied".

By the way, could you please provide a simple example of how to include the directories and libraries properly in the bindings.gyp file (with any other library, anything to check how it's done appropiately). I am really new to this, sorry if I am not aware of essential concepts. A great thank you again!

**Comment by NickNaso** [comment]
Hi @jmquilez,
after you installed `mongocxx` driver on your Ubuntu machine you should add some configurations on `cflags` and `libraries` sections like reported below:

```gyp
{
  "targets": [
    {
      "target_name": "addon",
      "cflags": [
        '<!@(pkg-config --cflags libmongocxx)'
      ],
      "cflags!": [ "-fno-exceptions" ],
      "cflags_cc!": [ "-fno-exceptions" ],
      "sources": [ "addon.cc" ],
      "include_dirs": [
        "<!@(node -p \"require('node-addon-api').include\")",
      ],
      "libraries": [
        '<!@(pkg-config --libs libmongocxx)',
      ],
      'defines': [ 'NAPI_DISABLE_CPP_EXCEPTIONS' ],
    }
  ]
}
```
I hope that this help you.

**Comment by jmquilez** [comment]
Thanks a lot! @NickNaso so that is the whole binding.gyp file required for an addon to work using the mongocxx library?

**Comment by jmquilez** [comment]
The computer is actually Windows, not Ubuntu (if that means any changes in the file)

**Comment by NickNaso** [comment]
Hi @jmquilez,
do you need some other help or could I close the issue?

**Comment by jmquilez** [comment]
Hi @NickNaso!
I'm really sorry for the late answer. In the end I got it to work on Windows, and in the future I think I will publish a simple guide on how to compile and build the mongocxx libraries on windows, because I found almost nothing useful on the Internet, even though I spent weeks searching for it. The trick was to use the msbuild Windows compiler and then modify the .xcodeproj files directly to include the directories of the library and then build the addon. Also had to set some .dll paths in the env vars, and that was all. Whenever I create the guide, I will post a link here.
Anyways, issue solved. Thank you very much for your help!

**Comment by NickNaso** [comment]
Hi @jmquilez,
I'm closing the issue. When your guidi will be ready feel free to open a PR and add it on section [More resource and info about native Addons](https://github.com/nodejs/node-addon-api#more-resource-and-info-about-native-addons).

**Comment by jmquilez** [comment]
Great, thanks for helping!
