### ISSUE TITLE
[tests] Test coverage report for String class

### ISSUE THREAD

**Issue by JckXia** [nodejs/node-addon-api#961]
| class                   | methods                                                                                                                          |
|-------------------------|----------------------------------------------------------------------------------------------------------------------------------|
|Covered(#47) |static String New(napi_env env, const std::string & value) |
|Covered(#47) |static String New(napi_env env, const std::u16string& value)  
|Covered(#27)  |static String New(napi_env env, const char * value) |
|Covered(#27) |static String New(napi_env env, const char16_t * value) |
|Covered(#27) |static String New(napi_env, const char* value, size_t length) |
|Covered(#27) |static String New(napi_env env, const char16_t* value, size_t length) |
|Covered(#280) |static String From(napi_env env, const T& value) |
|Covered(#27) |std::string() const |
|Covered(#27) |std::u16string() const |
|Covered(#16) |std::string Utf8Value() const|
|Covered(#47) |std::u16string Utf16Value() const |

**Comment by NickNaso** [comment]
I'm closing this issue because all seems to be covered.
