### ISSUE TITLE
Question: building node addon for ARM on Raspberry PI

### ISSUE THREAD

**Issue by bsrdjan** [nodejs/node-addon-api#962]
I should port the node addon to ARM on Raspberry PI.

Configuring the cross-compilation toolchain on Linux was complicated in the past and the native build on RPI worked but took days.

Should the build process be easier now with Apple M1? Any experience / example to share?

**Comment by mhdawson** [comment]
I don't have any direct experience to offer.

**Comment by bsrdjan** [comment]
Thanks, solved already.
