### ISSUE TITLE
`Napi::Obj` Get or Set by copy

### ISSUE THREAD

**Issue by aminya** [nodejs/node-addon-api#971]
I have faced a situation in which I need to make a new object in JavaScript from C++. 

But, when I `Get` a property of some object and `Set` it to another object, I get these circular references in the JavaScript code while I wanted a copy (a surprising behavior which I figured out by a lot of debugging!). 

Apparently, the copy constructor (`Napi::Object(ref)`) has no effect on the JS side.

The JavaScript solution is to use something like `copy = Object.assign({}, obj_ref)`. I want to know if there is a C++ solution too or I need to call the same thing from C++.
```cpp
Napi::Object copy(const Napi::Object &obj, const Napi::Env &env) {
    auto obj_copy = Napi::Object::New(env);
    env.Global().Get("Object").As<Napi::Object>().Get("assign").As<Napi::Function>().Call({ obj_copy, obj });
    return obj_copy;
}
```

**Comment by legendecas** [comment]
The copy constructor simply means copy the reference (you can call it a pointer to the JavaScript value or anything else) but not copy the JavaScript values. This matches across many other JavaScript engines' native API design.

As far as I can tell, using existing node-api and node-addon-api the solution you proposed is the one you can use across various Node.js versions.

**Comment by mhdawson** [comment]
I'm going to close this as there has been no further discussion since the initial answer to the question.  Please let us know if you feel that was not the right thing to do.
