### ISSUE TITLE
[Tests] Add test coverage for PropertyDescriptors

### ISSUE THREAD

**Issue by JckXia** [nodejs/node-addon-api#986]
| class                   | methods                                                                                                                          |
|-------------------------|----------------------------------------------------------------------------------------------------------------------------------|
|PropertyDescriptor | PropertyDescriptor(napi_property_descriptor desc) |
|Covered #610 |template <Napi::PropertyDescriptor::GetterCallback Getter> static PropertyDescriptor Napi::PropertyDescriptor::Accessor(__name, napi_property_attributes attributes = napi_default, void * data = nullptr)  |
 |Covered #610 |template<GetterCallback Getter, SetterCallback Setter> static PropertyDescriptor Accessor(__name, napi_property_attributes attributes = napi_default , void * data = nullptr)  |
 |Covered #343 |static PropertyDescriptor Accessor(__ name, Getter getter , napi_property_attributes attributes = napi_defaults, void * data = nullptr) |
 |Covered #652 |PropertyDescriptor Napi::PropertyDescriptor::Function( _-name, Callable cb, napi_property_attributes attributes = napi_default, void * data = nullptr) |
 |Covered #65 |PropertyDescriptor Value(__name, napi_value value, napi_property_attributes attributes = napi_default) | 
 |Covered #65|PropertyDescriptor Value(Name name, Value value, napi_property_attributes attributes = napi_default) |

**Comment by NickNaso** [comment]
I'm closing this issue because all seems to be covered.
