### ISSUE TITLE
[Tests] Add test coverage documents for Reference<T> class

### ISSUE THREAD

**Issue by JckXia** [nodejs/node-addon-api#987]
| class                   | methods                                                                                                                          |
|-------------------------|----------------------------------------------------------------------------------------------------------------------------------|
| Reference                | Reference()                                                                                                                       |
|                         | Reference(napi_env env, napi_ref ref)                                                                                        |
| Covered #212  |Reference::New(const T& value, uint32_t initRefCount = 0) |
| |  Reference(Reference&& other) |
| | Reference & operator = (Reference<T> && other) |
| |Env() const; |
|Covered #702 |bool IsEmpty() const |
| |bool operator == (const Reference<T>& other) const |
| |bool operator != (const Reference<T>& other) const |
|Covered #212  |T Value() const |
|Covered #212 |uint32_t Ref() |
|Covered #212 |uint32_t UnRef() |
| |void Reset() |
| |void Reset(const T& value, uint32_t refCount = 0) |

**Comment by legendecas** [comment]
Closed by #1277
