### ISSUE TITLE
threadsafe_function test - CI failing on Master since May 4th

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#994]
Running test 'objectwrap_worker_thread'
Running test 'promise'
Running test 'reference'
Running test 'run_script'
Running test 'threadsafe_function/threadsafe_function'
FATAL ERROR: DataSourceThread Queue was never closing
Tests aborted with SIGSEGV
Build step 'Conditional steps (multiple)' marked build as failure
Sending e-mails to: michael_dawson@ca.ibm.com gabriel.schulhof@intel.com Arunesh.Chandra@microsoft.com
Collecting metadata...
Metadata collection done.
Notifying upstream projects of job completion
Finished: FAILURE

This seems to fail every time now.

@KevinEady I think you know the test best
@legendecas were there any changes in master that you think might have affected this?

**Comment by mhdawson** [comment]
I wonder if this is related: https://github.com/nodejs/node-addon-api/issues/994

**Comment by mhdawson** [comment]
@indutny FYI

**Comment by legendecas** [comment]
7abc7e45b2e177307f67f33906663b5de02f2916 is landed on May 5th. And there is no significant updates in node-addon-api since late April...

**Comment by legendecas** [comment]
I can reproduce on local node.js main branch build. Will dig into the problem to seek a quick fix.

**Comment by mhdawson** [comment]
Resolved in #995, @legendecas thanks.
